import { describe, it, expect } from "vitest";
import {
  HOUSE_GENRES,
  TECHNO_GENRES,
  TRANCE_GENRES,
  DUBSTEP_GENRES,
  DNB_GENRES,
  UK_BASS_GENRES,
  TRAP_DRILL_GENRES,
  FUTURE_DOWNTEMPO_GENRES,
  HARD_ELECTRO_GENRES,
  ROCK_METAL_GENRES,
  HIPHOP_GENRES,
  JAZZ_BLUES_GENRES,
  POP_RNB_GENRES,
  LATIN_WORLD_GENRES,
} from "../data/genres";
import { GENRE_INDEX, GENRE_INDEX_MAP } from "../data/index/loader";
import type { GenreIndexItem } from "../types/genreIndex";
import type { Genre } from "../types/genre";

/**
 * E-07: `src/data/index/genresIndex.ts` is generated by `scripts/build_genre_index.ts`
 * from the 14 genre chunk modules, but nothing in the repo ever ran that generator and
 * no gate compared the two. BACKLOG P4-08 claimed "CI verifies generated output ==
 * repository data"; it did not exist.
 *
 * This test rebuilds the index exactly as the generator does — in memory, no script
 * runner needed — and asserts field-by-field equality with the committed file, so the
 * lightweight index can never silently drift from the genre database.
 */

const CHUNKS: Array<{ chunk: string; list: Genre[] }> = [
  { chunk: "house", list: HOUSE_GENRES },
  { chunk: "techno", list: TECHNO_GENRES },
  { chunk: "trance", list: TRANCE_GENRES },
  { chunk: "dubstep", list: DUBSTEP_GENRES },
  { chunk: "dnb", list: DNB_GENRES },
  { chunk: "uk_bass", list: UK_BASS_GENRES },
  { chunk: "trap_drill", list: TRAP_DRILL_GENRES },
  { chunk: "future_downtempo", list: FUTURE_DOWNTEMPO_GENRES },
  { chunk: "hard_electro", list: HARD_ELECTRO_GENRES },
  { chunk: "rock_metal", list: ROCK_METAL_GENRES },
  { chunk: "hiphop", list: HIPHOP_GENRES },
  { chunk: "jazz_blues", list: JAZZ_BLUES_GENRES },
  { chunk: "pop_rnb", list: POP_RNB_GENRES },
  { chunk: "latin_world", list: LATIN_WORLD_GENRES },
];

/** Mirrors scripts/build_genre_index.ts field for field. */
function buildExpectedIndex(): GenreIndexItem[] {
  const items: GenreIndexItem[] = [];
  for (const { chunk, list } of CHUNKS) {
    for (const g of list) {
      items.push({
        id: g.id,
        name: g.name,
        category: g.category,
        chunk,
        origin_decade: g.origin_decade,
        origin_year: g.origin_year,
        bpm_range: g.bpm_range,
        default_bpm: g.default_bpm,
        subgenres: g.subgenres || [],
        aliases: g.aliases || [],
        radar: g.radar_metrics,
      });
    }
  }
  return items;
}

describe("E-07 · lightweight genre index is in sync with the genre database", () => {
  const expected = buildExpectedIndex();

  it("contains the same number of entries in the same order", () => {
    expect(GENRE_INDEX.map((g) => g.id)).toEqual(expected.map((g) => g.id));
  });

  it("matches every indexed field of every genre", () => {
    const drift: string[] = [];
    expected.forEach((want, idx) => {
      const got = GENRE_INDEX[idx];
      if (!got) {
        drift.push(`[${idx}] ${want.id}: missing from the index`);
        return;
      }
      const fields: Array<keyof GenreIndexItem> = [
        "id",
        "name",
        "category",
        "chunk",
        "origin_decade",
        "origin_year",
        "bpm_range",
        "default_bpm",
      ];
      for (const field of fields) {
        if (got[field] !== want[field]) {
          drift.push(`[${idx}] ${want.id}.${String(field)}: index=${JSON.stringify(got[field])} data=${JSON.stringify(want[field])}`);
        }
      }
      if (JSON.stringify(got.aliases) !== JSON.stringify(want.aliases)) {
        drift.push(`[${idx}] ${want.id}.aliases drift`);
      }
      if (JSON.stringify(got.subgenres) !== JSON.stringify(want.subgenres)) {
        drift.push(`[${idx}] ${want.id}.subgenres drift`);
      }
      if (JSON.stringify(got.radar) !== JSON.stringify(want.radar)) {
        drift.push(`[${idx}] ${want.id}.radar drift`);
      }
    });
    expect(drift, `genresIndex.ts is stale — re-run scripts/build_genre_index.ts:\n${drift.slice(0, 20).join("\n")}`).toEqual([]);
  });

  it("keeps the id → entry map complete and consistent", () => {
    for (const item of GENRE_INDEX) {
      expect(GENRE_INDEX_MAP[item.id], `${item.id} missing from GENRE_INDEX_MAP`).toBe(item);
    }
    expect(Object.keys(GENRE_INDEX_MAP)).toHaveLength(GENRE_INDEX.length);
  });

  it("has no duplicate ids across chunks", () => {
    const ids = expected.map((g) => g.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});
