import { describe, expect, it } from "vitest";
import { validateProsody } from "../../mcp/prosody";

/**
 * The prosody check, on fixtures written by hand rather than generated by the implementation.
 *
 * The pairs below are the ones a person would use to argue the point: 能够 (阳平 + 去声 — rising then falling) is a 倒字 if it is sung
 * rising into falling, and 假如 (阳平 + 上声) is not. If a fixture here is wrong, the test is wrong, which is the point of writing them
 * down instead of trusting the rule table.
 */
describe("validateProsody", () => {
  it("warns when a falling tone is sung on a rising interval — the 倒字 case", () => {
    // 能够: 阳平 (rise) then 去声 (fall). The melody rises into the second syllable instead of falling.
    const report = validateProsody({ tones: [2, 4], pitches: [60, 64], syllables: ["能", "够"] });
    expect(report.warnings).toHaveLength(1);
    expect(report.warnings[0]).toMatchObject({ index: 1, tone: 4, expected: "fall", heard: "rise", interval: 4 });
    expect(report.warnings[0].syllable).toBe("够");
  });

  it("says nothing when the melody follows the tones", () => {
    const report = validateProsody({ tones: [2, 4], pitches: [60, 64 - 6] }); // rise, then fall
    expect(report.warnings).toEqual([]);
  });

  it("flips the expectation for two 上声 in a row, and says so", () => {
    // 3+3: the first syllable is expected to **rise**, so a rise there is correct rather than a warning.
    const report = validateProsody({ tones: [3, 3], pitches: [60, 63] });
    expect(report.expected[0]).toBe("rise");
    expect(report.sandhi).toHaveLength(1);
    expect(report.warnings).toEqual([]);
  });

  it("leaves neutral tones and the caller's own tone list alone", () => {
    const report = validateProsody({ tones: [5, 0], pitches: [60, 72] });
    expect(report.warnings).toEqual([]);
    expect(report.expected).toEqual(["free", "free"]);
    expect(report.checked).toBe(2);
  });

  it("only checks what it has pitches for, and never throws", () => {
    const report = validateProsody({ tones: [2, 4, 1], pitches: [60, 64] });
    expect(report.checked).toBe(2);
    expect(() => validateProsody({ tones: [], pitches: [] })).not.toThrow();
    expect(validateProsody({ tones: [], pitches: [] }).warnings).toEqual([]);
  });
});
