/**
 * **Two libraries left the catalogue, and the four the palette depends on did not.**
 *
 * On 2026-10-03 the owner had `freepats-tubular-bells1` (33 files / 16 551 617 bytes) and `gregsullivan-e-pianos`
 * (177 files / 21 484 144 bytes) removed from the manifest and from the R2 mirror. Four neighbouring FreePats
 * libraries were explicitly kept, because a palette row records them as the *recording* of an instrument:
 * `freepats-drawbar-organ` (`m1_organ`), `freepats-percussive-organ` (`organ_lead`), `freepats-fsbs-dist2`
 * (`distorted_guitar`) and `freepats-button-accordion-hn` (`accordion_lead`). Deleting those would not have trimmed
 * a catalogue — it would have broken four instruments and emptied an existing criterion
 * (`sampledInstrumentPaletteWiring.test.ts`), which is why the removal was scoped to two.
 *
 * ## Why this is a test rather than a note in the change's report
 *
 * The two halves of this change fail in opposite directions and both are silent:
 *
 *   - **The removal can be undone by an accident.** The manifest is a 5 MB JSON file regenerated by a script; a later
 *     run over "the whole survey" can put an entry back without anyone deciding to. Then the catalogue lists
 *     recordings whose bytes are no longer on the mirror — the exact "listed but unfetchable" state the deletion
 *     created a window for once and should not create again.
 *   - **The keep-list can be deleted by an over-eager follow-up.** "Remove the FreePats libraries" is a plausible
 *     next instruction, and the four rows above are FreePats libraries too. A criterion that names the four, with
 *     their byte tallies, is the difference between trimming and breaking.
 *
 * The byte tallies are asserted rather than only the ids because an id can survive while the entry behind it is
 * rebuilt from a different commit — the same reason `shippedManifest.test.ts` pins the drum kit's figures.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { catalogueFromManifestText } from "../data/sampleCatalogue";
import { ALL_SAMPLED_INSTRUMENTS } from "../data/sampledInstruments";

const MANIFEST_PATH = "public/samples/manifest.json";
const MANIFEST_TEXT = readFileSync(MANIFEST_PATH, "utf8");
const MANIFEST = JSON.parse(MANIFEST_TEXT) as {
  entries: { id: string; files: { path: string; bytes: number }[] }[];
};

const bytesOf = (id: string): number =>
  (MANIFEST.entries.find((entry) => entry.id === id)?.files ?? []).reduce((sum, file) => sum + file.bytes, 0);

/** The two the owner pointed at, with the figures the manifest carried when they left. */
const REMOVED = [
  { id: "freepats-tubular-bells1", files: 33, bytes: 16_551_617 },
  { id: "gregsullivan-e-pianos", files: 177, bytes: 21_484_144 },
] as const;

/**
 * The four that must not go, each with the instrument whose row is the reason — and the exact tallies, so "still
 * listed" cannot quietly become "still listed but rebuilt from something else".
 */
const KEPT = [
  { id: "freepats-drawbar-organ", instrument: "m1_organ", assetId: "freepats-drawbar-organ", files: 18, bytes: 6_505_808 },
  { id: "freepats-percussive-organ", instrument: "organ_lead", assetId: "freepats-percussive-organ", files: 34, bytes: 14_548_534 },
  { id: "freepats-fsbs-dist2", instrument: "distorted_guitar", assetId: "freepats-fsbs-dist2", files: 125, bytes: 136_921_363 },
  { id: "freepats-button-accordion-hn", instrument: "accordion_lead", assetId: "freepats-button-accordion-hn", files: 37, bytes: 4_470_533 },
] as const;

describe("the two libraries removed on 2026-10-03", () => {
  it("are not in the manifest any more — not as an entry, and not as a substring", () => {
    const ids = MANIFEST.entries.map((entry) => entry.id);
    for (const { id } of REMOVED) {
      expect(ids, `${id} is back in the manifest; its bytes are no longer on the mirror`).not.toContain(id);
      /**
       * The raw-text check is not redundant with the id check: "the entry is gone" and "the name is gone" are
       * different claims, and a re-add that only fixed the id (or a leftover in someone else's field) would pass the
       * first. This is the check that the removal is a fact about the file rather than about one array.
       */
      expect(MANIFEST_TEXT, `${id} is still written somewhere in ${MANIFEST_PATH}`).not.toContain(id);
    }
  });

  it("leaves the manifest at 32 entries and 315 program-level assets", () => {
    // ⭐ 2026-10-06: `karoryfer-big-rusty-drums` left the mirror — 8 programs, and the largest library the code named only
    // twice. The file count in its archive was far larger than its program count, so the number here is the pin's, not the
    // archive's.
    expect(MANIFEST.entries).toHaveLength(32);
    const assets = catalogueFromManifestText(MANIFEST_TEXT, "").assets;
    // 34 → 32 entries and 327 → 322 assets when the two libraries left (they held 2 and 3 SFZ programs); 32 → 33 and
    // 322 → 323 on 2026-10-03, when `karoryfer-pastabass` was added as the one program `pick_bass` moved onto. The
    // numbers are asserted because a list that silently shrank (or grew back) is the failure this file exists for.
    expect(assets).toHaveLength(315);
  });

  it("names neither library in any palette row, so no lane points at a recording that is gone", () => {
    const removedPrefixes = REMOVED.map(({ id }) => `${id}:`);
    const pointing = ALL_SAMPLED_INSTRUMENTS.filter((row) =>
      removedPrefixes.some((prefix) => row.assetId.startsWith(prefix) || row.assetId === prefix.slice(0, -1)),
    );
    expect(pointing.map((row) => `${row.instrument} → ${row.assetId}`)).toEqual([]);
  });
});

describe("the four libraries the keep-list names", () => {
  it("are still in the manifest, with the same files and the same bytes", () => {
    for (const { id, files, bytes } of KEPT) {
      const entry = MANIFEST.entries.find((candidate) => candidate.id === id);
      expect(entry, `${id} was removed, but ${id} is the recording four palette rows depend on`).toBeDefined();
      expect(entry!.files, `${id} changed size — the mirror and the manifest would disagree`).toHaveLength(files);
      expect(bytesOf(id), `${id} changed byte count`).toBe(bytes);
    }
  });

  it("are still the recording their palette row names", () => {
    for (const { instrument, assetId } of KEPT) {
      const rows = ALL_SAMPLED_INSTRUMENTS.filter((row) => row.instrument === instrument);
      expect(rows.length, `no row plays ${instrument}`).toBeGreaterThan(0);
      expect(
        rows.map((row) => row.assetId),
        `${instrument} no longer resolves to ${assetId}`,
      ).toContain(assetId);
    }
  });

  it("leaves the four instruments themselves declared, so the check above is not vacuous", () => {
    // Each keep-listed library is the *only* asset its row names, so "the row still points at it" and "the library
    // still exists" have to be the same fact rather than two that happen to agree today.
    for (const { instrument } of KEPT) {
      const assetIds = ALL_SAMPLED_INSTRUMENTS.filter((row) => row.instrument === instrument).map((row) => row.assetId);
      expect(new Set(assetIds).size, `${instrument} names more than one asset — this assumption is stale`).toBe(1);
    }
  });
});
