# Origin/history anchors (R5). Concrete place + era + signature equipment, venue
# or artefact for each genre. Used as ONE context element in the subject clause,
# never as a tourist-postcard of a city. No artists, brands or album covers.
ORIGINS = {
    "2-step-garage": "South London garage parties of the late 1990s, pirate radio and a two-step swing",
    "acid-house": "Chicago warehouse parties of 1987 and the squelching silver TB-303 bass machine",
    "acid-jazz": "London jazz-dance clubs of the early 1990s, a Fender Rhodes beside live horns",
    "acid-techno": "Berlin after 1989, stripped concrete clubs and a silver 303 bass machine",
    "afrobeat": "Lagos Nigeria in the 1970s, a big horn section over West African polyrhythm",
    "afro-house": "Johannesburg and Durban in the 2010s, Afro percussion under deep house",
    "alternative-rnb": "Toronto and Los Angeles of the 2010s, hazy chambers and a treated vocal",
    "alternative-rock": "Seattle and the US college circuit of the early 1990s, loud-quiet dynamics",
    "amapiano": "South African townships of the late 2010s, a log drum and jazzy piano",
    "ambient": "a 1970s English studio, tape loops and a treated piano left to decay",
    "ambient-dub": "Kingston Jamaica meets 1990s Berlin, tape delay and a dub mixing desk",
    "ambient-techno": "Detroit and Berlin in the 1990s, a Juno-106 pad over a soft machine kick",
    "bachata": "the Dominican Republic of the 1960s, a nylon-string guitar and a bongo",
    "bass-house": "the UK and Ibiza of the 2010s, a filtered bassline under a heavy kick",
    "bassline": "Sheffield and Leeds in the 2000s, a warping sub-bass over garage swing",
    "bebop": "Harlem after-hours clubs of the mid-1940s, trumpet and drums at furious tempo",
    "big-beat": "London in the late 1990s, block-party breakbeats and a wall of analogue gear",
    "black-metal": "the Norwegian fjords of the early 1990s, frost, tremolo riffs and blast beats",
    "blues-rock": "the British and American club circuit of the late 1960s, a cranked valve amp",
    "boom-bap": "New York City of the early 1990s, a crate of vinyl and a dusty drum break",
    "bossa-nova": "Rio de Janeiro in the late 1950s, a nylon-string guitar and a quiet voice",
    "breakbeat": "the UK rave warehouses of the early 1990s, chopped amen breaks and a sampler",
    "breakcore": "the European netlabel scene of the late 1990s, a sampler pushed past breaking",
    "brooklyn-drill": "Brooklyn in the 2010s, a sliding 808 bass under dark minor piano",
    "brostep": "the US festival circuit of the early 2010s, metallic bass growls over half-time",
    "chicago-blues": "Chicago's South Side clubs of the 1950s, a hollow-body guitar and a harp",
    "chicago-drill": "Chicago's South Side in the 2010s, grim piano loops and sliding bass",
    "chicago-house": "Chicago warehouse parties of the mid-1980s, a jacking beat and a drum machine",
    "chillstep": "the mid-2010s internet, half-time drums and a rain-streaked window",
    "chillwave": "the late-2000s blog era, washed-out synths and a sun-bleached cassette",
    "chiptune": "1980s Japanese game hardware, a square-wave sound chip and an arcade cabinet",
    "city-pop": "Tokyo in the 1980s, a neon waterfront and glossy FM synthesizers",
    "cloud-rap": "the late-2000s internet, hazy pads and a bedroom-lit ceiling",
    "conscious-hip-hop": "New York and Los Angeles in the early 1990s, soulful samples and dense verses",
    "contemporary-rnb": "Toronto and Atlanta in the 2010s, sparse beats and layered airy vocals",
    "cool-jazz": "New York after-hours clubs of the early 1950s, brushed snare and muted brass",
    "cumbia": "Colombia's Caribbean coast, an accordion and a guiro on a warm night",
    "dancehall": "Kingston Jamaica in the 1980s, a towering soundsystem and a digital riddim",
    "death-metal": "Florida and Stockholm in the early 1990s, down-tuned riffs and blast beats",
    "deathstep": "the early-2010s underground, a distorted kick fused with metallic bass",
    "deep-house": "Chicago and New York in the late 1980s, warm chords under a soft kick",
    "delta-blues": "the Mississippi Delta of the 1930s, a resonator guitar on a plantation porch",
    "detroit-techno": "Detroit in the late 1980s, rusting industry, afrofuturism and a TR-808",
    "disco": "New York City in 1977, a mirrored ball and lush strings over a live bass",
    "doom-metal": "Birmingham England in the early 1970s, down-tuned riffs at funeral pace",
    "downtempo": "Bristol and Vienna in the mid-1990s, slow dusty beats and a warm lounge",
    "dream-trance": "the late-1990s European trance floor, a staircase of light and euphoric pads",
    "drift-phonk": "Memphis and the internet of the 2010s, warped cowbells and a sliding 808",
    "dub": "Kingston Jamaica in the 1970s, a mixing desk, tape echo and a spring reverb",
    "dubstep": "South London in the early 2000s, a dark warehouse and a deep sub-bass",
    "dub-techno": "Berlin and Detroit in the 1990s, echoing chord stabs over rolling bass",
    "east-coast-hip-hop": "New York City in the early 1990s, a boombox on a stoop and jazzy breaks",
    "edm-trap": "the mid-2010s festival main stage, huge builds and hybrid trap drums",
    "electric-blues": "Chicago in the 1950s, a sunburst guitar through a small tweed amp",
    "electro": "New York City in 1982, an 808 drum machine and a vocoder over machine funk",
    "electro-house": "Paris and Berlin in the mid-2000s, filtered stabs and a strobe-lit floor",
    "emo-rap": "SoundCloud in the late 2010s, a melancholy guitar loop and distorted 808",
    "eurodance": "Germany and the Netherlands in the early 1990s, pumping stabs and a dance floor",
    "euro-trance": "the Netherlands and Germany in the late 1990s, a supersaw melody at sunrise",
    "footwork": "Chicago's South Side in the 2000s, fast chopped breaks and rapid dance battles",
    "free-jazz": "New York City in the early 1960s, collective improvisation without a fixed key",
    "frenchcore": "France and the Netherlands in the 2000s, a distorted kick at extreme tempo",
    "french-house": "Paris in the late 1990s, filtered disco loops and a touch of house",
    "funk": "Detroit and Dayton in the early 1970s, a slapped bass and tight horn stabs",
    "future-bass": "the mid-2010s internet, pitched vocal chops and luminous supersaws",
    "future-garage": "London in the late 2000s, shuffled two-step under chopped vocals",
    "future-house": "the 2010s club circuit, bright arpeggios and a glossed house groove",
    "g-funk": "South Central Los Angeles in the early 1990s, a lowrider and a whining lead synth",
    "ghetto-house": "Chicago and Detroit in the late 1980s, raw fast jacking drums and a bare floor",
    "glitch-hop": "the West Coast and Europe in the 2000s, stuttering sampled drums and wonky bass",
    "goa-trance": "Goa India in the early 1990s, a fluorescent fractal tunnel and rolling acid",
    "grime": "East London in the early 2000s, a tower-block stairwell and icy 140bpm synths",
    "grunge": "Seattle in the early 1990s, a battered guitar and flannel in a rehearsal room",
    "gypsy-jazz": "Paris in the 1930s, a Selmer guitar and violin playing hot club swing",
    "halftime": "the 2010s bass underground, half-time drums and cavernous low end",
    "happy-hardcore": "the UK rave scene of the late 1990s, hoover stabs at frantic tempo",
    "hard-bop": "New York City in the late 1950s, a quintet of horns swinging hard",
    "hardcore-gabber": "Rotterdam in the early 1990s, a distorted kick and a vast warehouse",
    "hard-rock": "London and Los Angeles in the early 1970s, a wall of valve amplifiers",
    "hardstyle": "the Netherlands in the 2000s, a reverse bass kick and a roaring stadium",
    "hard-techno": "Berlin in the 1990s, a pounding kick against bare concrete and steel",
    "hard-trance": "Germany in the late 1990s, a fast rolling bass and a searing lead",
    "hard-trap": "Atlanta in the mid-2010s, distorted 808s and aggressive horns",
    "heavy-metal": "the English Midlands in the early 1970s, a stack of valve amps and riveted steel",
    "hybrid-trap": "the mid-2010s festival circuit, orchestral stabs over trap drums",
    "idm": "Cornwall and Sheffield in the early 1990s, intricate broken beats and warm melody",
    "industrial-techno": "Berlin and Birmingham in the 1990s, rusted turbines and metallic clang",
    "jazz-fusion": "New York and Los Angeles in the early 1970s, electric piano and fretless bass",
    "jersey-club": "Newark New Jersey in the 2000s, fast chopped breaks in a concrete stairwell",
    "jersey-drill": "New Jersey in the 2010s, sliding bass under dark piano",
    "j-pop": "Tokyo in the 1990s and 2000s, polished stages and maximal bright melody",
    "jump-up": "London in the late 1990s, wobbling mid-range bass on a dark dancefloor",
    "jungle": "London in the early 1990s, chopped amen breaks and a deep sub-bass in a warehouse",
    "kawaii-future-bass": "Tokyo and the internet in the 2010s, pastel clouds and sugar-bright leads",
    "k-pop": "Seoul in the 2010s, precision choreography and a mirrored stage",
    "kuduro": "Luanda Angola in the 2000s, fast percussion at a street party",
    "liquid-dnb": "Bristol and London in the mid-1990s, rolling breaks and a warm sub-bass",
    "lofi-hip-hop": "the mid-2010s internet, a bedroom desk, a cassette deck and a rain window",
    "lofi-house": "the 2010s, soft filtered chords in a small warm room",
    "math-rock": "Chicago and the US Midwest in the 1990s, jagged odd-time interlocking guitars",
    "melodic-dubstep": "the late-2000s UK, an emotional lead over deep half-time bass",
    "melodic-house": "Berlin and Amsterdam in the 2010s, a grand piano over a rolling groove",
    "metalcore": "New England and the UK in the 2000s, breakdown riffs and twin-guitar melody",
    "microhouse": "Cologne and Berlin in the early 2000s, minuscule clicks and micro-samples",
    "minimal-techno": "Detroit and Berlin in the 1990s, sparse clicks on an empty grid",
    "modal-jazz": "New York City in 1959, modal vamps and spacious solos",
    "moombahton": "Washington DC in 2010, a dem-bow rhythm slowed under heavy bass",
    "motown": "Detroit in the mid-1960s, a studio floor with tambourine and punchy horns",
    "neo-soul": "Philadelphia and New York in the late 1990s, a Rhodes and a laid-back pocket",
    "neurofunk": "London and Bristol in the late 1990s, surgical distorted bass over tight breaks",
    "new-wave": "New York and London in 1979, cold synth hooks and angular guitar",
    "nu-disco-house": "the 2000s disco revival, a glittering ball and filtered live bass",
    "old-school-hip-hop": "the Bronx in 1979, a turntable, a painted boombox and a block party",
    "peak-time-techno": "Berlin in the 2010s, a monolithic speaker tower under a single white beam",
    "phonk": "Memphis in the 1990s and the internet of the 2010s, warped cowbells and smoke",
    "post-dubstep": "London in 2010, sparse bass weight and clipped vocal fragments",
    "post-punk": "Manchester and London in 1979, angular basslines and a cold rehearsal room",
    "progressive-house": "the UK and Netherlands in the mid-2000s, a long patient build",
    "progressive-rock": "London in the early 1970s, a rack of effects and long-form structure",
    "progressive-trance": "the late-1990s European trance floor, a slow evolving arpeggio",
    "psytrance": "Goa and Israel in the 1990s, a kaleidoscopic fractal at a desert party",
    "punk-rock": "London and New York in 1977, a battered guitar against a brick wall",
    "ragga-jungle": "London in the mid-1990s, a towering soundsystem and patois chant",
    "raw-techno": "Berlin and Rotterdam in the 1990s, stripped pounding drums and steel pillars",
    "reggae": "Kingston Jamaica in the early 1970s, a deep rolling bassline and offbeat skank",
    "reggaeton": "San Juan Puerto Rico in the 2000s, a dem-bow beat on a hot neon street",
    "riddim": "the 2010s dubstep underground, minimal wobbling bass on a dark stage",
    "rock-and-roll": "Memphis in 1954, a hollow-body guitar swung by its neck on a small stage",
    "salsa": "New York City's Spanish Harlem in the 1970s, congas, trumpets and a piano",
    "samba": "Rio de Janeiro, a circle of surdo drums and tambourines in the street",
    "sambass": "Brazil and London in the late 1990s, samba percussion over drum-and-bass breaks",
    "schranz": "Frankfurt in the late 1990s, abrasive looped drums and hydraulic pressure",
    "shoe-gaze": "the Thames Valley in the early 1990s, a guitar buried in white noise",
    "smooth-jazz": "Los Angeles in the mid-1980s, a polished saxophone in warm low light",
    "soul": "Memphis and Detroit in the mid-1960s, a Hammond organ and a vintage microphone",
    "southern-hip-hop": "Houston and Atlanta in the 2000s, a candy-painted car and heavy 808",
    "speedbass": "the 2010s bass underground, hyper-fast bass stabs at frantic tempo",
    "speed-garage": "London in 2001, a garage roller door and shuffled two-step",
    "synth-pop": "London and Berlin in 1981, a rack of analogue synthesizers",
    "synthwave": "the 2000s retro-future revival of 1980s neon, a chrome car and a striped sun",
    "tearout-dubstep": "the late-2000s UK, ferocious distorted bass on a festival floor",
    "tech-house": "London and Ibiza in the mid-2000s, a minimal drum machine and rolling bass",
    "techstep": "London in 1996, cold distorted bass and tight breaks in a dark corridor",
    "tech-trance": "Germany in the early 2000s, a churning turbine of light over rolling bass",
    "texas-blues": "Austin and the Texas roadhouses of the 1970s, a Stratocaster on a wooden porch",
    "thrash-metal": "the San Francisco Bay Area in 1983, frantic downpicked riffs at speed",
    "traditional-jazz": "New Orleans in the 1920s, a banjo, clarinet and brass bass on a bandstand",
    "traditional-pop": "the 1950s American songbook, a microphone on a stand under a warm spotlight",
    "trap-rap": "Atlanta in the 2010s, booming 808s and rattling hi-hats on a night street",
    "trip-hop": "Bristol in the early 1990s, slow dusty beats in a smoky dim lounge",
    "tropical-house": "the 2010s summer circuit, a thatched beach bar with a steel drum at dusk",
    "uk-drill": "South London in the 2010s, a rain-dark housing estate and sliding 808 bass",
    "uk-funky": "London in the late 2000s, a bare community hall and a warping bassline",
    "uk-garage": "London in the late 1990s, a garage forecourt at night and shuffled two-step",
    "uplifting-trance": "the Netherlands in the early 2000s, a sunrise above an ocean of clouds",
    "vaporwave": "early-1990s corporate computer imagery and dead mall aesthetics, pastel and hazy",
    "vocal-trance": "the late-1990s European trance floor, a soaring voice before a wall of light",
    "wave": "the mid-2010s internet, a monochrome skyline dissolving into cold fog",
    "west-coast-hip-hop": "Los Angeles in the early 1990s, a lowrider under palm trees",
}
