#!/usr/bin/env node
/**
 * Bundle the MCP server into one runnable file.
 *
 * Why a bundle at all: the app's sources use extensionless relative imports (Vite resolves them), Node's ESM
 * loader does not. Rather than rewrite the app's imports or add a runtime loader, esbuild resolves them into a
 * single `dist-mcp/groove-mcp.mjs` — which is also what makes the MCP client config a one-line `node <path>`.
 *
 * The bundle externalises nothing except the SDK's optional transports (express/hono, used only by the HTTP
 * transport this server does not expose) so the artifact stays small; Playwright is loaded lazily at runtime by
 * the render worker and is therefore marked external on purpose.
 */
import fs from "node:fs";
import path from "node:path";
import { build } from "esbuild";

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, "dist-mcp");
const OUT_FILE = path.join(OUT_DIR, "groove-mcp.mjs");
const CHECK = process.argv.includes("--check");

/** Read the repo's version so the MCP server can report what it was built from. */
const version = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")).version;

const result = await build({
  entryPoints: [path.join(ROOT, "mcp", "server.ts")],
  outfile: OUT_FILE,
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  sourcemap: false,
  minify: false,
  legalComments: "none",
  define: { "process.env.GROOVE_MCP_VERSION": JSON.stringify(version) },
  // Playwright is ~300 MB and only needed by render_audio; it must stay a runtime import.
  external: ["playwright", "playwright-core", "@cfworker/json-schema"],
  banner: {
    // No shebang here: `mcp/server.ts` has one and esbuild hoists it to line 1. A second copy in the banner
    // lands on line 2, where it is a syntax error rather than a comment.
    js: `// Generated by scripts/build_mcp.mjs — do not edit. Source: mcp/**.`,
  },
  logLevel: "warning",
  metafile: true,
});

const bytes = result.metafile.outputs[path.relative(ROOT, OUT_FILE)]?.bytes ?? 0;
fs.chmodSync(OUT_FILE, 0o755);

if (CHECK) {
  console.log(`✅ MCP server bundles (${(bytes / 1024).toFixed(0)} KB → dist-mcp/groove-mcp.mjs, v${version})`);
} else {
  console.log(`wrote dist-mcp/groove-mcp.mjs (${(bytes / 1024).toFixed(0)} KB, v${version})`);
}
