from gen_p1 import save_module

jazz_blues_list = [
  {"id": "delta-blues", "name": "Delta Blues", "aliases": ["三角洲布鲁斯"], "category": "Jazz/Blues", "year": "1900", "bpm": "80–120 BPM", "default_bpm": 100, "style": "standard", "place": {"en": "Mississippi Delta, USA", "zh": "美国密西西比三角洲"},
   "artists": ["Robert Johnson", "Charley Patton", "Son House", "Skip James", "Blind Willie Johnson"],
   "context": {"en": "One of the earliest forms of blues, born in the Mississippi Delta, driven by acoustic slide guitar, raw emotional vocals, and porch-stomp rhythms.", "zh": "布鲁斯最古老形态之一，诞生于密西西比三角洲，以原声滑棒吉他、粗犷撕裂的歌喉与踩击门廊的脚步节拍著称。"},
   "soundDesign": {"en": "Acoustic resonator guitars, brass slide, raw human vocals, foot tapping stomp.", "zh": "原声共鸣吉他、黄铜滑棒、原始撕裂人声与脚踏地面重音。"},
   "rhythmFeatures": {"en": "Loose, intuitive 12-bar blues pulse driven by foot stomps and thumb-picked bass beats.", "zh": "松散自然的 12 小节布鲁斯律动，由脚踏与大拇指拨奏低音驱动。"},
   "bassPattern": {"en": "Steady thumbed alternating bass notes on acoustic guitar lower strings.", "zh": "木吉他低音弦上大拇指交替弹奏的沉稳低音线条。"},
   "productionTips": {"en": ["Tune acoustic guitar to Open D or Open G for authentic slide playing", "Capture single-microphone performance to retain raw room intimacy", "Emphasize emotional vocal bends over perfect pitch"], "zh": ["吉他调至开放 D 或开放 G 弦演奏正宗滑棒", "采用单支大振膜电容话筒录音保留亲近空间感", "重视喉音弯音与即兴叹息胜过完美音准"]}},

  {"id": "chicago-blues", "name": "Chicago Blues", "aliases": ["芝加哥布鲁斯"], "category": "Jazz/Blues", "year": "1940", "bpm": "110–135 BPM", "default_bpm": 120, "style": "standard", "place": {"en": "Chicago, USA", "zh": "美国芝加哥"},
   "artists": ["Muddy Waters", "Howlin' Wolf", "Little Walter", "Buddy Guy", "Junior Wells"],
   "context": {"en": "Electrified delta blues in South Side Chicago clubs, adding amplified electric guitars, distorted harmonica, piano, and drums.", "zh": "将三角洲布鲁斯电气化，在芝加哥南区俱乐部加入通电电吉他、失真口琴、钢琴与架子鼓。"},
   "soundDesign": {"en": "Amplified distorted harmonica through bullet mic, Fender tube amps, upright bass, acoustic drums.", "zh": "子弹头话筒放大失真口琴、Fender 电子管箱头、立式贝斯与原声架子鼓。"},
   "rhythmFeatures": {"en": "The iconic Chicago shuffle rhythm: swinging 8th notes with cracking snare backbeats.", "zh": "经典芝加哥摇摆切分律动：摇摆八分音符与爽朗的后拍军鼓。"},
   "bassPattern": {"en": "Walking upright or electric basslines locking tightly into the shuffle kick.", "zh": "行进立式或电贝斯线条，紧紧咬合在摇摆底鼓踏板上。"},
   "productionTips": {"en": ["Drive harmonica through a vintage tube amplifier for that warm distorted roar", "Use a 12-bar blues structure in E or A major", "Layer acoustic upright piano playing boogie chords"], "zh": ["让口琴信号通过过载复古电子管箱头发出砂纸般嘶鸣", "以 E 或 A 调构建 12 小节标准和弦架构", "叠入原声立式钢琴弹奏布吉和弦"]}},

  {"id": "texas-blues", "name": "Texas Blues", "aliases": ["德克萨斯布鲁斯"], "category": "Jazz/Blues", "year": "1930", "bpm": "115–140 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "Texas, USA", "zh": "美国德克萨斯"},
   "artists": ["Stevie Ray Vaughan", "T-Bone Walker", "Albert Collins", "Lightnin' Hopkins", "Freddie King"],
   "context": {"en": "Known for blazing virtuosic guitar solos, heavy swing shuffle feels, brass horn sections, and stinging single-note bends.", "zh": "以电光石火般的大师级吉他独奏、极具弹性的重摇摆节拍、铜管乐组与如蜂蜇般的单音推弦闻名。"},
   "soundDesign": {"en": "Cranked Fender Stratocasters through Dumble/Super Reverb tube amps, Ibanez Tube Screamer.", "zh": "芬达吉他接入大功率电子管箱头并推入经典的 Ibanez Tube Screamer 单块。"},
   "rhythmFeatures": {"en": "Hard-swinging Texas shuffle rhythm with galloping snare work and dynamic accents.", "zh": "强劲跳跃的德州摇摆（Texas Shuffle）律动，伴随飞驰军鼓与丰富动态。"},
   "bassPattern": {"en": "Driving, powerful walking electric basslines holding down the high-speed shuffle.", "zh": "充满推进力与力量感的行进电贝斯线条，稳稳托举极速摇摆。"},
   "productionTips": {"en": ["Use heavy-gauge guitar strings (.011 or .013) for thick acoustic tone and sustain", "Kick an overdrive pedal into an already-warm tube amp for creamy lead tones", "Keep drum shuffle tight and swinging on the ride cymbal"], "zh": ["使用粗规格吉他琴弦（.011 或 .013）获取饱满琴体共鸣与延音", "用过载单块推向临界过载箱头获得醇厚独奏音色", "鼓组在 Ride 镲片上保持严丝合缝的弹性摇摆"]}},

  {"id": "electric-blues", "name": "Electric Blues", "aliases": ["电气布鲁斯"], "category": "Jazz/Blues", "year": "1948", "bpm": "90–130 BPM", "default_bpm": 110, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["B.B. King", "Albert King", "Freddie King", "John Lee Hooker", "Otis Rush"],
   "context": {"en": "Pioneered by B.B. King and The Three Kings, defining modern guitar expression with stinging vibrato, crying bends, and horn arrangements.", "zh": "由 B.B. King 等三大 King 确立，以如泣如诉的极深颤音、哭泣推弦与铜管管乐合奏定义了现代电吉他语言。"},
   "soundDesign": {"en": "Gibson ES-335 hollow-body guitars, expressive finger vibrato, warm brass sections.", "zh": "吉普森半空心电吉他、极具歌唱性的手指揉弦颤音与温暖铜管乐团。"},
   "rhythmFeatures": {"en": "Expressive, dynamic 12-bar blues groove supporting emotional call-and-response solos.", "zh": "富有动态起伏的 12 小节布鲁斯节拍，完美支撑人声与吉他的呼应式即兴。"},
   "bassPattern": {"en": "Melodic, supportive electric bass guitar playing traditional blues changes.", "zh": "悠扬悦耳且稳健甘当绿叶的电贝斯，弹奏经典布鲁斯和弦交替。"},
   "productionTips": {"en": ["Practice the vocal-style finger vibrato on sustained notes for iconic Lucille tone", "Leave spacious room for call-and-response between vocal phrases and guitar fills", "Pan brass sections across the stereo field"], "zh": ["在长延音上练习如同人类声带般的丰富手指揉弦颤音", "在每一句人声歌词后留出空白，让吉他即兴短句呼应对话", "将铜管声部在立体声场中舒展铺开"]}},

  {"id": "traditional-jazz", "name": "Traditional Jazz", "aliases": ["传统爵士", "新奥尔良爵士", "Dixieland"], "category": "Jazz/Blues", "year": "1910", "bpm": "120–180 BPM", "default_bpm": 140, "style": "standard", "place": {"en": "New Orleans, USA", "zh": "美国新奥尔良"},
   "artists": ["Louis Armstrong", "Jelly Roll Morton", "King Oliver", "Bix Beiderbecke", "Sidney Bechet"],
   "context": {"en": "Born in New Orleans brass bands, characterized by collective polyphonic improvisation where trumpet, clarinet, and trombone interweave melodies.", "zh": "诞生于新奥尔良街头铜管军乐，以小号、单簧管与长号互相交织的复调集体即兴（Collective Polyphony）为灵魂。"},
   "soundDesign": {"en": "Brass instruments (cornet, trumpet, trombone), clarinet, banjo, upright bass, tuba.", "zh": "短号、小号、长号、单簧管、班卓琴、立式低音提琴或大号。"},
   "rhythmFeatures": {"en": "Swinging two-beat or four-beat rhythm with bright banjo strums and syncopated snare work.", "zh": "跳跃的二拍或四拍摇摆律动，伴随欢快班卓琴扫弦与切分小军鼓。"},
   "bassPattern": {"en": "Punchy tuba or acoustic upright bass providing foundational root-fifth pulses on beats 1 and 3.", "zh": "有力的大号或原声低音提琴，在 1、3 拍提供纯正的根音-五音脉冲。"},
   "productionTips": {"en": ["Structure polyphony: trumpet plays lead melody, clarinet weaves high counterpoint, trombone provides low slides", "Capture brass instruments with vintage ribbon microphones for smooth highs", "Keep the groove joyous and celebratory"], "zh": ["构建复调织体：小号奏主旋律，单簧管穿插高音对位，长号负责低音滑音", "使用复古铝带话筒拾取铜管，获得温暖柔和的高频", "整体氛围保持欢庆雀跃的新奥尔良狂欢色彩"]}},

  {"id": "bebop", "name": "Bebop", "aliases": ["比波普爵士"], "category": "Jazz/Blues", "year": "1940", "bpm": "180–300+ BPM", "default_bpm": 220, "style": "standard", "place": {"en": "New York, USA", "zh": "美国纽约"},
   "artists": ["Charlie Parker", "Dizzy Gillespie", "Thelonious Monk", "Bud Powell", "Max Roach"],
   "context": {"en": "Revolutionized jazz in 1940s Harlem, turning dance music into complex high-art with blistering tempos, rapid chord substitutions (ii-V-I), and altered scales.", "zh": "在 1940 年代哈莱姆区彻底革新爵士乐，将流行舞曲升华为高阶艺术，以超高速、复杂代理和弦（ii-V-I）与变化音阶震撼乐坛。"},
   "soundDesign": {"en": "Acoustic alto sax, muted trumpet, bebop acoustic piano, ride cymbal swing, upright bass.", "zh": "原声中音萨克斯、弱音小号、原声钢琴、Ride 镲轻快摇摆与低音提琴。"},
   "rhythmFeatures": {"en": "Hyper-fast tempos (200+ BPM) with feathering kick drum and complex ride cymbal polyrhythms.", "zh": "超高速（200+ BPM）飞驰，底鼓微弱触击（Feathering），Ride 镲承担主要摇摆。"},
   "bassPattern": {"en": "Virtuosic 4-to-the-bar walking upright bass outlining complex chord changes and substitutions.", "zh": "大师级一拍一音（Walking Bass）低音提琴行进，勾勒复杂的代理和弦轮廓。"},
   "productionTips": {"en": ["Compose fast 8th-note lines using the Bebop Dominant scale with chromatic passing tones", "Use ride cymbal with a light wooden tip stick to carry the 240 BPM swing", "Keep piano comping sparse and syncopated"], "zh": ["使用带半音经过音的 Bebop 音阶创作行云流水的八分音符独奏", "用轻木质琴槌在 Ride 镲上轻盈承载 240 BPM 高速摇摆", "钢琴伴奏切分点缀保持精简克制，为管乐腾出即兴空间"]}},

  {"id": "hard-bop", "name": "Hard Bop", "aliases": ["硬波普爵士"], "category": "Jazz/Blues", "year": "1950", "bpm": "110–180 BPM", "default_bpm": 135, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Art Blakey & The Jazz Messengers", "Horace Silver", "Cannonball Adderley", "Clifford Brown", "John Coltrane"],
   "context": {"en": "Re-infused bebop with soulful blues, gospel chords, and driving rhythm and blues, creating infectious, accessible, and deeply emotional jazz anthems.", "zh": "将比波普与深情布鲁斯、福音和弦和强劲节奏布鲁斯重新熔融，创作出感染力极强、接地气且极富灵魂的爵士名曲。"},
   "soundDesign": {"en": "Soulful tenor sax, brassy trumpet, blues-drenched piano chords, punchy drum kit.", "zh": "深情次中音萨克斯、明亮小号、布鲁斯福音风钢琴和弦与充满冲击力的爵士架子鼓。"},
   "rhythmFeatures": {"en": "Solid, swinging 4/4 groove with heavy backbeat accents on beats 2 and 4 and driving snare pops.", "zh": "扎实摇摆的四四拍律动，在 2、4 拍上有厚重的后拍军鼓强调。"},
   "bassPattern": {"en": "Resonant walking upright bass with strong melodic blues inflections.", "zh": "共鸣饱满的行进低音提琴，带有浓郁的布鲁斯和声滑进。"},
   "productionTips": {"en": ["Incorporate gospel-style IV-I and ii-V progressions into your compositions", "Allow the drummer to drive dynamics with explosive rimshot accents", "Keep horns harmonized in tight 3rds and 6ths on the head motif"], "zh": ["在曲目创作中融入福音色彩的变格终止与 ii-V 进行", "让鼓手用充满张力的军鼓炸点推动乐曲起伏", "在主题呈示部让萨克斯与小号以纯正的三度或六度和声齐奏"]}},

  {"id": "cool-jazz", "name": "Cool Jazz", "aliases": ["冷爵士", "轻柔爵士"], "category": "Jazz/Blues", "year": "1949", "bpm": "90–130 BPM", "default_bpm": 110, "style": "standard", "place": {"en": "New York & California, USA", "zh": "美国纽约与加州"},
   "artists": ["Miles Davis", "Dave Brubeck", "Chet Baker", "Gerry Mulligan", "Stan Getz"],
   "context": {"en": "Pioneered by Miles Davis on 'Birth of the Cool', stepping back from bebop's blistering speed in favor of understated elegance, lighter tones, and classical arrangements.", "zh": "由 Miles Davis 凭借《Birth of the Cool》奠定，退去 Bebop 的狂飙燥热，取而代之以温文尔雅、轻柔内敛与古典室内乐般的从容编配。"},
   "soundDesign": {"en": "Harmon-muted trumpet, breathy tenor sax, cool vibraphone, brushed acoustic snare.", "zh": "Harmon 弱音小号、带有叹息呼吸感的萨克斯、空灵颤音琴（Vibraphone）与毛刷轻扫军鼓。"},
   "rhythmFeatures": {"en": "Relaxed, light swing played primarily with wire drum brushes on coated snare heads.", "zh": "舒缓轻柔的摇摆节拍，主要由钢丝鼓刷在涂层军鼓皮上轻扫绘制。"},
   "bassPattern": {"en": "Understated, gentle walking acoustic basslines holding the harmonic foundation quietly.", "zh": "优雅克制、轻描淡写的低音提琴行进，如绅士般静默托起和声地基。"},
   "productionTips": {"en": ["Use a Harmon mute with the stem removed on trumpet for the iconic Miles Davis tone", "Record drums with soft wire brushes instead of wooden drumsticks", "Focus on spacious melodies with plenty of breath and silence"], "zh": ["在小号上安装拔除管芯的 Harmon 弱音器复现 Miles Davis 标志音色", "鼓手完全使用柔软的钢丝鼓刷代替木质鼓棒", "旋律写作注重留白，让乐句在充沛的呼吸与寂静中延展"]}},

  {"id": "modal-jazz", "name": "Modal Jazz", "aliases": ["调式爵士"], "category": "Jazz/Blues", "year": "1958", "bpm": "100–140 BPM", "default_bpm": 120, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Miles Davis", "John Coltrane", "Bill Evans", "McCoy Tyner", "Herbie Hancock"],
   "context": {"en": "Epitomized by 'Kind of Blue' (1959), abandoning fast chord progressions to improvise extensively on musical modes (Dorian, Mixolydian) over static pedal points.", "zh": "以传世经典《Kind of Blue》（1959）为巅峰，摒弃高频切换的和弦体系，转而在单一调式（如多利亚、混合利底亚）与持续低音上进行沉思即兴。"},
   "soundDesign": {"en": "Sustained piano quartal voicings (So What chords), open acoustic trumpet, meditative bass pedal point.", "zh": "四度和弦排列（So What 和弦）、清亮原声小号与冥想式的低音踏板长音（Pedal Point）。"},
   "rhythmFeatures": {"en": "Hypnotic, flowing swing groove allowing soloists complete temporal freedom.", "zh": "催眠流动、充满水质流淌感的摇摆节拍，赋予即兴独奏者完全的时间自由。"},
   "bassPattern": {"en": "Held bass pedal points alternating with slow modal walking lines.", "zh": "坚实驻留的单音低音踏板长音，与缓慢的调式行进低音从容交替。"},
   "productionTips": {"en": ["Use quartal harmony (stacking notes in 4ths rather than 3rds) on piano for open modern voicings", "Stay on a single chord/mode for 8 to 16 bars to encourage melodic depth", "Capture the room acoustic reverb naturally"], "zh": ["钢琴伴奏使用四度叠置和弦（Quartal Voicing）构建开阔现代声响", "让单一调式持续 8 到 16 小节，迫使独奏者深挖旋律本质", "自然收录录音室房间的真实声学混响反射"]}},

  {"id": "free-jazz", "name": "Free Jazz", "aliases": ["自由爵士"], "category": "Jazz/Blues", "year": "1959", "bpm": "Atempo / Free", "default_bpm": 120, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Ornette Coleman", "John Coltrane", "Cecil Taylor", "Albert Ayler", "Sun Ra"],
   "context": {"en": "Pioneered by Ornette Coleman in 1959, shattering conventional rules of fixed tempo, predetermined chord changes, and traditional tonality in pursuit of raw expression.", "zh": "由 Ornette Coleman 于 1959 年开创，彻底打碎固定拍速、预设和弦走向与传统调性束缚，追求最狂野纯粹的生命本能表达。"},
   "soundDesign": {"en": "Screaming overblown saxophones, percussive piano clusters, bowed acoustic bass harmonics.", "zh": "超吹刺裂的高音萨克斯、打击乐般的集群钢琴重击与拉弦低音提琴泛音。"},
   "rhythmFeatures": {"en": "Fluid, meterless pulse with polyrhythmic drum improvisation moving freely without a grid.", "zh": "流动失重的非定量脉冲，鼓组多节奏即兴完全脱离小节网格自由流淌。"},
   "bassPattern": {"en": "Free, expressive bowed or plucked upright bass conversing dynamically with soloists.", "zh": "自由奔放的拉弓或拨奏低音提琴，与独奏管乐展开电光火石般的动态对话。"},
   "productionTips": {"en": ["Abandon fixed click tracks and tempo maps to capture the organic collective energy", "Embrace unconventional performance techniques: saxophone multiphonics and microtonal bends", "Record the ensemble live in a single room with spill"], "zh": ["完全摒弃节拍器与固定速度线，捕捉现场乐队不可复制的气场共振", "大胆运用非常规发声技巧：萨克斯复音（Multiphonics）与微音程推弦", "让全体乐手在同一声学房间中同期实录，接纳自然串音"]}},

  {"id": "jazz-fusion", "name": "Jazz Fusion", "aliases": ["爵士融合", "Fusion"], "category": "Jazz/Blues", "year": "1968", "bpm": "110–140 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Miles Davis", "Weather Report", "Return to Forever", "Herbie Hancock", "Mahavishnu Orchestra"],
   "context": {"en": "Forged by Miles Davis on 'Bitches Brew', fusing jazz harmonic complexity and improvisation with rock electricity, funk grooves, and synthesizers.", "zh": "由 Miles Davis 凭借《Bitches Brew》铸就，将爵士和声复杂度与即兴同摇滚的通电狂暴、放克律动及合成器熔为一炉。"},
   "soundDesign": {"en": "Fender Rhodes through wah-wah pedals, Minimoog synthesizer, distorted electric guitar, live percussion.", "zh": "挂接哇音踏板的 Fender Rhodes 电钢琴、Minimoog 合成器、失真电吉他与拉丁打击乐。"},
   "rhythmFeatures": {"en": "Heavy, syncopated funk-rock drumming with complex odd-meter subdivisions and tight hi-hat work.", "zh": "强劲切分的放克摇滚鼓点，融合奇数拍细分与极度紧凑的踩镲技法。"},
   "bassPattern": {"en": "Jaco Pastorius style fretless electric basslines with rich singing mid-range harmonics.", "zh": "Jaco Pastorius 式无品电贝斯线条，带有歌唱般明亮饱满的中频泛音。"},
   "productionTips": {"en": ["Run Rhodes electric piano through a tape echo and analog phaser pedal", "Use fretless electric bass with boosted 800Hz for expressive lyrical 'mwah' tone", "Incorporate complex odd meters like 7/8 and 11/8 into funk grooves"], "zh": ["将 Rhodes 电钢琴送入磁带回声与模拟移相单块创造太空感", "使用无品电贝斯并提升 800Hz 中频获取标志性的啼鸣歌唱（Mwah）音色", "将 7/8、11/8 等奇数非常规节拍融入强劲放克律动中"]}},

  {"id": "smooth-jazz", "name": "Smooth Jazz", "aliases": ["轻柔爵士", "顺滑爵士"], "category": "Jazz/Blues", "year": "1980", "bpm": "85–105 BPM", "default_bpm": 95, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Kenny G", "Grover Washington Jr.", "George Benson", "Dave Koz", "Fourplay"],
   "context": {"en": "A commercial crossover combining jazz melodic lines with slick pop R&B production, synthetic beats, and easy-listening soprano saxophone.", "zh": "商业跨界风格，将爵士旋律线条与精细顺滑的流行 R&B 制作、电子节拍及高亢甜美的高音萨克斯融合。"},
   "soundDesign": {"en": "Soprano saxophone, polished electric guitars with chorus, Yamaha DX7 electric pianos, soft synth pads.", "zh": "高音萨克斯、挂载合唱效果的精致电吉他、Yamaha DX7 晶莹电钢与柔顺合成铺底。"},
   "rhythmFeatures": {"en": "Gentle, polished 4/4 pop/R&B groove with soft electronic drum machine claps and shakers.", "zh": "温和顺滑的四四拍流行 R&B 节拍，伴随柔顺的电子鼓机拍手与轻巧沙锤。"},
   "bassPattern": {"en": "Smooth, rounded electric bass guitar lines with gentle slap accents on the groove.", "zh": "圆润顺滑的电贝斯线条，偶有轻巧克制的 Slap 弹跳点缀。"},
   "productionTips": {"en": ["Apply lush chorus and pristine stereo plate reverb to clean electric guitar leads", "Layer acoustic soprano sax with subtle synthetic doubling", "Keep dynamic range controlled and comfortable for radio broadcast"], "zh": ["为清音电吉他独奏挂载丰润合唱与纯净立体声板式混响", "在原声高音萨克斯下方叠加一层微弱的合成器同度重合", "将整体动态范围精细控制在适于电台播出的温润区间"]}},

  {"id": "acid-jazz", "name": "Acid Jazz", "aliases": ["酸性爵士"], "category": "Jazz/Blues", "year": "1987", "bpm": "100–120 BPM", "default_bpm": 110, "style": "breakbeat", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Jamiroquai", "Incognito", "The Brand New Heavies", "Guru (Jazzmatazz)", "Corduroy"],
   "context": {"en": "Originated in London clubs by DJs Gilles Peterson and Chris Bangs, blending vintage 70s jazz-funk with hip-hop breakbeats and soulful vocals.", "zh": "诞生于伦敦俱乐部，将 70 年代纯正爵士放克与嘻哈碎拍、灵魂乐人声及现场管乐跨界相融。"},
   "soundDesign": {"en": "Funky Fender Rhodes chords, live brass horn stabs, wah-wah funk rhythm guitars, slap bass.", "zh": "放克 Fender Rhodes 和弦、现场铜管齐鸣、哇音放克扫弦吉他与 Slap 贝斯。"},
   "rhythmFeatures": {"en": "Upbeat, swinging breakbeat groove (around 110 BPM) with syncopated live drums and shakers.", "zh": "轻快欢跃、摇摆感十足的 110 BPM 碎拍律动，现场真鼓与沙锤交相辉映。"},
   "bassPattern": {"en": "Infectious, funky slap and fingerstyle basslines driving relentless dance energy.", "zh": "极具感染力的放克 Slap 与指弹贝斯，驱动永不停息的舞动热量。"},
   "productionTips": {"en": ["Stack funky live horns (trumpet, sax, trombone) playing unison stabs", "Drive rhythm guitars through an envelope filter (auto-wah) for that vintage funk bounce", "Lock slap bass and kick drum onto the exact same groove grid"], "zh": ["编写现场铜管三重奏（小号、萨克斯、长号）齐奏放克刺音", "吉他接入包络滤波（Auto-wah）单块获取经典放克弹性扫弦", "将 Slap 贝斯击弦点与底鼓踏板对齐在同一节拍网格上"]}},

  {"id": "gypsy-jazz", "name": "Gypsy Jazz", "aliases": ["吉普赛爵士", "Jazz Manouche"], "category": "Jazz/Blues", "year": "1930", "bpm": "130–240 BPM", "default_bpm": 160, "style": "standard", "place": {"en": "Paris, France", "zh": "法国巴黎"},
   "artists": ["Django Reinhardt", "Stéphane Grappelli", "Biréli Lagrène", "Stochelo Rosenberg", "Angelo Debarre"],
   "context": {"en": "Created in 1930s Paris by guitarist Django Reinhardt and violinist Stéphane Grappelli, featuring acoustic Selmer guitars, soaring violin, and percussive rhythm chops.", "zh": "由吉他大师 Django Reinhardt 与小提琴大师 Stéphane Grappelli 于 1930 年代巴黎开创，以塞莫尔原声吉他、飞扬小提琴与打击乐般的扫弦（La Pompe）闻名。"},
   "soundDesign": {"en": "Selmer-Maccaferri acoustic guitars, passionate violin solos, acoustic upright bass.", "zh": "Selmer-Maccaferri D孔原声吉他、深情飞舞的小提琴独奏与原声低音提琴。"},
   "rhythmFeatures": {"en": "The signature 'La Pompe' rhythm guitar chop that functions as the drum kit with tight percussive downstrokes.", "zh": "标志性的 'La Pompe' 节奏吉他扫弦：充当架子鼓功能，以干净利落的下扫切音提供律动。"},
   "bassPattern": {"en": "Pumping 2-beat or 4-beat upright acoustic bass keeping steady swing time.", "zh": "沉稳弹奏的二拍或四拍原声低音提琴，维持坚如磐石的摇摆时值。"},
   "productionTips": {"en": ["Master the 'La Pompe' rhythm: quick downstroke on beat 1, heavy percussive chop on beat 2", "Use heavy, rounded guitar picks on acoustic Selmer guitars for loud acoustic volume", "Record violin and lead guitar with ribbon mics to avoid harsh high frequencies"], "zh": ["精通 'La Pompe' 扫弦：第 1 拍短促轻扫，第 2 拍重力打击切音替代军鼓", "在塞莫尔原声吉他上使用超厚水滴拨片获取巨大原声音量与圆润音色", "使用铝带话筒录制小提琴与主音吉他，避免高频刺耳"]}}
]

pop_rnb_list = [
  {"id": "traditional-pop", "name": "Traditional Pop", "aliases": ["传统流行", "经典声乐流行"], "category": "Pop/R&B", "year": "1940", "bpm": "70–120 BPM", "default_bpm": 95, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Frank Sinatra", "Tony Bennett", "Nat King Cole", "Ella Fitzgerald", "Dean Martin"],
   "context": {"en": "The golden age of the Great American Songbook, defined by lush big band orchestrations, string arrangements, and charismatic crooner vocal delivery.", "zh": "美国流行金曲簿的黄金年代，以恢弘的爵士大乐队管弦编配、交响弦乐与魅力十足的低音吟唱者（Crooner）唱腔为标志。"},
   "soundDesign": {"en": "Full symphonic string sections, big band brass, grand acoustic piano, upright bass.", "zh": "全交响弦乐声部、大乐队铜管阵列、三角大钢琴与原声低音提琴。"},
   "rhythmFeatures": {"en": "Gentle, elegant 4/4 swing rhythm played with soft wire brushes on snare drums.", "zh": "典雅从容的四四拍摇摆节拍，由软钢丝鼓刷在军鼓上细腻勾勒。"},
   "bassPattern": {"en": "Warm, resonant walking upright basslines supporting rich harmonic modulations.", "zh": "温暖醇厚的行进低音提琴线条，稳固托起丰富的和声离调与转调。"},
   "productionTips": {"en": ["Record lead vocals with a vintage tube condenser microphone (Telefunken U47 style)", "Arrange string sections with rich contrary motion to support the vocal line", "Allow the tempo to breathe naturally with emotional rubato passages"], "zh": ["使用经典电子管大振膜话筒实录主唱，捕捉丝绒般的醇厚胸腔共鸣", "弦乐声部采用丰富的反向进行织体，烘托人声起伏", "在抒情高潮段落允许速度有细微的人性化弹性速度（Rubato）起伏"]}},

  {"id": "synth-pop", "name": "Synth-pop", "aliases": ["合成器流行"], "category": "Pop/R&B", "year": "1977", "bpm": "115–130 BPM", "default_bpm": 120, "style": "four_on_floor", "place": {"en": "UK & Germany", "zh": "英国与德国"},
   "artists": ["Depeche Mode", "New Order", "Pet Shop Boys", "Eurythmics", "The Human League"],
   "context": {"en": "Pioneered in late-70s Europe, replacing traditional rock guitars with synthesizers and drum machines while crafting brilliant commercial pop hooks.", "zh": "70 年代末欧洲开创，用电子合成器与鼓机全面取代传统摇滚吉他，打造出传唱不衰的商业流行金曲。"},
   "soundDesign": {"en": "Roland Juno-60 pads, Minimoog bass, LinnDrum snares, bright analog synthesizer hooks.", "zh": "Roland Juno-60 温暖铺底、Minimoog 贝斯、LinnDrum 经典军鼓与明亮合成主音 Hook。"},
   "rhythmFeatures": {"en": "Driving, mechanical 4/4 rhythm sequenced on drum machines with snappy claps on 2 and 4.", "zh": "由电子鼓机精确量化的四四拍律动，2、4 拍上伴随清脆干练的拍手。"},
   "bassPattern": {"en": "Sequenced 16th-note analog basslines running continuously with bright filter envelopes.", "zh": "连续音序化的十六分音符模拟合成贝斯，带有明朗开合的滤波包络。"},
   "productionTips": {"en": ["Sequence repetitive 16th-note basslines on an analog monosynth for driving momentum", "Layer classic LinnDrum or Simmons electronic drum sounds", "Write catchy, bittersweet vocal hooks in minor keys"], "zh": ["在模拟单音合成器上编写重复的十六分音符低音线条，带来机械推进力", "叠入经典 LinnDrum 或 Simmons 标志性电子打击乐音色", "创作小调色彩、兼具甜美与伤感的过耳不忘副歌旋律"]}},

  {"id": "disco", "name": "Disco", "aliases": ["迪斯科"], "category": "Pop/R&B", "year": "1970", "bpm": "115–130 BPM", "default_bpm": 120, "style": "four_on_floor", "place": {"en": "New York & Philadelphia, USA", "zh": "美国纽约与费城"},
   "artists": ["Donna Summer", "Bee Gees", "Chic (Nile Rodgers)", "ABBA", "Earth, Wind & Fire"],
   "context": {"en": "Born in 1970s New York and Philadelphia clubs, defining dance music forever with four-on-the-floor kicks, soaring string sections, and Nile Rodgers funk guitar.", "zh": "70 年代诞生于纽约与费城俱乐部，以开创性的四四拍（Four-on-the-floor）底鼓、翱翔交响弦乐与 Nile Rodgers 放克吉他永远重塑了全球舞曲。"},
   "soundDesign": {"en": "Soaring orchestral disco strings, Nile Rodgers chucking guitar, slap bass, orchestral brass.", "zh": "翱翔起伏的迪斯科交响弦乐、Nile Rodgers 标志性切音放克吉他、Slap 电贝斯与嘹亮铜管。"},
   "rhythmFeatures": {"en": "The iconic four-on-the-floor kick with open hi-hats on every upbeat and syncopated snare claps.", "zh": "标志性四踩四底鼓，每一个反拍敲击清脆开镲，第 2、4 拍军鼓与拍手齐鸣。"},
   "bassPattern": {"en": "Active, syncopated, walking octave basslines playing constant dancefloor grooves.", "zh": "极度活跃、富于切分、充满八度跳跃的行进贝斯，驱动舞池狂欢。"},
   "productionTips": {"en": ["Arrange authentic disco strings: fast ascending octave runs into sustained high notes", "Record electric guitar playing sixteenth-note muted funk rhythm (the Chic 'chank')", "Place open hi-hats consistently on the 'and' of every beat"], "zh": ["编配正统迪斯科弦乐：极速八度爬升大滑弦随后切入高音长延音", "实录电吉他十六分音符闷音放克扫弦（Nile Rodgers 招牌技法）", "踩镲严格在每一拍的后半拍打开开镲（Open Hat）形成吸吐感"]}},

  {"id": "eurodance", "name": "Eurodance", "aliases": ["欧陆舞曲"], "category": "Pop/R&B", "year": "1989", "bpm": "135–145 BPM", "default_bpm": 140, "style": "four_on_floor", "place": {"en": "Europe", "zh": "欧洲"},
   "artists": ["2 Unlimited", "Snap!", "Culture Beat", "Corona", "Haddaway"],
   "context": {"en": "Swept 1990s Europe and the world, combining 140 BPM four-on-the-floor beats with high-energy rap verses and anthemic female vocal choruses.", "zh": "90 年代横扫全球，将 140 BPM 四踩四狂飙节拍、高能说唱主歌与女性大主唱史诗级洗脑副歌完美结合。"},
   "soundDesign": {"en": "Korg M1 piano chords, Roland JP-8000 supersaws, energetic male rap, soaring female vocals.", "zh": "Korg M1 亮丽大钢琴切片、Roland JP-8000 狂飙 Supersaw、硬核男性说唱与高亢女性主唱。"},
   "rhythmFeatures": {"en": "Fast, high-octane 140 BPM four-on-the-floor kick with driving offbeat open hats.", "zh": "高速高能的 140 BPM 四踩四底鼓，伴随充满前冲推力的反拍开镲。"},
   "bassPattern": {"en": "Punchy offbeat bassline or fast rolling 16th saw bass driving underneath piano chords.", "zh": "强劲反拍低音或快速滚动的十六分音符锯齿波贝斯，在钢琴和弦下方飞驰。"},
   "productionTips": {"en": ["Structure songs with an aggressive rap verse followed by a euphoric female sung hook", "Layer bright sampled M1 piano stabs across the quarter beats", "Keep the kick drum punchy and loud at 140 BPM"], "zh": ["采用经典曲式编排：充满压迫感的说唱主歌无缝衔接极度明亮的唱诗般副歌", "在四分音符强拍上叠置明亮 Korg M1 采样钢琴切片", "让底鼓在 140 BPM 高速下保持短促结实与极高响度"]}},

  {"id": "funk", "name": "Funk", "aliases": ["放克音乐"], "category": "Pop/R&B", "year": "1965", "bpm": "95–115 BPM", "default_bpm": 105, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["James Brown", "Parliament-Funkadelic", "Sly and the Family Stone", "The Meters", "Kool & The Gang"],
   "context": {"en": "Pioneered by James Brown in the mid-1960s, shifting musical emphasis from melody and harmony to a complex, interlocking rhythmic groove anchored on 'The One'.", "zh": "由 James Brown 于 1960 年代中期奠定，将音乐重心从旋律和声转移到以第 1 拍重音（The One）为核心的交错复合节奏律动中。"},
   "soundDesign": {"en": "Tight brass horn stabs, syncopated slap bass, clavinet through auto-wah, clean rhythm guitar.", "zh": "短促尖锐的铜管切片、切分 Slap 贝斯、过载自动哇音电古钢琴与清脆电吉他。"},
   "rhythmFeatures": {"en": "The One: massive downbeat impact on beat 1, followed by syncopated polyrhythmic funk pockets.", "zh": "“The One”哲学：第 1 拍绝对重击，随后展开千变万化切分交错的放克凹槽律动。"},
   "bassPattern": {"en": "Virtuosic, highly syncopated slap, pop, and fingerstyle basslines that lead the dance groove.", "zh": "大师级击勾弦（Slap & Pop）与指弹贝斯，直接统领舞曲律动灵魂。"},
   "productionTips": {"en": ["Make beat 1 undeniable: every instrument locks together on the downbeat of bar 1", "Use muted, scratching 16th-note rhythm guitar chops ('skank')", "Layer horn section hits tightly together with minimal reverb"], "zh": ["把第 1 拍做到无可撼动：所有乐器在第 1 小节首拍坚决合击", "节奏吉他采用十六分音符闷音轻微刮弦扫弦（Skank 技巧）", "铜管合奏切片保持高度干燥紧凑，避免大混响稀释冲击力"]}},

  {"id": "soul", "name": "Soul", "aliases": ["灵魂乐"], "category": "Pop/R&B", "year": "1955", "bpm": "70–115 BPM", "default_bpm": 95, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Aretha Franklin", "Otis Redding", "Ray Charles", "Sam Cooke", "Al Green"],
   "context": {"en": "Born out of African-American gospel music and rhythm and blues in the 1950s, defined by passionate, melismatic vocal delivery and deep emotional authenticity.", "zh": "1950 年代由非裔美国福音音乐与节奏布鲁斯融合诞生，以深情充沛的真挚花腔唱腔与触及灵魂的情感震撼世界。"},
   "soundDesign": {"en": "Warm Hammond B3 organ with Leslie speaker, real horn section, electric guitar, upright/Fender bass.", "zh": "连接莱斯利旋转扬声器的 Hammond B3 电子管风琴、真实铜管组、电吉他与贝斯。"},
   "rhythmFeatures": {"en": "Soulful 4/4 or 6/8 ballad groove with prominent backbeat tambourine and expressive drums.", "zh": "深情 4/4 或 6/8 拍慢板律动，伴随突出的后拍手摇铃与极具呼吸感的鼓组。"},
   "bassPattern": {"en": "Deep, lyrical electric basslines that melodically interact with the lead vocal phrases.", "zh": "深沉优美的旋律化电贝斯线条，与主唱唱段如同知己般交织唱和。"},
   "productionTips": {"en": ["Capture vocal performances without pitch correction to preserve raw emotional vibrato", "Use a real Leslie speaker simulator on the Hammond organ chords", "Place tambourine hits firmly on beats 2 and 4 alongside the snare"], "zh": ["完全杜绝人声音高修正插件，完整保留真实颤音与情感裂纹", "为 Hammond 风琴和弦加载真实的莱斯利旋转箱体立体声漫游效果", "在第 2、4 拍军鼓敲击瞬间精准叠加现场手摇铃提升亮度"]}},

  {"id": "neo-soul", "name": "Neo-Soul", "aliases": ["新灵魂乐"], "category": "Pop/R&B", "year": "1995", "bpm": "75–95 BPM", "default_bpm": 85, "style": "breakbeat", "place": {"en": "USA", "zh": "美国"},
   "artists": ["D'Angelo", "Erykah Badu", "Lauryn Hill", "Maxwell", "Jill Scott"],
   "context": {"en": "Pioneered in mid-90s by The Soulquarians (D'Angelo, J Dilla, Questlove), merging classic 70s soul with hip-hop beats, jazz chords, and deep groove pocket.", "zh": "由 Soulquarians 艺术家团体（D'Angelo、J Dilla、Questlove）在 90 年代中期开创，将 70 年代经典灵魂乐与嘻哈鼓点、爵士九和弦及深邃后倾律动交织。"},
   "soundDesign": {"en": "Fender Rhodes electric piano, unquantized live drums, warm bass guitar, subtle vocal layers.", "zh": "Fender Rhodes 电钢琴、未量化后倾现场原声鼓、温暖电贝斯与多轨和声人声。"},
   "rhythmFeatures": {"en": "Signature drunken, lazy, behind-the-beat swing (the D'Angelo / Questlove pocket).", "zh": "标志性微醺拖沓、深陷拍子后方的懒散摇摆律动（极具辨识度的 Questlove 节拍口袋）。"},
   "bassPattern": {"en": "Warm, fat, fingerstyle basslines played slightly behind the beat with lush low-mids.", "zh": "温暖饱满的指弹电贝斯线条，稍稍滞后于节拍点演奏，低频醇厚。"},
   "productionTips": {"en": ["Shift the snare drum 10-25 milliseconds later than the grid for that iconic lazy pocket", "Stack minor 9th and major 9th chords on a warm Rhodes electric piano", "Layer 4-8 tracks of tight vocal harmonies with subtle stereo panning"], "zh": ["将小军鼓比标准量化网格刻意延后 10-25 毫秒营造经典后倾拖泥带水感", "在温暖 Rhodes 电钢琴上弹奏延展的小九与大九和弦", "叠录 4-8 轨极其严谨的人声和声并做细腻立体声展开"]}},

  {"id": "contemporary-rnb", "name": "Contemporary R&B", "aliases": ["当代节奏布鲁斯"], "category": "Pop/R&B", "year": "1980", "bpm": "90–120 BPM", "default_bpm": 100, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Beyoncé", "Usher", "Whitney Houston", "R. Kelly", "Bruno Mars"],
   "context": {"en": "Evolved from soul and disco in the 1980s, combining electronic drum programming (TR-808), melismatic vocal virtuosity, and slick modern pop production.", "zh": "80 年代脱胎于灵魂乐与迪斯科，将电子鼓机编曲（TR-808）、高超花腔转音与现代精致流行舞曲制作融为一体。"},
   "soundDesign": {"en": "Roland TR-808 kicks and claps, lush digital synth pads, polished melismatic vocals.", "zh": "Roland TR-808 弹跳底鼓与拍手、精致现代数字铺底与精修花腔人声。"},
   "rhythmFeatures": {"en": "Bouncy, syncopated R&B groove with crisp electronic claps on beats 2 and 4.", "zh": "充满弹性跳跃感的切分 R&B 律动，在 2、4 拍击打清脆现代合成拍手。"},
   "bassPattern": {"en": "Smooth, rounded synth bass or deep 808 sub driving modern pop arrangements.", "zh": "圆润顺滑的合成低音或深沉 808 超低频，稳健推动现代流行曲式。"},
   "productionTips": {"en": ["Tune and tighten lead vocal tracks with modern pitch correction software while keeping expressive runs", "Layer layered background vocal stacks (lead, harmony high, harmony low)", "Sidechain bass gently to the kick drum"], "zh": ["使用现代修音软件对主唱音轨进行微调，同时完整保留华丽花腔转音", "多层堆叠背景和声体系（主声部、高三度、低八度）", "贝斯对底鼓进行温和侧链避让保持整体平滑通透"]}},

  {"id": "alternative-rnb", "name": "Alternative R&B", "aliases": ["另类节奏布鲁斯", "暗黑 R&B"], "category": "Pop/R&B", "year": "2010", "bpm": "110–135 BPM", "default_bpm": 120, "style": "half_time", "place": {"en": "USA & Canada", "zh": "美国与加拿大"},
   "artists": ["Frank Ocean", "The Weeknd", "SZA", "FKA twigs", "Jhené Aiko"],
   "context": {"en": "Emerged around 2011 led by Frank Ocean and The Weeknd, trading glossy pop R&B for moody atmospheres, pitch-shifted vocals, druggy synths, and indie songwriting.", "zh": "2011 年由 Frank Ocean 与 The Weeknd 引爆，舍弃甜美流行套路，换以幽暗电影氛围、变调人声、微醺迷幻合成器与自省独立创作。"},
   "soundDesign": {"en": "Filtered ambient synth pads, pitch-shifted vocal chops, murky sub-bass, underwater reverbs.", "zh": "经过深低通滤波的氛围铺底、变速变调人声微粒、深沉 Sub 贝斯与水下空间混响。"},
   "rhythmFeatures": {"en": "Spacious, slow-burning half-time beats with rolling hi-hats and muffled snares.", "zh": "开阔深邃、慢火慢炖的半速节拍，伴随细致踩镲滚奏与沉闷低调军鼓。"},
   "bassPattern": {"en": "Deep, rumbling 808 subs or warm Reese bass humming under dark minor progressions.", "zh": "深邃轰鸣的 808 超低频或在暗黑小调和弦下方低徊沉沦的温暖 Reese 贝斯。"},
   "productionTips": {"en": ["Apply a low-pass filter to the entire master drum bus to create an intimate, underwater sound", "Pitch-shift vocal doubles down 12 semitones with formant preservation for dark undertones", "Drench instruments in dark plate reverbs"], "zh": ["在鼓组总线上挂载低通滤波器营造亲密耳语般的水下沉浸听感", "将副人声音轨向下移调 12 个半音（低八度）并保留共振峰增添暗黑色彩", "将乐器浸润在暗黑板式混响中制造迷离空间"]}},

  {"id": "motown", "name": "Motown", "aliases": ["摩城音乐", "底特律灵魂乐"], "category": "Pop/R&B", "year": "1959", "bpm": "115–135 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "Detroit, Michigan, USA", "zh": "美国密歇根州底特律"},
   "artists": ["Stevie Wonder", "Marvin Gaye", "The Supremes", "The Temptations", "The Jackson 5"],
   "context": {"en": "Founded by Berry Gordy in Detroit ('Hitsville U.S.A.'), creating an iconic crossover sound with driving tambourines, melodic basslines, and gospel pop harmonies.", "zh": "由 Berry Gordy 在底特律创立，以极具推进力的手摇铃反拍、James Jamerson 的传世旋律贝斯与福音流行和声书写了辉煌奇迹。"},
   "soundDesign": {"en": "Fender Precision Bass through direct-box, driving tambourines, acoustic piano, vibraphone.", "zh": "Fender Precision 电贝斯直通（DI）录音、驱动性手摇铃、原声钢琴与颤音琴。"},
   "rhythmFeatures": {"en": "Incessant four-beat tambourine pulse with driving 4/4 snare claps and foot stomps.", "zh": "永不停歇的四拍连贯手摇铃脉冲，配合极富推进力的四四拍军鼓拍手。"},
   "bassPattern": {"en": "Legendary James Jamerson one-finger 'The Hook' syncopated, walking, melodic basslines.", "zh": "传奇乐手 James Jamerson 单指演奏的极富表现力、切分行进且极具歌唱性的神级贝斯线条。"},
   "productionTips": {"en": ["Use flatwound bass strings on a Fender P-bass and record direct into a vintage tube preamp", "Layer a bright tambourine on every beat (beats 1, 2, 3, 4) to propel the tempo", "Double the bassline with a muted acoustic baritone guitar"], "zh": ["在芬达 P-bass 上使用纯平卷琴弦（Flatwound）并直入复古电子管前级放大", "在每一拍（1、2、3、4拍）均匀叠加清亮手摇铃敲击以推动步频", "用弱音原声男低音吉他齐奏贝斯线条勾勒清晰轮廓"]}},

  {"id": "city-pop", "name": "City Pop", "aliases": ["城市流行"], "category": "Pop/R&B", "year": "1975", "bpm": "110–125 BPM", "default_bpm": 118, "style": "four_on_floor", "place": {"en": "Tokyo, Japan", "zh": "日本东京"},
   "artists": ["Tatsuro Yamashita", "Mariya Takeuchi", "Miki Matsubara", "Toshiki Kadomatsu", "Anri"],
   "context": {"en": "Boomed during Japan's 1970s/80s economic bubble, celebrating sophisticated metropolitan lifestyles with a lush fusion of funk, disco, soft rock, and jazz chords.", "zh": "繁盛于日本 70、80 年代经济黄金期，融合放克、迪斯科、轻摇滚与精致爵士和弦，歌唱大都会繁华都市夜生活与海滨浪漫。"},
   "soundDesign": {"en": "Sparkling Roland Rhodes electric piano, lush brass horns, slap bass, tight studio drums.", "zh": "晶莹明澈的电钢琴、华丽铜管阵列、放克 Slap 贝斯与精细棚录原声鼓。"},
   "rhythmFeatures": {"en": "Breezy, sophisticated 4/4 disco-funk groove with syncopated open hats and crisp snare.", "zh": "微风拂面般轻快考究的四四拍迪斯科放克律动，反拍开镲清脆利落。"},
   "bassPattern": {"en": "Virtuosic slap and pop funk basslines weaving through complex jazz chord transitions.", "zh": "大师级 Slap & Pop 放克电贝斯线条，游刃有余穿行于复杂爵士和弦过门之中。"},
   "productionTips": {"en": ["Utilize the 'Royal Road' chord progression (IVmaj7 - V7 - iiim7 - vim7) with sophisticated extensions", "Record live brass horn sections with wide stereo panning", "Use clean, compressed chorus guitars playing funky 16th-note chucks"], "zh": ["使用“王道进行”（IVmaj7 - V7 - iiim7 - vim7）并加入丰润扩展音", "实录现场铜管大编制声部并做华丽立体声左右拉宽", "电吉他挂载通透合唱效果器弹奏跳跃轻盈的十六分音符放克切音"]}},

  {"id": "k-pop", "name": "K-Pop", "aliases": ["韩国流行音乐"], "category": "Pop/R&B", "year": "1992", "bpm": "110–135 BPM", "default_bpm": 125, "style": "four_on_floor", "place": {"en": "Seoul, South Korea", "zh": "韩国首尔"},
   "artists": ["BTS", "BLACKPINK", "NewJeans", "EXO", "TWICE"],
   "context": {"en": "A globally dominant multi-genre spectacle originating from Seoul, characterized by hyper-polished production, sudden genre shifts within a single song, and choreography.", "zh": "从首尔走向全球的多元流派盛宴，以千锤百炼的极致工业制作、一首歌内戏剧性的跨流派突变与高能编舞著称。"},
   "soundDesign": {"en": "High-budget modern synthesizer stacks, processed vocal hooks, trap 808s, punchy modern drums.", "zh": "顶尖现代合成器音色堆叠、精细打磨人声 Hook、Trap 808 低音与现代高冲击力鼓组。"},
   "rhythmFeatures": {"en": "Dynamic rhythm switching frequently between four-on-the-floor house, half-time trap, and EDM drops.", "zh": "极度动态的节奏变换，在四踩四浩室、半速 Trap 与电子爆发之间自如穿梭切换。"},
   "bassPattern": {"en": "Massive modern synth basslines shifting seamlessly from FM plucks to sliding 808s.", "zh": "震撼现代合成贝斯线条，在清脆 FM 弹拨与下沉滑音 808 之间无缝流转。"},
   "productionTips": {"en": ["Introduce distinct musical genres in different sections (e.g. house verse, trap pre-chorus, rock drop)", "Process vocal chops with intense pitch and formant manipulation", "Maximize master loudness while maintaining crisp transient punch"], "zh": ["在不同段落大胆拼接截然不同的音乐风格（如浩室主歌+Trap过渡+摇滚爆发）", "对人声切片施加极致的音高与共振峰调制打造未来感", "在确保瞬态清脆有力的前提下将母带响度推向商业发行极致"]}},

  {"id": "j-pop", "name": "J-Pop", "aliases": ["日本流行音乐"], "category": "Pop/R&B", "year": "1988", "bpm": "120–170 BPM", "default_bpm": 145, "style": "standard", "place": {"en": "Tokyo, Japan", "zh": "日本东京"},
   "artists": ["Hikaru Utada", "YOASOBI", "Kenshi Yonezu", "Ayumi Hamasaki", "Official HIGE DANDISM"],
   "context": {"en": "Evolved from Kayōkyoku and City Pop, famous for rapid chord modulations, intricate melodic lines, anime theme power, and complex emotional songwriting.", "zh": "脱胎于昭和歌谣曲与 City Pop，以高速和弦调性转调、精细跌宕的优美旋律线、动漫主题曲感染力与宏大和声著称。"},
   "soundDesign": {"en": "Acoustic grand piano fast runs, strings, bright distorted guitars, punchy electronic drums.", "zh": "三角大钢琴高速跑音、交响弦乐合奏、明亮失真吉他与清脆电子鼓组。"},
   "rhythmFeatures": {"en": "High-speed 140-165 BPM driving rock-pop beats with tight snare accents and rapid hi-hats.", "zh": "时速 140-165 BPM 的高速推进摇滚流行节拍，伴随紧凑军鼓与飞驰踩镲。"},
   "bassPattern": {"en": "Hyperactive melodic walking basslines weaving between fast jazz chord changes.", "zh": "极度活跃、兼具歌唱性的旋律行进贝斯，穿梭在极速爵士和声转换中。"},
   "productionTips": {"en": ["Compose with the Royal Road chord progression and frequent half-step key changes", "Write hyper-melodic basslines that act as a second lead instrument", "Layer sweeping orchestral strings with fast rock drum kits"], "zh": ["巧妙运用王道和弦进行并在副歌前加入半音突然转调（Key Change）", "编写高度旋律化的贝斯线条，使其宛如第二主旋律般歌唱", "将恢弘交响弦乐与高速摇滚架子鼓精密贴合叠层"]}}
]

latin_world_list = [
  {"id": "salsa", "name": "Salsa", "aliases": ["萨尔萨音乐"], "category": "Latin/World", "year": "1965", "bpm": "160–220 BPM", "default_bpm": 180, "style": "standard", "place": {"en": "New York, Cuba & Puerto Rico", "zh": "纽约、古巴与波多黎各"},
   "artists": ["Celia Cruz", "Héctor Lavoe", "Willie Colón", "Tito Puente", "Fania All-Stars"],
   "context": {"en": "Developed in 1960s New York by Cuban and Puerto Rican immigrants, structured around the sacred Clave rhythm with furious brass, montuno piano, and congas.", "zh": "1960 年代由古巴与波多黎各移民在纽约确立，以神圣的克拉维节奏（Clave）为骨架，伴随咆哮铜管、Montuno 钢琴与康加鼓。"},
   "soundDesign": {"en": "Acoustic congas (tumbao), bongo, timbales, piano montuno, bright trumpet section.", "zh": "康加鼓 Tumbao 律动、邦戈鼓、天巴鼓、Montuno 钢琴琶音与明亮小号乐组。"},
   "rhythmFeatures": {"en": "Structured strictly around the 3:2 or 2:3 Son Clave with complex syncopated polyrhythms.", "zh": "严格围绕 3:2 或 2:3 的 Son Clave 击拍为核心，展开复杂的切分多重打击乐。"},
   "bassPattern": {"en": "The iconic 'Tumbao' bass: anticipating the root on the offbeat of beat 2 and beat 4, avoiding beat 1.", "zh": "标志性 Tumbao 贝斯：刻意避开第 1 拍，而在第 2 拍反拍与第 4 拍提前预击根音。"},
   "productionTips": {"en": ["Lock the entire arrangement strictly to either 3:2 or 2:3 Clave orientation", "The bass must play the anticipatory Tumbao pattern (silent on 1, hitting on 4)", "Layer timbales fills right before brass horn section explosions"], "zh": ["整首编曲必须严格统一遵循 3:2 或 2:3 的 Clave 律动朝向", "贝斯必须演奏标志性抢拍 Tumbao 律动（第 1 拍休止，在第 4 拍重弹）", "在铜管爆发前安插华丽的天巴鼓滚奏（Abanico）"]}},

  {"id": "bachata", "name": "Bachata", "aliases": ["巴恰塔"], "category": "Latin/World", "year": "1961", "bpm": "115–140 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "Dominican Republic", "zh": "多米尼加共和国"},
   "artists": ["Aventura", "Romeo Santos", "Juan Luis Guerra", "Prince Royce", "Frank Reyes"],
   "context": {"en": "Born in the rural Dominican Republic, evolving into a global romantic sensation driven by intricate acoustic Requinto guitar arpeggios, bongo, and güira.", "zh": "诞生于多米尼加乡村，由精致凄美的小吉他（Requinto）分解琶音、邦戈鼓与金属刮器（Güira）驱动，演化为全球浪漫舞曲。"},
   "soundDesign": {"en": "Requinto acoustic guitar with chorus pedal, bongo, güira metal scraper, electric bass.", "zh": "挂接合唱单块的 Requinto 木吉他、邦戈鼓、金属刮管（Güira）与电贝斯。"},
   "rhythmFeatures": {"en": "4/4 Latin rhythm characterized by the iconic bongo syncopation with pop accent on beat 4.", "zh": "4/4 拍拉丁律动，第 4 拍上带有鲜明跳跃的重音提拍。"},
   "bassPattern": {"en": "Syncopated, melodic bassline playing root on beat 1 and hopping rhythmically onto beat 4.", "zh": "切分悦耳的贝斯线条，在第 1 拍落根音，并在第 4 拍伴随人声轻盈起跳。"},
   "productionTips": {"en": ["Apply vintage stereo chorus to the acoustic Requinto lead guitar for authentic modern tone", "The güira metal scraper must carry a continuous 16th-note driving friction rhythm", "Accent the 4th beat with an open bongo pop"], "zh": ["为原声小吉他挂载复古立体声合唱单块获得现代标志音色", "金属刮管（Güira）必须持续演奏推进性的十六分音符摩擦律动", "在第 4 拍用开音邦戈鼓击打强调标志性起拍"]}},

  {"id": "reggae", "name": "Reggae", "aliases": ["雷鬼乐"], "category": "Latin/World", "year": "1968", "bpm": "60–90 BPM", "default_bpm": 75, "style": "standard", "place": {"en": "Kingston, Jamaica", "zh": "牙买加金斯敦"},
   "artists": ["Bob Marley & The Wailers", "Peter Tosh", "Burning Spear", "Dennis Brown", "Black Uhuru"],
   "context": {"en": "Originated in late-60s Kingston out of rocksteady and ska, anchored by Rastafari spirituality, the signature One-Drop drum beat, and offbeat guitar skanks.", "zh": "60 年代末发源于牙买加金斯敦，依托拉斯塔法里精神，以标志性的 One-Drop 鼓点与反拍吉他切弦（Skank）重塑世界音乐。"},
   "soundDesign": {"en": "Offbeat chop guitar (skank), Hammond organ bubble, heavy flatwound electric bass, rimshots.", "zh": "反拍切音吉他（Skank）、Hammond 管风琴气泡弹奏、纯平卷弦重低音贝斯与边击军鼓。"},
   "rhythmFeatures": {"en": "The iconic 'One Drop' beat: the kick and snare hit together strictly on beat 3 while beat 1 is silent.", "zh": "标志性 'One Drop' 鼓点：第 1 拍完全留空，底鼓与军鼓在第 3 拍同时重击下坠。"},
   "bassPattern": {"en": "Deep, foundational, highly melodic electric basslines that define the song identity.", "zh": "深沉圆润、作为整首歌曲灵魂支柱的旋律化电贝斯线条。"},
   "productionTips": {"en": ["Never hit the kick on beat 1; let the bassline and rhythm guitar carry the downbeat", "Double the offbeat guitar skank with a Hammond organ 'bubble' on the 16th-note upbeats", "Keep the bass tone warm by cutting high frequencies above 1kHz"], "zh": ["第 1 拍坚决不敲底鼓，让贝斯与反拍吉他承载首拍律动", "反拍吉他切弦与 Hammond 风琴十六分音符气泡弹奏紧密咬合", "彻底切除贝斯 1kHz 以上的高频，只保留醇厚如大地的低频"]}},

  {"id": "dancehall", "name": "Dancehall", "aliases": ["舞厅雷鬼"], "category": "Latin/World", "year": "1977", "bpm": "90–115 BPM", "default_bpm": 100, "style": "half_time", "place": {"en": "Kingston, Jamaica", "zh": "牙买加金斯敦"},
   "artists": ["Sean Paul", "Vybz Kartel", "Shabba Ranks", "Buju Banton", "Popcaan"],
   "context": {"en": "Evolved from reggae with digital Casio MT-40 riddims (Sleng Teng), energetic deejay toasting, hard synthetic drums, and raw party energy.", "zh": "脱胎于雷鬼，以 Casio MT-40 键盘开创的数码 Riddim（如 Sleng Teng）为里程碑，具备狂野喊麦与硬朗电子鼓组。"},
   "soundDesign": {"en": "Casio/Yamaha digital synths, crisp synthesized rimshots, heavy sub-bass, vocal toasting.", "zh": "卡西欧复古数字合成器、清脆合成边击军鼓、超重 Sub 贝斯与牙买加土语喊麦。"},
   "rhythmFeatures": {"en": "Syncopated digital riddim with kick on 1 and offbeat snare syncopations (precursor to dembow).", "zh": "切分数码 Riddim 节拍，第 1 拍底鼓配合反拍切分军鼓（Dembow 律动直系鼻祖）。"},
   "bassPattern": {"en": "Heavy, repetitive synthesized sub-bass loops providing colossal sound system pressure.", "zh": "厚重重复的合成超低频循环，专为牙买加户外巨型音响系统震颤而生。"},
   "productionTips": {"en": ["Create memorable 1-bar or 2-bar riddim bass loops that repeat hypnotically", "Layer short wooden rimshots with digital snares", "Leave plenty of sonic room for energetic vocal toasting"], "zh": ["打造极具记忆点的 1 小节或 2 小节洗脑 Riddim 低音循环", "将短小原声木质边击与数字军鼓紧密叠层", "为人声高速机关枪般的吐字留出宽裕的听觉空间"]}},

  {"id": "reggaeton", "name": "Reggaeton", "aliases": ["雷鬼顿"], "category": "Latin/World", "year": "1994", "bpm": "88–100 BPM", "default_bpm": 95, "style": "half_time", "place": {"en": "Puerto Rico & Panama", "zh": "波多黎各与巴拿马"},
   "artists": ["Daddy Yankee", "Bad Bunny", "J Balvin", "Don Omar", "Ozuna"],
   "context": {"en": "Born in Puerto Rico fusing Jamaican dancehall, hip-hop, and Latin rhythms around the infectious 4/4 Dembow drum beat.", "zh": "诞生于波多黎各地下俱乐部，将牙买加舞厅雷鬼、嘻哈与拉丁旋律围绕洗脑的 Dembow 鼓点熔合。"},
   "soundDesign": {"en": "Signature Dembow snare, synth brass, pitched autotuned vocals, deep 808 sub-bass.", "zh": "标志性 Dembow 军鼓切音、合成铜管、自动修音热带人声与深沉 808 超低音。"},
   "rhythmFeatures": {"en": "The iconic Dembow beat: 4/4 kick pulse paired with syncopated snare hits on beats 2-and and 4-and (boom-ch-boom-chick).", "zh": "传世 Dembow 律动：坚实的四四拍底鼓配合附点反拍军鼓（咚-恰-咚-恰）。"},
   "bassPattern": {"en": "Deep, warm sub-bass or 808 slides following the Dembow swing.", "zh": "深沉温暖的 Sub 低音或带有顺滑滑音的 808，紧随 Dembow 摇摆。"},
   "productionTips": {"en": ["Program the Dembow snare: dotted 8th note followed by a 16th note against the steady 4/4 kick", "Use synthesized brass stabs or minor piano chords for the main harmony", "Keep the mix clean and club-focused"], "zh": ["编写 Dembow 军鼓：稳健四踩四底鼓上覆盖附点八分音符接十六分音符军鼓", "使用合成铜管刺音或暗色小调钢琴构建主和声", "混音保持清脆透亮，低频在俱乐部大功率音响上直击胸膛"]}},

  {"id": "afrobeat", "name": "Afrobeat", "aliases": ["非洲节拍"], "category": "Latin/World", "year": "1968", "bpm": "110–130 BPM", "default_bpm": 120, "style": "standard", "place": {"en": "Lagos, Nigeria", "zh": "尼日利亚拉各斯"},
   "artists": ["Fela Kuti", "Tony Allen", "Antibalas", "Seun Kuti", "Femi Kuti"],
   "context": {"en": "Created in late-60s Lagos by Fela Kuti and legendary drummer Tony Allen, fusing Yoruba polyrhythms, funk, jazz, and political resistance.", "zh": "由 Fela Kuti 与传奇鼓手 Tony Allen 在拉各斯开创，将约鲁巴传统复合节奏、放克、爵士与反抗精神凝为史诗。"},
   "soundDesign": {"en": "Large big-band brass horns, interlocking funk guitars, organic percussion (claves, shekere), electric piano.", "zh": "大型大乐队铜管阵列、交错对位放克吉他、传统沙锤打击乐与电钢琴。"},
   "rhythmFeatures": {"en": "Tony Allen's four-limb polyrhythmic drumming: independent patterns across hi-hat, snare, kick, and toms.", "zh": "Tony Allen 标志性四肢独立多重节奏：踩镲、底鼓、通鼓与军鼓各奏完全不同独立切分。"},
   "bassPattern": {"en": "Hypnotic, syncopated electric bass grooves repeating relentlessly for 10-15 minutes.", "zh": "极度催眠、富有切分弹跳的电贝斯线条，在一首歌中持续狂奔 10 至 15 分钟。"},
   "productionTips": {"en": ["Arrange two rhythm guitars playing interlocking, syncopated single-note lines", "Layer shekere, congas, and woodblock percussion over the drum kit", "Keep arrangements expansive across 10+ minute tracks"], "zh": ["编排两把节奏吉他演奏相互咬合交错的单音放克切音线条", "在架子鼓上方叠录非洲传统沙锤（Shekere）、康加鼓与木鱼", "作品结构舒展宏大，留足器乐即兴与铜管呼应的长篇篇幅"]}},

  {"id": "amapiano", "name": "Amapiano", "aliases": ["阿玛钢琴", "南非钢琴浩室"], "category": "Latin/World", "year": "2012", "bpm": "110–118 BPM", "default_bpm": 113, "style": "four_on_floor", "place": {"en": "Johannesburg & Pretoria, South Africa", "zh": "南非约翰内斯堡与比勒陀利亚"},
   "artists": ["Kabza De Small", "DJ Maphorisa", "Focalistic", "Major League Djz", "Uncle Waffles"],
   "context": {"en": "Swept the globe from South Africa, blending deep house grooves with jazz piano chords, continuous shaker loops, and signature rolling log drums.", "zh": "从南非横扫全球的音乐奇迹，融合深邃浩室律动、爵士 Rhodes 钢琴、永不停歇的沙锤与标志性滚动的木原木鼓（Log Drum）。"},
   "soundDesign": {"en": "Signature synthesized 'Log Drum' (distorted 808 percussion bass), lush Rhodes chords, shaker loops.", "zh": "标志性合成原木鼓（Log Drum，带失真敲击瞬态的 808 贝斯）、典雅 Rhodes 和弦与沙锤循环。"},
   "rhythmFeatures": {"en": "Steady 113 BPM 4/4 kick accompanied by continuous, intricate, multi-layered shaker loops.", "zh": "稳健的 113 BPM 四四拍底鼓，伴随连绵不绝、层次细腻的多层沙锤循环。"},
   "bassPattern": {"en": "The iconic pitch-bending, syncopated rolling 'log drum' bassline playing complex polyrhythms.", "zh": "标志性带有音高弯音滑音与弹跳敲击质感的滚动原木鼓低音线条。"},
   "productionTips": {"en": ["Create the signature log drum using an FM or 808 kick with extreme pitch envelope and saturation", "Layer at least 3 distinct shaker loops playing slightly different syncopations", "Use lush jazz piano minor 9th chords on the breakdown"], "zh": ["使用具有极速音高包络与轻度饱和的 808 底鼓制作招牌 Log Drum", "叠置至少 3 条带有微小时间差与声像分置的细腻沙锤循环", "在分解段落使用优雅的爵士小九和弦电钢琴进行抒情点缀"]}},

  {"id": "bossa-nova", "name": "Bossa Nova", "aliases": ["波萨诺瓦", "巴萨诺瓦"], "category": "Latin/World", "year": "1957", "bpm": "110–140 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "Rio de Janeiro, Brazil", "zh": "巴西里约热内卢"},
   "artists": ["Antônio Carlos Jobim", "João Gilberto", "Astrud Gilberto", "Stan Getz", "Vinicius de Moraes"],
   "context": {"en": "Created in late-50s Rio de Janeiro by João Gilberto and Tom Jobim, slowing samba rhythms to a gentle acoustic sway with jazz harmonies and whispered vocals.", "zh": "50 年代末由 João Gilberto 与 Tom Jobim 开创于里约海滨，将狂欢桑巴转化为轻柔的木吉他摇曳、优雅爵士和声与耳语低吟。"},
   "soundDesign": {"en": "Nylon-string acoustic guitar, delicate brushed snare rim clicks, warm flute/sax, whisper vocals.", "zh": "尼龙弦古典吉他、细腻的鼓刷边击敲击、温暖木质长笛/萨克斯与耳语般人声。"},
   "rhythmFeatures": {"en": "Syncopated Brazilian acoustic guitar thumb-and-finger picking pattern simulating the samba groove.", "zh": "大拇指与手指拨奏的切分尼龙吉他律动，精巧模拟了巴西桑巴节拍。"},
   "bassPattern": {"en": "Soft, acoustic upright bass alternating between root and 5th on downbeats with gentle syncopation.", "zh": "柔和的原声立式低音提琴，在正拍与反拍间轻柔交替根音与五音。"},
   "productionTips": {"en": ["Play acoustic nylon guitar without a pick, using thumb for bass and three fingers for chords", "Cross-stick rim clicks should be soft and delicate on coated snare heads", "Compose using lush maj9, m9, and diminished passing chords"], "zh": ["不用拨片直接用右手大拇指与三指弹奏尼龙吉他拇指行进与和弦抓弦", "军鼓边击敲击务必柔和克制，使用带涂层鼓皮展现温度", "大量运用大九和弦、小九和弦与半音减七经过和弦"]}},

  {"id": "samba", "name": "Samba", "aliases": ["桑巴"], "category": "Latin/World", "year": "1910", "bpm": "90–120 BPM (2/4)", "default_bpm": 105, "style": "standard", "place": {"en": "Rio de Janeiro, Brazil", "zh": "巴西里约热内卢"},
   "artists": ["Cartola", "Beth Carvalho", "Zeca Pagodinho", "Alcione", "Jorge Ben Jor"],
   "context": {"en": "The heartbeat of Brazilian Carnival, born in Rio de Janeiro out of Afro-Brazilian traditions, driven by massive batucada percussion ensembles.", "zh": "巴西狂欢节的激荡心跳，脱胎于非裔巴西传统，由庞大的巴图卡达（Batucada）打击乐军团与桑巴歌者驱动。"},
   "soundDesign": {"en": "Surdo bass drums, cuíca friction drum, pandeiro tambourine, caixa snare, cavaquinho guitar.", "zh": "Surdo 重型低音大鼓、Cuíca 摩擦鼓、Pandeiro 巴西手鼓、Caixa 军鼓与卡瓦金尼奥小吉他。"},
   "rhythmFeatures": {"en": "Brisk 2/4 rhythm with characteristic syncopated pulse on the second beat provided by the surdo.", "zh": "轻快的 2/4 拍律动，在第 2 拍上由 Surdo 大鼓提供深沉鲜明的切分脉冲。"},
   "bassPattern": {"en": "Surdo-driven low-end acoustic pulse alternating between high and low surdo tones.", "zh": "由 Surdo 大鼓高低音交替敲击主导的宏大低频脉动。"},
   "productionTips": {"en": ["Layer the 3 sizes of Surdo drums: Surdo 1 (deep downbeat), Surdo 2 (answering high), Surdo 3 (syncopated cutting)", "Include the squeaking Cuíca friction drum for iconic carnival flavor", "Record cavaquinho strumming high-register chord rhythms"], "zh": ["叠录三种尺寸的 Surdo 大鼓：1号深沉重音、2号高音呼应、3号切分加花", "加入发出吱呀啸叫的 Cuíca 摩擦鼓增添原汁原味狂欢色彩", "录制卡瓦金尼奥四弦小吉他演奏高音区明朗扫弦"]}},

  {"id": "cumbia", "name": "Cumbia", "aliases": ["坎比亚"], "category": "Latin/World", "year": "1940", "bpm": "90–110 BPM", "default_bpm": 100, "style": "standard", "place": {"en": "Colombia", "zh": "哥伦比亚"},
   "artists": ["Los Ángeles Azules", "Lucho Bermúdez", "Totó La Momposina", "Ska Cubano", "Bomba Estéreo"],
   "context": {"en": "Traditional folk dance of Colombia that evolved into a pan-Latin American sensation, driven by accordion melodies, guache shakers, and infectious 2/4 bounce.", "zh": "诞生于哥伦比亚的传统民间歌舞，演化为风靡全拉丁美洲的文化瑰宝，以手风琴、沙锤与欢快 2/4 拍弹跳闻名。"},
   "soundDesign": {"en": "Button accordion, guache/maracón shakers, tambor alegre drum, acoustic electric bass.", "zh": "按钮手风琴、Guache 沙管/沙锤、Alegre 欢悦鼓与清脆电贝斯。"},
   "rhythmFeatures": {"en": "Characteristic 2/4 rhythm with the distinctive 'shhh-chika-chika' shaker scraping pattern.", "zh": "标志性 2/4 拍律动，伴随极具辨识度的沙锤沙沙声（shhh-chika-chika）。"},
   "bassPattern": {"en": "Bouncy, syncopated basslines playing continuous walking intervals that make dancing irresistible.", "zh": "富有弹性跳跃的切分低音线条，不断演奏行进音程催生难以自抑的舞动冲动。"},
   "productionTips": {"en": ["Record accordion playing bright, syncopated lead melodies with rich reed vibrato", "Keep the shaker scraping continuously on the 16th-note grid", "Use melodic acoustic basslines that emphasize the upbeat"], "zh": ["实录手风琴演奏明朗切分的主奏旋律，带有丰满的簧片颤音", "沙管刮管在十六分音符网格上持续不断地进行摩擦律动", "贝斯线条强调反拍弹跳以强化跳舞欲望"]}},

  {"id": "kuduro", "name": "Kuduro", "aliases": ["库杜罗"], "category": "Latin/World", "year": "1996", "bpm": "135–145 BPM", "default_bpm": 140, "style": "four_on_floor", "place": {"en": "Luanda, Angola", "zh": "安哥拉罗安达"},
   "artists": ["Buraka Som Sistema", "Titica", "Cabo Snoop", "Batida", "Nagrelha"],
   "context": {"en": "Born in Luanda, Angola, during the civil war, blending traditional Angolan soca/kilapanga with fast four-on-the-floor European techno beats and energetic vocal chants.", "zh": "诞生于内战时期的安哥拉首都罗安达，将传统索卡节拍与高速四踩四欧洲 Techno 鼓点和激情四射的人声呐喊结合。"},
   "soundDesign": {"en": "Fast syncopated congas, electronic whistle blasts, high-octane rap chants, heavy punchy kicks.", "zh": "极速切分康加鼓、电子裁判口哨声、高能葡语说唱呐喊与重击底鼓。"},
   "rhythmFeatures": {"en": "Furious 140 BPM four-on-the-floor kick pattern laced with polyrhythmic tribal percussion.", "zh": "狂风暴雨般的 140 BPM 四四拍底鼓，穿插交错着复合节奏部落打击乐。"},
   "bassPattern": {"en": "Short, punchy sub-bass hits locked with the kick drum to propel hyper-speed street choreography.", "zh": "短促有力的超低频重击，与底鼓紧密贴合，支撑极速街头斗舞步法。"},
   "productionTips": {"en": ["Keep tempo driving around 140 BPM with relentless energy", "Layer electronic sports whistle samples on key syncopated drops", "Process shouting group vocals with aggressive compression"], "zh": ["将速度稳稳锁定在 140 BPM 附近，释放不间断的澎湃动能", "在关键切分重拍上叠入狂欢运动口哨音效", "对群体呐喊人声施加激进压缩以强化现场呼号的感染力"]}}
]

save_module("jazz_blues.ts", "JAZZ_BLUES_GENRES", jazz_blues_list)
save_module("pop_rnb.ts", "POP_RNB_GENRES", pop_rnb_list)
save_module("latin_world.ts", "LATIN_WORLD_GENRES", latin_world_list)
print("Completed Batch 5: Jazz/Blues (14), Pop/R&B (13), Latin/World (11) = 38 genres!")
