from gen_p1 import save_module

rock_metal_list = [
  {"id": "rock-and-roll", "name": "Rock and Roll", "aliases": ["摇滚乐", "经典摇滚"], "category": "Rock/Metal", "year": "1950", "bpm": "140–175 BPM", "default_bpm": 150, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Chuck Berry", "Little Richard", "Elvis Presley", "Buddy Holly", "Jerry Lee Lewis"],
   "context": {"en": "Emerged in the US in the 1950s out of rhythm and blues, boogie-woogie, and country, driven by energetic backbeats and electric guitar licks.", "zh": "1950 年代初融合节奏布鲁斯、布吉乌吉与乡村音乐在美国诞生，由充满活力的反拍与电吉他激奏驱动。"},
   "soundDesign": {"en": "Vintage tube-overdriven electric guitars, upright acoustic bass, pounding honky-tonk piano.", "zh": "复古电子管轻度过载电吉他、立式原声贝斯与强劲的酒馆钢琴。"},
   "rhythmFeatures": {"en": "Driving 4/4 rhythm with strong accent on beats 2 and 4 (backbeat) and swinging 8th-note shuffle.", "zh": "驱动力十足的四四拍律动，在 2、4 拍上有强烈后拍（Backbeat）重音，带有八分音符摇摆。"},
   "bassPattern": {"en": "Walking upright bass playing classic 12-bar blues arpeggiated root-3rd-5th-6th lines.", "zh": "行进立式贝斯演奏经典 12 小节布鲁斯分解根音-三音-五音-六音走音。"},
   "productionTips": {"en": ["Use classic 12-bar blues progressions (I-IV-I-V-IV-I)", "Apply light analog tape slapback delay to lead vocals and guitars", "Keep drum sounds natural and dynamic without modern compression"], "zh": ["采用经典 12 小节布鲁斯和弦骨架（I-IV-I-V-IV-I）", "为主唱与吉他加入轻微模拟磁带拍击延迟（Slapback Echo）", "保持鼓组动态自然呼吸，避免现代过度压缩"]}},

  {"id": "blues-rock", "name": "Blues Rock", "aliases": ["布鲁斯摇滚"], "category": "Rock/Metal", "year": "1960", "bpm": "110–135 BPM", "default_bpm": 120, "style": "standard", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["The Jimi Hendrix Experience", "Cream", "Led Zeppelin", "Stevie Ray Vaughan", "The Rolling Stones"],
   "context": {"en": "Combines traditional blues improvisational scale runs with cranked electric guitar amplifiers and heavy driving rock rhythms.", "zh": "将传统布鲁斯即兴音阶演奏与开到极响的电吉他过载箱头和沉重推进的摇滚节拍结合。"},
   "soundDesign": {"en": "Fender Stratocaster / Gibson Les Paul into cranked Marshall stacks, fuzz pedals, wah-wah.", "zh": "芬达/吉普森吉他接入大功率马歇尔箱头、法兹单块与哇音踏板。"},
   "rhythmFeatures": {"en": "Heavy shuffle or straight rock groove with dynamic drum fills and prominent ride cymbal work.", "zh": "厚重摇摆或直板摇滚律动，伴随动态极大的鼓加花与突出的 Ride 镲片。"},
   "bassPattern": {"en": "Improvisational blues-scale walking basslines locking with the drummer's kick pedal.", "zh": "即兴布鲁斯音阶行进贝斯线条，与鼓手的底鼓踏板紧密契合。"},
   "productionTips": {"en": ["Capture real room bleed when tracking live guitar amplifier cabinets", "Use pentatonic minor scale with flattened 5th (the blue note) for searing solos", "Layer warm Hammond B3 organ beneath rhythm guitars"], "zh": ["实录电吉他箱头时捕捉自然的房间环境串音增添现场感", "使用带降五度（蓝调音）的小调五声音阶演奏撕裂独奏", "在节奏吉他下方铺一层温暖的 Hammond B3 电子管风琴"]}},

  {"id": "hard-rock", "name": "Hard Rock", "aliases": ["硬摇滚"], "category": "Rock/Metal", "year": "1968", "bpm": "115–140 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["Led Zeppelin", "AC/DC", "Deep Purple", "Guns N' Roses", "Aerosmith"],
   "context": {"en": "Pioneered in the late 1960s with heavily distorted guitars, aggressive power chord riffs, soaring vocals, and pounding drums.", "zh": "发端于 1960 年代末，以重度失真电吉他、具有侵略性的强力和弦 Riff、高亢主唱与重锤底鼓震撼世界。"},
   "soundDesign": {"en": "Overdriven Marshall guitar stacks, aggressive power chords, driving bass guitars, heavy room drums.", "zh": "过载马歇尔吉他箱头、强力和弦、穿透力强的电贝斯与宽广房间真鼓。"},
   "rhythmFeatures": {"en": "Solid, driving 4/4 beat with cracking snare on 2 and 4 and powerful downbeat kicks.", "zh": "扎实坚定的四四拍节奏，在 2、4 拍发出炸裂般的军鼓撞击。"},
   "bassPattern": {"en": "Thick, distorted pick-played bass doubling the main guitar riff for colossal weight.", "zh": "用拨片弹奏的厚重微失真贝斯，与主吉他 Riff 完全齐奏构筑磅礴分量。"},
   "productionTips": {"en": ["Double-track rhythm guitars hard left and hard right for a massive stereo wall", "Capture large ambient drum room mics and compress heavily with an 1176", "Keep the kick and bass frequencies tightly locked together"], "zh": ["将节奏吉他双实录并极左极右对称分置打造庞大立体声吉他音墙", "采集远距离大立体声房间鼓话筒并使用 1176 压缩器重度挤压", "将底鼓与贝斯的低频基频紧密咬合"]}},

  {"id": "punk-rock", "name": "Punk Rock", "aliases": ["朋克摇滚"], "category": "Rock/Metal", "year": "1975", "bpm": "160–200 BPM", "default_bpm": 175, "style": "standard", "place": {"en": "New York, USA & London, UK", "zh": "美国纽约与英国伦敦"},
   "artists": ["The Ramones", "Sex Pistols", "The Clash", "Green Day", "Bad Religion"],
   "context": {"en": "Stripped rock music down to its fast, raw, three-chord essentials in mid-70s NYC and London, embracing DIY counter-culture.", "zh": "70 年代中期在纽约与伦敦将摇滚剥离至极速、粗粝的三和弦本质，拥抱反叛的 DIY 独立文化。"},
   "soundDesign": {"en": "Distorted solid-body guitars through tube amps, aggressive plectrum bass, raw vocals.", "zh": "实心电吉他直入过载箱头、粗暴拨片弹奏贝斯与未经修饰的呐喊主唱。"},
   "rhythmFeatures": {"en": "Fast, driving straight 8th-note beats with pounding downstroke hi-hats and aggressive snares.", "zh": "高速飞驰的纯直板八分音符节拍，下扫踩镲与充满攻击性的干脆军鼓。"},
   "bassPattern": {"en": "Relentless 8th-note downpicked root notes driving straight ahead without fills.", "zh": "全下拨（Downpick）八分音符根音狂轰滥炸，毫无多余花哨装饰。"},
   "productionTips": {"en": ["Keep song arrangements short and direct (under 3 minutes)", "Use aggressive downpicking on rhythm guitars for punchy percussive impact", "Avoid studio polish; record the band live together in one room when possible"], "zh": ["歌曲编排短小精悍直截了当（通常在 3 分钟以内）", "节奏吉他采用全下拨扫弦获取极具打击感的颗粒度", "拒绝过度录音棚精修，尽可能让乐队同期在同一房间实录"]}},

  {"id": "post-punk", "name": "Post-Punk", "aliases": ["后朋克"], "category": "Rock/Metal", "year": "1977", "bpm": "120–145 BPM", "default_bpm": 130, "style": "standard", "place": {"en": "UK", "zh": "英国"},
   "artists": ["Joy Division", "The Cure", "Siouxsie and the Banshees", "Bauhaus", "Gang of Four"],
   "context": {"en": "Emerged from punk's wake, trading raw anger for artful experimentation, gothic atmospheres, prominent chorus basslines, and dance rhythms.", "zh": "脱胎于朋克浪潮，将粗糙愤怒升华至艺术探索、哥特幽暗氛围、突出的合唱低音与舞动节拍。"},
   "soundDesign": {"en": "Prominent bass guitar with chorus and flanger pedals, jangly chorus guitars, gated snares.", "zh": "挂载合唱与凸缘单块的突出贝斯、清脆合唱电吉他扫弦与门限军鼓。"},
   "rhythmFeatures": {"en": "Motorik or disco-influenced driving 4/4 beats with sharp rimshots and mechanical precision.", "zh": "受德国机械律动（Motorik）或迪斯科启发的推进节拍，机械利落。"},
   "bassPattern": {"en": "High-register, melodic basslines serving as the main melodic hook rather than just backing harmony.", "zh": "在高把位弹奏的极富歌唱性贝斯线条，直接担当歌曲核心主旋律 Hook。"},
   "productionTips": {"en": ["Place the bass guitar in the frequency and volume center of the mix with stereo chorus", "Apply cold, metallic plate reverbs to vocals and drums", "Use sparse, angular single-note guitar riffs"], "zh": ["将贝斯置于混音绝对核心并施加宽立体声合唱效果", "为人声与鼓组挂载冰冷金属质感的板式混响", "吉他编写稀疏、具有棱角感的单音 Riff 而非厚重和弦扫弦"]}},

  {"id": "new-wave", "name": "New Wave", "aliases": ["新浪潮"], "category": "Rock/Metal", "year": "1978", "bpm": "120–140 BPM", "default_bpm": 128, "style": "standard", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["Talking Heads", "Blondie", "The Police", "Devo", "Duran Duran"],
   "context": {"en": "Blended punk's energy with synthesizers, quirky pop songwriting, funky basslines, and polished art-school aesthetics.", "zh": "将朋克的朝气与电子合成器、前卫古怪的流行创作、放克贝斯与精致艺术美学交汇。"},
   "soundDesign": {"en": "Prophet-5 and Roland Jupiter synthesizers, clean chorused guitars, LinnDrum/acoustic hybrid drums.", "zh": "Prophet-5 与 Roland Jupiter 合成器、通透合唱清音吉他与原声/电子混血鼓组。"},
   "rhythmFeatures": {"en": "Upbeat, energetic 4/4 rhythms with dance-rock grooves and syncopated high-hat patterns.", "zh": "轻快活泼的四四拍律动，兼具舞曲摇滚动感与切分踩镲。"},
   "bassPattern": {"en": "Funky, syncopated electric basslines or pulsing analog synth bass lines.", "zh": "极富放克律动的切分电贝斯线条，或跳动感十足的模拟合成低音。"},
   "productionTips": {"en": ["Balance electronic synthesizers evenly against clean electric guitars", "Use crisp Roland CE-2 style chorus on guitars and bass", "Emphasize infectious, quirky vocal hooks and danceable grooves"], "zh": ["让电子合成器与清音电吉他在混音中保持声学平衡", "在吉他与贝斯上使用清脆通透的复古合唱效果器", "突出记忆点极强的洗脑人声唱段与适合跳舞的放克律动"]}},

  {"id": "heavy-metal", "name": "Heavy Metal", "aliases": ["重金属"], "category": "Rock/Metal", "year": "1969", "bpm": "110–140 BPM", "default_bpm": 120, "style": "standard", "place": {"en": "Birmingham, UK", "zh": "英国伯明翰"},
   "artists": ["Black Sabbath", "Judas Priest", "Iron Maiden", "Motörhead", "Ozzy Osbourne"],
   "context": {"en": "Forged in industrial Birmingham by Black Sabbath in 1969, defined by dark tritone riffs, down-tuned guitars, galloping rhythms, and operatic vocals.", "zh": "1969 年由 Black Sabbath 开创于伯明翰工业区，以暗黑三全音、降调失真吉他、铁骑奔腾节奏与戏剧性主唱著称。"},
   "soundDesign": {"en": "Heavy tube distortion, dark tritone intervals, Marshall stacks, galloping double bass drums.", "zh": "重度电子管失真、暗黑三全音（魔鬼音程）、马歇尔吉他箱头与狂奔的双底鼓。"},
   "rhythmFeatures": {"en": "Heavy pounding 4/4 beats, dynamic tempo changes, and galloping 16th-note double kicks.", "zh": "沉重轰鸣的四四拍节拍，戏剧性的速度变化与铁蹄飞奔般的十六分音符双踩底鼓。"},
   "bassPattern": {"en": "Galloping basslines (Iron Maiden Steve Harris style) locked to twin guitar harmonies.", "zh": "标志性的铁骑奔腾低音线条，与双吉他三度和声紧密齐奏。"},
   "productionTips": {"en": ["Use the tritone (augmented 4th / diminished 5th) interval to craft menacing dark riffs", "Pan twin lead guitars left and right playing tight melodic harmonies in thirds", "Use fast finger-style triplet picking on bass"], "zh": ["运用三全音（增四度/减五度）构筑充满末世压迫感的暗黑 Riff", "将双主音吉他左右分置演奏精密的三度和声对位", "在贝斯上采用极速三连音手指拨奏还原经典奔腾感"]}},

  {"id": "thrash-metal", "name": "Thrash Metal", "aliases": ["激流金属"], "category": "Rock/Metal", "year": "1981", "bpm": "170–220 BPM", "default_bpm": 190, "style": "standard", "place": {"en": "California, USA", "zh": "美国加州"},
   "artists": ["Metallica", "Slayer", "Megadeth", "Anthrax", "Exodus"],
   "context": {"en": "The Big Four emerged in early 1980s combining the fast tempos of hardcore punk with the intricate twin-guitar shredding of the NWOBHM.", "zh": "80 年代初由“激流四巨头”掀起风暴，结合硬核朋克的超高速度与重金属精致激进的双吉他速弹。"},
   "soundDesign": {"en": "Scooped-mid tube amplifiers, palm-muted high-speed riffing, tight clicky double kicks.", "zh": "凹陷中频（Scooped-mid）失真吉他箱头、极速手掌闷音扫弦与清脆双踩底鼓。"},
   "rhythmFeatures": {"en": "Breakneck 180+ BPM tempos with relentless machine-gun double-bass drums and skank beats.", "zh": "180+ BPM 极速飞驰，伴随狂风骤雨般的机关枪双踩底鼓与 Skank 快速朋克鼓点。"},
   "bassPattern": {"en": "Rapid-fire 16th-note downpicking tightly locked with palm-muted guitar chugs.", "zh": "速射十六分音符下拨低音，与吉他手掌闷音重击严丝合缝咬合。"},
   "productionTips": {"en": ["Scoop the 800Hz-1kHz range on rhythm guitars to create the aggressive thrash bite", "Ensure high-frequency transient click on double-bass drums for clarity at 200 BPM", "Tighten low-end guitar frequencies with a high-pass filter around 80Hz"], "zh": ["衰减吉他 800Hz-1kHz 中频塑造极具侵略性的经典金属切削感", "为双踩底鼓增强 4-5kHz 的清脆敲击瞬态以在 200 BPM 下保持颗粒清晰", "在 80Hz 对吉他做低切，杜绝超低频杂音与贝斯冲突"]}},

  {"id": "death-metal", "name": "Death Metal", "aliases": ["死亡金属"], "category": "Rock/Metal", "year": "1984", "bpm": "160–240 BPM", "default_bpm": 200, "style": "standard", "place": {"en": "Florida, USA & Sweden", "zh": "美国佛罗里达与瑞典"},
   "artists": ["Death", "Cannibal Corpse", "Morbid Angel", "Obituary", "Entombed"],
   "context": {"en": "Pioneered by Chuck Schuldiner (Death) and Possessed, pushing metal to brutal extremes with deep guttural growls and blast beats.", "zh": "由 Chuck Schuldiner（Death）等人开创，将金属乐推向凶狠极限，以低吼咆哮唱腔与狂暴碎拍（Blast Beat）著称。"},
   "soundDesign": {"en": "Heavily down-tuned guitars (D-standard, B-standard), Boss HM-2 buzzsaw pedal, guttural vocals.", "zh": "大幅降调吉他、Boss HM-2 电锯失真单块、低沉兽吼人声与金属打击击打。"},
   "rhythmFeatures": {"en": "Relentless blast beats, extreme double-bass drum barrages, and abrupt stop-start tempo shifts.", "zh": "暴风雨般的 Blast Beat 碎拍、极端双踩轰炸与急停急起的骤变变速。"},
   "bassPattern": {"en": "Distorted, down-tuned pick bass doubling complex chromatic guitar riffs.", "zh": "过载降调拨片贝斯，完全齐奏复杂半音阶吉他 Riff。"},
   "productionTips": {"en": ["Use the Boss HM-2 with all knobs set to 10 for the legendary Swedish buzzsaw tone", "Double-track death metal guttural vocals with an octave lower growl", "Use sample reinforcement on kick drums to maintain audible attack during blast beats"], "zh": ["将 Boss HM-2 踏板全部旋钮拧到满格获得传奇瑞典电锯吉他音色", "为死嗓人声叠录低八度的深喉咆哮", "在 Blast Beat 极速鼓点下使用底鼓采样强化敲击瞬间瞬态"]}},

  {"id": "black-metal", "name": "Black Metal", "aliases": ["黑金属"], "category": "Rock/Metal", "year": "1984", "bpm": "150–220 BPM", "default_bpm": 180, "style": "standard", "place": {"en": "Norway & Sweden", "zh": "挪威与瑞典"},
   "artists": ["Mayhem", "Darkthrone", "Burzum", "Emperor", "Immortal"],
   "context": {"en": "The early 90s Norwegian second wave defined the genre with raw cold lo-fi production, tremolo picking, blast beats, and high shrieking rasps.", "zh": "90 年代初挪威第二浪潮定义了黑金属，以寒冷粗糙的低保真制作、极速轮指扫弦、狂暴碎拍与高音嘶吼著称。"},
   "soundDesign": {"en": "Cold, treble-heavy distorted guitars, rapid tremolo picking, shrieking rasps, lo-fi cassette hiss.", "zh": "高频尖锐冰冷的失真吉他、极速轮指扫弦、凄厉尖叫与低保真磁带底噪。"},
   "rhythmFeatures": {"en": "Fast, continuous blast beats with washing cymbal rides creating a relentless wall of noise.", "zh": "极速持续不断的 Blast Beat 鼓点，伴随碎镲构筑持续不断的轰鸣噪音之墙。"},
   "bassPattern": {"en": "Buried, understated bassline following the guitar root notes in the background.", "zh": "沉潜、克制地跟随吉他根音在深暗背景中隐现的低音线条。"},
   "productionTips": {"en": ["Avoid clean studio compression; capture a raw, icy room sound", "Layer continuous tremolo picking guitars left and right without palm muting", "Use cold digital reverbs on vocals to evoke desolate northern winter landscapes"], "zh": ["拒绝过度修饰的录音棚平滑压缩，捕捉纯正冰冷的房间质感", "让吉他在左右声道持续全速轮指扫弦而不做手掌闷音", "为人声加入深邃冰冷的数字混响，勾勒北欧寒冬绝美与绝望"]}},

  {"id": "doom-metal", "name": "Doom Metal", "aliases": ["毁灭金属"], "category": "Rock/Metal", "year": "1980", "bpm": "45–80 BPM", "default_bpm": 65, "style": "standard", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["Candlemass", "Saint Vitus", "Trouble", "Electric Wizard", "Sleep"],
   "context": {"en": "Takes Black Sabbath's heaviest, slowest riffs to agonizingly slow tempos, invoking crushing weight, despair, and atmospheric gloom.", "zh": "将 Black Sabbath 最沉重的暗黑 Riff 推向极其漫长缓慢的时速，营造碾压式的绝望与深邃阴郁。"},
   "soundDesign": {"en": "Massively fuzz-distorted down-tuned guitars, thick analog bass fuzz, cavernous room drums.", "zh": "极端法兹过载的超低降调吉他、浓稠模拟贝斯失真与洞穴般开阔真鼓。"},
   "rhythmFeatures": {"en": "Glacial, agonizingly slow tempos with massive crashing cymbals and dragging snares.", "zh": "如冰川移动般极其缓慢的节奏，伴随震天动地的镲片巨响与拖沓军鼓。"},
   "bassPattern": {"en": "Massive, fuzzy, vibrating low-end bass riffs that sustain for full bars.", "zh": "庞大、法兹共振的超重低音 Riff，整小节持续延音撼动地板。"},
   "productionTips": {"en": ["Tune guitars down to C-standard or B-standard through vintage Sunn O))) or Orange amplifiers", "Keep tempos below 70 BPM to allow guitar chord sustain to fully bloom", "Layer a Big Muff fuzz pedal with an overdriven tube preamp"], "zh": ["吉他降调至 C 或 B 标准音，并通过经典 Sunn O))) 或 Orange 箱头放大", "速度严格保持在 70 BPM 以下，让吉他和弦延音充分泛音共振", "将 Big Muff 法兹单块与过载电子管前级串联获得浓稠低音"]}},

  {"id": "metalcore", "name": "Metalcore", "aliases": ["金属核"], "category": "Rock/Metal", "year": "1995", "bpm": "130–160 BPM", "default_bpm": 140, "style": "standard", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Killswitch Engage", "As I Lay Dying", "Bring Me The Horizon", "Architects", "Parkway Drive"],
   "context": {"en": "Fuses extreme metal guitar riffing and melodic death metal harmonies with the aggressive breakdowns and gang vocals of hardcore punk.", "zh": "将极端金属技巧与旋律死亡金属三度和声同硬核朋克的高能 Breakdown（大蹲点）与怒吼结合。"},
   "soundDesign": {"en": "High-gain modern 5150 guitar tone, sub-bass drops before breakdowns, crisp double kicks.", "zh": "高增益现代 5150 箱头吉他音色、Breakdown 前的超低频下沉炸点与清脆双踩。"},
   "rhythmFeatures": {"en": "Dynamic shifts between fast double-bass thrash beats and slow, punishing half-time breakdowns.", "zh": "在高速双踩狂奔节拍与极其沉重迟缓的半速 Breakdown 间形成强烈动态切换。"},
   "bassPattern": {"en": "Modern clanky, high-compression bass with distorted mids and clean sub fundamental.", "zh": "现代清脆金属撞击感（Clanky）贝斯，中频失真而超低频坚固干净。"},
   "productionTips": {"en": ["Insert a sub-bass sine drop right before the main half-time breakdown hits", "Use Darkglass distortion plugin on bass for that modern metallic clank", "Alternate between screamed verses and soaring clean vocal choruses"], "zh": ["在核心半速 Breakdown 爆发前插入超低频正弦波炸弹（Sub Drop）", "使用 Darkglass 类贝斯失真插件制作现代金属标志性的金属敲击咔哒声", "在嘶吼主歌与高亢清嗓副歌之间形成鲜明情感反差"]}},

  {"id": "grunge", "name": "Grunge", "aliases": ["垃圾摇滚", "西雅图之声"], "category": "Rock/Metal", "year": "1986", "bpm": "90–135 BPM", "default_bpm": 115, "style": "standard", "place": {"en": "Seattle, Washington, USA", "zh": "美国华盛顿州西雅图"},
   "artists": ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains", "Stone Temple Pilots"],
   "context": {"en": "Born in late-80s Seattle via Sub Pop records, fusing punk rock raw energy with heavy metal sludge and dynamic quiet-verse-explosive-chorus songwriting.", "zh": "80 年代末诞生于西雅图，融合朋克粗砺与重金属泥泞质感，以静谧主歌对撞爆发副歌的动态设计席卷世界。"},
   "soundDesign": {"en": "Fender Mustang / Jaguar through Boss DS-1 distortion, Electro-Harmonix Small Clone chorus.", "zh": "芬达吉他接入 Boss DS-1 失真单块与 Electro-Harmonix Small Clone 合唱效果器。"},
   "rhythmFeatures": {"en": "Loose, sludgy 4/4 rock beats with heavy acoustic drum room dynamics.", "zh": "松弛粗重、充满泥泞质感的四四拍摇滚律动，伴随辽阔原声房间动态。"},
   "bassPattern": {"en": "Warm, melodic, driving pick-played basslines anchoring verse structures.", "zh": "温暖、旋律优美且充满推进力的拨片贝斯线条，稳稳撑起主歌骨架。"},
   "productionTips": {"en": ["Master the 'quiet-verse, explosive-chorus' dynamic: clean chorused guitars in verse, stomped DS-1 in chorus", "Keep drum sounds organic, large, and natural without quantization", "Use raspy, emotionally raw vocal tracking"], "zh": ["精通“静音主歌-爆炸副歌”动态哲学：主歌清音合唱，副歌一脚踩下 DS-1 失真", "保持鼓组真实庞大自然，坚决不进行机械量化", "保留沙哑破音、情感近乎崩溃的原始人声实录"]}},

  {"id": "alternative-rock", "name": "Alternative Rock", "aliases": ["另类摇滚"], "category": "Rock/Metal", "year": "1982", "bpm": "110–140 BPM", "default_bpm": 125, "style": "standard", "place": {"en": "USA & UK", "zh": "美国与英国"},
   "artists": ["R.E.M.", "The Pixies", "Radiohead", "The Smashing Pumpkins", "Foo Fighters"],
   "context": {"en": "Rose from 1980s underground college radio into 1990s dominance, embracing diverse unconventional chord progressions and poetic angst.", "zh": "从 80 年代大学地下电台走向 90 年代全球主流，包容非常规和弦探索与诗意反叛。"},
   "soundDesign": {"en": "Jangly clean electric guitars, fuzz pedals, textured synthesizers, acoustic guitar layers.", "zh": "清脆晶莹电吉他、法兹过载、质感合成器与原声木吉他叠层。"},
   "rhythmFeatures": {"en": "Dynamic rock rhythm varying from delicate acoustic brush patterns to driving choruses.", "zh": "富于动态张力的摇滚节拍，从轻柔沙刷鼓点自由切换至怒放副歌。"},
   "bassPattern": {"en": "Expressive, melodic basslines that provide independent counterpoint to guitar hooks.", "zh": "富有歌唱性的独立贝斯线条，与吉他旋律形成精巧的对位呼应。"},
   "productionTips": {"en": ["Experiment with unconventional chord extensions (add9, sus4) to stand out from standard rock", "Blend acoustic and distorted electric guitars in the chorus", "Avoid over-tuning vocals to preserve human authenticity"], "zh": ["大胆使用非常规和弦扩展音（add9、sus4）摆脱平庸摇滚套路", "在副歌阶段将木吉他与重型失真电吉他叠层获得浩大声场", "避免过度使用音准修正，保留人声颤动与真挚情感"]}},

  {"id": "progressive-rock", "name": "Progressive Rock", "aliases": ["前卫摇滚", "Prog Rock"], "category": "Rock/Metal", "year": "1968", "bpm": "Complex / Shifting", "default_bpm": 120, "style": "standard", "place": {"en": "UK", "zh": "英国"},
   "artists": ["Pink Floyd", "King Crimson", "Yes", "Genesis", "Rush"],
   "context": {"en": "Elevated rock music to high art by incorporating classical composition, odd time signatures (7/8, 5/4), Mellotrons, and epic extended suites.", "zh": "将摇滚乐提升至高阶艺术殿堂，融入古典音乐作曲构架、奇数奇幻拍号（7/8、5/4）、Mellotron 采样器与史诗长篇套曲。"},
   "soundDesign": {"en": "Mellotron string/flute tapes, Hammond organs, Moog modular synths, acoustic 12-string guitars.", "zh": "Mellotron 磁带弦乐与长笛、Hammond 风琴、Moog 模块合成器与 12 弦原声吉他。"},
   "rhythmFeatures": {"en": "Constantly shifting, complex time signatures (5/8, 7/8, 11/8) with virtuosic drum fills.", "zh": "不断转换的复杂非常规拍号（5/8、7/8、11/8），伴随大师级演奏水准的鼓加花。"},
   "bassPattern": {"en": "Virtuosic, melodic Rickenbacker basslines played with bright attack and aggressive complexity.", "zh": "高超大师级、充满歌唱性的 Rickenbacker 贝斯演奏，音色明亮带有清脆击弦质感。"},
   "productionTips": {"en": ["Incorporate metric modulation and shifting time signatures across arrangement sections", "Layer Mellotron and Hammond organ to create symphonic rock textures", "Allow arrangements to breathe across extended 8-15 minute durations"], "zh": ["在不同段落间自由切换非常规拍号与速度度量转换", "将 Mellotron 磁带音色与 Hammond 风琴交叠打造交响摇滚质感", "给作品充足时间跨度展开（长达 8 至 15 分钟宏篇巨构）"]}},

  {"id": "math-rock", "name": "Math Rock", "aliases": ["数学摇滚"], "category": "Rock/Metal", "year": "1989", "bpm": "Intricate / Shifting", "default_bpm": 130, "style": "standard", "place": {"en": "USA & Japan", "zh": "美国与日本"},
   "artists": ["American Football", "Covet", "Toe", "Battles", "Don Caballero"],
   "context": {"en": "Characterized by complex, asymmetrical time signatures (often 7/8, 11/8), intricate two-handed guitar tapping, and clean melodic math precision.", "zh": "以非对称奇数拍号（7/8、11/8）、精细复杂的双手点弦技巧与清脆明澈的数学级精密旋律为标志。"},
   "soundDesign": {"en": "Sparkling clean Telecaster tones, two-handed finger tapping, natural acoustic drums.", "zh": "晶莹剔透的 Telecaster 清音吉他、双手点弦泛音与未修饰的自然原声鼓。"},
   "rhythmFeatures": {"en": "Asymmetrical polyrhythmic drum grooves shifting between 5/4, 7/8, and 13/8 meters.", "zh": "在 5/4、7/8 与 13/8 节拍间自如穿梭的非对称复合节奏鼓组。"},
   "bassPattern": {"en": "Intricate counter-melodic basslines threading between complex guitar tapping loops.", "zh": "复杂对位旋律贝斯线条，在交织的点弦吉他乐句中如穿针引线。"},
   "productionTips": {"en": ["Use open tunings (such as DAEAC#E or FACGCE) for resonant two-handed tapping", "Keep guitar tone sparkling clean with subtle compression and fast room reverb", "Record drums with minimal compression to preserve wide dynamic subtleties"], "zh": ["使用特殊开放调弦（如 DAEAC#E 或 FACGCE）获取空灵点弦共鸣", "吉他音色保持极致清澈，配合微量压缩与短房间混响", "鼓组录音避免重度压缩，完整保留乐手演奏的呼吸弱音细节"]}},

  {"id": "shoe-gaze", "name": "Shoegaze", "aliases": ["自赏摇滚", "鞋窥摇滚"], "category": "Rock/Metal", "year": "1988", "bpm": "95–130 BPM", "default_bpm": 115, "style": "standard", "place": {"en": "UK & Ireland", "zh": "英国与爱尔兰"},
   "artists": ["My Bloody Valentine", "Slowdive", "Ride", "Lush", "Swervedriver"],
   "context": {"en": "Pioneered by Kevin Shields with Loveless, drowning dream-pop melodies in colossal walls of whammy-bar reverse-reverb guitar noise.", "zh": "由 Kevin Shields（My Bloody Valentine）等人开创，将梦泡旋律彻底沉浸在由摇把滑弦、反向混响与失真共筑的浩瀚吉他音海中。"},
   "soundDesign": {"en": "Yamaha SPX90 reverse reverb, glide guitar whammy strumming, fuzz walls, hushed whisper vocals.", "zh": "Yamaha SPX90 反向混响、摇把滑弦演奏（Glide Guitar）、法兹音墙与耳畔低语般的人声。"},
   "rhythmFeatures": {"en": "Steady, driving 4/4 beats buried softly beneath an all-consuming sonic wave of swirling distortion.", "zh": "沉潜于铺天盖地失真音浪之下的稳定四四拍节奏，柔和而不失律动。"},
   "bassPattern": {"en": "Driving root-note basslines holding the harmonic anchor while guitars swirl chaotically.", "zh": "坚实稳固的根音贝斯线条，在吉他狂乱回旋飘扬时牢牢锁定和声引力。"},
   "productionTips": {"en": ["Route fuzz pedals into a reverse reverb processor (or reverse reverb into fuzz) for the signature MBV wall", "Hold the guitar tremolo arm while strumming to create the iconic pitch glide", "Bury the vocals in the mix at equal volume with the guitars"], "zh": ["将法兹单块接入反向混响（或反向混响推入法兹）获得标志性 MBV 轰鸣音墙", "扫弦时右手手掌始终握住吉他摇把形成迷离音高微滑（Glide Guitar）", "将人声音轨音量降至与吉他平齐，制造隐匿于云雾中的朦胧听感"]}}
]

hiphop_list = [
  {"id": "old-school-hip-hop", "name": "Old School Hip Hop", "aliases": ["老派嘻哈"], "category": "Hip Hop", "year": "1973", "bpm": "95–115 BPM", "default_bpm": 105, "style": "breakbeat", "place": {"en": "Bronx, New York, USA", "zh": "美国纽约布朗克斯"},
   "artists": ["DJ Kool Herc", "Grandmaster Flash", "Afrika Bambaataa", "Sugarhill Gang", "Kurtis Blow"],
   "context": {"en": "Born at Bronx block parties when DJ Kool Herc isolated drum breaks using two turntables, inspiring emcees to rap rhyming party poetry.", "zh": "诞生于纽约布朗克斯街头街区派对，DJ Kool Herc 用双黑胶唱机循环延长鼓循环碎拍，催生了 MC 押韵说唱艺术。"},
   "soundDesign": {"en": "Two turntables, disco/funk drum breaks, vinyl scratches, Roland TR-808, simple vocal chants.", "zh": "双唱机、放克黑胶碎拍、黑胶搓碟声、Roland TR-808 与现场派对呼喊。"},
   "rhythmFeatures": {"en": "Funky syncopated drum breaks sampled from 1970s funk records, heavy on the downbeat.", "zh": "源自 70 年代放克黑胶唱片的切分碎拍，首拍坚实有力。"},
   "bassPattern": {"en": "Live electric funk bass riffs sampled directly from records and looped continuously.", "zh": "直接从黑胶唱片中截取并无限循环的生动电贝斯放克 Riff。"},
   "productionTips": {"en": ["Isolate the 2-bar drum break of a 70s soul record and loop it seamlessly", "Layer scratching sounds on the offbeats", "Keep MC vocal delivery rhythmic and call-and-response oriented"], "zh": ["截取一段 70 年代灵魂乐中的 2 小节鼓 Solo 并做无缝循环", "在反拍叠入黑胶搓碟拟音（Scratch）", "说唱人声强调清晰节奏押韵与派对呼应互动"]}},

  {"id": "boom-bap", "name": "Boom Bap", "aliases": ["轰趴嘻哈", "经典东海岸嘻哈"], "category": "Hip Hop", "year": "1988", "bpm": "85–95 BPM", "default_bpm": 90, "style": "breakbeat", "place": {"en": "New York, USA", "zh": "美国纽约"},
   "artists": ["DJ Premier", "Pete Rock", "Nas", "The Notorious B.I.G.", "A Tribe Called Quest"],
   "context": {"en": "Golden Age hip-hop defined by hard acoustic kicks ('Boom') and cracking vinyl snares ('Bap') chopped from jazz records on the Akai MPC60.", "zh": "嘻哈黄金时代的代名词，由 Akai MPC60 采样爵士黑胶切片，以硬朗原声底鼓（Boom）与炸裂军鼓（Bap）著称。"},
   "soundDesign": {"en": "Akai MPC60/SP-1200 12-bit crunch, chopped jazz Rhodes and horns, crackling vinyl snare.", "zh": "Akai MPC/SP-1200 12位粗糙采样颗粒感、切碎爵士电钢琴与管乐、黑胶爆豆军鼓。"},
   "rhythmFeatures": {"en": "The definitive swing: heavy kick on 1 and 3-and, sharp cracking acoustic snare on 2 and 4.", "zh": "黄金律动：第 1 拍和第 3 拍后半拍沉重底鼓，第 2、4 拍清脆炸裂原声军鼓。"},
   "bassPattern": {"en": "Deep, low-passed acoustic upright bass loops or warm filtered sub-bass following the jazz sample.", "zh": "低通滤波的原声立式贝斯循环，或紧密跟随爵士采样的温暖 Sub 低音。"},
   "productionTips": {"en": ["Chop jazz piano and horn stabs into micro-chops and replay on an MPC grid", "Apply low-pass filter at 150Hz on the bass sample and boost 60Hz", "Layer a vinyl crackle loop beneath the drums"], "zh": ["将爵士钢琴与铜管刺音切成微片段并在打击垫上网格化重奏", "对采样贝斯在 150Hz 做低通滤波并提升 60Hz 超低频基音", "在鼓组下方轻柔铺垫黑胶唱针爆豆声底噪"]}},

  {"id": "g-funk", "name": "G-Funk", "aliases": ["帮匪放克"], "category": "Hip Hop", "year": "1991", "bpm": "88–98 BPM", "default_bpm": 92, "style": "standard", "place": {"en": "Los Angeles, California, USA", "zh": "美国加州洛杉矶"},
   "artists": ["Dr. Dre", "Snoop Dogg", "Warren G", "Nate Dogg", "DJ Quik"],
   "context": {"en": "Pioneered by Dr. Dre on 'The Chronic', marrying laid-back West Coast hip-hop with high-pitched Portamento Moog synth leads and Parliament-Funkadelic samples.", "zh": "由 Dr. Dre 凭借《The Chronic》确立，将西海岸悠闲说唱同高音滑音 Moog 合成器单音以及 P-Funk 经典放克结合。"},
   "soundDesign": {"en": "High-pitched sine/saw lead with portamento glide, live slap bass, Rhodes chords, Parliament samples.", "zh": "高音滑音正弦/锯齿波合成主奏、现场 Slap 贝斯、Rhodes 和弦与 P-Funk 经典放克采样。"},
   "rhythmFeatures": {"en": "Laid-back, hypnotic 4/4 groove with crisp handclaps layered over live-sounding snares.", "zh": "慵懒从容、极具催眠感的四四拍放克律动，清脆拍手叠置在原声军鼓之上。"},
   "bassPattern": {"en": "Funky, syncopated live electric bass guitar playing deep melodic walking grooves.", "zh": "充满放克弹跳律动的现场电贝斯吉他，演奏深沉流畅的行进低音线条。"},
   "productionTips": {"en": ["Program a high-octave monophonic lead synth with generous portamento (glide time around 120ms)", "Use warm, real electric bass guitar recordings with plenty of groove swing", "Re-play samples live with studio musicians rather than simple audio chops"], "zh": ["高八度单音合成器开启 120ms 左右的长滑音（Portamento）打造标志旋律", "使用带摇摆弹性的真实电贝斯实录录音", "聘请乐手现场重新演奏经典采样片段赋予温暖生命力"]}},

  {"id": "trap-rap", "name": "Trap Rap", "aliases": ["陷阱说唱"], "category": "Hip Hop", "year": "2003", "bpm": "130–150 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "Atlanta, Georgia, USA", "zh": "美国佐治亚州亚特兰大"},
   "artists": ["T.I.", "Gucci Mane", "Future", "Metro Boomin", "Travis Scott"],
   "context": {"en": "Originated in Atlanta in the early 2000s, defined by gritty street storytelling over booming Roland TR-808 subs, rapid hi-hat rolls, and dark minor bells.", "zh": "2000 年代初起源于亚特兰大，以阴冷街头叙事、轰鸣的 Roland TR-808 超重低音、极速飞驰三连音踩镲与暗黑钟琴为核心。"},
   "soundDesign": {"en": "Booming Roland TR-808 sub-bass, rapid triplet hi-hats, minor brass stabs, eerie flutes.", "zh": "轰鸣 Roland TR-808 超低音、速射三连音踩镲、小调铜管刺音与阴郁长笛。"},
   "rhythmFeatures": {"en": "Half-time 140 BPM rhythm with sharp snare or clap on beat 3 and intricate 1/32 hi-hat rolls.", "zh": "140 BPM 半速节拍，第 3 拍落锋利军鼓/拍手，穿插精密的三十二分音符踩镲滚奏。"},
   "bassPattern": {"en": "Deep 808 sub bass glides providing both foundational chord weight and rhythmic drive.", "zh": "深沉的 808 超低音滑音，兼具和声根音重量与节拍推进动力。"},
   "productionTips": {"en": ["Automate pitch and panning on fast 1/32 triplet hi-hat rolls", "Distort the 808 sub slightly to generate harmonics audible on smartphone speakers", "Keep melodies sparse to allow maximum room for rap vocals"], "zh": ["对三十二分音符三连音踩镲滚奏做音高与立体声声像自动化", "对 808 低频施加适度轻微失真，确保在手机扬声器上清晰呈现", "保持旋律高度精炼稀疏，留给说唱歌词充分动态空间"]}},

  {"id": "conscious-hip-hop", "name": "Conscious Hip Hop", "aliases": ["有意识说唱", "自觉嘻哈"], "category": "Hip Hop", "year": "1987", "bpm": "85–95 BPM", "default_bpm": 90, "style": "breakbeat", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Kendrick Lamar", "Mos Def", "Common", "Public Enemy", "Talib Kweli"],
   "context": {"en": "Focuses on social justice, political awareness, and philosophical introspection over thoughtful jazz, soul, and funk musical beds.", "zh": "专注于社会公平、政治觉醒与哲学思辨，以富有沉淀感的爵士、灵魂乐与放克作为音乐底色。"},
   "soundDesign": {"en": "Organic live instrumentation, upright acoustic bass, live horn sections, Rhodes piano.", "zh": "有机现场原声乐器编配、立式原声贝斯、现场铜管组与温润 Rhodes 电钢琴。"},
   "rhythmFeatures": {"en": "Dynamic, human-played hip-hop grooves with delicate brush snares and expressive cymbals.", "zh": "富有动态与人手演奏质感的嘻哈律动，伴随细腻的沙刷军鼓与表现力镲片。"},
   "bassPattern": {"en": "Sophisticated upright acoustic basslines playing expressive, walking jazz chord progressions.", "zh": "复杂优雅的立式原声贝斯线条，演奏富有叙事感的行进爵士和声。"},
   "productionTips": {"en": ["Incorporate live studio musicians (saxophone, upright bass, piano) rather than loop packs", "Master track with wide dynamic range and avoid over-squashing with limiters", "Use conversational, articulate vocal mixing"], "zh": ["引入真实的萨克斯、立式贝斯与钢琴乐手实录而非使用套件采样", "母带处理保留宽广动态范围，避免用限制器盲目压死", "人声混音追求如同面对面交谈般清澈自然的质感"]}},

  {"id": "emo-rap", "name": "Emo Rap", "aliases": ["情绪说唱"], "category": "Hip Hop", "year": "2015", "bpm": "120–140 BPM", "default_bpm": 130, "style": "half_time", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Juice WRLD", "Lil Peep", "XXXTENTACION", "iann dior", "Lil Tracy"],
   "context": {"en": "Mid-2010s movement blending confessional melancholic indie/midwest emo guitar loops with trap 808 beats and vulnerable singing.", "zh": "2010 年代中期风潮，将感伤自白的独立/中西部 Emo 摇滚吉他循环与 Trap 808 鼓点和脆弱深情歌唱交织。"},
   "soundDesign": {"en": "Clean plucked acoustic or electric guitar loops, autotuned emotional vocals, booming 808s.", "zh": "清脆原声或电吉他拨弦循环、自动修音（Autotune）深情吟唱与轰鸣 808。"},
   "rhythmFeatures": {"en": "Half-time trap beats with rolling hi-hats, soft claps, and melancholic pauses.", "zh": "半速 Trap 节拍，穿插细腻踩镲滚奏、柔和拍手与充满感伤的停顿。"},
   "bassPattern": {"en": "Deep 808 sub-bass following sad indie chord progressions (often vi-IV-I-V).", "zh": "紧随悲伤独立和弦走向（常含 vi-IV-I-V）流淌的深沉 808 超低音。"},
   "productionTips": {"en": ["Record a gentle electric guitar riff with chorus and reverb in a minor key", "Use heavy pitch correction as an artistic emotional effect on lead vocals", "Keep the 808 soft and rounded rather than harshly distorted"], "zh": ["在小调上录制带有合唱与温和混响的木吉他/电吉他拨弦", "将高强度自动修音（Autotune）作为抒发脆弱情绪的艺术音色手段", "让 808 保持圆润温暖而非暴烈失真"]}},

  {"id": "lofi-hip-hop", "name": "Lo-Fi Hip Hop", "aliases": ["低保真嘻哈", "治愈嘻哈"], "category": "Hip Hop", "year": "2013", "bpm": "70–85 BPM", "default_bpm": 80, "style": "breakbeat", "place": {"en": "Internet & Japan", "zh": "互联网与日本"},
   "artists": ["Nujabes", "J Dilla", "Knxwledge", "ChilledCow / Lofi Girl", " idealism"],
   "context": {"en": "Pioneered by Nujabes and J Dilla, globally celebrated for relaxing, nostalgic boom-bap beats, SP-404 vinyl crackle, and muted jazz chords for studying.", "zh": "由 Nujabes 与 J Dilla 开创并风靡全球的疗愈风格，以松弛怀旧的 Boom-Bap 碎拍、SP-404 黑胶底噪与温暖爵士和弦陪伴无数人学习睡眠。"},
   "soundDesign": {"en": "Vinyl crackle, muted Rhodes piano chords, cassette tape warble, soft acoustic drums.", "zh": "黑胶爆豆底噪、弱音温暖 Rhodes 电钢琴、磁带音高抖晃与柔软原声鼓。"},
   "rhythmFeatures": {"en": "Unquantized, lazy, behind-the-beat boom-bap swing with soft kicks and brushing snares.", "zh": "未量化、松散后倾的醉人摇摆节拍，搭配柔和底鼓与轻扫军鼓。"},
   "bassPattern": {"en": "Warm, round, low-passed sine or acoustic upright bass gently humming root notes.", "zh": "温暖圆润、经过深低通滤波的正弦波或原声立式贝斯轻柔低鸣。"},
   "productionTips": {"en": ["Disable grid snapping and nudge hi-hats and snares manually for lazy J Dilla swing", "Add cassette wow/flutter modulation on piano samples", "Apply low-pass filter to the master drum bus around 8kHz to remove harsh highs"], "zh": ["关闭宿主节拍吸附，手动错开军鼓与踩镲营造 J Dilla 式慵懒人手微延迟", "为钢琴音色加入模拟卡带走带不均的音高颤动（Wow/Flutter）", "在 8kHz 处对鼓总线做低通滚降吸收一切刺耳高频"]}},

  {"id": "east-coast-hip-hop", "name": "East Coast Hip Hop", "aliases": ["东海岸嘻哈"], "category": "Hip Hop", "year": "1985", "bpm": "85–95 BPM", "default_bpm": 90, "style": "breakbeat", "place": {"en": "New York, USA", "zh": "美国纽约"},
   "artists": ["Wu-Tang Clan", "Mobb Deep", "Nas", "Big L", "Jay-Z"],
   "context": {"en": "Centered in New York, famed for complex multi-syllabic lyricism, dark minor piano chops, gritty vinyl crackle, and aggressive street realism.", "zh": "以纽约为大本营，以错综复杂的多音节押韵技巧、暗黑小调黑胶钢琴切片与冷酷写实的街头叙事著称。"},
   "soundDesign": {"en": "Kung fu movie voice samples, dark minor grand piano loops, crackling vinyl breaks, SP-1200 grit.", "zh": "功夫电影对话采样、暗黑小调大钢琴循环、黑胶爆豆碎拍与 SP-1200 粗砺采样声。"},
   "rhythmFeatures": {"en": "Hard, aggressive boom-bap drums with cracking snares hitting dead-on on beats 2 and 4.", "zh": "刚硬有力的 Boom-Bap 鼓点，脆响军鼓在 2、4 拍精准下坠。"},
   "bassPattern": {"en": "Deep, rumbling acoustic bass or filtered bass guitar loops anchoring the street poetry.", "zh": "深沉低鸣的原声贝斯或滤波贝斯吉他循环，稳稳锚定街头诗篇。"},
   "productionTips": {"en": ["Sample kung fu film dialogues or vintage eerie crime soundtracks", "Chop piano chords aggressively and replay with sharp attacks", "Keep the drum kit raw and hard-hitting with analog clipping"], "zh": ["采样老派功夫电影对话或复古犯罪悬疑配乐", "将小调钢琴和弦粗暴切片并以急促起音重奏", "通过模拟过载剪切让鼓组敲击保持生猛原始冲击力"]}},

  {"id": "west-coast-hip-hop", "name": "West Coast Hip Hop", "aliases": ["西海岸嘻哈"], "category": "Hip Hop", "year": "1983", "bpm": "90–102 BPM", "default_bpm": 95, "style": "standard", "place": {"en": "Los Angeles, California, USA", "zh": "美国加州洛杉矶"},
   "artists": ["N.W.A", "Ice Cube", "2Pac", "Eazy-E", "DJ Yella"],
   "context": {"en": "Originated in LA, fusing electro-funk and heavy synthesized basslines with raw gangsta rap storytelling and sun-drenched cruising grooves.", "zh": "起源于加州洛杉矶，将电子放克与重型合成低音线条同街头说唱故事及加州阳光下的巡游律动融合。"},
   "soundDesign": {"en": "Heavy analog synth bass, talkbox vocoders, crisp handclaps, funk rhythm guitars.", "zh": "重型模拟合成贝斯、谈话盒人声效果器、清脆拍手与放克扫弦吉他。"},
   "rhythmFeatures": {"en": "Driving mid-tempo funk groove with crisp 808-style claps and prominent open hi-hats.", "zh": "推进式中速放克节拍，伴随清脆 808 风格叠层拍手与标志性开镲。"},
   "bassPattern": {"en": "Bouncing, highly syncopated analog synth basslines that propel cruising car sound systems.", "zh": "弹跳切分的模拟合成低音线条，专为在低底盘汽车音响中巡游炸街而生。"},
   "productionTips": {"en": ["Layer handclaps with crisp snares on beats 2 and 4", "Write syncopated 16th-note basslines using Moog Minimoog sawtooth and square waves", "Add talkbox vocal phrases for classic West Coast swagger"], "zh": ["在 2、4 拍将响亮拍手与清脆军鼓紧密叠合", "使用 Moog Minimoog 锯齿波与方波编写切分十六分音符贝斯线条", "加入谈话盒（Talkbox）人声音效赋予纯正西海岸韵味"]}},

  {"id": "southern-hip-hop", "name": "Southern Hip Hop", "aliases": ["南方嘻哈", "Dirty South"], "category": "Hip Hop", "year": "1990", "bpm": "70–80 BPM (140-160)", "default_bpm": 75, "style": "half_time", "place": {"en": "Houston, Memphis & Atlanta, USA", "zh": "美国休斯敦、孟菲斯与亚特兰大"},
   "artists": ["Outkast", "Three 6 Mafia", "UGK", "Ludacris", "Lil Wayne"],
   "context": {"en": "Defined by the bounce of Atlanta, the chopped-and-screwed sound of Houston, and dark Memphis tape loops, celebrating massive low end and energetic chants.", "zh": "融合亚特兰大弹跳、休斯敦降速撕扯（Chopped and Screwed）与孟菲斯暗黑磁带，以庞大低频与呐喊口号征服全球。"},
   "soundDesign": {"en": "Roland TR-808 sub bass, brass synthesizer blasts, chants (Yeah!, What!), chopped slowed-down vocals.", "zh": "Roland TR-808 超重低音、铜管合成器齐鸣、口号呐喊切片与降速变调人声。"},
   "rhythmFeatures": {"en": "Heavy half-time bounce with syncopated 808 kicks and rapid hi-hat trills.", "zh": "沉重半速弹跳，伴随切分 808 底鼓与极速踩镲颤音。"},
   "bassPattern": {"en": "Massive booming 808 sub kicks held long with pitch drops.", "zh": "庞大轰鸣的 808 超重底鼓，带有长延音与音高下潜。"},
   "productionTips": {"en": ["Slow down track tempo by 15-20% to emulate the iconic Houston chopped-and-screwed feel", "Stack brass synthesisers playing staccato chords in minor keys", "Place energetic crowd hype chants on the offbeats"], "zh": ["将整首音乐降速 15-20% 复刻休斯敦标志性 Chopped and Screwed 质感", "多层叠置小调短促断奏铜管合成器和弦", "在反拍安放充满感染力的现场人声口号喊麦"]}},

  {"id": "cloud-rap", "name": "Cloud Rap", "aliases": ["云雾说唱"], "category": "Hip Hop", "year": "2009", "bpm": "120–140 BPM", "default_bpm": 130, "style": "half_time", "place": {"en": "USA & Sweden", "zh": "美国与瑞典"},
   "artists": ["Clams Casino", "A$AP Rocky", "Yung Lean", "Lil B", "Bladee"],
   "context": {"en": "Pioneered by Clams Casino, featuring ethereal, dreamlike synth pads, slowed-down vocal sighs, floating atmospheres, and spaced-out trap beats.", "zh": "由 Clams Casino 等人开创，以缥缈虚幻的梦境合成铺底、叹息般的人声切片、浮空氛围与冥想 Trap 节拍著称。"},
   "soundDesign": {"en": "Ethereal synth clouds, reversed female vocal sighs, drowning plate reverbs, warm 808s.", "zh": "飘渺空灵合成器云雾、反向人声叹息、浸没式板式混响与温暖 808。"},
   "rhythmFeatures": {"en": "Spacious, floating half-time trap rhythm with muffled snares and understated hi-hats.", "zh": "空旷失重的半速 Trap 节拍，搭配柔和沉闷军鼓与低调细致踩镲。"},
   "bassPattern": {"en": "Warm, round 808 sub bass that hums gently beneath the dreamlike synth layers.", "zh": "温暖圆润的 808 超低音，在梦幻合成音色下方沉静低鸣。"},
   "productionTips": {"en": ["Take an ethereal female vocal phrase, reverse it, pitch it down, and drown it in 80% wet reverb", "Filter drum kicks to remove harsh clicks and preserve weight", "Keep musical elements floating without sharp transients"], "zh": ["截取空灵女性人声音节反向翻转、降调并推入 80% 湿声混响中", "对底鼓做滤波软化瞬态敲击头，保留温润低频重力", "让所有音乐元素如云朵般轻柔漂浮，避免一切尖锐瞬态"]}}
]

save_module("rock_metal.ts", "ROCK_METAL_GENRES", rock_metal_list)
save_module("hiphop.ts", "HIPHOP_GENRES", hiphop_list)
print("Completed Batch 4: Rock/Metal (17), Hip Hop (11) = 28 genres!")
