from gen_p1 import save_module

house_list = [
  {"id": "chicago-house", "name": "Chicago House", "aliases": ["芝加哥浩室"], "category": "Electronic", "year": "1984", "bpm": "120–128 BPM", "default_bpm": 124, "style": "four_on_floor", "place": {"en": "Chicago, USA", "zh": "美国芝加哥"},
   "artists": ["Frankie Knuckles", "Marshall Jefferson", "Larry Heard", "Ron Hardy", "Chip E."],
   "context": {"en": "Pioneered at The Warehouse club, turning disco into hypnotic 4/4 electronic drum workouts.", "zh": "发源于芝加哥 The Warehouse 俱乐部，将迪斯科改造为催眠的四四拍电子鼓机律动。"},
   "soundDesign": {"en": "TR-909 open hats, punchy analog kicks, Korg M1 organ bass stabs.", "zh": "Roland TR-909 反拍开镲、厚重模拟底鼓与 Korg M1 风琴贝斯切片。"},
   "rhythmFeatures": {"en": "Four-on-the-floor kick with 16th swing claps and offbeat open hi-hats.", "zh": "四踩四底鼓配合带摇摆的十六分音符拍手与反拍开镲。"},
   "bassPattern": {"en": "Walking organ or analog basslines with octave leaps locked to kick.", "zh": "八度跳跃的行进风琴或模拟低音线条，与底鼓紧密贴合。"},
   "productionTips": {"en": ["Tune kick to 55Hz", "Apply 55% swing", "Use M1 organ stabs"], "zh": ["底鼓调至 55Hz", "应用 55% 摇摆度", "使用 M1 风琴和弦切片"]}},
  
  {"id": "deep-house", "name": "Deep House", "aliases": ["深邃浩室"], "category": "Electronic", "year": "1985", "bpm": "120–125 BPM", "default_bpm": 122, "style": "four_on_floor", "place": {"en": "Chicago & NY, USA", "zh": "美国芝加哥与纽约"},
   "artists": ["Larry Heard", "Kerri Chandler", "Theo Parrish", "Moodymann", "Maya Jane Coles"],
   "context": {"en": "Infuses house with sophisticated jazz chords, soulful Rhodes, and ambient warmth.", "zh": "将复杂的爵士和弦、深情的 Rhodes 电钢琴与氛围深度注入浩室。"},
   "soundDesign": {"en": "Fender Rhodes chords, low-pass filtered pads, warm sine sub-bass.", "zh": "Fender Rhodes 电钢琴、低通滤波铺底与纯净正弦波 Sub 贝斯。"},
   "rhythmFeatures": {"en": "Laid-back, slightly behind-the-beat 4/4 groove with pillowy kicks.", "zh": "从容放松、微带后倾的四四拍律动，搭配柔软底鼓与有机木质打击乐。"},
   "bassPattern": {"en": "Melodic sine sub lines weaving under minor 9th jazz chord changes.", "zh": "深沉悠扬的正弦波低音线条，在小九度爵士和弦变换下方游走穿梭。"},
   "productionTips": {"en": ["Stack minor 9th chords", "Filter cutoff down to 800Hz", "Attenuate kick above 3kHz"], "zh": ["堆叠小九和弦", "低通滤波截止压在 800Hz", "衰减底鼓 3kHz 以上高频"]}},

  {"id": "tech-house", "name": "Tech House", "aliases": ["科技浩室"], "category": "Electronic", "year": "1994", "bpm": "124–128 BPM", "default_bpm": 126, "style": "four_on_floor", "place": {"en": "London & Ibiza", "zh": "伦敦与伊比萨"},
   "artists": ["Fisher", "Jamie Jones", "Michael Bibi", "Green Velvet", "Solardo"],
   "context": {"en": "Fuses hypnotic techno drive with funky house swing and bouncy sub-bass.", "zh": "融合了 Techno 机械催眠的驱动力与 House 的放克摇摆及弹性低频。"},
   "soundDesign": {"en": "Short punchy kicks, resonant FM rolling bass, metallic rimshots.", "zh": "短促有力的瞬态底鼓、滚动的 FM 合成贝斯与金属边击。"},
   "rhythmFeatures": {"en": "Relentless rolling percussion groove with syncopated 16th hats.", "zh": "连续不断的滚动打击乐律动，切分十六分音符踩镲与幽灵军鼓。"},
   "bassPattern": {"en": "Rolling 16th-note sub bass or syncopated offbeat bouncy FM pluck bass.", "zh": "滚动的十六分音符 Sub 低音或富有弹性跳跃感的反拍 FM 拨弦贝斯。"},
   "productionTips": {"en": ["Write rolling 16th bassline", "Add 1/16 delay to clicks", "Keep harmony sparse"], "zh": ["编写十六分音符滚动低音", "打击乐加 1/16 延迟", "保持和声高度精简"]}},

  {"id": "future-house", "name": "Future House", "aliases": ["未来浩室"], "category": "Electronic", "year": "2013", "bpm": "125–128 BPM", "default_bpm": 126, "style": "four_on_floor", "place": {"en": "Netherlands & UK", "zh": "荷兰与英国"},
   "artists": ["Oliver Heldens", "Don Diablo", "Tchami", "Brooks", "Mesto"],
   "context": {"en": "Pairs UK Garage metallic FM bass stabs with modern EDM festival arrangements.", "zh": "将 UK Garage 金属质感 FM 贝斯与现代 EDM 音乐节曲式融合。"},
   "soundDesign": {"en": "Metallic FM bass stabs, crisp claps, high-passed vocal chops.", "zh": "金属质感 FM 合成贝斯切片、清脆高频拍手与高通滤波人声切片。"},
   "rhythmFeatures": {"en": "Bouncy 4/4 rhythm with crisp claps on 2 and 4, sharp open hats.", "zh": "弹性十足的 4/4 拍律动，2、4 拍重击拍手，反拍搭配锋利开镲。"},
   "bassPattern": {"en": "Melodic FM pluck bass playing syncopated hooks across 2 octaves.", "zh": "兼任旋律与节奏骨架的跨双八度切分拨弦 FM 贝斯。"},
   "productionTips": {"en": ["Use 1:2 FM ratio with quick decay", "Layer clean sub sine wave", "Use OTT multiband compression"], "zh": ["使用 1:2 频率比与快速衰减包络", "贝斯下方叠一层纯正超低正弦波", "使用 OTT 多频段压缩获得透亮感"]}},

  {"id": "progressive-house", "name": "Progressive House", "aliases": ["渐进浩室"], "category": "Electronic", "year": "1990", "bpm": "126–130 BPM", "default_bpm": 128, "style": "four_on_floor", "place": {"en": "UK & Sweden", "zh": "英国与瑞典"},
   "artists": ["Avicii", "Swedish House Mafia", "Deadmau5", "Eric Prydz", "Alesso"],
   "context": {"en": "Famous for expansive build-ups, soaring anthemic melodies, and cathartic drops.", "zh": "以漫长递进的情感铺垫、辽阔恢弘的和弦走向与排山倒海的释放著称。"},
   "soundDesign": {"en": "Multi-layered detuned supersaws, massive white-noise sweeps, sidechained pads.", "zh": "多层立体声去谐 Supersaw 主音、震撼白噪声扫频与深度侧链泵动的铺底。"},
   "rhythmFeatures": {"en": "Big room punchy kick, heavy clap on 2 and 4, rising snare rolls.", "zh": "极具冲击力的大底鼓，2、4 拍重击拍手，在 Build-up 阶段带有极速递进军鼓。"},
   "bassPattern": {"en": "Driving saw bass following root notes, heavily ducked under the kick.", "zh": "紧跟和弦根音进行的强劲反拍锯齿波贝斯，在底鼓敲击瞬间深度避让。"},
   "productionTips": {"en": ["Layer 3-4 synth presets for lead", "Automate filter cutoff over 32 bars", "High-shelf boost at 10kHz"], "zh": ["为主音旋律叠加 3-4 层音色", "滤波截止在 32 小节内平滑提升", "10kHz 高架均衡提亮光泽"]}},

  {"id": "electro-house", "name": "Electro House", "aliases": ["电子浩室"], "category": "Electronic", "year": "2002", "bpm": "128–132 BPM", "default_bpm": 128, "style": "four_on_floor", "place": {"en": "Europe & USA", "zh": "欧洲与美国"},
   "artists": ["Benny Benassi", "Wolfgang Gartner", "Hardwell", "Fedde Le Grand", "Steve Aoki"],
   "context": {"en": "Abrasive buzzing saw basslines, heavy distortion, and aggressive sidechain pumping.", "zh": "以侵略性蜂鸣电锯锯齿波贝斯、重度失真与夸张侧链闪避著称。"},
   "soundDesign": {"en": "Detuned saw waves with bitcrushing, vocoders, aggressive sub drops.", "zh": "经过降采样失真处理的去谐锯齿波、声码器机械人声和强烈的超低频下潜。"},
   "rhythmFeatures": {"en": "Heavy stomping 4/4 beat with sharp layered snares and punchy claps.", "zh": "重击般的四踩四底鼓律动，伴随锋利的双层叠军鼓和强劲拍手。"},
   "bassPattern": {"en": "Buzz-saw staccato riffs playing rapid syncopations right on the grid.", "zh": "电锯般撕裂的断奏低音 Riff，在节拍网格上进行极速切分轰击。"},
   "productionTips": {"en": ["Apply hard clipping distortion on saw bass", "Use heavy ducking sidechain", "Invert phases to prevent cancellation"], "zh": ["锯齿波贝斯硬剪切失真", "施加激进侧链闪避", "检查多层合成器相位反转"]}},

  {"id": "bass-house", "name": "Bass House", "aliases": ["低音浩室"], "category": "Electronic", "year": "2014", "bpm": "126–128 BPM", "default_bpm": 128, "style": "four_on_floor", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["Jauz", "Habstrakt", "JOYRYDE", "AC Slater", "Ephwurd"],
   "context": {"en": "Fuses 4/4 house groove with aggressive FM growls and sheer low-end weight.", "zh": "融合了 4/4 浩室律动与 Dubstep 及英国低音狂暴的 FM 嘶吼与超重低频。"},
   "soundDesign": {"en": "Wavetable growls, metallic FM screech plucks, fast pitch bends.", "zh": "受 LFO 调制的波表嘶吼低音、金属 FM 尖叫弹拨与快速音高滑音。"},
   "rhythmFeatures": {"en": "Tight punchy 4/4 kicks with chunky claps and snappy ghost percussion.", "zh": "紧凑扎实的 4/4 底鼓，搭配厚实的拍手与干脆利落的幽灵打击乐过门。"},
   "bassPattern": {"en": "Heavy syncopated wobbly bass shifting between mid-growl and rumbling sub.", "zh": "重型切分摇摆贝斯，在中频咆哮旋律与轰鸣超低频之间交织切换。"},
   "productionTips": {"en": ["Design bass in wavetables with comb filters", "Split bass at 120Hz", "Add pitch bends at note starts"], "zh": ["波表合成器利用梳状滤波增添金属感", "在 120Hz 处分频处理", "在每个贝斯起始处加微小滑音"]}},

  {"id": "ghetto-house", "name": "Ghetto House", "aliases": ["贫民区浩室"], "category": "Electronic", "year": "1992", "bpm": "125–135 BPM", "default_bpm": 130, "style": "four_on_floor", "place": {"en": "Chicago, USA", "zh": "美国芝加哥"},
   "artists": ["DJ Deeon", "DJ Slugo", "DJ Funk", "Paul Johnson", "Houz' Mon"],
   "context": {"en": "Stripped house down to fast 808/909 drum workouts with repetitive vocal loops.", "zh": "将音乐精简为极速的 808/909 鼓机节奏与直白露骨的人声循环。"},
   "soundDesign": {"en": "Raw TR-808 cowbells and toms, unpolished tape distortion, vocal chops.", "zh": "未经修饰的 TR-808 牛铃与通鼓、磁带失真质感与短促人声切片。"},
   "rhythmFeatures": {"en": "Fast 4/4 kicks with syncopated 808 clap rolls and energetic toms.", "zh": "快速奔跑的四踩四底鼓，穿插切分 808 拍手滚奏与活力通鼓。"},
   "bassPattern": {"en": "Boom-heavy 808 sub kicks doubled with short analog bass stabs.", "zh": "极简的 808 超重轰鸣低频，与短促的模拟合成贝斯刺音双重叠加。"},
   "productionTips": {"en": ["Embrace raw drum programming", "Pitch up vocal snippet and loop", "Overdrive mixer input channel"], "zh": ["保持粗犷未过度打磨的鼓机编写", "截取口号词汇升高两个半音循环", "调音台输入增益适度过载"]}},

  {"id": "tropical-house", "name": "Tropical House", "aliases": ["热带浩室"], "category": "Electronic", "year": "2013", "bpm": "100–115 BPM", "default_bpm": 108, "style": "four_on_floor", "place": {"en": "Norway & Australia", "zh": "挪威与澳大利亚"},
   "artists": ["Kygo", "Thomas Jack", "Matoma", "Sam Feldt", "Robin Schulz"],
   "context": {"en": "Slowed house music down to breezy tempos, evoking sunny beach vibes with acoustic instruments.", "zh": "将浩室节奏放慢至惬意的 100-115 BPM，融入原声乐器勾勒阳光明媚海滩度假听感。"},
   "soundDesign": {"en": "Wooden marimbas, pan flutes, bright acoustic guitar plucks, saxophones.", "zh": "木质马林巴琴、排箫、明亮原声吉他拨弦、萨克斯与空灵混响空间。"},
   "rhythmFeatures": {"en": "Relaxed bounce-oriented 4/4 kick with gentle claps, bongos, and shakers.", "zh": "舒缓兼具弹跳感的 4/4 底鼓，柔和拍手、邦戈鼓与清脆沙锤循环。"},
   "bassPattern": {"en": "Warm bouncy upright bass or soft round sub complementing melody.", "zh": "温暖有弹性的原声贝斯或圆润 Sub 低音，轻柔支撑着主旋律线条。"},
   "productionTips": {"en": ["Layer marimba with plucked synth", "Keep tempo below 115 BPM", "Use lush hall reverbs with pre-delay"], "zh": ["物理建模马林巴琴与合成拨弦叠层", "速度控制在 115 BPM 以下", "原声乐器使用预延时大厅混响"]}},

  {"id": "acid-house", "name": "Acid House", "aliases": ["酸性浩室"], "category": "Electronic", "year": "1985", "bpm": "120–130 BPM", "default_bpm": 125, "style": "four_on_floor", "place": {"en": "Chicago, USA", "zh": "美国芝加哥"},
   "artists": ["Phuture", "DJ Pierre", "Sleezy D", "808 State", "Adonis"],
   "context": {"en": "Invented on the Roland TB-303, squelchy resonant sweeps sparked the 1988 Second Summer of Love.", "zh": "在 Roland TB-303 上偶然创立，尖锐酸楚的共鸣滤波扫频催生了 1988 年“第二爱之夏”。"},
   "soundDesign": {"en": "Roland TB-303 with high resonance, modulated cutoff, accented steps.", "zh": "调高谐振峰的 Roland TB-303 贝斯合成器，搭配手拧滤波截止与磁带饱和。"},
   "rhythmFeatures": {"en": "TR-707 or 909 4/4 drums with snapping snares, rimshots, and driving rides.", "zh": "Roland TR-707/909 四四拍鼓机节奏，脆响军鼓、边击和激进 Ride 镲。"},
   "bassPattern": {"en": "Hypnotic 16-step 303 sequence full of slide and accent commands.", "zh": "催眠魔性的 16 步 303 音序，充满连音滑音（Slide）与重音（Accent）。"},
   "productionTips": {"en": ["Program legato notes for slide", "Automate cutoff and resonance in real-time", "Add distortion before delay"], "zh": ["将音序音符编写为连奏触发连音滑音", "实时自动化滤波截止与谐振峰", "延迟前串联轻微失真单块穿透混音"]}},

  {"id": "french-house", "name": "French House", "aliases": ["法国浩室", "French Touch"], "category": "Electronic", "year": "1995", "bpm": "120–128 BPM", "default_bpm": 124, "style": "four_on_floor", "place": {"en": "Paris, France", "zh": "法国巴黎"},
   "artists": ["Daft Punk", "Cassius", "Alan Braxe", "Fred Falke", "Stardust"],
   "context": {"en": "French Touch took 70s disco vinyl samples and drenched them in extreme sidechain pumping.", "zh": "法式触感截取 70 年代迪斯科黑胶采样，浸润在极度夸张的侧链抽吸压缩与移相器中。"},
   "soundDesign": {"en": "Alesis 3630 sidechain pumping, sweeping phasers, vinyl disco chops, slap bass.", "zh": "Alesis 3630 侧链抽吸泵感、大范围扫动移相器、复古黑胶切片与放克 Slap 贝斯。"},
   "rhythmFeatures": {"en": "Uplifting 4/4 kick with disco hi-hat shuffles, handclaps, and tambourines.", "zh": "充满欢愉能量的四四拍底鼓，迪斯科摇摆踩镲、拍手与摇铃滚奏。"},
   "bassPattern": {"en": "Funky walking slap electric bass or rounded Juno bass mirroring sample.", "zh": "极富放克律动的行进 Slap 贝斯或圆润 Juno 低音，呼应采样的放克和弦。"},
   "productionTips": {"en": ["Sample 2-bar disco loop into sidechain compressor", "Use vintage phaser with high feedback", "Layer live slap bass directly underneath"], "zh": ["截取迪斯科采样挂载由底鼓触发的侧链压缩", "施加慢速高反馈复古移相器", "在采样下方叠录一条 Slap 原声电贝斯"]}},

  {"id": "melodic-house", "name": "Melodic House", "aliases": ["旋律浩室"], "category": "Electronic", "year": "2016", "bpm": "120–125 BPM", "default_bpm": 123, "style": "four_on_floor", "place": {"en": "Berlin & London", "zh": "柏林与伦敦"},
   "artists": ["Ben Böhmer", "Lane 8", "Tale of Us", "Yotto", "Nora En Pure"],
   "context": {"en": "Blends deep house grooves with emotive, cinematic synth arpeggios and poignant harmonies.", "zh": "将深邃四四拍律动与充满电影感的花阶合成琶音和小调和声深度结合。"},
   "soundDesign": {"en": "Intricate synth arpeggios, organic percussion, felt piano, tape delays.", "zh": "细腻调制的花阶合成琶音、有机原声打击乐、毛毡静音真钢琴与磁带模拟延迟。"},
   "rhythmFeatures": {"en": "Deep driving kick with organic shaker loops, subtle clicks, delicate offbeat hats.", "zh": "深沉推进的圆润底鼓，有机沙锤循环、细小质感打击击弦音与反拍踩镲。"},
   "bassPattern": {"en": "Warm rolling Reese or Moog saw bass filtered down with gentle LFO movement.", "zh": "温暖滚动的 Reese 贝斯或低通滤波 Moog 低音，带有柔和 LFO 呼吸感。"},
   "productionTips": {"en": ["Automate arpeggio decay and cutoff over 32 bars", "Layer real percussion with synthetic drums", "Use ping-pong delay with dotted-eighths"], "zh": ["对琶音衰减与滤波截止长达 32 小节自动化推演", "原声打击乐与电子鼓组交叠注入温度", "使用附点八分音符乒乓延迟构筑空间"]}},

  {"id": "afro-house", "name": "Afro House", "aliases": ["非洲浩室"], "category": "Electronic", "year": "2000", "bpm": "120–125 BPM", "default_bpm": 122, "style": "four_on_floor", "place": {"en": "South Africa & Angola", "zh": "南非与安哥拉"},
   "artists": ["Black Coffee", "Culoe De Song", "Da Capo", "Shimza", "THEMBA"],
   "context": {"en": "Combines hypnotic 4/4 deep house with traditional African percussion, polyrhythms, and chants.", "zh": "将 Deep House 四四拍基调与非洲传统打击乐、交错复合节奏与灵性咏唱熔铸。"},
   "soundDesign": {"en": "Organic djembes, congas, talking drums, warm Rhodes, and grounded sub-bass.", "zh": "原声非洲金贝鼓、康加鼓、会说话的鼓、温暖 Rhodes 和弦与沉稳超低频。"},
   "rhythmFeatures": {"en": "Polyrhythmic drum layering with triplets, syncopated rimshots, and 4/4 kick.", "zh": "复杂复合节奏鼓组叠置，三连音与十六分音符相互嵌套，切分边击与底鼓呼应。"},
   "bassPattern": {"en": "Rolling syncopated low-end basslines weaving between traditional drum hits.", "zh": "滚动切分的低音线条，穿插游走于传统打击乐鼓点之间。"},
   "productionTips": {"en": ["Incorporate 3-against-4 polyrhythms against kick", "Keep sub clean below 70Hz for congas", "Use dynamic EQ on drums to tame harshness"], "zh": ["三对四复合节奏打击乐与底鼓互相碰撞", "70Hz 以下超低频纯净腾出中低频区间", "原声打击乐采用动态均衡器吸收毛刺"]}},

  {"id": "nu-disco-house", "name": "Nu-Disco House", "aliases": ["新迪斯科浩室"], "category": "Electronic", "year": "2002", "bpm": "118–124 BPM", "default_bpm": 120, "style": "four_on_floor", "place": {"en": "Norway & UK", "zh": "挪威与英国"},
   "artists": ["Todd Terje", "Lindstrøm", "Purple Disco Machine", "Dimitri From Paris", "Yuksek"],
   "context": {"en": "Revitalization of vintage disco with analog synths, live slap bass, and modern punch.", "zh": "对经典迪斯科的现代化复兴，融合复古模拟合成器、生动的放克贝斯与现代清脆重击。"},
   "soundDesign": {"en": "Arp Odyssey and Juno arpeggios, slap bass guitar, clavinet chops, brass stabs.", "zh": "复古合成琶音、Slap 电贝斯、电古钢琴切片与明亮铜管刺音。"},
   "rhythmFeatures": {"en": "Crisp 4/4 disco beat with offbeat open hats, acoustic snare + claps, cowbells.", "zh": "清脆四四拍迪斯科律动，反拍开镲、原声军鼓与拍手层叠敲击及律动牛铃。"},
   "bassPattern": {"en": "Syncopated live funk bass featuring slap/pop articulations and ghost notes.", "zh": "极富表现力的切分现场放克贝斯线条，充满击勾弦与幽灵音符。"},
   "productionTips": {"en": ["Program realistic bass ghost notes for pocket", "Add auto-wah envelope follower to clavinet", "Use tape flanging across drum bus in fills"], "zh": ["编写贝斯幽灵音营造放克松弛感", "为电古钢琴加上包络跟随器获得自动哇音", "过门加花阶段为鼓总线挂载磁带凸缘效果"]}},

  {"id": "microhouse", "name": "Microhouse", "aliases": ["微型浩室"], "category": "Electronic", "year": "1998", "bpm": "120–126 BPM", "default_bpm": 122, "style": "four_on_floor", "place": {"en": "Germany & Canada", "zh": "德国与加拿大"},
   "artists": ["Akufen", "Ricardo Villalobos", "Matthew Herbert", "Jan Jelinek", "Luomo"],
   "context": {"en": "Minimal house characterized by micro-samples, audio clicks and cuts, and subtle swing.", "zh": "由微采样切片、精巧毛刺与极度精简骨架鼓组构筑的极简浩室流派。"},
   "soundDesign": {"en": "Microscopic radio clicks, vinyl needle drops, subtle low-passed chords, sub sine.", "zh": "显微镜般的收音机电流轻击声、唱针摩擦音、低通滤波和弦与纯净正弦波。"},
   "rhythmFeatures": {"en": "Sparse, delicate rhythm composed of clicks, cuts, and organic foley over 4/4 kick.", "zh": "由咔哒声与微小拟音构筑的细腻稀疏节拍，倚靠在柔软四四拍底鼓之上。"},
   "bassPattern": {"en": "Subdued warm sine pulses beneath micro-percussions without drawing attention.", "zh": "克制温润的正弦低频在微观打击乐下方轻柔脉动。"},
   "productionTips": {"en": ["Slice radio snippet into 32 micro-grains", "Keep transient clicks at around -18dB", "Pan subtle micro-percussions randomly left and right"], "zh": ["短波收音机广播切分成 32 个微颗粒按律动编排", "瞬态咔哒声电平控制在 -18dB 保留亲近听感", "微型打击乐使用随机声像偏置营造沉浸空间"]}}
]

techno_list = [
  {"id": "detroit-techno", "name": "Detroit Techno", "aliases": ["底特律铁克诺"], "category": "Electronic", "year": "1985", "bpm": "125–135 BPM", "default_bpm": 128, "style": "four_on_floor", "place": {"en": "Detroit, USA", "zh": "美国底特律"},
   "artists": ["Juan Atkins", "Derrick May", "Kevin Saunderson", "Jeff Mills", "Robert Hood"],
   "context": {"en": "Created in mid-1980s Detroit, channeling post-industrial decline into Afro-futurist machine funk.", "zh": "1980 年代中期开创于底特律，将后工业时代的萧条感化为科幻意象的机械放克。"},
   "soundDesign": {"en": "Roland TR-909/808 drums, Juno synths, Yamaha DX100, metallic string stabs.", "zh": "Roland TR-909/808 鼓机、Roland Juno 与 Yamaha DX100 合成器及金属弦乐刺音。"},
   "rhythmFeatures": {"en": "Driving 4/4 mechanical pulse, high-energy ride cymbals, syncopated snares.", "zh": "极富催眠感的四四拍机械脉冲，能量充沛的 Ride 镲片敲击与切分军鼓。"},
   "bassPattern": {"en": "Repetitive, driving synth bass sequences locked with kick for relentless momentum.", "zh": "重复性极高的合成贝斯音序与底鼓咬合，赋予不可阻挡的向前冲击力。"},
   "productionTips": {"en": ["Sequence dynamic 16th-note hats with velocity nuances", "Sample orchestral stabs, pitch down 4 semitones", "Keep arrangement minimal, introducing elements slowly"], "zh": ["踩镲轨道编写带有力度阶梯的十六分音符", "采样管弦乐刺音向下移调 4 个半音获复古色彩", "结构极简克制，缓慢引入变化"]}},

  {"id": "minimal-techno", "name": "Minimal Techno", "aliases": ["极简铁克诺"], "category": "Electronic", "year": "1994", "bpm": "124–130 BPM", "default_bpm": 126, "style": "four_on_floor", "place": {"en": "Detroit & Berlin", "zh": "底特律与柏林"},
   "artists": ["Robert Hood", "Richie Hawtin", "Daniel Bell", "Ricardo Villalobos", "Marc Houle"],
   "context": {"en": "Stripped techno down to skeletal rhythms and skeletal repetition, avoiding overproduction.", "zh": "反抗过度制作的繁杂，将音乐精炼为骨骼般的纯粹节奏与极简重复。"},
   "soundDesign": {"en": "Short metallic clicks, resonant blips, filtered noise bursts, dry sub-bass kicks.", "zh": "极短金属敲击声、高共鸣蜂鸣点音、滤波噪声突发与干燥超低底鼓。"},
   "rhythmFeatures": {"en": "Hypnotic stripped 4/4 kick with micro-timed percussion clicks and sparse hats.", "zh": "极富催眠感的极简四踩四底鼓，搭配微观时值控制的打击乐点击声。"},
   "bassPattern": {"en": "Monolithic single-note sub pulses or short bass staccato pulses locked on grid.", "zh": "铁板一块的单音超低频脉冲，或节拍网格上短促干练的断奏贝斯跳动。"},
   "productionTips": {"en": ["Limit composition to 6-8 audio tracks", "Rely on envelope adjustments rather than new sounds", "Use tight noise gates to chop sound tails"], "zh": ["强制整首作品使用不超过 6 到 8 条音轨", "依靠毫秒级衰减与释放包络微调推进段落", "使用严格噪声门切断尾音获得冷峻利落感"]}},

  {"id": "acid-techno", "name": "Acid Techno", "aliases": ["酸性铁克诺"], "category": "Electronic", "year": "1992", "bpm": "135–145 BPM", "default_bpm": 138, "style": "four_on_floor", "place": {"en": "London & Berlin", "zh": "伦敦与柏林"},
   "artists": ["Chris Liberator", "D.A.V.E. The Drummer", "Sterling Moss", "Hardfloor", "Emmanuel Top"],
   "context": {"en": "Marrying squelching TB-303s with hard distorted 140+ BPM kicks and raw squat rave energy.", "zh": "将酸性尖叫的 TB-303 与 140+ BPM 硬核失真底鼓和暴烈地下狂欢能量联姻。"},
   "soundDesign": {"en": "Multiple overdriven TB-303 synths, screaming resonance, distorted 909 kicks.", "zh": "多台踏板过载的 TB-303、咆哮共振峰、失真 TR-909 底鼓与工业警报声。"},
   "rhythmFeatures": {"en": "Aggressive 4/4 stomping kick, relentless 16th-note ride cymbals, whipping snares.", "zh": "极速暴击的四踩四重踏底鼓、不休止的十六分音符 Ride 镲与清脆军鼓。"},
   "bassPattern": {"en": "Dual interleaved 303 sequences running high resonance and continuous slides.", "zh": "双轨交错的 303 音序，开启高谐振峰与连续不断的音高连音滑音。"},
   "productionTips": {"en": ["Route 303 into guitar amp distortion simulator", "Stack two 303 patterns an octave apart", "Sidechain 303 heavily to kick"], "zh": ["将 303 接入吉他箱头失真单块模拟器", "相隔八度的两条 303 音序并置播放制造音墙", "在 140 BPM 极速下对 303 精细侧链闪避"]}},

  {"id": "dub-techno", "name": "Dub Techno", "aliases": ["回响铁克诺"], "category": "Electronic", "year": "1993", "bpm": "118–125 BPM", "default_bpm": 120, "style": "four_on_floor", "place": {"en": "Berlin, Germany", "zh": "德国柏林"},
   "artists": ["Basic Channel", "Deepchord", "Echospace", "Rhythm & Sound", "Rod Modell"],
   "context": {"en": "Invented by Basic Channel in Berlin, fusing Detroit techno with tape delays and cavernous reverb.", "zh": "由 Basic Channel 在柏林开创，将底特律 Techno 与牙买加 Dub 磁带回声和洞穴混响交融。"},
   "soundDesign": {"en": "Tape-delayed minor chord stabs, sweeping filters with high feedback, analog noise.", "zh": "磁带延迟小调和弦切片、大反馈滤波回响、黑胶底噪与棉花般超低频。"},
   "rhythmFeatures": {"en": "Subdued soft 4/4 kick pulse muffled under analog noise and delayed percussive ripples.", "zh": "在层层模拟底噪与延迟波纹下沉潜的温和四四拍底鼓，克制冥想。"},
   "bassPattern": {"en": "Warm round sub-bass drone pulsing gently in sync with filtered chords.", "zh": "温暖圆润的超低频长鸣，与滤波和弦保持同步的微弱呼吸起伏。"},
   "productionTips": {"en": ["Feed tape delay output back into resonant filter", "Stack minor 9th stabs into 100% wet spring reverb", "Keep continuous analog hiss in background"], "zh": ["磁带延迟输出重新环回馈入带共振低通滤波器", "小九和弦刺音推入全湿弹簧混响", "始终保留一条持续的模拟磁带嘶嘶声"]}},

  {"id": "industrial-techno", "name": "Industrial Techno", "aliases": ["工业铁克诺"], "category": "Electronic", "year": "1990", "bpm": "135–150 BPM", "default_bpm": 140, "style": "four_on_floor", "place": {"en": "UK & Germany", "zh": "英国与德国"},
   "artists": ["Perc", "Paula Temple", "Surgeon", "Ancient Methods", "Dax J"],
   "context": {"en": "A dark subgenre merging techno hypnotic repetition with metal scrapes, clangs, and brutal distortion.", "zh": "将 Techno 催眠循环律动与工业金属摩擦声、机械撞击声和残暴失真融合。"},
   "soundDesign": {"en": "Crushed anvil impacts, distorted 909 kicks into analog mixers, harsh metallic feedback.", "zh": "重击铁砧采样、在模拟调音台上爆表的失真 909 底鼓与尖锐金属啸叫。"},
   "rhythmFeatures": {"en": "Heavy stomping kicks with syncopated metallic clangs serving as percussive markers.", "zh": "重型践踏式压迫底鼓，穿插着切分金属敲击声作为节奏标尺。"},
   "bassPattern": {"en": "Massive distorted low-end rumble generated by overdriving reverb tails from kick.", "zh": "由底鼓的超长混响尾音经过激进过载失真后形成的庞大低频轰鸣。"},
   "productionTips": {"en": ["Send kick to reverb at 100% wet and bitcrush", "Sample metal impacts and pitch down for claps", "Apply aggressive parallel distortion"], "zh": ["底鼓送入纯湿声混响切低通并加失真制造轰鸣", "采集金属撞击声向下移调制作暗黑拍手", "对鼓组采用并行失真保留瞬态清晰度"]}},

  {"id": "peak-time-techno", "name": "Peak Time Techno", "aliases": ["黄金时段铁克诺"], "category": "Electronic", "year": "2010", "bpm": "130–136 BPM", "default_bpm": 132, "style": "four_on_floor", "place": {"en": "Berlin & Amsterdam", "zh": "柏林与阿姆斯特丹"},
   "artists": ["Adam Beyer", "Charlotte de Witte", "Amelie Lens", "Enrico Sangiuliano", "Joyhauser"],
   "context": {"en": "Tailored for peak-time stages with thunderous sub rumbles and dramatic breakdowns.", "zh": "专为音乐节黄金时段量身定制，以雷霆万钧的低频轰鸣与戏剧性合成器大分解著称。"},
   "soundDesign": {"en": "Pulsing rumble kicks, monosynth hook lines, white-noise risers, vocal chants.", "zh": "脉动轰鸣底鼓（Rumble Kick）、催眠单音合成器 Hook、白噪升效与沉浸吟唱。"},
   "rhythmFeatures": {"en": "Straight driving 4/4 kicks with high-energy rolling 16th hats and build-up snare risers.", "zh": "笔直推进的四四拍底鼓，伴随高能量滚动十六分音符踩镲与密集军鼓提升。"},
   "bassPattern": {"en": "Tuned kick-rumble bassline locked into root note providing continuous low-end tsunami.", "zh": "定调精准紧扣主根音的底鼓轰鸣低音，制造源源不断的低频海啸。"},
   "productionTips": {"en": ["Craft rumble kick using delay + reverb + overdrive", "Automate reverb send and delay feedback during breakdowns", "Keep master dynamics punchy with modern limiter"], "zh": ["利用延迟+混响+过载反向侧链雕琢 Rumble Kick", "在转场阶段对主旋律合成器混响做激进抬升", "使用透明度极高的母带限制器控制峰值"]}},

  {"id": "hard-techno", "name": "Hard Techno", "aliases": ["硬核铁克诺"], "category": "Electronic", "year": "1995", "bpm": "145–160 BPM", "default_bpm": 152, "style": "four_on_floor", "place": {"en": "Frankfurt & Paris", "zh": "法兰克福与巴黎"},
   "artists": ["Nico Moreno", "Klangkuenstler", "I Hate Models", "Alignment", "Viper Diva"],
   "context": {"en": "Pushes tempos past 150 BPM with distorted blown-out kick drums and relentless aggression.", "zh": "将速度狂飙至 150 BPM 以上，以失真炸裂的底鼓、复古狂欢旋律与野蛮冲击力著称。"},
   "soundDesign": {"en": "Hard clipped kicks, screaming screech synths, metallic clatter, saturated rave stabs.", "zh": "硬剪切底鼓、尖叫撕裂的 Screech 合成音色、金属碎裂声与饱和复古刺音。"},
   "rhythmFeatures": {"en": "Blistering 4/4 pounding kicks with furious 16th-note ride cymbals, whipping offbeat snares.", "zh": "狂风骤雨般的四四拍狂锤底鼓，配合暴风般的十六分音符 Ride 镲与反拍军鼓。"},
   "bassPattern": {"en": "Extreme distorted sub bass tails that continuously shake the low spectrum without pauses.", "zh": "极度失真过载的超低音尾音，密不透风地持续撼动整个超低音频段。"},
   "productionTips": {"en": ["Overdrive drum bus with analog tape saturation", "Tweak high-pass filters on mid screeches", "Layer punch kicks with shortened decay for 155 BPM"], "zh": ["使用模拟磁带饱和插件适度过载鼓组总线", "对中频尖叫音色做严格高通切除防止污染低频", "选用衰减极短的高瞬态底鼓确保 155 BPM 清晰"]}},

  {"id": "ambient-techno", "name": "Ambient Techno", "aliases": ["氛围铁克诺"], "category": "Electronic", "year": "1991", "bpm": "115–124 BPM", "default_bpm": 120, "style": "four_on_floor", "place": {"en": "UK & Belgium", "zh": "英国与比利时"},
   "artists": ["The Orb", "Biosphere", "Aphex Twin", "Global Communication", "GAS"],
   "context": {"en": "Chill-out room music merging subtle 4/4 techno pulses with weightless ambient soundscapes.", "zh": "派对 Chill-out 休息区音乐，将 Techno 克制四四拍脉动与 Ambient 辽阔声音景观熔合。"},
   "soundDesign": {"en": "Ethereal synth washes, shimmering reverbs, nature field recordings, pillowy kicks.", "zh": "飘渺空灵的合成铺底、闪烁晶莹的漫长混响、自然环境采样与柔和底鼓。"},
   "rhythmFeatures": {"en": "Gentle, understated 4/4 rhythm providing a hypnotic anchor without overwhelming space.", "zh": "温和内敛的四四拍节奏，为浩瀚声音空间提供催眠引力锚点。"},
   "bassPattern": {"en": "Deep, slow-moving sine sub-bass drones shifting gently over extended periods.", "zh": "深沉缓慢移动的正弦波低音长鸣，在漫长时间跨度内平缓流动。"},
   "productionTips": {"en": ["Send pads into reverbs with decay over 10 seconds", "Layer vinyl noise or forest ambience", "Soften drum transients with slow attack compressors"], "zh": ["合成器送入衰减超过 10 秒的深空混响", "在背景层叠录微弱黑胶爆豆声注入触觉温度", "使用慢起音压缩器软化鼓组瞬态使其融入环境"]}},

  {"id": "raw-techno", "name": "Raw Techno", "aliases": ["原始铁克诺"], "category": "Electronic", "year": "2012", "bpm": "130–138 BPM", "default_bpm": 134, "style": "four_on_floor", "place": {"en": "UK & Germany", "zh": "英国与德国"},
   "artists": ["Oscar Mulero", "Blawan", "Karenn", "Shifted", "Setaoc Mass"],
   "context": {"en": "A return to analog hardware fundamentals and tape grit, prioritizing modular polyrhythms.", "zh": "对模拟硬件本源与磁带粗糙质感的致敬与回归，专注于模块化复合节奏与深层催眠律动。"},
   "soundDesign": {"en": "Overdriven analog drum synths, Eurorack modular squeals, tape hiss, dark metal percussion.", "zh": "过载模拟鼓机音色、模块合成啸叫、磁带底噪与暗色金属敲击打击乐。"},
   "rhythmFeatures": {"en": "Syncopated hypnotic percussive grooves with polyrhythmic step sequencing and ghost hits.", "zh": "切分且极其催眠的打击乐律动，充满多节奏音序排列与幽灵敲击点。"},
   "bassPattern": {"en": "Subdued analog sub-frequency pulses locking tightly with the kick tail.", "zh": "深潜内敛的模拟超低频脉冲，与底鼓尾部紧密啮合为一体。"},
   "productionTips": {"en": ["Record hardware synthesizers live", "Drive drum loops through real analog guitar preamps", "Automate envelope parameters polyrhythmically"], "zh": ["实时实录硬件合成器演奏保留微妙时间差", "将鼓循环送入真实吉他前级电子管设备染色", "采用非常规步进循环对包络进行调制"]}},

  {"id": "schranz", "name": "Schranz", "aliases": ["施兰茨铁克诺"], "category": "Electronic", "year": "1999", "bpm": "150–160 BPM", "default_bpm": 155, "style": "four_on_floor", "place": {"en": "Frankfurt, Germany", "zh": "德国法兰克福"},
   "artists": ["Chris Liebing", "DJ Rush", "Speedy J", "Boris S.", "Felix Kröcher"],
   "context": {"en": "150+ BPM techno built around heavily distorted, repetitive rhythmic loops that sound like smashing metal.", "zh": "速度突破 150+ BPM、围绕极度失真重复的铁石击打般碎裂循环建立的高能硬核 Techno。"},
   "soundDesign": {"en": "Massively compressed saturated loops, heavily distorted kicks, grinding metallic noise.", "zh": "超高压缩比与极度饱和打击乐循环、重度失真削波底鼓与摩擦金属噪声。"},
   "rhythmFeatures": {"en": "Monolithic pulverizing 4/4 kick assault with syncopated distorted loops at breakneck speed.", "zh": "如压路机般碾压的坚硬四踩四底鼓轰炸，伴随极速飞驰的切分失真循环。"},
   "bassPattern": {"en": "Blended completely into distorted kick body, forming a relentless low-end sledgehammer.", "zh": "完全融化在失真底鼓本体中，形成一柄毫无停歇的超重低频铁锤。"},
   "productionTips": {"en": ["Slam drum loop through 3 consecutive distortion plugins", "Apply aggressive band-pass filtering for mid punch", "Keep kicks tuned and tight to prevent mud at 155 BPM"], "zh": ["鼓循环连续送入 3 个串联过载失真效果器", "对节奏循环使用窄频带通滤波打造中频重击", "底鼓精准定调并收紧衰减防止低频混浊"]}}
]

trance_list = [
  {"id": "uplifting-trance", "name": "Uplifting Trance", "aliases": ["升华出神"], "category": "Electronic", "year": "1997", "bpm": "136–142 BPM", "default_bpm": 138, "style": "four_on_floor", "place": {"en": "Germany & UK", "zh": "德国与英国"},
   "artists": ["Armin van Buuren", "Aly & Fila", "Paul van Dyk", "Ferry Corsten", "John O'Callaghan"],
   "context": {"en": "Soaring emotional melodies, massive multi-octave supersaws, dramatic piano breakdowns, and euphoric drops.", "zh": "以直冲云霄的情感旋律、跨多八度的史诗 Supersaw 音墙、宏伟钢琴分解段落与升华释放著称。"},
   "soundDesign": {"en": "Detuned supersaw synth leads, dramatic piano chords, lush strings, soaring sweeps.", "zh": "多层去谐超锯齿波主音（Roland JP-8000）、戏剧性纯钢琴和弦与宏阔交响弦乐铺底。"},
   "rhythmFeatures": {"en": "Fast driving 138 BPM 4/4 kick drum with snappy offbeat open hats and continuous 16th bass.", "zh": "极速推进的 138 BPM 四踩四底鼓，配合明快的反拍开镲与奔流不息的十六分音符滚动贝斯。"},
   "bassPattern": {"en": "Rolling 16th-note triplets or driving sub-bass lines following chord root notes.", "zh": "滚动的十六分音符或三连音推进式低音线条，紧跟和弦根音波澜壮阔流转。"},
   "productionTips": {"en": ["In breakdown remove percussion, let piano build tension", "Layer 7 detuned saw oscillators with stereo spread", "Sidechain lead supersaws gently to kick"], "zh": ["在转场过渡段切除打击乐蓄积情感张力", "使用 7 个去谐立体声锯齿波振荡器", "对主音 Supersaw 音墙进行轻度侧链闪避"]}},

  {"id": "progressive-trance", "name": "Progressive Trance", "aliases": ["前卫出神"], "category": "Electronic", "year": "1996", "bpm": "128–134 BPM", "default_bpm": 132, "style": "four_on_floor", "place": {"en": "UK & Israel", "zh": "英国与以色列"},
   "artists": ["Above & Beyond", "Sasha & John Digweed", "Cosmic Gate", "Grum", "Ilan Bluestone"],
   "context": {"en": "Focuses on steady atmospheric progression rather than rapid breakdowns, blending trance melodies with house grooves.", "zh": "注重平稳连贯的氛围递进演变而非突兀大起大落，将 Trance 和声美感与深邃浩室律动结合。"},
   "soundDesign": {"en": "Plucked synth arpeggios, filtered analog pads, warm low-end basslines, delay tails.", "zh": "弹拨合成琶音、经过滤波的模拟铺底、温润有力的低音线条与精细回声尾音。"},
   "rhythmFeatures": {"en": "Tight balanced 4/4 beat at around 130 BPM with syncopated shaker loops and dynamic hats.", "zh": "在 130 BPM 保持紧凑均衡的四踩四节拍，搭配切分沙锤循环与富于动态变化的踩镲。"},
   "bassPattern": {"en": "Grooving offbeat bass or syncopated rolling lines with modulated filter cutoffs.", "zh": "富有律动感的反拍贝斯或带有平滑滤波调制的切分滚动线条。"},
   "productionTips": {"en": ["Focus on 32-bar blocks that evolve subtly", "Blend plucked transient layer with sustained pad", "High-pass non-bass elements above 120Hz"], "zh": ["以 32 小节为单元依靠平缓滤波自动化实现蜕变", "将瞬态弹拨层与延音铺底层叠合获得多维和弦", "对所有非贝斯乐器在 120Hz 处做干净高通切除"]}},

  {"id": "psytrance", "name": "Psytrance", "aliases": ["迷幻出神"], "category": "Electronic", "year": "1995", "bpm": "138–148 BPM", "default_bpm": 142, "style": "four_on_floor", "place": {"en": "Goa & Israel", "zh": "果阿与以色列"},
   "artists": ["Infected Mushroom", "Astrix", "Vini Vici", "Ace Ventura", "1200 Micrograms"],
   "context": {"en": "Relentless rolling 16th-note basslines (K-B-B-B), otherworldly psychedelic synth sweeps, and tribal chants.", "zh": "以标志性如疾风骤雨般的十六分音符低音（K-B-B-B 律动）、天外来客般的迷幻滤波扫频闻名。"},
   "soundDesign": {"en": "Complex FM squelches, resonant pitch zaps, granular audio glitches, tribal chants.", "zh": "复杂的 FM 酸性啸叫、高谐振音高扫频、粒子化音频毛刺与古老部落呼唤人声。"},
   "rhythmFeatures": {"en": "Punchy 4/4 kick immediately followed by three rolling 16th-note bass hits on each quarter beat.", "zh": "极速有力的四踩四底鼓，每拍后紧随三个十六分音符的连贯暴击（Kick-Bass-Bass-Bass）。"},
   "bassPattern": {"en": "Signature K-B-B-B saw bass with tight decay envelope and surgical EQ notched for kick.", "zh": "标志性 K-B-B-B 贝斯线：锯齿波配合紧凑衰减包络与手术刀式挖频。"},
   "productionTips": {"en": ["Tune kick and bass to exact same key", "Set bass notes with zero attack and 60ms decay", "Create psychedelic squelches using FM with random LFO"], "zh": ["将底鼓与贝斯精准校准在相同调性上对齐相位", "贝斯包络设定为 0 起音、60ms 衰减确保机关枪颗粒感", "使用 FM 合成器将随机 LFO 路由至音高生成迷幻音色"]}},

  {"id": "goa-trance", "name": "Goa Trance", "aliases": ["果阿出神"], "category": "Electronic", "year": "1992", "bpm": "130–145 BPM", "default_bpm": 138, "style": "four_on_floor", "place": {"en": "Goa, India", "zh": "印度果阿"},
   "artists": ["Astral Projection", "Man With No Name", "Hallucinogen", "Juno Reactor", "Total Eclipse"],
   "context": {"en": "Born on the beaches of Goa in the early 1990s, blending spiritual Indian scales, 303 acid lines, and outdoor celebration vibes.", "zh": "发端于 90 年代初印度果阿海滩，将灵性神秘的印度调式、高共振 303 酸性旋律与满月户外狂欢熔铸。"},
   "soundDesign": {"en": "Multiple layered 303 acid riffs, eastern modal melodies, sitar/tanpura textures.", "zh": "多层叠置的 303 酸性 Riff、东方神秘调式旋律、西塔琴环境纹理与共鸣滤波扫频。"},
   "rhythmFeatures": {"en": "Driving 4/4 kicks with continuous rolling percussion and syncopated 16th closed hats.", "zh": "推进式四踩四底鼓，伴随连续不断的滚动打击乐和切分十六分音符闭镲。"},
   "bassPattern": {"en": "Bouncy offbeat analog saw bass galloping rhythmically behind the driving kick.", "zh": "富有弹性跳跃感的反拍模拟锯齿波贝斯，在推进的底鼓后方如骏马奔腾。"},
   "productionTips": {"en": ["Compose melodies using Phrygian Dominant scale", "Layer two 303 synths playing counterpoint arpeggios", "Incorporate ethnic instruments with long stereo delay"], "zh": ["使用弗里吉亚属调式构筑神秘主义色彩异域旋律", "两台 303 合成器演奏对位琶音制造交织光芒", "加入经立体声漫长延时重复处理的传统民族乐器"]}},

  {"id": "tech-trance", "name": "Tech Trance", "aliases": ["科技出神"], "category": "Electronic", "year": "1999", "bpm": "138–144 BPM", "default_bpm": 140, "style": "four_on_floor", "place": {"en": "Germany & UK", "zh": "德国与英国"},
   "artists": ["Marco V", "Sander van Doorn", "Bryan Kearney", "Mark Sherry", "Jordan Suckley"],
   "context": {"en": "Fuses aggressive industrial percussion and dark basslines of techno with soaring trance energy.", "zh": "将 Techno 坚硬冰冷的工业打击乐与 Uplifting Trance 激昂升腾的能量和史诗爆发焊接。"},
   "soundDesign": {"en": "Distorted kicks, metallic percussive clicks, short aggressive saw stabs, stutter FX.", "zh": "过载坚实底鼓、金属质感点击打击乐、短促凶猛锯齿波刺音与门限卡顿效果。"},
   "rhythmFeatures": {"en": "Hard stomping 4/4 techno beat integrated with rapid syncopated percussion fills.", "zh": "硬朗重踏的四四拍 Techno 鼓点，融合极速切分的打击乐加花与利落军鼓。"},
   "bassPattern": {"en": "Relentless rolling sub-bass or offbeat staccato bass with extreme punch.", "zh": "持续不断的滚动超低频或极具压迫感瞬态冲力的反拍断奏低音。"},
   "productionTips": {"en": ["Layer heavy acoustic kick click on top of electronic sub boom", "Use pitch-shifters on vocal chops for dark robotic textures", "Keep breakdown brief to maintain dancefloor pressure"], "zh": ["在电子超低频底鼓上方叠一层高瞬态有机敲击头", "对人声切片做音高下移处理打造暗黑机械质感", "保持转场时间紧凑短促，防止舞池被过长抒情打断"]}},

  {"id": "hard-trance", "name": "Hard Trance", "aliases": ["硬核出神"], "category": "Electronic", "year": "1993", "bpm": "140–152 BPM", "default_bpm": 145, "style": "four_on_floor", "place": {"en": "Frankfurt, Germany", "zh": "德国法兰克福"},
   "artists": ["Cosmic Baby", "Nostrum", "Scot Project", "Yoji Biomehanika", "Jones & Stephenson"],
   "context": {"en": "Takes trance to higher BPMs with hard resonant kicks, distorted basslines, and fast acid riffs.", "zh": "将 Trance 推向更高 BPM 极限，具备硬朗结实的重击底鼓与飞旋酸性 Riff。"},
   "soundDesign": {"en": "Heavily compressed 909 kicks, screaming resonant acid leads, aggressive hoover synths.", "zh": "高强度压缩 909 底鼓、尖啸共鸣酸性主音与侵略性 Hoover 合成音效。"},
   "rhythmFeatures": {"en": "High-tempo 145 BPM driving 4/4 kick with pounding offbeat reverse-bass energy.", "zh": "145 BPM 高速飞驰的四踩四底鼓，伴随充满反冲推力的反拍反转贝斯能量。"},
   "bassPattern": {"en": "Aggressive offbeat reverse-bass punching through the mix on the offbeat.", "zh": "高侵略性的反拍 Reverse-bass 或失真锯齿波低音，在反拍凶狠穿透混音。"},
   "productionTips": {"en": ["Process bass with reverse-decay envelope for whoop effect", "Use hard clipping on drum channel for warehouse power", "Introduce anthemic synth stabs with wide stereo"], "zh": ["反向衰减包络处理贝斯创造经典吸入后抛感", "鼓组通道应用硬剪切失真还原老派仓库暴烈感", "宏大宽立体声和弦刺音覆盖在单声道鼓机之上"]}},

  {"id": "vocal-trance", "name": "Vocal Trance", "aliases": ["人声出神"], "category": "Electronic", "year": "1998", "bpm": "135–140 BPM", "default_bpm": 138, "style": "four_on_floor", "place": {"en": "Netherlands & UK", "zh": "荷兰与英国"},
   "artists": ["OceanLab", "ATB", "Dash Berlin", "Emma Hewitt", "Gareth Emery"],
   "context": {"en": "Emotive female vocal top-lines paired with verse-chorus song structures in majestic trance productions.", "zh": "以深情凄美的主旋律人声咏唱为核心，依托经典主歌-副歌结构，由壮丽出神舞曲烘托。"},
   "soundDesign": {"en": "Polished vocal chains with autotune and lush delays, warm pianos, massive supersaws.", "zh": "精心打磨的人声音轨链（含精致修音与辽阔延迟）、温暖原声钢琴与宏大宽立体声 Supersaw。"},
   "rhythmFeatures": {"en": "Crisp 138 BPM 4/4 beats with light shakers, bright open hats, pre-chorus builds.", "zh": "清脆利落的 138 BPM 四踩四节拍，搭配轻盈沙锤、明亮开镲与副歌爆发前戏剧性递增。"},
   "bassPattern": {"en": "Melodic rolling 16th basslines ducking smoothly beneath vocals and kick.", "zh": "悠扬滚动的十六分音符低音线条，在人声歌词与底鼓重击下平滑自如地闪避。"},
   "productionTips": {"en": ["Carve out pocket between 1kHz-3kHz in synths for vocals", "Add stereo ping-pong delay to vocal ad-libs", "Drop heavy drums during verse for intimacy"], "zh": ["在主音合成器 1kHz 到 3kHz 挖空隙确保人声清晰", "为人声吟唱尾音加入附点八分音符立体声乒乓回声", "在人声主歌段落撤掉全部重型打击乐将亲密感拉满"]}},

  {"id": "euro-trance", "name": "Euro-Trance", "aliases": ["欧陆出神"], "category": "Electronic", "year": "1998", "bpm": "138–144 BPM", "default_bpm": 140, "style": "four_on_floor", "place": {"en": "Germany & Belgium", "zh": "德国与比利时"},
   "artists": ["Cascada", "Groove Coverage", "Milk Inc.", "Lasgo", "Special D"],
   "context": {"en": "A commercialized pop-trance hybrid with high-energy lead melodies, dance-pop vocals, and offbeat bass.", "zh": "高度商业化流行出神跨界风格，以高能量快乐跳跃的主旋律、流行舞曲人声与反拍贝斯著称。"},
   "soundDesign": {"en": "Bright supersaw stabs, commercial pop vocal production, bouncy synth leads.", "zh": "明亮轻快 Supersaw 弹拨、流行人声精细制作、极具弹跳感的合成主奏与白噪声冲刷。"},
   "rhythmFeatures": {"en": "Driving 4/4 kicks with high-energy claps on 2 and 4 and bouncy offbeat open hats.", "zh": "充满推进力的四四拍底鼓，2、4 拍搭配高能量拍手与充满弹跳感的反拍开镲。"},
   "bassPattern": {"en": "Bouncy offbeat pluck bassline alternating octaves to propel fast forward motion.", "zh": "带有弹性跳跃感的反拍拨弦贝斯，在高低八度之间快速交替以推动舞步狂欢。"},
   "productionTips": {"en": ["Focus on memorable 4-bar repeating motifs", "Layer sharp bell on top of supersaw lead", "Keep BPM stable at 140 to maximize club energy"], "zh": ["专注于创作朗朗上口的 4 小节精悍重复乐汇", "在 Supersaw 主音上方叠一层清脆电铃弹拨", "将 BPM 牢牢稳定在 140 最大化点燃狂欢派对能量"]}},

  {"id": "dream-trance", "name": "Dream Trance", "aliases": ["梦幻出神"], "category": "Electronic", "year": "1995", "bpm": "130–138 BPM", "default_bpm": 134, "style": "four_on_floor", "place": {"en": "Italy & Switzerland", "zh": "意大利与瑞士"},
   "artists": ["Robert Miles", "DJ Dado", "Zhi-Vago", "Nylon Moon", "Mauro Picotto"],
   "context": {"en": "Pioneered by Robert Miles with Children in 1995, featuring soothing acoustic piano over rolling trance beats.", "zh": "由 Robert Miles 凭《Children》开创，以舒缓清澈的原声钢琴在出神节拍上流淌闻名。"},
   "soundDesign": {"en": "Acoustic grand piano, soft synth pads, gentle string sweeps, warm round drum hits.", "zh": "温暖原声大钢琴、柔和合成器铺底、典雅弦乐扫弦与温润圆滑的电子鼓机击打。"},
   "rhythmFeatures": {"en": "Smooth non-aggressive 4/4 kicks with gentle shakers and muted open hats.", "zh": "平滑不显突兀的四踩四底鼓，搭配轻柔沙锤与暗色开镲营造恬静梦幻体验。"},
   "bassPattern": {"en": "Gentle offbeat or rolling sub-bass following piano chord progressions.", "zh": "轻柔的反拍或滚动超低音，伴随钢琴和弦轻缓前行，温顺而从不抢戏。"},
   "productionTips": {"en": ["Use high-quality grand piano samples with natural dynamics", "Add lush hall reverbs with 4-5s decay to piano", "Soften kick punch by rolling off high-end at 4kHz"], "zh": ["使用高品质大钢琴采样保留逼真人手动态", "为钢琴主旋律挂载衰减 4-5 秒的大厅混响", "在 4kHz 处轻柔滚降底鼓高频使其更显温润"]}}
]

save_module("house.ts", "HOUSE_GENRES", house_list)
save_module("techno.ts", "TECHNO_GENRES", techno_list)
save_module("trance.ts", "TRANCE_GENRES", trance_list)
print("Completed Batch 1: House (15), Techno (10), Trance (9) = 34 genres!")
