from gen_p1 import save_module

dubstep_list = [
  {"id": "dubstep", "name": "Dubstep", "aliases": ["回响贝斯", "深邃回响"], "category": "Electronic", "year": "2002", "bpm": "138–142 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "South London, UK", "zh": "英国南伦敦"},
   "artists": ["Skream", "Benga", "Digital Mystikz (Mala & Coki)", "Loefah", "Kode9"],
   "context": {"en": "Emerged from South London around 2002 out of 2-step garage and dub, defined by cavernous space, half-time 140 BPM riddims, and physical sub-bass weight.", "zh": "2002 年前后发源于英国南伦敦，脱胎于 2-Step 与牙买加 Dub，以深邃洞穴混响空间、140 BPM 半速律动与撼动身体的超低频著称。"},
   "soundDesign": {"en": "Chest-rattling sub-bass below 50Hz, cavernous spring reverbs, tape delays, sparse rim clicks.", "zh": "震撼胸腔的 50Hz 以下超低音、深邃弹簧混响、磁带延迟与稀疏边击。"},
   "rhythmFeatures": {"en": "Syncopated half-time beat with kick on beat 1 and heavy snare/clap on beat 3.", "zh": "切分的半速（Half-time）节拍，第 1 拍下底鼓，第 3 拍重击军鼓。"},
   "bassPattern": {"en": "Deep, undulating sine sub-bass and low-passed modulated Reese lines with physical chest pressure.", "zh": "深沉起伏的正弦波超低音与低通滤波 Reese 贝斯线条，带来极强的身体压迫感。"},
   "productionTips": {"en": ["Tune sub sine bass strictly between 40-55Hz", "Use long tape delays with feedback on snare rimshots", "Leave generous empty space between drum hits"], "zh": ["超低正弦波严格对齐在 40-55Hz 之间", "在军鼓边击上使用高反馈长磁带延迟", "在鼓点之间保留大量令人窒息的呼吸空白"]}},

  {"id": "brostep", "name": "Brostep", "aliases": ["咆哮贝斯", "狂暴回响"], "category": "Electronic", "year": "2009", "bpm": "140–150 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "USA & UK", "zh": "美国与英国"},
   "artists": ["Skrillex", "Excision", "Datsik", "Zomboy", "Knife Party"],
   "context": {"en": "Popularized by Skrillex in 2010, shifting focus from low-end sub bass to aggressive mid-range FM screech growls and robotic talk-box talkers.", "zh": "2010 年由 Skrillex 等人引爆全球，将视觉焦点从地底 Sub 转移至狂暴的中频 FM 嘶吼咆哮音色与机器人谈话盒滤波。"},
   "soundDesign": {"en": "Aggressive wavetable growls, vocal formants (Yoii/Auu), heavy OTT compression, and punchy snares.", "zh": "狂暴波表咆哮低音、人声元音共振峰（Yoii/Auu）、多重 OTT 压缩与厚重军鼓。"},
   "rhythmFeatures": {"en": "Half-time 140 BPM with thunderous snare on beat 3 and machine-gun syncopated growl fills.", "zh": "140 BPM 半速节拍，第 3 拍雷霆军鼓，伴随机关枪般切分的凶狠咆哮加花。"},
   "bassPattern": {"en": "Interlocking puzzle of 5-8 different screech and growl basses exchanging every beat.", "zh": "由 5 至 8 种不同质感的尖叫与嘶吼贝斯切片拼图般严丝合缝交替拼装。"},
   "productionTips": {"en": ["Bounce audio clips and chop tiny 1/16 growl snippets", "Apply OTT compression at 50-80% depth on bass bus", "Layer acoustic snare with synthesized white noise burst"], "zh": ["导出音频块并切碎为十六分音符短切片重新拼接", "在贝斯总线上挂载深度 50-80% 的 OTT 压缩", "将真军鼓敲击与合成白噪声爆炸紧密叠层"]}},

  {"id": "riddim", "name": "Riddim", "aliases": ["锐汀贝斯", "极简回响"], "category": "Electronic", "year": "2012", "bpm": "140–145 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["Subtronics", "Virtual Riot", "Infekt", "Aweminus", "Boogie T"],
   "context": {"en": "A minimalist, repetitious strain of dubstep focused on syncopated square-wave and FM laser stabs over a relentless triplet swing bounce.", "zh": "Dubstep 的极简高度重复分支，专注于切分方波与 FM 激光短刺音，并在三连音弹跳律动中循环往复。"},
   "soundDesign": {"en": "Resonant square wave plucks, laser pitch-down zaps, short wooden snares, and flanged sub.", "zh": "高谐振方波拨弦、激光下扫音、短促木质军鼓与微带凸缘的超低音。"},
   "rhythmFeatures": {"en": "Hypnotic 5-beat syncopation and triplet feel with snare consistently on beat 3.", "zh": "极富催眠感的切分三连音摇摆弹性，军鼓坚定地落在第 3 拍。"},
   "bassPattern": {"en": "Sparse, repeating single-bar laser synth stab riff playing with micro-timing variations.", "zh": "极简重复的单小节激光合成贝斯短 Riff，伴随微小时值迟滞变化。"},
   "productionTips": {"en": ["Use flanger on square bass with high feedback and short delay time", "Keep the main bass motif repeating for at least 16 bars with subtle fills", "Make your snare very short and punchy around 200Hz"], "zh": ["在方波贝斯上挂载高反馈短延迟的凸缘效果器", "让核心贝斯乐句重复至少 16 小节仅做微量加花", "将第 3 拍军鼓做得短促干练，基频锁定 200Hz"]}},

  {"id": "melodic-dubstep", "name": "Melodic Dubstep", "aliases": ["旋律回响贝斯"], "category": "Electronic", "year": "2012", "bpm": "140–150 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Seven Lions", "Illenium", "Said The Sky", "Adventure Club", "Au5"],
   "context": {"en": "Pioneered by Seven Lions, combining aggressive dubstep drums with lush, emotive progressive trance supersaws and epic vocal anthems.", "zh": "由 Seven Lions 等人奠定，将狂野的 Dubstep 半速鼓组与辽阔凄美的情感 Trance Supersaw 音墙及宏大史诗歌词结合。"},
   "soundDesign": {"en": "Massive layered supersaws, sweeping vocal chops, acoustic piano, and deep mono sub-bass.", "zh": "宏大多层 Supersaw 音墙、滑音人声切片、清澈原声钢琴与纯净单声道超低音。"},
   "rhythmFeatures": {"en": "Huge halftime punch with reverb-soaked snare on beat 3 and rapid hi-hat rolls.", "zh": "震撼半速重击，第 3 拍是饱满浸润在混响中的大军鼓，配合细密踩镲滚奏。"},
   "bassPattern": {"en": "Heavily sidechained sub bass following chord progression root notes under lush supersaws.", "zh": "在宏大和弦下方紧随根音进行的深度侧链 Sub 贝斯。"},
   "productionTips": {"en": ["Stack 8+ supersaw layers detuned and panned wide across stereo", "Automate pitch-bend on chord drops for emotional slides", "Sidechain the entire drop synth bus violently to the kick and snare"], "zh": ["堆叠 8 层以上去谐立体声 Supersaw 并大幅度声像展宽", "在副歌和弦释放瞬间加入音高滑音营造揪心下潜", "将整个释放段落的合成器总线极度凶猛地侧链给底鼓与军鼓"]}},

  {"id": "future-garage", "name": "Future Garage", "aliases": ["未来车库"], "category": "Electronic", "year": "2008", "bpm": "130–136 BPM", "default_bpm": 134, "style": "breakbeat", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Burial", "Synkro", "Sorrow", "Volor Flex", "Phaeleh"],
   "context": {"en": "Pioneered by Burial, defined by syncopated 2-step swing, melancholic pitched-down vocal chops, vinyl crackle, and rainy night nostalgia.", "zh": "由 Burial 等人开创，以切分 2-Step 摇摆律动、凄美哀伤的降调人声切片、黑胶爆豆底噪与雨夜怀旧情绪著称。"},
   "soundDesign": {"en": "Vinyl crackle, rain soundscapes, pitched and time-stretched vocal fragments, warm Reese bass.", "zh": "黑胶唱片刮擦爆豆声、雨声自然采样、变速变调的人声碎片与温润 Reese 贝斯。"},
   "rhythmFeatures": {"en": "Irregular syncopated 2-step skips, ghost rim clicks, off-grid wooden percussion.", "zh": "不规则切分的 2-Step 跳跃节奏、幽灵边击与脱离量化网格的天然木质打击乐。"},
   "bassPattern": {"en": "Warm, detuned low-pass filtered Reese bass humming smoothly beneath the percussion.", "zh": "温暖、去谐并经过深低通滤波的 Reese 低音，在打击乐下方如海潮般低鸣。"},
   "productionTips": {"en": ["Nudge hi-hats and snares manually off the grid for human swing", "Pitch vocal phrases down 5-7 semitones with formant preservation", "Drench foley clicks in medium dark plate reverbs"], "zh": ["手动将踩镲和军鼓移出量化节拍线营造真实人手摇摆", "将人声旋律向下移调 5-7 个半音并保留共振峰", "将拟音打击乐浸润在中等暗色的板式混响中"]}},

  {"id": "post-dubstep", "name": "Post-Dubstep", "aliases": ["后回响贝斯"], "category": "Electronic", "year": "2009", "bpm": "120–138 BPM", "default_bpm": 130, "style": "half_time", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["James Blake", "Mount Kimbie", "SBTRKT", "Jamie xx", "Joy Orbison"],
   "context": {"en": "A deconstruction of bass music blending minimalist soul, indie songwriting, warm analog synths, and spacious club rhythms.", "zh": "低音音乐的解构主义流派，融合极简灵魂乐、独立创作精神、温暖模拟合成器与留白深沉的俱乐部节奏。"},
   "soundDesign": {"en": "Intimate vocal recordings, warm Moog bass, organic acoustic samples, short gated reverbs.", "zh": "极近距离的亲密人声录音、温暖 Moog 贝斯、有机原声采样与短促门限混响。"},
   "rhythmFeatures": {"en": "Deconstructed half-time or syncopated 4/4 beats with unexpected pauses and negative space.", "zh": "解构的半速或切分四踩四节拍，充满意想不到的停顿与充满张力的留白。"},
   "bassPattern": {"en": "Heavy physical sub-bass notes held long beneath delicate fragile vocal phrases.", "zh": "在脆弱纤细的人声下方长久支撑的极具物理压迫感的超低音音符。"},
   "productionTips": {"en": ["Use extreme dynamic contrast between silent drops and roaring sub hits", "Layer pitched vocal harmonies with analog chorus pedals", "Keep drum sounds completely dry without reverbs"], "zh": ["在寂静停顿与轰鸣超低频之间拉开极端的动态对比", "用模拟合唱单块让人声音轨层叠产生复古和声", "保持鼓组完全干燥不加过量混响以突出近场质感"]}},

  {"id": "tearout-dubstep", "name": "Tearout Dubstep", "aliases": ["撕裂回响贝斯"], "category": "Electronic", "year": "2018", "bpm": "140–150 BPM", "default_bpm": 145, "style": "half_time", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Marauda", "SVDDEN DEATH", "Trampa", "Nimda", "PhaseOne"],
   "context": {"en": "An ultra-aggressive modern evolution of dubstep featuring machine-gun metallic stabs, brutal distortion, and continuous high-intensity walls of sound.", "zh": "Dubstep 现代极限狂暴演进，以机关枪般金属撕裂刺音、残暴过载与持续高能的金属音墙轰炸著称。"},
   "soundDesign": {"en": "Machine-gun comb-filtered metallic basses, extreme clipping distortion, aggressive gun cock FX.", "zh": "机关枪般的梳状滤波金属贝斯、极端削波失真与凶狠枪械上膛音效。"},
   "rhythmFeatures": {"en": "Relentless 1/8 and 1/16 rapid-fire syncopated machine-gun snare attacks at 145 BPM.", "zh": "在 145 BPM 下进行不休止的八分与十六分音符速射切分军鼓攻击。"},
   "bassPattern": {"en": "Continuous tearing metallic screech basses with minimal silence between rhythmic bars.", "zh": "连绵不断撕裂耳膜的金属尖叫贝斯，各小节之间几乎不留任何喘息余地。"},
   "productionTips": {"en": ["Use comb filters modulated by ultra-fast LFOs on wavetable synths", "Drive bass bus into hard clip limiters for maximum perceived loudness", "Layer gunshots on top of snare transients"], "zh": ["在波表合成器上用极速 LFO 调制梳状滤波器产生金属撕裂感", "将贝斯总线推入硬剪切限制器榨取极致响度", "在军鼓瞬态上方叠加真实枪栓与射击采样"]}},

  {"id": "chillstep", "name": "Chillstep", "aliases": ["舒缓回响贝斯"], "category": "Electronic", "year": "2010", "bpm": "135–140 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "Global & UK", "zh": "全球与英国"},
   "artists": ["Blackmill", "Seven Lions", "CMA", "MitiS", "Jacoo"],
   "context": {"en": "Slow, relaxed 140 BPM half-time beats layered with serene ambient pads, acoustic melodies, and soothing sub bass.", "zh": "从容舒缓的 140 BPM 半速节拍，交织着宁静空灵的铺底、原声乐器旋律与温润抚慰人心的超低频。"},
   "soundDesign": {"en": "Soft Rhodes electric piano, acoustic guitar strums, lush ambient reverb washes, smooth sub sine.", "zh": "柔和 Rhodes 电钢琴、木吉他扫弦、如梦似幻的开阔混响与平滑纯正弦低音。"},
   "rhythmFeatures": {"en": "Gentle, non-aggressive half-time drums with soft claps and whispered hi-hats.", "zh": "温和舒缓的半速鼓组，搭配轻柔拍手与微风细雨般的踩镲。"},
   "bassPattern": {"en": "Soothing, warm sine sub-bass flowing harmonically with chord progressions.", "zh": "温暖治愈的正弦超低频线条，随和声和弦水乳交融般缓缓流动。"},
   "productionTips": {"en": ["Keep drum transients soft and rounded with gentle low-pass filtering", "Apply large hall reverbs with 6+ seconds decay to vocal samples", "Use minor pentatonic guitar plucks for peaceful hooks"], "zh": ["对鼓组瞬态做温和低通滤波保持圆润不刺耳", "为人声采样挂载混响时间超过 6 秒的大厅混响", "使用小调五声原声吉他弹拨创作宁静悠远的旋律"]}},

  {"id": "deathstep", "name": "Deathstep", "aliases": ["死亡回响贝斯"], "category": "Electronic", "year": "2011", "bpm": "140–150 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "Global", "zh": "全球"},
   "artists": ["Code: Pandorum", "Captain Panic!", "Mantis", "Sadhu", "D-Jahsta"],
   "context": {"en": "Blends extreme death metal aesthetics, horror movie voice samples, and blast-beat-like intensity with brutal dubstep growls.", "zh": "将极端死亡金属的美学意象、恐怖电影对白采样与残暴 Dubstep 咆哮低音融为一体。"},
   "soundDesign": {"en": "Down-tuned distorted electric guitars, guttural demon growls, industrial slams, and sub explosions.", "zh": "降调重度失真电吉他、低沉恶魔嘶吼采样、工业重击与超低频爆炸。"},
   "rhythmFeatures": {"en": "Pounding half-time drum beat combined with double-bass pedal drum rolls and thrashing snares.", "zh": "重击半速鼓点，融合双踩双底鼓滚奏与碾压式军鼓击打。"},
   "bassPattern": {"en": "Violently modulated wavetable guttural basses matching distorted metal power chords.", "zh": "剧烈调制的波表喉音嘶吼贝斯，与失真金属强力和弦完全同步轰击。"},
   "productionTips": {"en": ["Sample real death metal guitar chugs and layer with FM synthesized growls", "Process vocal growls with ring modulators for monstrous alien textures", "Keep sub below 80Hz in mono and slam through wave-shapers"], "zh": ["采样真实金属闷音吉他并与 FM 合成嘶吼低音紧密叠层", "对人声嘶吼使用环形调制器（Ring Mod）制造异形怪物质感", "严格将 80Hz 以下 Sub 保持单声道并经波形塑形器推向极限"]}}
]

dnb_list = [
  {"id": "jungle", "name": "Jungle", "aliases": ["丛林乐"], "category": "Electronic", "year": "1992", "bpm": "155–165 BPM", "default_bpm": 160, "style": "breakbeat", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Goldie", "LTJ Bukem", "Dillinja", "Roni Size", "Congo Natty"],
   "context": {"en": "Born in early 90s UK rave culture, slicing the Amen break at high tempo with heavy Jamaican sound-system reggae basslines and ragga toasting.", "zh": "90 年代初诞生于英国，在高速下切碎重组 Amen Break 鼓循环，结合牙买加雷鬼超重低频与 Ragga 喊麦。"},
   "soundDesign": {"en": "Chopped Amen breaks, Roland S950 time-stretch artifacts, 808 sub booms, reggae sirens.", "zh": "切碎的 Amen Break、Roland S950 采样器变速拉伸杂音、808 超重轰鸣与雷鬼警报。"},
   "rhythmFeatures": {"en": "Frantic, highly syncopated sliced drum breaks with rapid ghost snare rolls and cymbal crashes.", "zh": "狂乱极度切分的碎拍，交织着极速幽灵军鼓滚奏与碎镲。"},
   "bassPattern": {"en": "Massive 808 sub basslines dropping deep pitch bombs and melodic reggae walking patterns.", "zh": "庞大的 808 Sub 低音，不断投下深沉的音高重磅炸弹与雷鬼行进线条。"},
   "productionTips": {"en": ["Slice the Amen break into individual hits and pitch up 4-6 semitones", "Embrace vintage Akai time-stretching crunch on vocal stabs", "Keep the 808 sub clean without distortion for physical chest resonance"], "zh": ["切碎 Amen break 并向上移调 4-6 个半音获得清脆质感", "保留老式 Akai 采样器时间拉伸时的颗粒粗糙感", "超低 808 保持纯净正弦波不加失真以获得胸腔共振"]}},

  {"id": "liquid-dnb", "name": "Liquid DnB", "aliases": ["流动鼓打贝斯", "流体鼓贝"], "category": "Electronic", "year": "2000", "bpm": "170–175 BPM", "default_bpm": 174, "style": "breakbeat", "place": {"en": "UK", "zh": "英国"},
   "artists": ["High Contrast", "Calibre", "Logistics", "Hybrid Minds", "Fred V & Grafix"],
   "context": {"en": "Championed by Fabio and Hospital Records, bringing soulful vocals, lush Rhodes chords, and smooth rolling bass to high-speed 174 BPM beats.", "zh": "由 Fabio 与 Hospital Records 等引领，将深情灵魂乐人声、温暖 Rhodes 和弦与行云流水的低音融入 174 BPM 疾驰节拍。"},
   "soundDesign": {"en": "Soulful Rhodes electric pianos, lush acoustic strings, warm filtered Reese bass, vocal loops.", "zh": "深情 Rhodes 电钢琴、原声弦乐铺底、温暖滤波 Reese 贝斯与悠扬人声循环。"},
   "rhythmFeatures": {"en": "Clean, rolling 2-step breakbeat pattern with crisp ghost snares and silky ride cymbals.", "zh": "干净流畅的 2-Step 碎拍律动，伴随清脆幽灵军鼓与丝绸般顺滑的 Ride 镲片。"},
   "bassPattern": {"en": "Smooth, rolling melodic Reese bass gliding effortlessly beneath jazz chord changes.", "zh": "平滑悠扬滚动的 Reese 贝斯，在爵士和弦变换下方行云流水般滑行穿梭。"},
   "productionTips": {"en": ["Keep drum breaks high-passed around 150Hz to leave space for the sub", "Use sidechain on Reese bass triggered by the kick and snare", "Layer acoustic upright bass with clean sine wave for organic low end"], "zh": ["鼓循环在 150Hz 处高通切除为 Sub 低音让路", "使用底鼓与军鼓对 Reese 贝斯进行轻柔侧链避让", "将原声贝斯弹拨与纯正弦波叠层兼备质感与冲击力"]}},

  {"id": "neurofunk", "name": "Neurofunk", "aliases": ["神经放克"], "category": "Electronic", "year": "1997", "bpm": "172–176 BPM", "default_bpm": 174, "style": "breakbeat", "place": {"en": "UK & Europe", "zh": "英国与欧洲"},
   "artists": ["Noisia", "Black Sun Empire", "Mefjus", "Ed Rush & Optical", "Phace"],
   "context": {"en": "Pioneered by Ed Rush, Optical, and perfected by Noisia, focusing on dark sci-fi aesthetics, surgical distortion, and modulated morphing Reese basslines.", "zh": "由 Ed Rush、Optical 开创并被 Noisia 磨砺至巅峰，以硬核科幻暗黑美学、手术刀般精密失真与复杂的变形 Reese 贝斯著称。"},
   "soundDesign": {"en": "Modulated multi-band distorted Reese basses, razor-sharp clinical transients, metallic foley.", "zh": "多频段调制失真 Reese 贝斯、锋利如手术刀的冷峻瞬态与金属质感拟音。"},
   "rhythmFeatures": {"en": "Tight, punchy 174 BPM 2-step drum programming with hyper-processed synthetic snares.", "zh": "紧凑有力的 174 BPM 2-Step 鼓点，搭配经过极限深度处理的合成军鼓。"},
   "bassPattern": {"en": "Complex, morphing modulated reese riffs moving across stereo field with notch-filtering.", "zh": "复杂的变形滤波调制 Reese 旋律，在立体声场中结合陷波滤波剧烈扭动。"},
   "productionTips": {"en": ["Split Reese bass into 3 bands: process mid/high with flangers, comb filters, and notch sweeps", "Keep sub strictly mono and compressed with brickwall limiter", "Layer transient clicks on snares for cutting presence at 174 BPM"], "zh": ["将 Reese 贝斯分成三频段：中高频加入凸缘、梳状滤波与扫频", "超低频严格单声道并用砖墙限制器夯实", "在军鼓上叠一层瞬态敲击头确保 174 BPM 强穿透力"]}},

  {"id": "jump-up", "name": "Jump Up", "aliases": ["跳跃鼓贝"], "category": "Electronic", "year": "1996", "bpm": "174–178 BPM", "default_bpm": 175, "style": "breakbeat", "place": {"en": "UK", "zh": "英国"},
   "artists": ["DJ Hazard", "Original Sin", "Hedex", "Macky Gee", "Sub Zero"],
   "context": {"en": "A high-energy, rowdy party strain of DnB centered around playful screeching basslines, simple driving drums, and hype MC delivery.", "zh": "狂野躁动的派对向 DnB 分支，以跳跃怪诞的尖叫低音、直球有力的鼓组与现场 MC 喊麦互动为核心。"},
   "soundDesign": {"en": "High-pitched square/FM screech bass synths, punchy clean kicks, loud laser sweeps.", "zh": "高音调方波与 FM 尖叫贝斯合成器、扎实干净的底鼓与响亮激光扫频。"},
   "rhythmFeatures": {"en": "Straightforward, high-octane 2-step break with heavy emphasis on the main snare drop.", "zh": "直截了当的高能 2-Step 鼓点，极度强调重击军鼓的下落爆发。"},
   "bassPattern": {"en": "Bouncy, repetitive mid-frequency screech hooks playing rhythmic call-and-response.", "zh": "富有弹性跳跃的中频尖叫 Hook，采用洗脑的呼应式（Call-and-response）编排。"},
   "productionTips": {"en": ["Use FM synthesis with simple ratios (1:3 or 1:4) and high pitch modulation", "Keep drums clean and relatively dry to leave room for the screech", "Create memorable 2-bar bass hooks that crowds can chant"], "zh": ["使用简单比例（1:3 或 1:4）的 FM 合成与快速音高调制", "鼓组保持干净干燥，为尖叫低音留出充足声学空间", "打造极易被全场观众跟着哼唱的 2 小节洗脑贝斯 Hook"]}},

  {"id": "techstep", "name": "Techstep", "aliases": ["科技步进"], "category": "Electronic", "year": "1995", "bpm": "165–172 BPM", "default_bpm": 168, "style": "breakbeat", "place": {"en": "UK", "zh": "英国"},
   "artists": ["Ed Rush", "Optical", "Trace", "Bad Company UK", "Fierce"],
   "context": {"en": "Cold, dystopian mid-90s DnB replacing jungle's warm reggae soul with dark industrial techno drums and sci-fi paranoia.", "zh": "90 年代中期的冷峻末世流派，用冰冷工业 Techno 鼓点与科幻恐惧感取代了丛林乐的温暖雷鬼灵魂。"},
   "soundDesign": {"en": "Distorted Roland TR-808 kicks, metal clangs, cold low-passed drone pads, gritty Reese bass.", "zh": "失真的 TR-808 底鼓、金属撞击声、冰冷低通长鸣铺底与粗砺 Reese 贝斯。"},
   "rhythmFeatures": {"en": "Mechanical, quantized 2-step breakbeats stripped of human funk, driving with cold precision.", "zh": "机械化量化的 2-Step 碎拍，剥离了人手放克感，以冷酷的精密感飞速推进。"},
   "bassPattern": {"en": "Dark, groaning Reese basslines filtered down and driven through analog preamps.", "zh": "暗黑呻吟的 Reese 贝斯线条，经过深低通滤波并通过模拟前级放大过载。"},
   "productionTips": {"en": ["Resample bass sounds through analog guitar distortion pedals", "Use cold digital reverbs rather than lush acoustic spaces", "Keep drums tight and stripped-down without extra percussion"], "zh": ["将贝斯声音送入吉他失真单块重新重采样染色", "使用冰冷的数字混响而非温润的原声大厅空间", "保持鼓组紧凑精炼，杜绝多余的花哨打击乐装饰"]}},

  {"id": "halftime", "name": "Halftime DnB", "aliases": ["半速鼓贝"], "category": "Electronic", "year": "2014", "bpm": "85–88 BPM (170)", "default_bpm": 86, "style": "half_time", "place": {"en": "UK & Europe", "zh": "英国与欧洲"},
   "artists": ["Ivy Lab", "Alix Perez", "Current Value", "Shield", "Eprom"],
   "context": {"en": "Fuses 170 BPM drum and bass modular sound design and deep sub weight with hip-hop and trap half-time bounce.", "zh": "将 170 BPM 鼓打贝斯的模块化前沿音色与超重低频，同嘻哈与 Trap 的半速弹跳律动融合。"},
   "soundDesign": {"en": "Deep modular analog subs, crunchy hip-hop snare claps, Foley clicks, stereo glitch textures.", "zh": "深沉模块化模拟超低频、干脆嘻哈军鼓拍手、拟音微撞击与立体声毛刺纹理。"},
   "rhythmFeatures": {"en": "Half-time swing bounce (effectively 85-87 BPM) with heavy emphasis on the downbeat.", "zh": "半速摇摆律动（折合 85-87 BPM），在首拍与反拍之间制造巨大低频反差。"},
   "bassPattern": {"en": "Sub-heavy 808 glides combined with intricate neuro-modulated mid bass stabs.", "zh": "超重 808 音高滑音与精细神经质调制的中频贝斯切片交相辉映。"},
   "productionTips": {"en": ["Program drum bounce with heavy swing between 58% and 62%", "Design mono sub bass with subtle saturation to generate audible harmonics on small speakers", "Use vinyl noise loops for analog texture"], "zh": ["鼓组律动应用 58% 到 62% 的深度摇摆", "为超低音注入微量饱和在小喇叭上清晰可辨", "叠入黑胶底噪循环增添模拟触感"]}},

  {"id": "breakcore", "name": "Breakcore", "aliases": ["碎核乐"], "category": "Electronic", "year": "1995", "bpm": "180–220+ BPM", "default_bpm": 190, "style": "breakbeat", "place": {"en": "Berlin & Bristol", "zh": "柏林与布里斯托"},
   "artists": ["Venetian Snares", "Igorrr", "Bong-Ra", "Otto von Schirach", "Shitmat"],
   "context": {"en": "Extreme underground electronic music taking sliced Amen breaks to chaotic, hyper-speed tempos with noise and classical sampling.", "zh": "极端地下电子流派，将 Amen break 碎拍切片狂飙至极速疯狂境界，融入重度失真与古典采样。"},
   "soundDesign": {"en": "Surgically glitch-edited Amen slices, bitcrushed noise bursts, speed-ramped audio, hardcore kicks.", "zh": "手术刀级精密毛刺切片、降采样噪声突发、急刹车变速音频与硬核底鼓。"},
   "rhythmFeatures": {"en": "Chaotic, ever-shifting time signatures (often 7/8, 5/4) with extreme break manipulation.", "zh": "混沌多变、随时突变的拍号（常含 7/8、5/4），伴随极度狂暴的碎拍翻转。"},
   "bassPattern": {"en": "Heavily distorted gabber kicks alternating with hyper-speed pitch-bent sub hits.", "zh": "重度失真 Gabber 底鼓与极速音高弯音的超低重击快速穿梭。"},
   "productionTips": {"en": ["Slice Amen breaks into 64th-note fragments and rearrange randomly", "Utilize odd time signatures (e.g. 7/4 or 11/8) for unpredictability", "Slam audio tracks through extreme wave-shapers and distortion"], "zh": ["将 Amen break 切碎为六十四分音符微粒并随机重组", "运用奇数非常规拍号（如 7/4、11/8）创造无法预测的张力", "将音轨暴力推入波形塑形器与极限过载中"]}},

  {"id": "ragga-jungle", "name": "Ragga Jungle", "aliases": ["拉格丛林"], "category": "Electronic", "year": "1993", "bpm": "160–168 BPM", "default_bpm": 164, "style": "breakbeat", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Congo Natty", "Shy FX", "Remarc", "General Levy", "Rebel MC"],
   "context": {"en": "Pioneered in London, marrying fast chopped Amen breaks with prominent Jamaican sound system culture, dancehall vocals, and dub sirens.", "zh": "在伦敦发端，将高速切割的 Amen 碎拍与深厚的牙买加音响系统文化、Dancehall 人声喊麦及警报紧密熔铸。"},
   "soundDesign": {"en": "Dancehall vocal toasting, dub sirens, spring reverb splashes, 808 sub bass, chopped snare rolls.", "zh": "Dancehall 人声喊麦、Dub 警报声、弹簧混响泼溅水声、808 低音与切碎军鼓。"},
   "rhythmFeatures": {"en": "Fast syncopated breakbeats interspersed with rapid snare rolls and sudden drops to half-time.", "zh": "快速切分碎拍，穿插着极速军鼓滚奏与突如其来的半速悬崖跌落。"},
   "bassPattern": {"en": "Heavy, booming 808 sub basslines following classic dub and reggae roots melodies.", "zh": "厚重轰鸣的 808 超低音线条，遵循经典牙买加根源雷鬼和声走向。"},
   "productionTips": {"en": ["Sample authentic Jamaican sound-clash acapellas and pitch up", "Use spring reverb plugin on snare rimshots with high decay", "Cut all bass frequencies from vocal samples to leave room for 808"], "zh": ["采样原汁原味的牙买加现场喊麦人声并向上移调", "在军鼓边击上挂载长衰减弹簧混响", "彻底切除人声采样中的低频成分为 808 超低频留出空间"]}},

  {"id": "sambass", "name": "Sambass", "aliases": ["桑巴鼓贝"], "category": "Electronic", "year": "2001", "bpm": "170–175 BPM", "default_bpm": 172, "style": "breakbeat", "place": {"en": "Brazil", "zh": "巴西"},
   "artists": ["DJ Marky", "DJ Patife", "XRS", "Bebel Gilberto", "Fernanda Porto"],
   "context": {"en": "Originated in Brazil, fusing high-speed drum and bass breakbeats with traditional Brazilian samba, bossa nova guitars, and batucada percussion.", "zh": "发源于巴西，将高速 170 BPM 鼓打贝斯碎拍与传统巴西桑巴、Bossa Nova 尼龙吉他及狂欢节打击乐结合。"},
   "soundDesign": {"en": "Acoustic nylon guitars, live cuíca friction drums, pandeiro, warm rolling upright bass.", "zh": "尼龙弦原声吉他、巴西库伊卡摩擦鼓（Cuíca）、手鼓与温暖行进立式原声低音。"},
   "rhythmFeatures": {"en": "Fast 172 BPM 2-step break layered with syncopated polyrhythmic live Brazilian batucada shakers.", "zh": "高速 172 BPM 2-Step 碎拍叠置上切分复合节奏的巴西狂欢节真实沙锤打击乐。"},
   "bassPattern": {"en": "Bouncy, syncopated acoustic or electric basslines playing traditional samba walking patterns.", "zh": "充满弹跳感的切分原声或电贝斯线条，演奏传统桑巴行进低音模式。"},
   "productionTips": {"en": ["Record or sample live acoustic nylon-string guitar playing bossa chords", "Layer real pandeiro and shaker loops over synthetic DnB kicks", "Keep the groove upbeat with major 7th and minor 9th Brazilian harmonies"], "zh": ["录制或采样真实尼龙弦木吉他演奏的 Bossa Nova 和弦", "在电子 DnB 底鼓上方叠录真实巴西手鼓与沙锤", "采用大七与小九度巴西和声体系保持欢愉明朗色彩"]}}
]

ukbass_list = [
  {"id": "uk-garage", "name": "UK Garage", "aliases": ["车库舞曲", "UKG"], "category": "Electronic", "year": "1994", "bpm": "128–134 BPM", "default_bpm": 130, "style": "four_on_floor", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["MJ Cole", "Todd Edwards", "Grant Nelson", "Tuff Jam", "Sunship"],
   "context": {"en": "Evolved from New York garage house in London clubs, speeding up the beat, adding heavy syncopated shuffle, vocal chops, and bouncy organ basslines.", "zh": "在伦敦俱乐部脱胎于纽约车库浩室，加快速度并注入重度切分摇摆、短促人声切片与弹跳风琴低音。"},
   "soundDesign": {"en": "Time-stretched vocal micro-samples, Korg M1 organ bass stabs, crisp high hats, warm vinyl dust.", "zh": "时间拉伸的人声微粒切片、Korg M1 风琴低音刺音、清脆踩镲与温暖黑胶底噪。"},
   "rhythmFeatures": {"en": "Shuffled 4/4 or 2-step rhythm with heavy 16th-note swing between 56% and 62%.", "zh": "深度摇摆的 4/4 拍或 2-Step 节奏，十六分音符摇摆度高达 56% 到 62%。"},
   "bassPattern": {"en": "Bouncy, syncopated organ or sine basslines playing energetic question-and-answer hooks.", "zh": "充满弹性的切分风琴或正弦波贝斯，演奏充满活力的呼应式旋律 Hook。"},
   "productionTips": {"en": ["Pitch vocal syllables up 3 semitones and chop into 16th notes", "Use 16th-note triplet swing on hi-hats for classic London bounce", "Layer an organ stab with a sub sine to hit hard on dancefloors"], "zh": ["将人声音节升高 3 个半音并切成十六分音符短促片段", "在踩镲上应用十六分音符三连音摇摆获取正宗伦敦弹性律动", "把风琴音色与纯低音正弦波叠合确保舞池打击力"]}},

  {"id": "2-step-garage", "name": "2-Step Garage", "aliases": ["两步车库"], "category": "Electronic", "year": "1997", "bpm": "130–136 BPM", "default_bpm": 132, "style": "breakbeat", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Artful Dodger", "Craig David", "Sticky", "Wookie", "Zed Bias"],
   "context": {"en": "Stripped the steady 4/4 kick of house, creating an irregular syncopated skip with kick on beat 1 and 2-and, sparking a massive UK pop and underground movement.", "zh": "抽去 House 坚硬稳固的四踩四底鼓，代之以极富切分跳跃感的两步跳跃节奏，引爆了英国流行乐与地下低音革命。"},
   "soundDesign": {"en": "Smooth R&B vocal acapellas, Rhodes chords, snappy rimshots, bouncy sub-bass.", "zh": "丝滑 R&B 人声干声、Rhodes 和弦、脆响边击与弹跳超低频。"},
   "rhythmFeatures": {"en": "The iconic 2-step skip: kick on 1, ghost snare, snare on 2 and 4 with kick skipping on offbeats.", "zh": "标志性 2-Step 跳步：第 1 拍底鼓，反拍底鼓跳跃，第 2、4 拍利落军鼓与幽灵音。"},
   "bassPattern": {"en": "Deep, rolling, syncopated basslines skipping around the vocal delivery with playful bounce.", "zh": "深沉、滚动且高度切分的贝斯线条，配合人声起伏跳跃。"},
   "productionTips": {"en": ["Mute kick on beat 2 and 4 to let the snare and bassline bounce", "Add swing around 60% on all percussive layers", "Sidechain sub bass to ghost percussions for pump"], "zh": ["静音 2、4 拍的底鼓，留给军鼓与贝斯充沛的弹跳空间", "在所有打击乐轨道注入 60% 左右的深度摇摆", "使超低频针对幽灵打击乐做微妙侧链闪避增添动感"]}},

  {"id": "speed-garage", "name": "Speed Garage", "aliases": ["极速车库"], "category": "Electronic", "year": "1996", "bpm": "128–135 BPM", "default_bpm": 132, "style": "four_on_floor", "place": {"en": "UK", "zh": "英国"},
   "artists": ["Double 99", "187 Lockdown", "Armand Van Helden", "Rip Productions", "Serious Danger"],
   "context": {"en": "High-octane evolution of garage with 4/4 driving beats, warped time-stretched vocal screams, and thunderous sub-bass drops.", "zh": "高能车库演变流派，具备四踩四强劲底鼓、扭曲拉伸的人声尖叫与惊雷般的超低频重击。"},
   "soundDesign": {"en": "Warped time-stretch artifacts, heavy sirens, pitched-down jungle breaks, roaring sub drops.", "zh": "变速拉伸扭曲声、强力警报、降调丛林碎拍与咆哮超低频下沉。"},
   "rhythmFeatures": {"en": "Fast 4/4 driving kick with syncopated 16th hats and explosive pre-drop snare fills.", "zh": "高速 4/4 推进底鼓，伴随切分十六分音符踩镲与转场前爆炸般的军鼓加花。"},
   "bassPattern": {"en": "Heavy, distorted offbeat bassline or resonant pitch-diving low-end bomb.", "zh": "厚重失真的反拍贝斯或带有共鸣音高下落的低频重击炸弹。"},
   "productionTips": {"en": ["Use extreme time-stretching on vocal loops to create grainy high-end textures", "Drop all drums before the bassline punches on the upbeat of beat 1", "Layer 909 kick with a sub-bass sine drop"], "zh": ["对人声循环进行极端时间拉伸制造粗颗粒高频纹理", "在贝斯于第 1 拍后半拍重击前瞬间切除所有鼓点", "将 909 底鼓与超低正弦波下沉音叠层"]}},

  {"id": "grime", "name": "Grime", "aliases": ["污垢乐"], "category": "Electronic", "year": "2002", "bpm": "140 BPM", "default_bpm": 140, "style": "half_time", "place": {"en": "East London, UK", "zh": "英国东伦敦"},
   "artists": ["Dizzee Rascal", "Wiley", "Skepta", "Jme", "Kano"],
   "context": {"en": "Forged on East London pirate radio, marrying 140 BPM square-wave video-game synth plucks with rapid-fire, aggressive UK street lyricism.", "zh": "熔铸于东伦敦黑广播电台，将 140 BPM 方波电子游戏芯片音色与狂风暴雨般的硬核伦敦街头说唱结合。"},
   "soundDesign": {"en": "PlayStation/Korg Triton square wave bass, laser zaps, 8-bit chip blips, cold orchestral stabs.", "zh": "复古主机/Korg Triton 方波贝斯、激光射线音、8位芯片点音与冰冷管弦乐刺音。"},
   "rhythmFeatures": {"en": "Staccato, jagged 140 BPM half-time rhythm with sparse, mechanical clap/snare hits.", "zh": "短促锯齿状的 140 BPM 半速节拍，伴随稀疏机械的拍手/军鼓敲击。"},
   "bassPattern": {"en": "Aggressive, buzzing square-wave sub bass playing raw, single-finger melodies.", "zh": "粗砺蜂鸣的方波超低频贝斯，演奏纯粹生猛的单指旋律。"},
   "productionTips": {"en": ["Use cheap GM MIDI sound sets or vintage gaming synths for authentic raw grit", "Keep drum sounds extremely dry without any room reverb", "Write melodies with harsh minor second dissonances"], "zh": ["使用廉价复古游戏芯片或通用 MIDI 音色获取原汁原味的粗糙质感", "保持鼓组完全干冷绝不加任何房间混响", "在旋律中大胆使用尖锐的小二度不协和音程增添攻击性"]}},

  {"id": "bassline", "name": "Bassline", "aliases": ["低音线", "Bassline House"], "category": "Electronic", "year": "2002", "bpm": "135–142 BPM", "default_bpm": 138, "style": "four_on_floor", "place": {"en": "Sheffield & Leeds, UK", "zh": "英国谢菲尔德与利兹"},
   "artists": ["T2", "DJ Q", "Flava D", "TS7", "Burgaboy"],
   "context": {"en": "Born in Northern UK clubs like Niche in Sheffield, featuring 4/4 four-on-the-floor kicks, catchy female vocal pop hooks, and aggressive bouncy warped basslines.", "zh": "诞生于英国北部俱乐部（如谢菲尔德 Niche），具备 4/4 四踩四底鼓、洗脑女性流行人声与弹跳扭动的强劲贝斯。"},
   "soundDesign": {"en": "Pitched-up catchy vocal hooks, screaming FM donk bass, bouncy Reese plucks, clean claps.", "zh": "升调洗脑人声 Hook、尖叫 FM 碰碰低音（Donk）、弹跳 Reese 弹拨与清脆拍手。"},
   "rhythmFeatures": {"en": "Energetic 4-on-the-floor kick with sharp offbeat hi-hats and syncopated clap fills.", "zh": "高能四踩四底鼓，搭配锐利反拍踩镲与切分拍手加花。"},
   "bassPattern": {"en": "Intensely bouncy, syncopated basslines skipping rapidly across 2 octaves.", "zh": "极富弹跳力与摇摆感的切分低音线条，在两个八度内快速跳跃穿梭。"},
   "productionTips": {"en": ["Create bouncy 'donk' sounds using FM synthesis with pitch envelopes", "Keep the kick punchy and tuned around 55Hz", "Layer sweet commercial pop vocals with high compression over violent basslines"], "zh": ["使用带有快速音高包络的 FM 合成制作标志性弹跳 Donk 音色", "底鼓保持扎实有力，精准定调在 55Hz", "将甜美商业流行人声经过高压缩后与狂暴弹跳贝斯反差碰撞"]}},

  {"id": "uk-funky", "name": "UK Funky", "aliases": ["英伦放克"], "category": "Electronic", "year": "2006", "bpm": "128–132 BPM", "default_bpm": 130, "style": "four_on_floor", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Crazy Cousinz", "Donae'o", "Lil Silva", "Roska", "Kyla"],
   "context": {"en": "Fuses UK garage with African polyrhythms, soca, and tribal house, creating infectious syncopated dance rhythms.", "zh": "将英国车库音乐与非洲复合节奏、加勒比索卡（Soca）及部落浩室交融，创造出极具感染力的切分舞曲律动。"},
   "soundDesign": {"en": "Resonant bongos, congas, bright piano stabs, smooth female vocals, deep sub-bass.", "zh": "共振邦戈鼓、康加鼓、明亮钢琴刺音、顺滑女性人声与深沉超低频。"},
   "rhythmFeatures": {"en": "Tribal, syncopated 4/4 rhythm with swinging congas, rimshots, and rolling triplets.", "zh": "部落切分四四拍律动，伴随摇摆的康加鼓、边击与滚动的连音。"},
   "bassPattern": {"en": "Warm, rolling sub-bass that snakes dynamically around the tribal percussion hits.", "zh": "温暖滚动的超低音，在部落打击乐的鼓点缝隙中自如游弋。"},
   "productionTips": {"en": ["Layer organic Latin/African percussion loops over standard 4/4 electronic kicks", "Use syncopated piano chord stabs on the upbeats", "Keep basslines warm with low-pass filtered triangle waves"], "zh": ["在标准 4/4 电子底鼓上方叠置原声拉丁与非洲打击乐循环", "在反拍使用切分的明亮钢琴和弦切片", "使用低通滤波三角波保持贝斯线条的圆润与温暖"]}},

  {"id": "dub", "name": "Dub", "aliases": ["配音音乐", "回响音乐"], "category": "Electronic", "year": "1968", "bpm": "65–85 BPM (130-170)", "default_bpm": 75, "style": "half_time", "place": {"en": "Kingston, Jamaica", "zh": "牙买加金斯敦"},
   "artists": ["King Tubby", "Lee 'Scratch' Perry", "Scientist", "Augustus Pablo", "Mad Professor"],
   "context": {"en": "Originated in late-60s Jamaica by studio geniuses who treated the mixing desk as an instrument, pioneering tape delays, reverb drops, and massive sub-bass.", "zh": "60 年代末诞生于牙买加，先锋录音师将调音台作为乐器，开创了磁带延迟、混响跌落与超重低频的现代制作基石。"},
   "soundDesign": {"en": "Tape echo delay oscillations, spring reverb tank crashes, melodica, deep electric bass.", "zh": "磁带回声自激震荡、弹簧混响敲击声、口风琴与深沉原声电贝斯。"},
   "rhythmFeatures": {"en": "One-drop drum pattern with kick hitting on beat 3, rimshots with infinite echo repeats.", "zh": "One-drop 鼓点模式（底鼓仅落在第 3 拍），边击带有无尽回响延迟。"},
   "bassPattern": {"en": "Heavy, melodic, foundational electric basslines dominating the frequency spectrum.", "zh": "厚重、极富歌唱性且作为灵魂地基的电贝斯线条，统治整个低音频段。"},
   "productionTips": {"en": ["Feed delays back into themselves until they border on harmonic self-oscillation", "Kick your spring reverb unit (or emulate it) for classic metallic dub splash", "Mute rhythm guitar and let bass and drums carry the entire weight"], "zh": ["让延迟效果器产生反馈环回直至临近自激震荡", "制造弹簧混响的敲击金属泼溅水花音效", "突然静音节奏吉他，仅留贝斯与鼓组承载全部重力"]}},

  {"id": "speedbass", "name": "Speedbass", "aliases": ["极速低音"], "category": "Electronic", "year": "2018", "bpm": "155–165 BPM", "default_bpm": 160, "style": "breakbeat", "place": {"en": "UK & Global", "zh": "英国与全球"},
   "artists": ["Zero", "Corrupt UK", "Sammy Virji", "Holy Goof", "Darkzy"],
   "context": {"en": "A modern hyper-speed hybrid fusing the 160 BPM velocity of DnB and Footwork with the bouncy bassline wobbles and vocal hooks of UK Bassline.", "zh": "现代高能跨界流派，将 160 BPM 的高速冲击力同 UK Bassline 的弹跳低音与人声 Hook 熔合。"},
   "soundDesign": {"en": "High-velocity FM bass wobbles, metallic donk plucks, speed-pitched vocal shouts.", "zh": "高速飞驰的 FM 摇摆低音、金属质感 Donk 弹拨与变速人声喊麦。"},
   "rhythmFeatures": {"en": "Breakneck 4/4 or syncopated 160 BPM hybrid beat driving furious club energy.", "zh": "在 160 BPM 极速下的四四拍与切分混血节拍，点燃狂暴俱乐部能量。"},
   "bassPattern": {"en": "Hyperactive syncopated FM growl and pluck basslines switching tones every 2 beats.", "zh": "极度活跃的切分 FM 咆哮与弹拨贝斯，每两拍便切换一次音色质感。"},
   "productionTips": {"en": ["Design short, punchy bass plucks with instant envelope releases to avoid blur at 160 BPM", "Keep the kick punchy and under 40ms decay", "Use high-pass sidechain on master compressor to preserve punch"], "zh": ["为贝斯设计瞬时释放的短促弹拨，避免在 160 BPM 下糊成一片", "底鼓衰减保持在 40ms 以内确保拳拳到肉", "母带压缩器开启高通侧链保留低频冲击力"]}}
]

save_module("dubstep.ts", "DUBSTEP_GENRES", dubstep_list)
save_module("dnb.ts", "DNB_GENRES", dnb_list)
save_module("uk_bass.ts", "UK_BASS_GENRES", ukbass_list)
print("Completed Batch 2: Dubstep (9), DnB (9), UK Bass (8) = 26 genres!")
