from gen_p1 import save_module

trap_drill_list = [
  {"id": "edm-trap", "name": "EDM Trap", "aliases": ["舞曲陷阱"], "category": "Electronic", "year": "2012", "bpm": "140–150 BPM", "default_bpm": 145, "style": "half_time", "place": {"en": "USA", "zh": "美国"},
   "artists": ["RL Grime", "Baauer", "Flosstradamus", "Yellow Claw", "Boombox Cartel"],
   "context": {"en": "Exploded onto the festival scene around 2012, blending Southern hip-hop 808 booms and rapid hi-hat rolls with big room Dutch house build-ups and brass leads.", "zh": "2012 年前后引爆大型音乐节，将美国南方嘻哈轰鸣 808 与极速三连音踩镲同欧洲高能铜管主音融合。"},
   "soundDesign": {"en": "Massive pitch-bent 808 sub kicks, synthesized brass horns, vocal chants, rave lasers.", "zh": "大范围音高滑音 808 超重底鼓、合成号角铜管刺音、人声口号喊麦与激光枪音效。"},
   "rhythmFeatures": {"en": "Half-time 145 BPM bounce with rolling 1/16 and 1/32 triplet hi-hats, hard claps on 3.", "zh": "145 BPM 半速弹跳律动，穿插密集飞驰的三连音踩镲滚奏，第 3 拍重击拍手。"},
   "bassPattern": {"en": "Long gliding 808 sub bass notes sliding across octaves beneath brass stabs.", "zh": "在铜管刺音下方跨八度自由大幅度滑音延音的 808 巨幅超低音。"},
   "productionTips": {"en": ["Tune your 808 sample to match the track key perfectly", "Use envelope pitch-glides (Portamento) on 808 notes for octave leaps", "Layer crisp claps with bright white-noise bursts"], "zh": ["精准校准 808 采样调性与工程和声完全一致", "为 808 开启滑音（Portamento）实现顺滑八度飞掠", "将清脆拍手与明亮白噪声瞬态叠加"]}},

  {"id": "hard-trap", "name": "Hard Trap", "aliases": ["硬核陷阱"], "category": "Electronic", "year": "2016", "bpm": "145–155 BPM", "default_bpm": 150, "style": "half_time", "place": {"en": "USA & Europe", "zh": "美国与欧洲"},
   "artists": ["SayMyName", "Sikdope", "Carnage", "Junkie Kid", "Lit Lords"],
   "context": {"en": "Pioneered by SayMyName, fusing distorted hardstyle reverse kicks and harsh screeches with half-time trap rhythms.", "zh": "由 SayMyName 等人开创，将 Hardstyle 失真反转底鼓、狂暴尖叫与半速 Trap 律动融合。"},
   "soundDesign": {"en": "Distorted 808s, hardstyle screeches, aggressive industrial sirens, compressed vocal screams.", "zh": "重度失真 808、Hardstyle 金属尖啸音、工业警报与极限压缩人声嘶吼。"},
   "rhythmFeatures": {"en": "Aggressive half-time bounce with crushing snares and rapid-fire metallic percussion.", "zh": "极具攻击性的半速弹跳，伴随具有粉碎感的军鼓与金属质感速射打击乐。"},
   "bassPattern": {"en": "Hard-clipped, overdriven 808s with extreme harmonic saturation punching the master bus.", "zh": "硬剪切过载 808，带有极端高次谐波饱和，猛烈撞击母带总线。"},
   "productionTips": {"en": ["Drive 808s into hard clipping limiters for aggressive square-wave buzz", "Layer screech synths with comb filters", "Keep breakdown brief and high in tension"], "zh": ["将 808 推入硬剪切限制器获得侵略性方波质感", "利用梳状滤波强化尖叫合成器的金属撕裂感", "转场保持紧凑高压，迅速汇聚能量"]}},

  {"id": "hybrid-trap", "name": "Hybrid Trap", "aliases": ["混种陷阱"], "category": "Electronic", "year": "2014", "bpm": "140–150 BPM", "default_bpm": 145, "style": "half_time", "place": {"en": "USA", "zh": "美国"},
   "artists": ["NGHTMRE", "Herobust", "Boombox Cartel", "Slander", "Lookas"],
   "context": {"en": "Combines the half-time bounce and sliding 808s of trap with modulated dubstep FM growls and sound design.", "zh": "将 Trap 的半速弹跳、滑音 808 与 Dubstep 复杂的 FM 调制嘶吼咆哮低音深度熔接。"},
   "soundDesign": {"en": "Modulated FM growls, metallic tearout screeches, brass synth horns, punchy transient kicks.", "zh": "受 LFO 调制的 FM 咆哮、金属撕裂尖叫、铜管合成器与超高瞬态底鼓。"},
   "rhythmFeatures": {"en": "Syncopated half-time bounce with intricate percussion fills and snare drops on beat 3.", "zh": "切分半速律动，搭配精巧绝伦的打击乐加花，第 3 拍落重击军鼓。"},
   "bassPattern": {"en": "Rapid-fire alternation between sliding 808 sub kicks and aggressive mid-growl bass fills.", "zh": "在滑音 808 超低频与狂暴中频咆哮音色之间进行高频次的无缝切替。"},
   "productionTips": {"en": ["Chop growl basses into 1/16 snippets and alternate between 4 different patches", "Use pitch bends on 808s at the end of bars for bouncy movement", "Saturate the mid-band of the bass to cut through mobile speakers"], "zh": ["将咆哮贝斯切碎为十六分音符短片并在 4 种预设间交替", "在小节末尾为 808 加入上滑滑音制造回弹动力", "饱和增强贝斯中频以确保手机扬声器清晰听感"]}},

  {"id": "wave", "name": "Wave", "aliases": ["浪潮音乐"], "category": "Electronic", "year": "2015", "bpm": "120–140 BPM", "default_bpm": 130, "style": "half_time", "place": {"en": "London & Global", "zh": "伦敦与全球"},
   "artists": ["Kareful", "Sorsari", "Skeler", "Barnacle Boi", "Deadcrow"],
   "context": {"en": "An emotional, atmospheric underground electronic genre blending cinematic trap beats, detuned Reese bass, and cyberpunk nostalgia.", "zh": "充满深沉情感与电影氛围的地下流派，融合电影质感 Trap 节拍、去谐 Reese 低音与赛博朋克怀旧美学。"},
   "soundDesign": {"en": "Detuned Reese bass, lush sidechained supersaw arpeggios, rain ambiences, re-pitched vocal chops.", "zh": "去谐 Reese 贝斯、深度侧链的 Supersaw 琶音、淅沥雨声环境音与变调人声切片。"},
   "rhythmFeatures": {"en": "Slow, spacious trap half-time beats with rolling hi-hats and gentle rim clicks.", "zh": "开阔深邃的 Trap 半速节拍，伴随轻盈细腻的踩镲滚奏与温和边击。"},
   "bassPattern": {"en": "Massive, warm Reese bass that slides smoothly across notes, creating an ocean of low end.", "zh": "庞大温暖的 Reese 贝斯线条，在不同音符间顺滑滑动，构筑低频汪洋。"},
   "productionTips": {"en": ["Use generous stereo detune on Reese bass while keeping frequencies below 100Hz in mono", "Drench supersaws in cavernous reverbs", "Incorporate cyberpunk neon soundscapes in the background"], "zh": ["对 Reese 贝斯施加宽立体声去谐，同时严格保持 100Hz 以下单声道", "将 Supersaw 浸润在深邃如深空的辽阔混响中", "在背景层轻微混入赛博朋克霓虹雨夜环境纹理"]}},

  {"id": "chicago-drill", "name": "Chicago Drill", "aliases": ["芝加哥钻头"], "category": "Electronic", "year": "2011", "bpm": "130–145 BPM", "default_bpm": 138, "style": "half_time", "place": {"en": "Chicago, Illinois, USA", "zh": "美国芝加哥"},
   "artists": ["Chief Keef", "King Von", "Lil Durk", "Young Chop", "G Herbo"],
   "context": {"en": "Born on Chicago's South Side, reflecting grim street reality through dark trap beats, menacing minor bells, and thunderous 808 kicks.", "zh": "发端于芝加哥南区街头，以阴暗冷酷的小调钟琴琶音、肃杀氛围与轰鸣 808 底鼓折射残酷现实。"},
   "soundDesign": {"en": "Dark minor-key bells, menacing brass stabs, Roland TR-808 sub booms, clean rim snares.", "zh": "暗黑小调钟琴、肃杀铜管刺音、Roland TR-808 轰鸣与清脆边击军鼓。"},
   "rhythmFeatures": {"en": "Half-time trap groove with rapid hi-hat rolls and snare hitting firmly on beat 3.", "zh": "半速 Trap 律动，伴随极速十六分与三连音踩镲滚奏，军鼓重重落在第 3 拍。"},
   "bassPattern": {"en": "Booming, punchy 808 sub kicks anchoring the downbeat with minimal melodic glides.", "zh": "质朴强悍的 808 超重底鼓锁定重拍，较少使用复杂的滑音，突出骨架力量。"},
   "productionTips": {"en": ["Write simple 2-bar repeating melodies using minor second intervals", "Keep the 808 kick punchy with clean sub fundamental around 45Hz", "Use acoustic clap layered with bright snare"], "zh": ["使用小二度音程创作极度阴暗冰冷的 2 小节重复旋律", "保持 808 底鼓基频在 45Hz 附近坚如磐石", "将原声拍手与明亮军鼓紧密叠层增强打击感"]}},

  {"id": "uk-drill", "name": "UK Drill", "aliases": ["英国钻头"], "category": "Electronic", "year": "2015", "bpm": "140–145 BPM", "default_bpm": 142, "style": "half_time", "place": {"en": "London, UK", "zh": "英国伦敦"},
   "artists": ["Russ Millions", "Headie One", "Digga D", "Unknown T", "Loski"],
   "context": {"en": "Evolved from Chicago drill in Brixton, London, revolutionizing modern rap with sliding 808 pitch glides and syncopated snare skips.", "zh": "由伦敦布里克斯顿青年将芝加哥钻头本土化，以标志性的长程 808 音高大幅度滑音与切分跳跃军鼓震撼全球。"},
   "soundDesign": {"en": "Extreme gliding 808 subs, melancholic minor piano, reversing hi-hats, vocal ad-lib cries.", "zh": "大幅度滑音 808 超低音、忧郁小调真钢琴、反向抽吸踩镲与空灵人声呼喊。"},
   "rhythmFeatures": {"en": "The iconic drill skip: snare on beat 3 and beat 8 (syncopated offbeat skip) with triplet hats.", "zh": "标志性 Drill 切分律动：军鼓落在第 3 拍与第 8 拍（反拍切分跳跃），配合三连音踩镲。"},
   "bassPattern": {"en": "High-register 808 slides jumping up an octave or 7 semitones with rapid pitch envelopes.", "zh": "跨越八度或 7 个半音的高音区 808 剧烈滑音，带有极快的音高弯音包络。"},
   "productionTips": {"en": ["Program slide notes in your 808 piano roll with portamento time around 100ms", "Place the secondary snare hit on the 8th sixteenth-note of the bar", "Add pitch modulation and reverse automation to hi-hat loops"], "zh": ["在 808 钢琴窗中写入跨八度滑音音符，滑音时间设在 100ms 左右", "将第二个军鼓拍点准确安放在小节的第 8 个十六分音符上", "在踩镲循环中加入音高颤音自动化与反向抽吸切片"]}},

  {"id": "brooklyn-drill", "name": "Brooklyn Drill", "aliases": ["布鲁克林钻头"], "category": "Electronic", "year": "2018", "bpm": "140–145 BPM", "default_bpm": 142, "style": "half_time", "place": {"en": "Brooklyn, New York, USA", "zh": "美国纽约布鲁克林"},
   "artists": ["Pop Smoke", "Fivio Foreign", "Sheff G", "Sleepy Hallow", "22Gz"],
   "context": {"en": "Brought UK drill production back to New York, popularized globally by Pop Smoke with baritone growls and high-energy Brooklyn swagger.", "zh": "将英国钻头制作带回纽约，由 Pop Smoke 等人推向世界顶峰，融合雄浑低沉的嗓音与布鲁克林自信嚣张的能量。"},
   "soundDesign": {"en": "Aggressive sliding 808s, haunting music box bells, heavy sub saturation, gunshot FX.", "zh": "凶狠滑音 808、凄美八音盒钟琴、厚重超低频饱和与真实枪声拟音。"},
   "rhythmFeatures": {"en": "Bouncy 142 BPM syncopated UK drill skip paired with explosive 808 slides and sharp snares.", "zh": "充满弹跳感的 142 BPM 切分跳跃节奏，搭配爆炸般的 808 滑音与锋利军鼓。"},
   "bassPattern": {"en": "Aggressive, pitch-bent 808 lines weaving dynamically around the vocal delivery.", "zh": "极具侵略性的大范围音高滑音 808，与说唱人声交错呼应。"},
   "productionTips": {"en": ["Drive the 808 into soft saturation to give it mid-range presence for smartphones", "Use short, crisp acoustic snares layered with synthesized rims", "Keep bell melodies eerie and repetitive"], "zh": ["对 808 施加温和饱和失真，确保在手机扬声器上清晰辨识", "选用短小干脆的原声军鼓与合成边击叠层", "保持小调钟琴旋律阴冷孤寂且不断循环"]}},

  {"id": "jersey-drill", "name": "Jersey Drill", "aliases": ["泽西钻头"], "category": "Electronic", "year": "2022", "bpm": "135–142 BPM", "default_bpm": 140, "style": "four_on_floor", "place": {"en": "New Jersey, USA", "zh": "美国新泽西"},
   "artists": ["Bandmanrill", "DJ Smallz 732", "MCVERTT", "Sha EK", "DD Osama"],
   "context": {"en": "A viral hybrid marrying Brooklyn drill's aggressive sliding 808s with the fast 5-beat bouncy kick pattern of Jersey Club.", "zh": "风靡互联网的跨界风格，将布鲁克林钻头的凶狠滑音 808 与新泽西俱乐部标志性的 5 拍弹跳底鼓浑然交融。"},
   "soundDesign": {"en": "Sliding 808s, bed squeak samples, water drop foley, chopped sample flips.", "zh": "滑音 808、标志性床簧吱呀声、水滴拟音与经典老歌变速切片。"},
   "rhythmFeatures": {"en": "The iconic 5-beat Jersey Club kick bounce: Boom... Boom... Boom-Boom-Boom, at 140 BPM.", "zh": "标志性 5 拍泽西弹跳底鼓律动：咚……咚……咚-咚-咚，时速 140 BPM。"},
   "bassPattern": {"en": "Rapid 808 slides locking directly onto the 5-beat bouncy kick hits.", "zh": "极速滑音 808 牢牢咬合在 5 拍弹跳底鼓鼓点之上。"},
   "productionTips": {"en": ["Sequence the 5-beat kick pattern: beats 1, 2, and the 16th-notes of beats 3 and 4", "Sample popular pop/R&B acapellas, pitch up 3 semitones and speed up to 140 BPM", "Slide the 808 up on the rapid double-kicks"], "zh": ["编写经典 5 拍底鼓：落在 1、2 拍及 3、4 拍的十六分音符跳跃点", "采样流行歌曲原声切片，升高 3 个半音并加速至 140 BPM", "在极速连击底鼓点上让 808 音高极速上滑"]}}
]

future_downtempo_list = [
  {"id": "future-bass", "name": "Future Bass", "aliases": ["未来贝斯"], "category": "Electronic", "year": "2012", "bpm": "140–160 BPM", "default_bpm": 150, "style": "half_time", "place": {"en": "Australia & USA", "zh": "澳大利亚与美国"},
   "artists": ["Flume", "San Holo", "Illenium", "Marshmello", "Wave Racer"],
   "context": {"en": "Emerged in early 2010s championed by Flume, featuring sidechained lush supersaw chords modulated by LFOs, bright arpeggios, and heavy 808s.", "zh": "2010 年代初由 Flume 等人掀起风潮，以受 LFO 调制的侧链明亮 Supersaw 和弦、晶莹琶音与厚重 808 著称。"},
   "soundDesign": {"en": "Detuned supersaws with low-pass LFO wobble, vocal chops, bright arpeggios, clean 808 bass.", "zh": "带有 LFO 滤波摇动的去谐 Supersaw、音高滑音人声切片、闪烁琶音与纯净 808 贝斯。"},
   "rhythmFeatures": {"en": "Syncopated half-time groove with prominent snare on beat 3 and stuttering hi-hat rolls.", "zh": "切分半速律动，第 3 拍落响亮大军鼓，配合灵动的踩镲滚奏与顿挫停顿。"},
   "bassPattern": {"en": "Deep 808 sub bass following chord root notes with smooth envelope glides.", "zh": "紧跟和弦根音进行的深沉 808 超低音，带有顺滑的包络滑音。"},
   "productionTips": {"en": ["Modulate low-pass filter cutoff with a syncopated LFO on the supersaw bus", "Use vocal chops as melodic lead elements with heavy stereo ping-pong delay", "Sidechain everything to the kick and snare for immense bounce"], "zh": ["用切分节奏的 LFO 调制 Supersaw 总线上的低通滤波截止频率", "把人声切片作为主音旋律并挂载宽立体声乒乓延迟", "对所有和声乐器施加深侧链闪避营造极佳弹性"]}},

  {"id": "kawaii-future-bass", "name": "Kawaii Future Bass", "aliases": ["可爱未来贝斯"], "category": "Electronic", "year": "2015", "bpm": "150–165 BPM", "default_bpm": 160, "style": "half_time", "place": {"en": "Japan", "zh": "日本"},
   "artists": ["Snail's House", "Yunomi", "Kero Kero Bonito", "TORIENA", "PSYQUI"],
   "context": {"en": "Pioneered in Japan by Snail's House, infusing future bass with cheerful anime vocal samples, chiptune 8-bit blips, and upbeat major keys.", "zh": "由 Snail's House 等人在日本创立，将未来贝斯与欢快萌系动漫人声采样、8位复古芯片音效及阳光大调旋律结合。"},
   "soundDesign": {"en": "High-pitched anime vocal giggles, 8-bit game arpeggios, bright bells, super-bouncy supersaws.", "zh": "高音调动漫萌系人声、8位复古游戏点音、晶莹八音盒电铃与极具弹跳感的亮彩 Supersaw。"},
   "rhythmFeatures": {"en": "Frantic, playful half-time beats layered with rapid foley clicks, vinyl pops, and bright claps.", "zh": "活泼俏皮的半速节拍，叠置密集的拟音微撞击、黑胶爆豆与清脆拍手。"},
   "bassPattern": {"en": "Warm, bouncing sub-bass supporting cheerful major 7th and add9 chord progressions.", "zh": "温暖有弹性的超低音，坚实托起欢欣的大七（maj7）与加九（add9）和弦走向。"},
   "productionTips": {"en": ["Compose in major keys (F major, C major) with anime-style IV-V-iii-vi chord progressions", "Incorporate video game foley (coin collects, jump sounds) as percussion", "Keep saw chords bright by leaving the low-pass filter open"], "zh": ["使用王道进行（IV-V-iii-vi）等日系大调和弦创作旋律", "融入复古电子游戏音效（金币拾取、跳跃弹簧）作为打击乐点缀", "让低通滤波器充分打开保持和弦音色晶莹剔透"]}},

  {"id": "synthwave", "name": "Synthwave", "aliases": ["合成器波", "复古合成"], "category": "Electronic", "year": "2005", "bpm": "100–125 BPM", "default_bpm": 115, "style": "four_on_floor", "place": {"en": "France & USA", "zh": "法国与美国"},
   "artists": ["Kavinsky", "Carpenter Brut", "The Midnight", "GUNSHIP", "Timecop1983"],
   "context": {"en": "Inspired by 1980s film soundtracks and video games, celebrating retro-futuristic nostalgia with gated reverbs and analog polysynths.", "zh": "灵感源自 80 年代经典科幻电影配乐与街机游戏，以门限混响军鼓与经典模拟多音合成器颂唱复古未来怀旧。"},
   "soundDesign": {"en": "LinnDrum/Oberheim DMX gated snares, Roland Jupiter-8 polysynth pads, Yamaha DX7 electric pianos.", "zh": "LinnDrum 门限混响军鼓、Roland Jupiter-8 温暖多音铺底与 Yamaha DX7 晶莹电钢琴。"},
   "rhythmFeatures": {"en": "Driving 4/4 rhythm with powerful gated snare on beats 2 and 4 and driving 16th hats.", "zh": "充满推进力的四四拍律动，在 2、4 拍击打震耳欲聋的门限混响大军鼓。"},
   "bassPattern": {"en": "Driving, running 16th-note analog arpeggiated basslines (the 'running bass').", "zh": "飞驰奔流的十六分音符模拟合成琶音低音（经典的 Running Bass 律动）。"},
   "productionTips": {"en": ["Apply non-linear gated reverb to your snare with 0.5s cutoff", "Use an arpeggiator on an analog saw bass preset running 16th notes", "Add subtle pitch chorus and tape flutter to polysynth pads"], "zh": ["为军鼓挂载衰减 0.5 秒截断的非线性门限混响（Gated Reverb）", "在模拟锯齿波低音上加载十六分音符琶音器打造奔跑律动", "为和弦铺底加入微小合唱与模拟磁带颤音效果"]}},

  {"id": "vaporwave", "name": "Vaporwave", "aliases": ["蒸汽波"], "category": "Electronic", "year": "2010", "bpm": "60–90 BPM", "default_bpm": 75, "style": "breakbeat", "place": {"en": "Internet", "zh": "互联网"},
   "artists": ["Macintosh Plus", "Saint Pepsi", "Blank Banshee", "Surfing", "ECO VIRTUAL"],
   "context": {"en": "An internet-born satirical microgenre chopping and slowing down 1980s smooth jazz, corporate lounge music, and commercial jingles.", "zh": "发端于互联网的解构流派，截取 80 年代轻柔爵士、电梯音乐与广告伴奏并降速变调，充盈消费主义迷梦。"},
   "soundDesign": {"en": "Slowed-down vinyl samples, phasers, tape chorus, muffled telephone filters.", "zh": "降速降调的黑胶采样、移相器、磁带合唱与沉闷的电话滤波质感。"},
   "rhythmFeatures": {"en": "Languid, heavy, slowed-down 4/4 or boom-bap beats with lazy swung hi-hats.", "zh": "慵懒沉重、放慢步调的四四拍或 Boom-Bap 节拍，踩镲带有松垮摇摆。"},
   "bassPattern": {"en": "Warm, pillowy, pitched-down acoustic or synth bass lines from original samples.", "zh": "源自原采样的温暖绵软、降调后充满低频共鸣的原声或合成贝斯线条。"},
   "productionTips": {"en": ["Slow down a 1980s city pop or smooth jazz track by 15-25% without time correction", "Apply stereo phasers and tape flangers to the entire master bus", "Layer tape hiss and VHS audio static in the background"], "zh": ["将 80 年代城市流行或轻爵士采样降速 15-25% 且不进行时间矫正", "在总线上挂载宽立体声移相器与磁带凸缘效果", "在背景层轻柔铺设录像带（VHS）电流底噪"]}},

  {"id": "chillwave", "name": "Chillwave", "aliases": ["冷波", "寒潮音乐"], "category": "Electronic", "year": "2009", "bpm": "80–100 BPM", "default_bpm": 90, "style": "breakbeat", "place": {"en": "USA", "zh": "美国"},
   "artists": ["Washed Out", "Toro y Moi", "Neon Indian", "Small Black", "Memory Tapes"],
   "context": {"en": "Emerged in late 2000s, characterized by hazy analog synths, reverb-soaked vocals, lo-fi aesthetics, and sunny summer nostalgia.", "zh": "兴起于 2000 年代末，以如梦似幻的薄雾模拟合成器、浸润混响的梦幻人声与夏日怀旧感闻名。"},
   "soundDesign": {"en": "Analog polysynths, woozy tape vibrato, drenched vocal reverbs, soft acoustic drums.", "zh": "温暖模拟多音合成器、微醺的磁带音高抖动、开阔人声混响与松软原声鼓。"},
   "rhythmFeatures": {"en": "Mid-tempo, relaxing drum machine rhythms with gentle tambourines and loose swing.", "zh": "中速舒缓的电子鼓机节拍，穿插着柔和的手摇铃与松散自然的摇摆。"},
   "bassPattern": {"en": "Simple, melodic, warm synth basslines holding down relaxed chord progressions.", "zh": "质朴温暖且极具旋律美的合成低音线条，托举舒缓惬意的和弦流动。"},
   "productionTips": {"en": ["Add tape pitch flutter modulation (vibrato) to synth chords for an authentic vintage warp", "Drench vocals in 100% wet plate reverb with long decay", "Keep drum machine sounds warm with analog tape saturation"], "zh": ["为合成和弦加入磁带音高颤动调制，营造复古微醺感", "将背景人声推入全湿板式混响中打造空灵氛围", "对电子鼓组做模拟磁带饱和让击打质地温润自然"]}},

  {"id": "downtempo", "name": "Downtempo", "aliases": ["缓拍音乐", "慢摇"], "category": "Electronic", "year": "1990", "bpm": "80–105 BPM", "default_bpm": 90, "style": "breakbeat", "place": {"en": "UK & Europe", "zh": "英国与欧洲"},
   "artists": ["Bonobo", "Tycho", "Thievery Corporation", "Kruder & Dorfmeister", "Zero 7"],
   "context": {"en": "A relaxed electronic genre emphasizing acoustic instruments, ambient atmospheres, warm organic grooves, and slow breakbeats.", "zh": "注重原声乐器质感、环境氛围、温暖有机律动与慢速碎拍的舒缓电子流派。"},
   "soundDesign": {"en": "Acoustic bass guitars, warm Fender Rhodes, lush string quartets, gentle wind chimes.", "zh": "原声贝斯吉他、温暖 Fender Rhodes、原声弦乐四重奏与轻柔风铃。"},
   "rhythmFeatures": {"en": "Relaxed, laid-back breakbeat groove with organic percussion layers and subtle ghost notes.", "zh": "从容放松的慢速碎拍律动，配合有机打击乐叠层与细腻幽灵音。"},
   "bassPattern": {"en": "Warm acoustic upright bass or round electric bass playing expressive walking lines.", "zh": "温暖的立式原声低音或圆润电贝斯，演奏富有表现力的行进低音。"},
   "productionTips": {"en": ["Layer real recorded shakers and bongos over electronic drum loops", "Use dynamic tape saturation on acoustic instruments", "Keep track tempos below 100 BPM for ultimate relaxation"], "zh": ["在电子鼓循环上方叠录真实的沙锤与邦戈鼓敲击", "在原声乐器上应用动态磁带饱和赋予模拟厚度", "严格将速度控制在 100 BPM 以下以确保极致放松体验"]}},

  {"id": "trip-hop", "name": "Trip Hop", "aliases": ["神游舞曲"], "category": "Electronic", "year": "1993", "bpm": "75–95 BPM", "default_bpm": 85, "style": "breakbeat", "place": {"en": "Bristol, UK", "zh": "英国布里斯托"},
   "artists": ["Massive Attack", "Portishead", "Tricky", "DJ Shadow", "Morcheeba"],
   "context": {"en": "Pioneered in Bristol by Massive Attack and Portishead, blending slow hip-hop breakbeats with dark cinematic strings, jazz samples, and soul.", "zh": "由 Massive Attack 与 Portishead 等人在布里斯托创立，将慢速嘻哈碎拍、暗黑电影弦乐与迷幻爵士融于一炉。"},
   "soundDesign": {"en": "Cinematic dark strings, crackling vinyl jazz chops, muted trumpets, heavy sub-bass.", "zh": "暗黑电影管弦乐、黑胶爵士切片、弱音小号与深沉超低频。"},
   "rhythmFeatures": {"en": "Heavy, slow, dragging hip-hop breakbeat with crackling vinyl snare and laid-back feel.", "zh": "沉重拖沓的慢速嘻哈碎拍，伴随黑胶爆豆军鼓与深沉后倾听感。"},
   "bassPattern": {"en": "Deep, rumbling dub-influenced electric basslines anchoring dark minor chords.", "zh": "受牙买加 Dub 启发的深邃轰鸣电贝斯线条，奠定暗黑小调和声地基。"},
   "productionTips": {"en": ["Sample vintage 1960s spy or noir soundtrack strings", "Slow down acoustic funk drum breaks to 85 BPM for heavy drag", "Add spring reverb to guitars and rimshots for shadowy space"], "zh": ["采样 60 年代复古黑色谍战电影弦乐片段", "将原声放克鼓循环放慢至 85 BPM 营造沉重拖拽感", "为吉他与边击挂载弹簧混响营造阴郁悬疑空间"]}},

  {"id": "glitch-hop", "name": "Glitch Hop", "aliases": ["故障嘻哈"], "category": "Electronic", "year": "2001", "bpm": "100–115 BPM", "default_bpm": 105, "style": "breakbeat", "place": {"en": "Global", "zh": "全球"},
   "artists": ["The Glitch Mob", "Koan Sound", "Opiuo", "GRiZ", "Prefuse 73"],
   "context": {"en": "Marries the funky swing of mid-tempo hip-hop with cutting-edge digital audio glitches, micro-edits, and neuro-bass sound design.", "zh": "将中速嘻哈的放克摇摆与前沿数字音频毛刺、微观精密切片及神经质贝斯音色设计融合。"},
   "soundDesign": {"en": "Microscopic buffer repeats, bitcrushed clicks, funky clavinet stabs, modular growl basses.", "zh": "微观音频缓冲重复、降采样点击声、放克电古钢琴刺音与模块化咆哮贝斯。"},
   "rhythmFeatures": {"en": "Funky, swinging 105 BPM groove with heavily syncopated snares and micro-stutter fills.", "zh": "极具放克摇摆感的 105 BPM 律动，切分军鼓穿插着毫秒级音频口吃加花。"},
   "bassPattern": {"en": "Surgically processed neurofunk-style mid-bass growls punctuated by clean sub-bass drops.", "zh": "经过手术刀级精雕细琢的中频咆哮贝斯，与纯净超低音重击穿插交织。"},
   "productionTips": {"en": ["Use buffer-repeat or granular stutter plugins on rhythmic fills", "Lock your swing around 58% to get that funky hip-hop pocket at 105 BPM", "Automate bitcrush depth on drum fills right before drops"], "zh": ["在加花段落使用音频缓冲重复或粒子卡顿插件", "将摇摆度锁定在 58% 左右获取正宗放克弹性", "在进入 Drop 前对鼓组加花段落做降采样自动化"]}},

  {"id": "idm", "name": "IDM", "aliases": ["智能舞曲", "脑力舞曲"], "category": "Electronic", "year": "1992", "bpm": "110–180 BPM", "default_bpm": 130, "style": "breakbeat", "place": {"en": "UK", "zh": "英国"},
   "artists": ["Aphex Twin", "Autechre", "Squarepusher", "Boards of Canada", "Plaid"],
   "context": {"en": "Pioneered by Warp Records artists, prioritizing complex rhythmic sequencing, generative algorithms, and avant-garde headphone listening over dancefloors.", "zh": "由 Warp 唱片旗下先锋艺术家开创，专注于复杂多变的算法音序、前卫听觉探索与耳机内深层冥想。"},
   "soundDesign": {"en": "Generative modular bleeps, granular audio clouds, micro-sampled transients, FM bells.", "zh": "生成式模块蜂鸣、粒子合成云、微采样瞬态打击乐与复杂 FM 金属钟声。"},
   "rhythmFeatures": {"en": "Intricate, constantly evolving algorithmic beat slicing, polyrhythms, and metric modulation.", "zh": "错综复杂且不断蜕变的算法碎拍切片、复合节奏与速度度量调制。"},
   "bassPattern": {"en": "Unpredictable analog sub bursts and rapid pitch-sliding micro basses weaving through chaos.", "zh": "难以预测的模拟超低音突发脉冲与快速滑音微型贝斯穿梭于混沌之中。"},
   "productionTips": {"en": ["Utilize Max/MSP or modular sequencers to generate semi-random drum triggers", "Reverse tiny micro-slices within a standard breakbeat", "Contrast harsh digital clicks with warm analog synth melodies"], "zh": ["利用模块化音序器生成半随机鼓点触发", "在标准碎拍中将极短微切片进行反向翻转", "用冰冷尖锐的数字咔哒声与温暖如春的模拟旋律制造张力"]}},

  {"id": "ambient", "name": "Ambient", "aliases": ["氛围音乐", "环境音乐"], "category": "Electronic", "year": "1975", "bpm": "Free / Beatless", "default_bpm": 60, "style": "breakbeat", "place": {"en": "UK", "zh": "英国"},
   "artists": ["Brian Eno", "Harold Budd", "Stars of the Lid", "Tim Hecker", "William Basinski"],
   "context": {"en": "Conceived by Brian Eno in the mid-1970s as music intended to induce calm and space to think, designed to be as ignorable as it is interesting.", "zh": "由 Brian Eno 于 1970 年代中期开创，旨在营造宁静氛围与沉思空间，可被聆听亦可浑然融入环境。"},
   "soundDesign": {"en": "Infinite reverb washes, tape loop decay, bowed guitars, subtle sub-bass drones.", "zh": "无垠混响、磁带循环自然物理衰减、弓弦拉奏吉他与微弱超低频长鸣。"},
   "rhythmFeatures": {"en": "Generally beatless or featuring gentle, non-metered rhythmic pulses and nature recordings.", "zh": "通常完全无明确鼓点节拍，或仅包含轻柔非定量的脉动与自然环境录音。"},
   "bassPattern": {"en": "Slow, evolving sub-bass foundation that supports shifting acoustic chords over minutes.", "zh": "极缓舒展的超低频基石，在数分钟的漫长时间跨度内平缓托举和声变迁。"},
   "productionTips": {"en": ["Use 100% wet convolution reverbs with impulse responses from cathedrals or caves", "Automate volume faders slowly with gentle curves over 2-3 minutes", "Introduce subtle pitch drift with analog tape emulation plugins"], "zh": ["使用大教堂或洞穴脉冲响应的全湿卷积混响", "以极平缓的弧线在 2-3 分钟内慢慢推移音轨音量", "挂载模拟磁带插件为铺底引入微小的音高漂移"]}},

  {"id": "ambient-dub", "name": "Ambient Dub", "aliases": ["氛围回响"], "category": "Electronic", "year": "1991", "bpm": "70–110 BPM", "default_bpm": 80, "style": "half_time", "place": {"en": "UK & Germany", "zh": "英国与德国"},
   "artists": ["The Orb", "Bill Laswell", "Linton Kwesi Johnson", "Pole", "Automaton"],
   "context": {"en": "Blends the vast spaciousness of ambient soundscapes with the heavy, pulsing basslines and tape delays of dub reggae.", "zh": "将氛围音乐的辽阔空灵与牙买加 Dub 雷鬼沉重脉动的低音线条和磁带回声融为一体。"},
   "soundDesign": {"en": "Cavernous tape delay feedbacks, warm sine sub-bass, floating synth pads, echo splashes.", "zh": "深邃洞穴磁带延迟反馈、温润正弦波超低音、漂浮合成铺底与回声泼溅。"},
   "rhythmFeatures": {"en": "Sparse, skeletal slow beats anchored by intermittent rimshots and deep delayed percussions.", "zh": "稀疏骨架化的慢速节拍，由间歇性的边击与深沉延迟打击乐锚定。"},
   "bassPattern": {"en": "Heavy, resonant low-frequency dub basslines pulsing through the ambient space.", "zh": "厚重、带有深邃共鸣的低频 Dub 贝斯线条，穿透氛围空间深沉脉动。"},
   "productionTips": {"en": ["Route tape delays through a sweeping low-pass filter with high resonance", "Keep the kick drum sub-heavy and muted with low-pass filtering around 300Hz", "Let space and silence breathe between dub hits"], "zh": ["将磁带延迟输出路由至带高共鸣的低通滤波器", "底鼓保持深沉并做 300Hz 低通滤波以柔化瞬态", "在每次 Dub 重击之间留足让空间与寂静回响的空白"]}},

  {"id": "lofi-house", "name": "Lo-Fi House", "aliases": ["低保真浩室"], "category": "Electronic", "year": "2015", "bpm": "120–126 BPM", "default_bpm": 124, "style": "four_on_floor", "place": {"en": "Global & UK", "zh": "全球与英国"},
   "artists": ["Mall Grab", "DJ Seinfeld", "Ross From Friends", "DJ Boring", "Baltic Fleet"],
   "context": {"en": "A gritty, nostalgic mid-2010s movement recording house tracks to cassette tape with murky filters, crunchy drums, and bittersweet soul samples.", "zh": "2010 年代中期的复古粗糙潮流，将浩室录入卡式磁带，以浑浊滤波、颗粒感鼓组与苦甜相伴的采样著称。"},
   "soundDesign": {"en": "Cassette tape saturation and wow/flutter, crunchy 909 drums, muffled soul chops.", "zh": "卡式磁带饱和与抖晃颤音、粗颗粒 909 鼓组与沉闷怀旧灵魂乐采样。"},
   "rhythmFeatures": {"en": "Raw, dusty 4/4 four-on-the-floor kick with crunchy compressed open hats and dusty claps.", "zh": "粗砺布满灰尘感的四四拍底鼓，搭配高压缩颗粒感开镲与暗色拍手。"},
   "bassPattern": {"en": "Simple, saturated analog basslines or warm sine subs humming through tape fuzz.", "zh": "质朴饱和的模拟贝斯线条或在磁带底噪中轻柔嗡鸣的温暖正弦低音。"},
   "productionTips": {"en": ["Record your entire mix to a real cassette tape deck and re-record it back into your DAW", "Use heavy low-pass filtering and bitcrushing on drum samples", "Layer nostalgic anime or movie voiceover samples before drops"], "zh": ["将整首混音实录到真实的卡带机中再录回宿主", "对鼓组采样施加较重的低通滤波与降采样处理", "在 Drop 爆发前叠入一段怀旧电影或动漫对白采样"]}},

  {"id": "chiptune", "name": "Chiptune", "aliases": ["芯片音乐", "8-Bit"], "category": "Electronic", "year": "1980", "bpm": "120–160 BPM", "default_bpm": 140, "style": "breakbeat", "place": {"en": "Global & Japan", "zh": "全球与日本"},
   "artists": ["Anamanaguchi", "Disasterpeace", "Chipzel", "Sabrepulse", "Yuzo Koshiro"],
   "context": {"en": "Synthesized electronic music created using vintage programmable sound generator (PSG) sound chips from classic game consoles (NES, Game Boy, Commodore 64).", "zh": "使用复古经典主机（NES、Game Boy、C64）的可编程声音发生芯片创作的原生复古电子音乐。"},
   "soundDesign": {"en": "Pure square waves, triangle wave bass, pseudo-random white noise percussions, rapid arpeggios.", "zh": "纯方波、三角波低音、伪随机白噪声打击乐与极速分解琶音。"},
   "rhythmFeatures": {"en": "Punchy 8-bit rhythms built purely out of noise channel bursts and rapid volume envelopes.", "zh": "完全由白噪声通道突发与快速音量包络构筑的清脆 8 位节拍。"},
   "bassPattern": {"en": "Clean, unadorned triangle-wave basslines playing tight, energetic melodic runs.", "zh": "干净无修饰的纯三角波低音线条，演奏紧凑充满活力的旋律跑动。"},
   "productionTips": {"en": ["Emulate hardware constraints: restrict yourself to 2 pulse channels, 1 triangle wave, and 1 noise channel", "Use ultra-fast 3-note arpeggios on a single pulse channel to fake chords", "Avoid all modern reverb and delay plugins"], "zh": ["严格遵循硬件物理限制：仅使用 2 轨方波、1 轨三角波与 1 轨噪声通道", "在单个方波通道上使用极速三连琶音模拟复合和弦", "杜绝现代混响与延迟，保留最纯粹干燥的芯片音质"]}}
]

hard_electro_list = [
  {"id": "hardstyle", "name": "Hardstyle", "aliases": ["硬派舞曲"], "category": "Electronic", "year": "1999", "bpm": "148–152 BPM", "default_bpm": 150, "style": "four_on_floor", "place": {"en": "Netherlands & Italy", "zh": "荷兰与意大利"},
   "artists": ["Headhunterz", "Wildstylez", "Noisecontrollers", "Coone", "Sub Zero Project"],
   "context": {"en": "Born in the Netherlands and Italy around 1999, famous for its signature pitched, distorted kick drum tail (the 'reverse bass'), emotional melody builds, and 150 BPM energy.", "zh": "1999 年前后诞生于荷兰与意大利，以标志性定调失真底鼓尾部（Reverse Bass）、宏大史诗旋律与 150 BPM 能量著称。"},
   "soundDesign": {"en": "Pitched distorted kick drums, detuned screech leads, epic supersaw melodies, euphoric anthems.", "zh": "定调失真大底鼓、高侵略性 Screech 尖叫合成器与恢弘史诗 Supersaw 旋律。"},
   "rhythmFeatures": {"en": "Driving 150 BPM four-on-the-floor stomping kick with offbeat reverse bass energy.", "zh": "推进式 150 BPM 四踩四重踏底鼓，伴随充满反冲推力的反拍低音。"},
   "bassPattern": {"en": "Pitch-following distorted kick tail that plays the melodic bassline notes directly.", "zh": "紧随主和弦音高变换的失真底鼓尾音，直接承担旋律低音线条功能。"},
   "productionTips": {"en": ["Layer a punchy transient kick with an overdriven, pitched low-pass tail", "Use distortion, EQ, and saturation in 5+ successive stages to sculpt the kick", "Stack massive supersaw leads with reverb for the emotional climax"], "zh": ["将高瞬态敲击头与经过多级过载定调的低通尾部紧密贴合", "使用失真、EQ 与饱和器连续串联 5 级以上精心雕琢底鼓音色", "为高潮段落堆叠宽广混响的巨幅 Supersaw 音墙"]}},

  {"id": "hardcore-gabber", "name": "Hardcore / Gabber", "aliases": ["嘎巴硬核", "早期硬核"], "category": "Electronic", "year": "1992", "bpm": "160–200 BPM", "default_bpm": 175, "style": "four_on_floor", "place": {"en": "Rotterdam, Netherlands", "zh": "荷兰鹿特丹"},
   "artists": ["Angerfist", "Paul Elstak", "Neophyte", "Mad Dog", "Evil Activities"],
   "context": {"en": "Born in Rotterdam in 1992 as a furious counter-reaction to commercial house, pushing tempos past 170 BPM with extreme distorted 909 kicks and hoover synths.", "zh": "1992 年发源于荷兰鹿特丹，反叛商业浩室，将速度推向 170-200 BPM，以极限失真 909 底鼓与 Hoover 合成器统治地下。"},
   "soundDesign": {"en": "Severely clipped and overdriven TR-909 kicks, classic Alpha Juno hoovers, dark pitch risers.", "zh": "极度削波过载的 TR-909 底鼓、经典 Alpha Juno 狂暴真空管吸尘器音效（Hoover）与暗黑升效。"},
   "rhythmFeatures": {"en": "Relentless, furious 175+ BPM 4/4 stomping kick barrage with offbeat distorted noise.", "zh": "狂暴不息的 175+ BPM 四踩四践踏式底鼓弹幕，伴随反拍失真噪声。"},
   "bassPattern": {"en": "Kick and bass are completely fused into a single pulverizing, distorted low-end hammer.", "zh": "底鼓与低音完全熔铸为单一柄粉碎性的失真超低频铁锤。"},
   "productionTips": {"en": ["Slam a 909 kick into analog mixer overdrive until the sine wave squares off", "Use Alpha Juno 'What the' preset for the authentic classic hoover lead", "Keep percussion minimal to leave maximum energy for the kick"], "zh": ["将 909 底鼓推入调音台过载直至正弦波被削成方波", "使用 Alpha Juno 经典音色复现纯正老派 Hoover 尖叫", "精简打击乐配器，将极致动态与能量全部留给重击底鼓"]}},

  {"id": "frenchcore", "name": "Frenchcore", "aliases": ["法兰西硬核"], "category": "Electronic", "year": "1998", "bpm": "190–210 BPM", "default_bpm": 200, "style": "four_on_floor", "place": {"en": "France", "zh": "法国"},
   "artists": ["Sefa", "Dr. Peacock", "Radium", "The Sickest Squad", "Billx"],
   "context": {"en": "Emerged from the French free party rave scene, characterized by blistering 200 BPM tempos, dynamic offbeat bass kicks, and euphoric classical/folk melodies.", "zh": "脱胎于法国自由派对地下狂欢，以极速 200 BPM 飞驰、弹跳反拍失真底鼓与壮丽交响/民谣旋律著称。"},
   "soundDesign": {"en": "Bouncy distorted kick with distinctive offbeat tail, orchestral strings, choir chants, accordion.", "zh": "带有鲜明反拍弹跳尾音的失真底鼓、管弦乐弦乐、史诗唱诗班合唱与手风琴。"},
   "rhythmFeatures": {"en": "Ultra-fast 200 BPM four-on-the-floor kick with an unmistakable bouncy offbeat pump.", "zh": "极速 200 BPM 四四拍底鼓，伴随极具辨识度的弹跳反拍抽吸律动。"},
   "bassPattern": {"en": "Fast, driving reverse-bass offbeat that creates a continuous galloping sensation at 200 BPM.", "zh": "高速飞奔的反拍反转低音，在 200 BPM 下构筑骏马奔腾般的飞驰推进感。"},
   "productionTips": {"en": ["Shape the kick with a short snappy attack and a resonant offbeat bass swell", "Incorporate classical piano and orchestral breakdowns before drop assaults", "High-pass melodic elements around 250Hz to preserve clarity at 200 BPM"], "zh": ["将底鼓塑形为短促干脆的敲击头与带共振的反拍涌动尾音", "在极速爆发前加入古典钢琴与恢弘管弦乐大分解段落", "对旋律元素在 250Hz 做高通滤波保证 200 BPM 下纯净不混浊"]}},

  {"id": "happy-hardcore", "name": "Happy Hardcore", "aliases": ["快乐硬核"], "category": "Electronic", "year": "1994", "bpm": "165–180 BPM", "default_bpm": 170, "style": "four_on_floor", "place": {"en": "UK & Scotland", "zh": "英国与苏格兰"},
   "artists": ["Scott Brown", "DJ Paul Elstak", "Darren Styles", "Slammin Vinyl", "Hixxy"],
   "context": {"en": "Mid-90s UK rave movement combining 170 BPM breakbeats, upbeat piano stabs, pitched-up chipmunk vocals, and euphoric joyful melodies.", "zh": "90 年代中期英国狂欢运动，将 170 BPM 碎拍、欢快钢琴切片、升调花栗鼠人声与极乐旋律融为一体。"},
   "soundDesign": {"en": "Pitch-shifted female vocals (+5 to +7 semitones), bright M1 piano stabs, euphoric supersaws, 909 kicks.", "zh": "大幅升调的人声（+5至+7个半音）、明亮 M1 钢琴和弦切片、欢乐 Supersaw 与 909 底鼓。"},
   "rhythmFeatures": {"en": "Fast 4/4 kick layered with rolling syncopated breakbeats running at 170 BPM.", "zh": "高速 4/4 底鼓与在 170 BPM 下狂奔的切分碎拍紧密贴合。"},
   "bassPattern": {"en": "Bouncy offbeat analog pluck or rounded sub-bass bouncing happily beneath piano riffs.", "zh": "富有弹性跳跃的反拍模拟弹拨或圆润超低音，在钢琴旋律下方快乐跳动。"},
   "productionTips": {"en": ["Pitch upbeat vocal acapellas up 5-6 semitones for the signature chipmunk effect", "Layer bright acoustic piano chords with 16th-note syncopations", "Keep track energy overwhelmingly positive and joyful in major keys"], "zh": ["将人声干声向上移调 5-6 个半音获得标志性花栗鼠声线", "用明亮真钢琴和弦弹奏切分的十六分音符律动", "在大调和声中保持压倒性的纯粹快乐与阳光能量"]}},

  {"id": "moombahton", "name": "Moombahton", "aliases": ["蒙巴顿"], "category": "Electronic", "year": "2009", "bpm": "108–112 BPM", "default_bpm": 110, "style": "half_time", "place": {"en": "Washington DC, USA", "zh": "美国华盛顿特区"},
   "artists": ["Dave Nada", "Dillon Francis", "Major Lazer", "Munchi", "Diplo"],
   "context": {"en": "Invented by Dave Nada in 2009 by slowing down Afrojack's remix of 'Moombah' to 108 BPM, merging Dutch house screeches with the reggaeton dembow beat.", "zh": "由 Dave Nada 于 2009 年将 Afrojack 的混音慢放至 108 BPM 时偶然创立，将荷兰浩室的尖叫音色与雷鬼顿 Dembow 律动结合。"},
   "soundDesign": {"en": "Dutch house laser synths, pitched vocal shouts, thick sub-bass, Latin percussion fills.", "zh": "荷兰浩室高音激光尖叫、调音人声呼喊、厚重超低音与拉丁打击乐加花。"},
   "rhythmFeatures": {"en": "The iconic 108 BPM dembow rhythm: 4/4 kick pulse with syncopated snare on beats 2-and and 4-and.", "zh": "标志性 108 BPM Dembow 律动：四踩四底鼓脉冲，军鼓落在附点反拍上（咚-哒-咚-哒）。"},
   "bassPattern": {"en": "Deep, rolling sub-bass that follows the swinging dembow rhythm with tropical warmth.", "zh": "深沉滚动的超低音，伴随着摇摆的 Dembow 节奏散发热带温度。"},
   "productionTips": {"en": ["Program the dembow snare pattern: dotted 8th note followed by 16th note", "Slow down screechy 128 BPM electro synths to 108 BPM for thick swing", "Layer timbales and cowbells for Latin flavor"], "zh": ["编写经典的 Dembow 军鼓律动（附点八分音符紧随十六分音符）", "将 128 BPM 尖啸合成音色降速至 108 BPM 增添厚重视听感", "加入铜铃与天巴鼓（Timbales）赋予纯正拉丁色彩"]}},

  {"id": "jersey-club", "name": "Jersey Club", "aliases": ["泽西俱乐部"], "category": "Electronic", "year": "2001", "bpm": "130–140 BPM", "default_bpm": 135, "style": "four_on_floor", "place": {"en": "Newark, New Jersey, USA", "zh": "美国新泽西纽瓦克"},
   "artists": ["DJ Sliink", "DJ Tameil", "Uniiqu3", "Trippyturtle", "Nadus"],
   "context": {"en": "Emerged from Newark, NJ, evolving from Baltimore club, known for its signature 5-beat kick pattern, squeaky bed spring samples, and rapid vocal chops.", "zh": "诞生于新泽西纽瓦克，演化自巴尔的摩俱乐部音乐，以标志性 5 拍弹跳底鼓、吱呀床簧采样与极速人声切片风靡。"},
   "soundDesign": {"en": "Bed spring squeak sample, water drop clicks, gunshots, chopped vocal loop stutters.", "zh": "床簧吱呀声采样、水滴轻响、开枪射击声与短促卡顿人声切片。"},
   "rhythmFeatures": {"en": "The iconic 5-beat kick pattern: boom... boom... boom-boom-boom with rapid triple claps.", "zh": "标志性 5 拍弹跳底鼓：咚……咚……咚-咚-咚，伴随极速三连拍手。"},
   "bassPattern": {"en": "Short, bouncy 808 sub hits that punctuate the 5-beat kick pattern with instant releases.", "zh": "短促有弹性的 808 超低音重击，紧密配合 5 拍底鼓，带有干脆利落的瞬时释放。"},
   "productionTips": {"en": ["Place the bed spring squeak sample on the offbeat after beat 2", "Program the 5-beat kick bounce: beat 1, beat 2, and beats 3, 3.5, 4", "Chop an R&B vocal hook and trigger it every quarter note"], "zh": ["在第 2 拍的反拍安放经典床簧吱呀采样", "编写 5 拍底鼓弹跳：第 1 拍、第 2 拍以及 3、3.5、4 拍", "截取 R&B 人声片段并每隔一拍进行触发形成洗脑循环"]}},

  {"id": "footwork", "name": "Footwork", "aliases": ["步法舞曲", "芝加哥步法"], "category": "Electronic", "year": "1998", "bpm": "155–165 BPM", "default_bpm": 160, "style": "breakbeat", "place": {"en": "Chicago, Illinois, USA", "zh": "美国芝加哥"},
   "artists": ["DJ Rashad", "DJ Spinn", "RP Boo", "Jlin", "DJ Taye"],
   "context": {"en": "Evolved from Chicago ghetto house and juke for hyper-speed competitive dance battles, featuring 160 BPM syncopated polyrhythmic triplets and micro-chopped soul loops.", "zh": "由芝加哥贫民窟浩室与 Juke 演化而来，专为极速斗舞比赛打造，具备 160 BPM 切分三连音复合节奏与微切片灵魂乐采样。"},
   "soundDesign": {"en": "Rapid-fire 808 toms, sliced soul vocals repeated frantically, sub-bass pitch dives.", "zh": "速射 808 通鼓、疯狂重复切碎的灵魂乐人声与快速音高下坠的超低音。"},
   "rhythmFeatures": {"en": "Frenetic 160 BPM syncopation switching between half-time 80 BPM feel and polyrhythmic triplets.", "zh": "狂热飞奔的 160 BPM 切分节奏，在 80 BPM 半速与多节奏三连音之间瞬息万变。"},
   "bassPattern": {"en": "Gliding 808 sub drops and rapid walking tom-bass patterns shifting constantly.", "zh": "滑音 808 下沉音与极速行进的通鼓贝斯模式不断交织演变。"},
   "productionTips": {"en": ["Chop a 1-second soul vocal loop into 16 slices and trigger across complex triplet grids", "Use rapid-fire Roland 808 low toms as melodic bass elements", "Keep the energy raw, unpolished, and spontaneous"], "zh": ["将 1 秒灵魂乐采样切碎为 16 片并排布在复杂三连音网格上", "将速射 Roland 808 低通鼓作为旋律低音乐器使用", "保持声音质感质朴粗砺与不可预测的即兴冲动"]}},

  {"id": "phonk", "name": "Phonk", "aliases": ["放克说唱", "孟菲斯放克"], "category": "Electronic", "year": "2012", "bpm": "130–145 BPM", "default_bpm": 135, "style": "half_time", "place": {"en": "Memphis, USA & Online", "zh": "美国孟菲斯与互联网"},
   "artists": ["SpaceGhostPurrp", "DJ Smokey", "Soudiere", "Mythic", "Roland Jones"],
   "context": {"en": "Emerged online inspired by 1990s Memphis rap cassette tapes, defined by chopped Memphis rap vocal loops, jazz Rhodes chords, and Roland TR-808 cowbells.", "zh": "发端于网络，致敬 90 年代孟菲斯地下磁带说唱，以孟菲斯人声切片、爵士 Rhodes 和弦与 TR-808 标志性牛铃为特征。"},
   "soundDesign": {"en": "Roland TR-808 cowbell leads, dusty vinyl Rhodes, chopped Memphis acapellas, cassette hiss.", "zh": "Roland TR-808 牛铃主音旋律、蒙尘黑胶 Rhodes 电钢、孟菲斯人声干声与磁带底噪。"},
   "rhythmFeatures": {"en": "Heavy 135 BPM half-time bounce with rolling hi-hats and deep booming 808 kicks.", "zh": "沉重有力的 135 BPM 半速弹跳，伴随细密踩镲滚奏与轰鸣 808 底鼓。"},
   "bassPattern": {"en": "Heavy, warm 808 sub kicks with long decay that fill the low end with analog tape fuzz.", "zh": "厚重深沉的纯正 808 超低音，带有超长衰减，充盈着模拟磁带的温暖毛刺。"},
   "productionTips": {"en": ["Program melodies using the classic Roland TR-808 cowbell pitched across minor scales", "Apply vintage cassette tape saturation and low-pass filtering to sample chops", "Layer chopped vocal chants from 90s Memphis rap tapes"], "zh": ["将经典 Roland TR-808 牛铃采样在小调音阶上编排洗脑旋律", "在采样切片上挂载复古磁带饱和与温和低通滤波", "叠入 90 年代孟菲斯地下说唱磁带的人声呐喊口号"]}},

  {"id": "drift-phonk", "name": "Drift Phonk", "aliases": ["漂移放克"], "category": "Electronic", "year": "2018", "bpm": "150–165 BPM", "default_bpm": 160, "style": "four_on_floor", "place": {"en": "Russia & Global", "zh": "俄罗斯与全球"},
   "artists": ["Kordhell", "DVRST", "PlayaPhonk", "Pharmacist", "Hensonn"],
   "context": {"en": "High-octane evolution of phonk popularized via car drifting videos, featuring heavily distorted 808 cowbell melodies and brutal bass saturation.", "zh": "由汽车漂移短视频引爆全球的高能放克演进，以极度失真过载的 808 牛铃旋律与暴烈低频饱和震撼舞池。"},
   "soundDesign": {"en": "Blown-out overdriven 808 cowbells, heavily clipped sub bass, aggressive industrial vocal shouts.", "zh": "炸裂过载的 808 牛铃、硬剪切削波超低频与侵略性工业人声嘶吼。"},
   "rhythmFeatures": {"en": "Driving 160 BPM beats with crushing distorted snares, fast triplet hi-hats, and raw bounce.", "zh": "飞驰的 160 BPM 推进节拍，伴随粉碎性失真军鼓与极速三连音踩镲。"},
   "bassPattern": {"en": "Massive distorted 808 basslines driven past 0dB to create square-wave low-end roar.", "zh": "推过 0dB 极限失真的庞大 808 低音线条，营造方波撕裂般的超低频咆哮。"},
   "productionTips": {"en": ["Drive the 808 cowbell melody through severe wave-shaping distortion", "Clip the master output with soft/hard clipping for relentless perceived volume", "Keep tempo fast around 160 BPM for high adrenaline"], "zh": ["让 808 牛铃旋律通过激进的波形塑形失真单块", "在母带输出端使用软/硬剪切压榨出极致听觉响度", "将速度保持在 160 BPM 左右点燃肾上腺素"]}},

  {"id": "electro", "name": "Electro", "aliases": ["电子放克", "Classic Electro"], "category": "Electronic", "year": "1982", "bpm": "120–135 BPM", "default_bpm": 128, "style": "breakbeat", "place": {"en": "New York & Detroit, USA", "zh": "美国纽约与底特律"},
   "artists": ["Afrika Bambaataa", "Cybotron", "Egyptian Lover", "Kraftwerk", "Aux 88"],
   "context": {"en": "Pioneered in 1982 by Afrika Bambaataa ('Planet Rock') and Cybotron, merging Kraftwerk's electronic minimalism with funk rhythms and the Roland TR-808.", "zh": "由 Afrika Bambaataa 与 Cybotron 于 1982 年开创，将 Kraftwerk 的极简电子律动与放克节拍和 Roland TR-808 完美结合。"},
   "soundDesign": {"en": "Robotic vocoder vocals, Roland TR-808 syncopated drum breaks, laser zaps, analog saw synths.", "zh": "机器人声码器人声、Roland TR-808 切分鼓点、激光音效与模拟锯齿波合成器。"},
   "rhythmFeatures": {"en": "Syncopated, mechanical breakbeats powered by TR-808 kick patterns and crisp handclaps on 2 and 4.", "zh": "切分机械的碎拍，由 TR-808 底鼓与在 2、4 拍击打的清脆拍手驱动。"},
   "bassPattern": {"en": "Bouncy, syncopated analog synth basslines playing futuristic funk riffs.", "zh": "富有弹跳感的切分模拟合成贝斯线条，演奏未来主义放克 Riff。"},
   "productionTips": {"en": ["Use genuine TR-808 drum samples with accent nuances on the hi-hats and snares", "Run lead vocals through a hardware vocoder fed by a sawtooth carrier synth", "Keep drum sounds completely dry for authentic early-80s punch"], "zh": ["使用纯正 TR-808 鼓组采样并保留踩镲与军鼓的重音力度差异", "将人声送入以锯齿波为载波的硬件声码器中", "保持鼓组音色干燥无混响还原 80 年代初扎实质感"]}},

  {"id": "breakbeat", "name": "Breakbeat", "aliases": ["碎拍乐"], "category": "Electronic", "year": "1990", "bpm": "125–135 BPM", "default_bpm": 130, "style": "breakbeat", "place": {"en": "UK & USA", "zh": "英国与美国"},
   "artists": ["The Crystal Method", "Freestylers", "Plump DJs", "Stanton Warriors", "Krafty Kuts"],
   "context": {"en": "Evolved from funk drum breaks into an energetic 4/4 non-four-on-the-floor dance music style featuring rolling basslines and dancefloor party grooves.", "zh": "脱胎于放克鼓循环，发展为充满能量的非直板四踩四电子舞曲，以连绵滚动的贝斯与派对律动著称。"},
   "soundDesign": {"en": "Punchy syncopated acoustic drum chops, heavy sub-bass, acid squeals, vinyl scratches.", "zh": "清脆切分的原声鼓切片、厚重超低音、酸性啸叫与黑胶搓碟声。"},
   "rhythmFeatures": {"en": "Driving syncopated drum break with kick on 1, snare on 2 and 4, and offbeat secondary kicks.", "zh": "充满推进力的切分鼓循环，第 1 拍底鼓，2、4 拍军鼓，并穿插反拍跳跃底鼓。"},
   "bassPattern": {"en": "Heavy rolling Reese or acid basslines locking tightly into the syncopated drum breaks.", "zh": "厚重滚动的 Reese 或酸性低音线条，与切分碎拍紧密贴合。"},
   "productionTips": {"en": ["Layer processed acoustic drum breaks with modern punchy synthesized kicks and snares", "Add shuffle swing around 55% to the hi-hats", "Use dynamic sidechain on the bass to duck whenever the broken kick hits"], "zh": ["将处理过的原声碎拍与现代高冲击力合成底鼓和军鼓叠层", "为踩镲注入 55% 左右的摇摆度", "在每个切分底鼓敲击瞬间对贝斯做动态侧链闪避"]}},

  {"id": "big-beat", "name": "Big Beat", "aliases": ["大碎拍"], "category": "Electronic", "year": "1995", "bpm": "120–135 BPM", "default_bpm": 128, "style": "breakbeat", "place": {"en": "London & Brighton, UK", "zh": "英国伦敦与布莱顿"},
   "artists": ["The Prodigy", "The Chemical Brothers", "Fatboy Slim", "Propellerheads", "Crystal Method"],
   "context": {"en": "Pioneered in mid-90s UK by Fatboy Slim and The Chemical Brothers, marrying heavy, distorted rock-like drum breaks with aggressive guitar riffs and acid synths.", "zh": "90 年代中叶由 Fatboy Slim 与 The Chemical Brothers 等开创，将粗重失真如摇滚般的鼓循环与狂暴吉他 Riff 和酸性合成器联姻。"},
   "soundDesign": {"en": "Heavy distorted acoustic drum breaks, fuzz guitars, TB-303 acid sweeps, brass samples.", "zh": "重度失真原声鼓循环、法兹过载吉他、TB-303 酸性扫频与铜管采样。"},
   "rhythmFeatures": {"en": "Mid-tempo, massively compressed drum loops with thunderous snare clacks and syncopated kicks.", "zh": "中速大动态压缩的狂暴鼓循环，带有雷霆万钧的军鼓与切分底鼓。"},
   "bassPattern": {"en": "Abrasive, buzzing fuzz bass or distorted acid lines driving infectious party energy.", "zh": "粗砺蜂鸣的法兹贝斯或失真酸性线条，驱动派对狂欢能量。"},
   "productionTips": {"en": ["Compress drum loops heavily using an analog limiter until the room tone pumps audibly", "Layer distorted rock guitar power chords over electronic synthesizers", "Drop unexpected vocal and horn samples right before main drops"], "zh": ["使用模拟限制器极度重压鼓循环，使房间混响产生明显抽吸", "在电子合成器上方叠加失真摇滚吉他强力和弦", "在主爆发前插入出其不意的人声或号角切片"]}}
]

save_module("trap_drill.ts", "TRAP_DRILL_GENRES", trap_drill_list)
save_module("future_downtempo.ts", "FUTURE_DOWNTEMPO_GENRES", future_downtempo_list)
save_module("hard_electro.ts", "HARD_ELECTRO_GENRES", hard_electro_list)
print("Completed Batch 3: Trap/Drill (8), Future/Downtempo (13), Hard/Electro (12) = 33 genres!")
