#!/usr/bin/env node
/**
 * Single source of truth for the app version (E-05).
 *
 * `package.json#version` is the ONE place a human edits.
 * Everything else is derived:
 *   - src/version.ts          (APP_VERSION constant)
 *   - public/version.json     (top-level `version` + `releaseDate`)
 *   - public/sw.js            (CACHE_VERSION)
 *
 *   node scripts/version.mjs sync    # rewrite derived files from package.json
 *   node scripts/version.mjs check   # verify they are in sync (CI / red line)
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const pkgPath = path.join(ROOT, "package.json");
const versionTsPath = path.join(ROOT, "src/version.ts");
const versionJsonPath = path.join(ROOT, "public/version.json");
const changelogJsonPath = path.join(ROOT, "public/changelog.json");
const swPath = path.join(ROOT, "public/sw.js");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const version = pkg.version;
if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`\u274c package.json version is not semver: ${version}`);
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);

const desiredTs = `/**
 * AUTO-GENERATED by scripts/version.mjs \u2014 do not edit by hand.
 * Source of truth: package.json#version
 */
export const APP_VERSION = "${version}";
export const BUILD_DATE = "${today}";
`;

function desiredSw(current) {
  const re = /const CACHE_VERSION = "[^"]*";/;
  if (!re.test(current)) {
    console.error("\u274c Could not locate CACHE_VERSION in public/sw.js");
    process.exit(1);
  }
  return current.replace(re, `const CACHE_VERSION = "groove-v${version}";`);
}

/**
 * Caps a release entry so `version.json` can never outgrow its 8 KB budget (red line R7a).
 *
 * `version.json` exists to answer "is there a newer build?" cheaply; the full release text
 * belongs in `changelog.json`, which the history panel fetches on demand. Writing the whole
 * newest entry into the small file made the budget a function of how verbose one release's
 * notes happened to be — it tripped twice. A summary plus a `truncated` flag keeps the
 * check payload bounded no matter how detailed the notes are, and the panel still shows the
 * complete text because it prefers the archive.
 */
const LATEST_MAX_HIGHLIGHTS = 3;
const LATEST_MAX_CHARS = 480;

function clip(text) {
  if (typeof text !== "string" || text.length <= LATEST_MAX_CHARS) return text;
  return `${text.slice(0, LATEST_MAX_CHARS - 1).trimEnd()}\u2026`;
}

function condenseLatest(entry) {
  if (!entry) return null;
  const all = Array.isArray(entry.highlights) ? entry.highlights : [];
  return {
    ...entry,
    highlights: all.slice(0, LATEST_MAX_HIGHLIGHTS).map((h) => ({ zh: clip(h.zh), en: clip(h.en) })),
    /** True when the archive holds more than this summary — the panel fetches it anyway. */
    truncated: all.length > LATEST_MAX_HIGHLIGHTS,
  };
}

/**
 * A-08: the update CHECK only needs the current version, so `version.json` stays
 * tiny. The full (and ever-growing) bilingual changelog lives in `changelog.json`
 * and is fetched only when the user actually opens the history.
 */
function splitVersionFiles(currentVersionJson, currentChangelogJson) {
  const data = JSON.parse(currentVersionJson);

  // The archive lives in changelog.json. Older layouts kept it inside version.json,
  // so accept both — but NEVER let a sync wipe the archive just because the small
  // file no longer carries it.
  let changelog = [];
  if (currentChangelogJson) {
    try {
      const parsed = JSON.parse(currentChangelogJson);
      if (Array.isArray(parsed?.changelog)) changelog = parsed.changelog;
    } catch {
      /* fall through to version.json */
    }
  }
  if (changelog.length === 0 && Array.isArray(data.changelog)) {
    changelog = data.changelog;
  }
  /**
   * Keep the **newest ten** entries.
   *
   * The history panel is for "what changed lately", and a file that grows forever stops being readable long before
   * it stops being fetched. Ten is the owner's call (2026-09-24) and this is where it is enforced, so a release
   * cannot quietly grow the archive back: `version:sync` is part of `npm run verify`, and a test holds the file at
   * the limit. The full history lives in git, which is what git is for.
   */
  const CHANGELOG_KEEP = 10;
  const trimmed = changelog.slice(0, CHANGELOG_KEEP);
  const latest = condenseLatest(trimmed.find((e) => e.version === version) || trimmed[0] || null);

  /**
   * The release date belongs to the *version*, not to the calendar.
   *
   * `releaseDate: today` made `version:check` fail every day after the artifact was written — CI's first step was
   * red on a tree nobody had touched, purely because the date had rolled over (the branch was pushed on the 23rd
   * against a file written on the 22nd, and `npm run verify` failed at `version:check`). Reusing the committed date
   * while the version is unchanged keeps the date meaningful (it is when the version was cut) and keeps the check
   * about the single source of truth rather than about the hour.
   */
  const releaseDate = data?.version === version && typeof data?.releaseDate === "string" ? data.releaseDate : today;
  const small = {
    version,
    releaseDate,
    changelogCount: trimmed.length,
    latest,
  };
  const full = { version, changelog: trimmed };

  return {
    versionJson: `${JSON.stringify(small, null, 2)}\n`,
    changelogJson: `${JSON.stringify(full)}
`,
  };
}

const currentTs = fs.existsSync(versionTsPath) ? fs.readFileSync(versionTsPath, "utf8") : "";
const currentSw = fs.readFileSync(swPath, "utf8");
const currentJson = fs.readFileSync(versionJsonPath, "utf8");
const currentChangelog = fs.existsSync(changelogJsonPath) ? fs.readFileSync(changelogJsonPath, "utf8") : "";

const split = splitVersionFiles(currentJson, currentChangelog);

/**
 * E-09: the planning documents state the current version in their headers, and
 * `scripts/check_docs.mjs` fails when they drift. Rather than hand-editing them on every release,
 * `sync` rewrites those specific header claims.
 *
 * The old `IMPROVEMENT_PLAN.md` header also carried a src file/line count, and a `measureSourceSize()`
 * kept it fresh. Both went with the document when the repository was prepared for open source: the
 * count described 194 files and had drifted ~40 %, `docs:check` owns no such claim any more, and a
 * stale count is worse than no count.
 */

const DOC_VERSION_PATTERNS = [
  { file: "ROADMAP_V2.md", re: /\*\*当前基线\*\*：v\d+\.\d+\.\d+/, replacement: () => `**当前基线**：v${version}` },
  { file: "BACKLOG.md", re: /当前基线：\*\*v\d+\.\d+\.\d+\*\*/, replacement: () => `当前基线：**v${version}**` },
];

// Group by file first: several patterns target the same document, and computing each
// "desired" content independently from the original text meant the later write silently
// reverted the earlier fix (observed when several patterns targeted one document, whose
// header then claimed the previous version). Apply every pattern to one shared buffer.
const patternsByFile = new Map();
for (const entry of DOC_VERSION_PATTERNS) {
  if (!patternsByFile.has(entry.file)) patternsByFile.set(entry.file, []);
  patternsByFile.get(entry.file).push(entry);
}

const docTargets = [...patternsByFile.entries()].map(([file, patterns]) => {
  const abs = path.join(ROOT, file);
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : "";
  let desired = current;
  for (const { re, replacement } of patterns) {
    if (re.test(desired)) desired = desired.replace(re, replacement(desired));
  }
  return { label: file, path: abs, current, desired };
});

const targets = [
  { label: "src/version.ts", path: versionTsPath, desired: desiredTs, current: currentTs },
  { label: "public/sw.js", path: swPath, desired: desiredSw(currentSw), current: currentSw },
  { label: "public/version.json", path: versionJsonPath, desired: split.versionJson, current: currentJson },
  { label: "public/changelog.json", path: changelogJsonPath, desired: split.changelogJson, current: currentChangelog },
  ...docTargets,
];

const mode = process.argv[2] ?? "check";

if (mode === "sync") {
  let changed = 0;
  for (const t of targets) {
    if (t.desired !== t.current) {
      fs.writeFileSync(t.path, t.desired);
      console.log(`\u270f\ufe0f  ${t.label} \u2192 v${version}`);
      changed += 1;
    }
  }
  console.log(changed === 0 ? `\u2705 Already in sync with v${version}` : `\u2705 Synced ${changed} file(s) to v${version}`);
  process.exit(0);
}

const drifted = targets.filter((t) => t.desired !== t.current);
// src/version.ts only carries the version; BUILD_DATE differences are expected on check.
const hardDrift = drifted.filter((t) => {
  if (t.label !== "src/version.ts") return true;
  return !new RegExp(`APP_VERSION = "${version}";`).test(t.current);
});

if (hardDrift.length > 0) {
  console.error("\u274c Version drift detected (run `npm run version:sync`):");
  for (const t of hardDrift) console.error(`   - ${t.label}`);
  process.exit(1);
}
console.log(`\u2705 Version single-source in sync: v${version}`);
