#!/usr/bin/env node
/**
 * Single source of truth for the app version (E-05).
 *
 * `package.json#version` is the ONE place a human edits.
 * Everything else is derived:
 *   - src/version.ts          (APP_VERSION constant)
 *   - public/version.json     (top-level `version` + `releaseDate`)
 *   - public/sw.js            (CACHE_VERSION)
 *
 *   node scripts/version.mjs sync    # rewrite derived files from package.json
 *   node scripts/version.mjs check   # verify they are in sync (CI / red line)
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const pkgPath = path.join(ROOT, "package.json");
const versionTsPath = path.join(ROOT, "src/version.ts");
const versionJsonPath = path.join(ROOT, "public/version.json");
const swPath = path.join(ROOT, "public/sw.js");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const version = pkg.version;
if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`\u274c package.json version is not semver: ${version}`);
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);

const desiredTs = `/**
 * AUTO-GENERATED by scripts/version.mjs \u2014 do not edit by hand.
 * Source of truth: package.json#version
 */
export const APP_VERSION = "${version}";
export const BUILD_DATE = "${today}";
`;

function desiredSw(current) {
  const re = /const CACHE_VERSION = "[^"]*";/;
  if (!re.test(current)) {
    console.error("\u274c Could not locate CACHE_VERSION in public/sw.js");
    process.exit(1);
  }
  return current.replace(re, `const CACHE_VERSION = "groove-v${version}";`);
}

function desiredVersionJson(current) {
  const data = JSON.parse(current);
  data.version = version;
  data.releaseDate = today;
  return `${JSON.stringify(data, null, 2)}\n`;
}

const currentTs = fs.existsSync(versionTsPath) ? fs.readFileSync(versionTsPath, "utf8") : "";
const currentSw = fs.readFileSync(swPath, "utf8");
const currentJson = fs.readFileSync(versionJsonPath, "utf8");

const targets = [
  { label: "src/version.ts", path: versionTsPath, desired: desiredTs, current: currentTs },
  { label: "public/sw.js", path: swPath, desired: desiredSw(currentSw), current: currentSw },
  { label: "public/version.json", path: versionJsonPath, desired: desiredVersionJson(currentJson), current: currentJson },
];

const mode = process.argv[2] ?? "check";

if (mode === "sync") {
  let changed = 0;
  for (const t of targets) {
    if (t.desired !== t.current) {
      fs.writeFileSync(t.path, t.desired);
      console.log(`\u270f\ufe0f  ${t.label} \u2192 v${version}`);
      changed += 1;
    }
  }
  console.log(changed === 0 ? `\u2705 Already in sync with v${version}` : `\u2705 Synced ${changed} file(s) to v${version}`);
  process.exit(0);
}

const drifted = targets.filter((t) => t.desired !== t.current);
// src/version.ts only carries the version; BUILD_DATE differences are expected on check.
const hardDrift = drifted.filter((t) => {
  if (t.label !== "src/version.ts") return true;
  return !new RegExp(`APP_VERSION = "${version}";`).test(t.current);
});

if (hardDrift.length > 0) {
  console.error("\u274c Version drift detected (run `npm run version:sync`):");
  for (const t of hardDrift) console.error(`   - ${t.label}`);
  process.exit(1);
}
console.log(`\u2705 Version single-source in sync: v${version}`);
