#!/usr/bin/env python3
"""Batch data for the groove genre-cover run.

GENRES maps genre-id -> (subject, character).
`subject` is a concrete imageable noun phrase substituted into the per-skin
prompt template from ART_DIRECTION.md; `character` is an adjective phrase.
Neither contains text/logos/real people (see ART_DIRECTION.md section 0).
"""

GENRES = {
    # --- A ---
    "2-step-garage": ("a car door left open on a rain-slick South London street at 3am, interior light on", "skipping shuffled drums, clipped vocal chops, midnight tension"),
    "acid-house": ("a silver analogue bass synthesizer with its knobs turned to extremes, lit by a single strobe", "squelching resonant bassline, relentless machine pulse"),
    "acid-jazz": ("a saxophone and a Fender Rhodes sharing a cramped club stage, one bare bulb overhead", "live funk drums, walking bass, sharp brass stabs"),
    "acid-techno": ("a bank of modular synthesizers patched with cables, spiralling fluorescent light above", "corrosive rolling bassline, hypnotic 303 repetition"),
    "afrobeat": ("a wall of conga drums and a horn section on a sunlit open-air stage", "interlocking polyrhythm, long hypnotic horn vamps"),
    "afro-house": ("a dusty djembe beside a turntable on a red-earth terrace at dusk", "rolling organic percussion, warm deep bass, communal trance"),
    "alternative-rnb": ("a microphone on a stand in an empty concrete rehearsal room, cold window light", "hazy spacious chords, breathy intimate vocals, sparse beats"),
    "alternative-rock": ("a battered guitar amp and a scuffed pedalboard in a graffiti-free underpass", "distorted riffs, restless dynamics, brooding restraint"),
    "amapiano": ("a lone log drum on a linoleum floor with a glass of whisky beside it", "airy log-drum bass, jazzy piano, laid-back groove"),
    "ambient": ("a wide empty hall filled with slow-drifting fog and one distant window", "slow evolving pads, no pulse, weightless drift"),
    "ambient-dub": ("a reel of tape and a spring reverb tank submerged in dark water", "cavernous delay, submerged bass, ghostly echoes"),
    "ambient-techno": ("a lone sphere of pulsing light suspended in a vast concrete hall", "pulsing hypnotic pads, deep soft kick, meditative motion"),
    # --- B ---
    "bachata": ("a nylon-string guitar resting on a wooden chair beside an open window at night", "romantic syncopated guitar, close warm rhythm"),
    "bass-house": ("a subwoofer cone caught mid-throw in a dark club, dust leaping off it", "heavy filtered bassline, chunky four-to-the-floor"),
    "bassline": ("a bass guitar leaning against a wet brick wall under a sodium lamp", "warping wobble bass, garage swing, northern grit"),
    "bebop": ("a trumpet and a drum kit jammed into a tiny basement club, smoke in the air", "fast angular improvisation, ride cymbal chatter"),
    "big-beat": ("a stack of vintage drum machines and a breakbeat record on a concrete floor", "block-rocking breakbeats, fat analogue bass"),
    "black-metal": ("a frost-covered pine forest under a moonless sky, one distant ridge", "tremolo riffs, blast beats, freezing atmosphere"),
    "blues-rock": ("a worn electric guitar propped on a road case in a dim club corner", "heavy blues riffing, overdriven swagger"),
    "boom-bap": ("a turntable and a crate of vinyl records on a graffiti-free subway platform", "dusty sampled loops, punchy swung drums"),
    "bossa-nova": ("a nylon-string guitar on a balcony overlooking a calm morning bay", "soft syncopated guitar, murmured melody, gentle swing"),
    "breakbeat": ("a drummer's snare and a sampler on a warehouse floor, strobe frozen mid-flash", "chopped amen drums, rolling funky breaks"),
    "breakcore": ("a shattered drum machine exploding into flying circuit fragments", "frantic broken drums, overloaded distortion, chaos"),
    "brooklyn-drill": ("a low-lit corner store awning and a parked car on a Brooklyn block at night", "sliding 808 bass, dark minor keys, menacing stride"),
    "brostep": ("a monstrous speaker stack in an arena, rippling with visible energy", "aggressive metallic bass growls, half-time crunch"),
    "chicago-blues": ("a battered hollow-body guitar and a harp on a bar stool in a smoky room", "raw electric slide, shuffling live band"),
    "chicago-drill": ("a chain-link fence and a bare streetlight on a cold Midwestern block", "grim piano loops, sliding bass, cold menace"),
    "chicago-house": ("a drum machine and a jacking bassline on a warehouse floor, disco ball above", "raw jacking drums, soulful vocal loops"),
    "chillstep": ("a rain-streaked window with headphones and a mug on the sill at night", "soft half-time beats, lush reverb, calm melancholy"),
    "chillwave": ("a sun-bleached cassette deck and sunglasses on a faded beach towel", "hazy washed synths, slow nostalgic drift"),
    "chiptune": ("an arcade cabinet on a moonlit hill with pixel waveform towers behind", "square-wave melody, 8-bit pulse, nostalgic adventure"),
    "city-pop": ("a convertible parked on a Tokyo waterfront at sunset, skyline glowing", "glossy FM synths, bright chorus guitar, breezy optimism"),
    "cloud-rap": ("a bedroom ceiling with glow-in-the-dark stars and a phone face-down on the floor", "hazy ethereal pads, mumbled melody, weightless drift"),
    "conscious-hip-hop": ("a microphone and a notebook on a community-centre table under fluorescent light", "soulful sampled loops, dense articulate delivery"),
    "contemporary-rnb": ("silk sheets and a studio microphone in a dark room lit by one neon strip", "smooth sparse beats, airy layered vocals"),
    "cool-jazz": ("a brushed snare and an upright bass in a dim after-hours club", "relaxed swinging restraint, muted brass"),
    "cumbia": ("an accordion and a guiro on a dance floor strung with paper flags", "lilting dance rhythm, warm accordion melody"),
    "dancehall": ("a towering speaker box painted in bright colours on a dusty street corner", "heavy digital riddim, patois chant, bouncing bass"),
    "death-metal": ("a wall of stacked amplifier cabinets glowing red in a dark room", "down-tuned blast riffs, guttural roar, brutal weight"),
    "deathstep": ("a shattered amplifier core venting black smoke and sparks", "crushing distorted bass, machine-gun drums, terror"),
    # --- C ---
    "deep-house": ("a submerged grand piano in a dark flooded room, light from above", "warm deep chords, gentle four-to-the-floor, soulful hush"),
    "delta-blues": ("a battered resonator guitar on a porch step beside a dirt road", "raw slide guitar, dusty stomp, lonesome grit"),
    "detroit-techno": ("a rusted factory assembly line reimagined as a drum machine", "futuristic machine funk, stark syncopation"),
    "disco": ("a mirrored ball casting light across a polished dance floor", "lush strings, four-to-the-floor groove, euphoric lift"),
    "doom-metal": ("a colossal stone slab crushing a broken amplifier, embers falling", "glacial down-tuned riffs, immense oppressive weight"),
    "downtempo": ("a low sofa and a turntable in a warm dim lounge, curtains half drawn", "slow smoky beats, languid bass, relaxed haze"),
    "dream-trance": ("a stairway of light rising into a violet cloudscape", "soaring euphoric pads, shimmering arpeggios, blissful lift"),
    "drift-phonk": ("a low car sliding through tyre smoke on a midnight overpass", "warped 808 cowbells, sliding bass, hypnotic drift"),
    "dub": ("a mixing desk with tape delay and spring reverb in a dark studio", "cavernous echo, dropped bass, spacious rhythm"),
    "dubstep": ("a lone subwoofer pulsing in a dark warehouse, floor rippling", "deep sub bass, half-time swing, tense space"),
    "dub-techno": ("a chord stab dissolving into ripples across a black pool", "echoing chords, rolling bass, hypnotic space"),
    "east-coast-hip-hop": ("a boombox on a brownstone stoop beside a fire hydrant", "dusty drum breaks, jazzy samples, confident flow"),
    "edm-trap": ("a festival main stage of lights at night, confetti frozen mid-air", "festival drops, hybrid trap drums, huge builds"),
    "electric-blues": ("a sunburst electric guitar plugged into a small tweed amp", "raw overdriven lead, shuffling live band"),
    "electro": ("a robot arm and a drum machine on a neon-lit factory floor", "crisp 808 drums, vocoder funk, machine precision"),
    "electro-house": ("a strobe-lit crowd of raised hands seen from the stage", "filtered synth stabs, driving four-to-the-floor"),
    "emo-rap": ("a gravestone-shaped guitar leaning on a bedroom wall, fairy lights", "melancholy guitar loops, distorted 808, raw ache"),
    "eurodance": ("a pyramid of coloured light beams over a packed 90s dance floor", "pumping synth stabs, euphoric female hook"),
    "euro-trance": ("a hand reaching toward a sunrise above a sea of clouds", "rolling bassline, soaring supersaw melody, euphoria"),
    "footwork": ("a pair of worn dance shoes blurred on a linoleum floor", "frantic chopped breaks, rapid-fire vocal stabs"),
    "free-jazz": ("a drum kit, saxophone and double bass scattered mid-performance", "unfettered collective improvisation, restless energy"),
    "frenchcore": ("a distorted kick drum smashing through a wall of speakers", "hyper-speed distorted kick, manic intensity"),
    "french-house": ("a filter knob turned all the way up on a glowing mixer", "filtered disco loops, pumping groove, French touch"),
    "funk": ("a giant hand slapping a bass guitar that bends like rubber", "slap bass, tight horn stabs, irresistible pocket"),
    "future-bass": ("a cloud of glowing geometric shards bursting above a dark stage", "pitched vocal chops, lush supersaws, emotional drop"),
    "future-garage": ("a rain-soaked pavement reflecting violet club light", "chopped vocals, shuffled garage drums, deep sub"),
    "future-house": ("a chrome torus rotating above a dark dance floor", "bright arpeggios, punchy house groove, glossy future"),
    "g-funk": ("a lowrider car with its hydraulic stance on a sunlit boulevard", "whining lead synth, deep funk groove, laid-back swagger"),
    "ghetto-house": ("a bare bulb swinging over a stripped concrete dance floor", "raw fast jacking drums, crude bass, sweat"),
    "glitch-hop": ("a record player shattering into stop-motion fragments mid-spin", "stuttering glitched drums, wonky bass, playful chaos"),
    "goa-trance": ("a fluorescent fractal tunnel spiralling into a desert night", "rolling acid bassline, psychedelic arpeggios, trance"),
    "grime": ("a tower block stairwell lit by a single cold fluorescent tube", "sparse icy synths, skittering 140 drums, cold menace"),
    "grunge": ("a battered guitar and a flannel shirt on a rehearsal room floor", "sludgy distorted riffs, raw dynamics, apathy"),
    "gypsy-jazz": ("a violin and a Selmer guitar on a café table, chairs pushed back", "fast swung acoustic runs, hot club swing"),
    "halftime": ("a colossal slow-motion wave frozen above a dark city", "half-time drums, cavernous bass, suspended tension"),
    "happy-hardcore": ("a rainbow of strobe beams over a bouncing crowd, hands up", "pounding kick, euphoric hoover stabs, giddy speed"),
    "hard-bop": ("a quintet's horns and drums crowded on a small bandstand", "driving swinging horns, bluesy virtuoso solos"),
    "hardcore-gabber": ("a fist raised in front of a thunderous distorted speaker wall", "relentless distorted kick, furious tempo, rage"),
    "hard-rock": ("a stack of Marshall cabinets with a Les Paul leaning against them", "heavy riffing, screaming lead, stadium power"),
    "hardstyle": ("a colossal red wedge of sound over a roaring stadium crowd", "screeching reverse bass, euphoric kicks, defiance"),
    "hard-techno": ("a black steel piston slamming down onto a concrete floor", "brutal pounding kick, industrial percussion, force"),
    "hard-trance": ("a laser fan sweeping over a dark arena of raised arms", "fast rolling bass, searing lead, relentless euphoria"),
    "hard-trap": ("a wall of subwoofers flexing in a fog-filled arena", "distorted 808s, aggressive horns, heavy drops"),
    "heavy-metal": ("a massive steel speaker cabinet with a glowing grille and riveted seams", "chugging riffs, double-kick drive, heavy power"),
    "hybrid-trap": ("a shattered orchestral timpani bleeding into an 808 drum machine", "orchestral stabs, trap drums, cinematic drops"),
    "idm": ("a lattice of clockwork gears and circuit boards mid-motion", "intricate broken beats, warm analogue melody"),
    "industrial-techno": ("a rusted turbine hall with pipes and steel grating under harsh light", "pounding machine rhythm, metallic clang, cold force"),
    "jazz-fusion": ("an electric piano and a fretless bass on a studio floor, cables everywhere", "virtuosic solos, syncopated funk, electric colour"),
    "jersey-club": ("a concrete stairwell with a phone flashlight raking the wall", "fast chopped breaks, bed-squeak samples, frantic energy"),
    "jersey-drill": ("a corner store shutter and a parked bike on a rain-dark street", "sliding bass, dark piano, cold street menace"),
    "j-pop": ("a pastel stage of glowing panels with confetti mid-fall", "bright maximal melody, glossy synths, joyful energy"),
    "jump-up": ("a coiled spring of bass energy launching off a dark stage", "wobbling mid-range bass, dancefloor punch"),
    "jungle": ("a pair of turntables and a stack of rave flyers in a dark warehouse", "chopped amen breaks, deep sub bass, rave energy"),
    "kawaii-future-bass": ("a pastel candy-coloured cloud with pixel hearts floating in it", "sugary chopped vocals, bright supersaws, playful"),
    "k-pop": ("a polished stage of mirrored panels and coloured spotlights", "tight maximal production, catchy hooks, precision"),
    "kuduro": ("a battered plastic speaker on a sunlit dirt street, dust in the air", "fast frantic percussion, shout-along energy"),
    "liquid-dnb": ("rain-slick neon street reflected in a puddle, a lone passing car", "smooth rolling breaks, warm sub bass, soulful haze"),
    "lofi-hip-hop": ("a bedroom desk with a cassette deck and a rain-streaked window", "dusty warm loops, soft swung drums, calm"),
    "lofi-house": ("a worn sofa and a warm lamp beside a turntable in a small room", "soft filtered chords, gentle groove, cosy haze"),
    "math-rock": ("a guitar with an unusual tuning chart scrawled nowhere, tangled pedals", "jagged odd-time riffs, precise interlocking parts"),
    "melodic-dubstep": ("a glowing wireframe heart pulsing in a dark void", "emotional melodic lead, deep bass, half-time"),
    "melodic-house": ("a grand piano in a dark room flooded with soft aurora light", "warm piano chords, rolling groove, emotional lift"),
    "metalcore": ("a shattered concrete wall with steel rebar bursting outward", "breakdown riffs, twin-guitar melody, raw scream"),
    "microhouse": ("a single tiny click and a hairline crack across a pristine surface", "minimal clicks, micro-samples, subtle swing"),
    "minimal-techno": ("a single industrial click on an otherwise empty grid of dots", "sparse clicks, hypnotic pulse, extreme reduction"),
    "modal-jazz": ("a piano trio's instruments arranged in a bare rehearsal hall", "modal vamps, spacious solos, contemplative swing"),
    "moombahton": ("a slow-motion tidal wave of bass over a tropical dance floor", "dem-bow rhythm, slow heavy bass, sweltering"),
    "motown": ("a vintage tambourine and a bass guitar on a studio floor with a single mic", "bright punchy horns, walking bass, joyful soul"),
    "neo-soul": ("a Fender Rhodes and a lit candle in a warm dim room", "lush chords, laid-back pocket, intimate warmth"),
    "neurofunk": ("a chrome insectile machine flexing its mandibles in the dark", "surgical distorted bass, rolling breaks, precision"),
    "new-wave": ("a skinny-tie silhouette against a wall of cold neon", "cold synth hooks, angular guitar, detached cool"),
    "nu-disco-house": ("a glittering mirror ball over a warm polished dance floor", "filtered disco samples, live bass, joyful groove"),
    # --- O ---
    "old-school-hip-hop": ("a turntable and a painted boombox on a cardboard mat", "punchy drum breaks, scratch hooks, block-party energy"),
    "peak-time-techno": ("a monolithic dark speaker tower pulsing under a single white beam", "driving relentless kick, hypnotic tension, peak energy"),
    "phonk": ("a low car with hazy purple headlights on a foggy night road", "warped cowbell loops, distorted 808, smoked-out drift"),
    "post-dubstep": ("a hollow bass chamber with light leaking through its seams", "sparse bass weight, clipped vocal fragments, space"),
    "post-punk": ("a bare rehearsal room with a bass guitar and a cold strip light", "angular basslines, sharp guitar, cold urgency"),
    "progressive-house": ("a slow-building staircase of light ascending into darkness", "long evolving groove, layered melody, patient build"),
    "progressive-rock": ("an elaborate rack of effects pedals lit by a single spot", "long-form structure, technical playing, epic sweep"),
    "progressive-trance": ("a vast cosmic spiral turning slowly above a dark horizon", "evolving arpeggios, long build, hypnotic euphoria"),
    "psytrance": ("a kaleidoscopic fractal mandala breathing in a dark desert night", "rolling acid bassline, psychedelic leads, trance"),
    "punk-rock": ("a battered guitar slammed against a brick wall, dust flying", "fast power chords, shouted chorus, raw energy"),
    "ragga-jungle": ("a towering soundsystem stack on a dark dance floor, dust in the beam", "chopped breaks, patois chant, deep sub bass"),
    "raw-techno": ("a bare industrial hall with a single strobe and steel pillars", "stripped pounding drums, abrasive texture, force"),
    "reggae": ("a bass guitar leaning against a palm trunk beside a wooden shack", "deep rolling bassline, offbeat skank, warm sun"),
    "reggaeton": ("a slow-moving car with tinted windows on a hot neon street", "dem-bow beat, deep bass, swaggering heat"),
    "riddim": ("a single coiled spring of bass flexing on a dark stage", "minimal wobbling bass, repetitive hypnotic drop"),
    "rock-and-roll": ("a hollow-body guitar swung by its neck on a small stage, dust flying", "raw driving rhythm, rebellious swagger"),
    "salsa": ("a wall of congas, trumpets and a piano in a packed dance hall", "hot interlocking horns, driving clave, joy"),
    "samba": ("a circle of surdo drums and tambourines on a sunlit street", "rolling communal percussion, festive swing"),
    "sambass": ("a surdo drum fused with a drum machine on a rain-dark street", "fast samba percussion over drum-and-bass breaks"),
    "schranz": ("a hydraulic press slamming steel plate in a dark factory", "abrasive looped drums, relentless industrial pressure"),
    "shoe-gaze": ("a guitar engulfed in a wall of white noise and haze", "blissful distorted wash, buried melody, dreamy weight"),
    "smooth-jazz": ("a saxophone resting on a bar top beside a glass, warm low light", "polished mellow sax, soft groove, easy glide"),
    "soul": ("a vintage microphone and a Hammond organ in a warm wood-panelled room", "warm gospel chords, passionate vocal, deep groove"),
    "southern-hip-hop": ("a candy-painted car with its trunk open on a hot suburban street", "heavy 808 bass, chant hooks, slow swagger"),
    "speedbass": ("a bass cone vibrating so fast it blurs into a ring of light", "hyper-speed bass stabs, frantic rhythm"),
    "speed-garage": ("a garage roller door half-open on a rain-slick drive at night", "shuffled two-step drums, pitched vocal chops, dark bass"),
    "synth-pop": ("a rack of analogue synths glowing in a dark studio", "bright synth hooks, drum machine beat, melodic cool"),
    "synthwave": ("a chrome sports car driving toward a huge striped setting sun", "retro analogue arpeggios, gated drums, neon nostalgia"),
    "tearout-dubstep": ("a shredded metal speaker grille exploding outward", "ferocious distorted bass, aggressive drop, violence"),
    "tech-house": ("a gleaming minimal drum machine on a dark club podium", "rolling groovy bassline, crisp percussion, hypnotic"),
    "techstep": ("a dark corridor of steel doors lit by a single cold beam", "cold distorted bass, tight breaks, bleak tension"),
    "tech-trance": ("a churning turbine of light spinning above a dark arena", "driving rolling bass, melodic build, relentless lift"),
    "texas-blues": ("a battered Stratocaster on a wooden porch, dust on the boards", "sharp overdriven lead, shuffling roadhouse groove"),
    "thrash-metal": ("a wall of amplifiers mid-collapse with sparks in the air", "frantic downpicked riffs, rapid double kick, aggression"),
    "traditional-jazz": ("a banjo, clarinet and brass bass arrayed on a wooden bandstand", "collective polyphonic swing, bright brass"),
    "traditional-pop": ("a vintage microphone on a music stand under a warm spotlight", "melodic standards, lush arrangement, timeless warmth"),
    "trap-rap": ("a blacked-out car with its doors open on an empty night street", "booming 808s, rattling hi-hats, dark swagger"),
    "trip-hop": ("a smoky dim lounge with a turntable and a half-full glass", "slow dusty beats, brooding bass, cinematic haze"),
    "tropical-house": ("a thatched beach bar with a steel drum and string lights at dusk", "breezy steel melody, warm house groove, summer"),
    "uk-drill": ("a rain-dark housing estate with one lit stairwell window", "sliding 808 bass, dark melodic keys, cold threat"),
    "uk-funky": ("a bare community hall floor with a sole speaker and a glow stick", "warping bassline, broken percussion, raw energy"),
    "uk-garage": ("a garage forecourt at night with a shutter half down", "shuffled two-step, warm sub bass, slick vocal chops"),
    "uplifting-trance": ("a sunrise breaking above an ocean of glowing clouds", "soaring euphoric lead, rolling bass, pure lift"),
    "vaporwave": ("a marble bust beside an old television on a pastel pink grid floor", "slowed nostalgic samples, hazy reverb, faded memory"),
    "vocal-trance": ("a silhouetted figure with arms raised before a wall of light", "soaring female vocal, euphoric chords, rolling bass"),
    "wave": ("a monochrome city skyline dissolving into cold fog", "brooding minor synth melody, sparse trap drums, melancholy"),
    "west-coast-hip-hop": ("a lowrider parked under palm trees on a sunlit boulevard", "funky rolling bass, bright lead synth, laid-back"),
}

# Skin-scoped subject overrides. The per-skin medium changes, so a few subjects
# are re-aimed at what actually renders well in that direction.
SKIN_SUBJECT_OVERRIDE = {
    # minimal is a flat two-ink editorial system; photographic subjects must be
    # reduced to geometry or they fight the medium.
    "minimal": {
        "ambient": "a single large solid black disc behind one thin concentric ring, one blue hairline crossing it",
        "cool-jazz": "a stepped stack of solid black rectangular bars with one bar in ultramarine blue",
        "smooth-jazz": "three stacked black horizontal bars of unequal length, one blue dot at their edge",
        "modal-jazz": "a black square split by one diagonal, a blue hairline running off the edge",
        "bebop": "a dense cluster of black tick marks scattering from one blue arc",
        "free-jazz": "scattered black fragments bursting from a single blue line",
        "ambient-dub": "a large black circle overlapping a black bar, one blue hairline between them",
        "trip-hop": "a heavy black bar resting low in the frame under a thin blue line",
    },
    # sovietYears is flat red/black litho; a chiptune cabinet or a chrome car is wrong.
    "sovietYears": {
        "synthwave": "a monumental red sun disc cut by black parallel bands over a flat black horizon",
    },
    # comic wants loud heroic bodies and objects, not calm interiors.
    "comic": {
        "ambient": "a colossal black disc radiating speed lines across a cream field",
        "ambient-techno": "a huge glowing sphere bursting through a slab, action lines radiating",
        "chillstep": "a giant rain cloud bursting over a lone figure, hard black outlines",
    },
}

# Origin/history anchors (R5) live in a separate module for editability.
from _batch_origins_A import ORIGINS  # noqa: E402,F401
