/**
 * Reading a **Logic Pro project** — the third producer on the road the MusicXML and MIDI imports already share.
 *
 * A `.logicx` is a directory, and only two of its files carry music this model can hold:
 *
 *   Alternatives/NNN/ProjectData       the binary: tracks, regions, the notes inside them, tempo and meter
 *   Alternatives/NNN/MetaData.plist    the plain plist beside it
 *   Resources/ProjectInformation.plist which alternative `NNN` is the active one — **not** always `000`
 *
 * So the entry point takes **those files' bytes**, not a bundle: a `.logicx`'s `Media/` may hold gigabytes of audio
 * that Phase 1 cannot use, and MCP arguments are JSON, so the caller sends the two small files and says which
 * variant it read. `activeVariant` reads the third file.
 *
 * ## What is proven, and what is only what the specification says
 *
 * There is **no Mac and no Logic on this machine**, so there is **no ground truth**: nothing here has been opened in
 * Logic and compared. What the criteria below do prove is that this parses **what the byte-level specification and the
 * bytes themselves say** — the record framing, the note encoding, the tempo slot, the meter header — and that the
 * bytes of real community fixtures agree with those readings. "This parses what the specification says" is the whole
 * claim; "the import is correct" is not, and a green test here must not be read as one.
 *
 * The byte-level spec is `jonkubis/logicproformatwriter`'s `PROJECTDATA_FORMAT.md` (**MIT**). The parser is written
 * here in TypeScript rather than ported. The GPL-licensed analyser (`geoffmyers/logicx-analyzer`) was not copied.
 *
 * ## The honest boundaries, which reach `problems` by name
 *
 * Audio regions, AU plugin chains and automation have **no counterpart** in `TrackKindV2` — there is no audio kind,
 * no plugin graph and no automation lane — so they are **reported, never dropped quietly**. A Drummer/Session Player
 * track carries MIDI and does convert, but "this was generated by a model" is a fact the arrangement cannot hold, and
 * the import says so.
 */
import type { NoteEvent } from "../types/arrangementV2";
import type { ImportedPart } from "./musicxmlImport";

/** 960 ticks per quarter note, the resolution Logic writes into `ProjectData`. */
export const LOGIC_TICKS_PER_QUARTER = 960;

/** The ticks a region's placement is counted from: nine bars of 4/4 (the spec's region-origin). */
const REGION_ORIGIN_TICKS = 34560;

/** The ticks a note event's position is counted from (the spec's tempo/marker origin: region-origin + one bar). */
const NOTE_ORIGIN_TICKS = 38400;

export interface LogicProjectInput {
  /** `Alternatives/NNN/ProjectData`. */
  projectData: Uint8Array;
  /** `Alternatives/NNN/MetaData.plist` — XML or binary plist. */
  metaData: Uint8Array;
}

export interface LogicProjectImport {
  /** One per MIDI region this model can hold, named from the region. */
  parts: ImportedPart[];
  /**
   * Everything the project held that this model cannot, **in the words a person needs to act on it**: an audio track,
   * a plugin chain, an automation lane. An empty list means the project was MIDI-only.
   */
  problems: string[];
  /** The project tempo in beats per minute, when the project states one. */
  tempoBpm?: number;
  /** The initial meter as `"4/4"`, when the project states one. */
  timeSignature?: string;
}

export interface LogicProjectInfo {
  /** The alternative `ProjectInformation.plist` names as active, or `undefined` when it names none. */
  activeVariant?: string;
}

/* ------------------------------------------------------------------ *
 * The plist reader, both of the shapes Logic writes
 * ------------------------------------------------------------------ */

/** A parsed plist value, in the subset the two files use. */
type PlistValue = string | number | boolean | Date | Uint8Array | PlistValue[] | { [key: string]: PlistValue };

/**
 * `ProjectInformation.plist` is a **binary** plist and `MetaData.plist` may be either, and this runs in the browser
 * as well as in Node — where `Buffer` exists but a plist library does not. So the reader is here: the binary
 * container is small and fully specified, and the XML half is a lookup of `<key>`/value pairs rather than a DOM.
 */
export function parsePlist(bytes: Uint8Array): PlistValue {
  // The binary magic is ASCII `bplist`; an XML plist starts `<` (with an optional BOM).
  if (bytes.length >= 6 && bytes[0] === 0x62 && bytes[1] === 0x70 && bytes[2] === 0x6c && bytes[3] === 0x69) {
    return parseBinaryPlist(bytes);
  }
  const text = decodeUtf8(bytes);
  return parseXmlPlist(text);
}

function decodeUtf8(bytes: Uint8Array): string {
  if (typeof TextDecoder === "undefined") {
    // Older runtimes without TextDecoder: the plists here are ASCII in every field this reads.
    let out = "";
    for (const byte of bytes) out += String.fromCharCode(byte);
    return out;
  }
  return new TextDecoder("utf-8").decode(bytes);
}

/* --- binary plist --- */

interface BinaryPlistReader {
  bytes: Uint8Array;
  /** The offset-size table's width, in bytes. */
  offsetIntSize: number;
  /** How wide an object reference is, in bytes. */
  objectRefSize: number;
  offsets: number[];
}

/**
 * A big-endian unsigned integer of 1, 2, 4 or 8 bytes.
 *
 * The 8-byte case goes through `DataView` rather than repeating `value * 256 + byte`: that form is exact only up to
 * 2^53, and the multiply-and-add failure is silent — it yields a plausible, wrong number, which is worse than a
 * crash because the next read simply lands somewhere else in the file.
 */
function readUint(bytes: Uint8Array, offset: number, size: number): number {
  if (size === 8) {
    const view = new DataView(bytes.buffer, bytes.byteOffset + offset, 8);
    return view.getUint32(0, false) * 4294967296 + view.getUint32(4, false);
  }
  let value = 0;
  for (let index = 0; index < size; index += 1) value = value * 256 + bytes[offset + index]!;
  return value;
}

function parseBinaryPlist(bytes: Uint8Array): PlistValue {
  const trailer = bytes.length - 32;
  const offsetIntSize = bytes[trailer + 6]!;
  const objectRefSize = bytes[trailer + 7]!;
  const objectCount = readUint(bytes, trailer + 8, 8);
  const topObject = readUint(bytes, trailer + 16, 8);
  const offsetTableStart = readUint(bytes, trailer + 24, 8);
  const offsets: number[] = [];
  for (let index = 0; index < objectCount; index += 1) {
    offsets.push(readUint(bytes, offsetTableStart + index * offsetIntSize, offsetIntSize));
  }
  const reader: BinaryPlistReader = { bytes, offsetIntSize, objectRefSize, offsets };
  return readBinaryObject(reader, topObject);
}

function readBinaryObject(reader: BinaryPlistReader, index: number): PlistValue {
  const { bytes, offsets, objectRefSize } = reader;
  const start = offsets[index]!;
  const marker = bytes[start]!;
  const kind = marker >> 4;
  const info = marker & 0x0f;
  const body = start + 1;

  /** Lengths of 15 mean "the real length is in an integer object next". */
  const length = (): { length: number; start: number } => {
    if (info !== 0x0f) return { length: info, start: body };
    const sizeMarker = bytes[body]!;
    const sizeBytes = 1 << (sizeMarker & 0x0f);
    return { length: readUint(bytes, body + 1, sizeBytes), start: body + 1 + sizeBytes };
  };

  switch (kind) {
    case 0x0:
      if (info === 0x0) return false;
      if (info === 0x8) return true;
      return 0;
    case 0x1: {
      const size = 1 << info;
      return readUint(bytes, body, size);
    }
    case 0x2: {
      /**
       * A **real**, which is an IEEE-754 float and not an integer — `0x22` is a 4-byte big-endian float, `0x23` an
       * 8-byte one.
       *
       * Reading these as unsigned integers produces a plausible, wrong number, which is the worst kind: a real
       * `MetaData.plist` says `BeatsPerMinute = 120.0`, whose bytes read as the integer `1123024896`. That number
       * then reaches the caller as the project's tempo and, worse, makes the "MetaData and ProjectData disagree"
       * check fire on **every** project while never catching a real disagreement.
       *
       * A width that is neither 4 nor 8 is not a float this format defines; the big-endian read is kept as the
       * fallback so the shape still parses rather than returning a wrong kind of value.
       */
      const size = 1 << info;
      if (size === 4) return new DataView(bytes.buffer, bytes.byteOffset + body, 4).getFloat32(0, false);
      if (size === 8) return new DataView(bytes.buffer, bytes.byteOffset + body, 8).getFloat64(0, false);
      return readUint(bytes, body, size);
    }
    case 0x3: {
      if (info !== 0x3) return 0;
      // A date: seconds since 2001-01-01, stored as a float64 big-endian.
      const seconds = new DataView(bytes.buffer, bytes.byteOffset + body, 8).getFloat64(0, false);
      return new Date(Date.UTC(2001, 0, 1) + seconds * 1000);
    }
    case 0x4: {
      const { length: count, start: from } = length();
      return bytes.slice(from, from + count);
    }
    case 0x5: {
      const { length: count, start: from } = length();
      let out = "";
      for (let at = 0; at < count; at += 1) out += String.fromCharCode(bytes[from + at]!);
      return out;
    }
    case 0x6: {
      const { length: count, start: from } = length();
      let out = "";
      for (let at = 0; at < count; at += 1) out += String.fromCharCode(readUint(bytes, from + at * 2, 2));
      return out;
    }
    case 0xa: {
      const { length: count, start: from } = length();
      const items: PlistValue[] = [];
      for (let at = 0; at < count; at += 1) {
        items.push(readBinaryObject(reader, readUint(bytes, from + at * objectRefSize, objectRefSize)));
      }
      return items;
    }
    case 0xd: {
      const { length: count, start: from } = length();
      const out: { [key: string]: PlistValue } = {};
      for (let at = 0; at < count; at += 1) {
        const key = readBinaryObject(reader, readUint(bytes, from + at * objectRefSize, objectRefSize));
        const value = readBinaryObject(reader, readUint(bytes, from + count * objectRefSize + at * objectRefSize, objectRefSize));
        out[String(key)] = value;
      }
      return out;
    }
    default:
      return 0;
  }
}

/* --- XML plist --- */

const XML_ENTITIES: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'" };

function decodeXmlText(text: string): string {
  return text.replace(/&(#x?[0-9a-fA-F]+|amp|lt|gt|quot|apos);/g, (whole, entity: string) => {
    if (entity.startsWith("#x") || entity.startsWith("#X")) return String.fromCodePoint(parseInt(entity.slice(2), 16));
    if (entity.startsWith("#")) return String.fromCodePoint(parseInt(entity.slice(1), 10));
    return XML_ENTITIES[entity] ?? whole;
  });
}

/**
 * An XML plist read as **the keys this file needs**, not as a DOM: `<key>` names the next value, and only `string`,
 * `integer`, `real`, `true`/`false` and the two array/dict shapes matter. A shape this does not know is skipped
 * rather than guessed at, and a file that is not a plist at all yields `{}` so a missing tempo is a missing tempo.
 */
function parseXmlPlist(text: string): PlistValue {
  const out: { [key: string]: PlistValue } = {};
  const keyPattern = /<key>([\s\S]*?)<\/key>/g;
  const matches: { key: string; end: number }[] = [];
  for (let match = keyPattern.exec(text); match !== null; match = keyPattern.exec(text)) {
    matches.push({ key: decodeXmlText(match[1]!), end: match.index + match[0].length });
  }
  for (let index = 0; index < matches.length; index += 1) {
    const { key, end } = matches[index]!;
    const limit = index + 1 < matches.length ? matches[index + 1]!.end : text.length;
    const segment = text.slice(end, limit);
    const value = readXmlValue(segment);
    if (value !== undefined) out[key] = value;
  }
  return out;
}

function readXmlValue(segment: string): PlistValue | undefined {
  const open = /<(\w+)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/.exec(segment);
  if (open === null) return undefined;
  const tag = open[1]!;
  const inner = open[2]!;
  if (tag === "string") return decodeXmlText(inner);
  if (tag === "integer") return Number(decodeXmlText(inner).trim());
  if (tag === "real") return Number(decodeXmlText(inner).trim());
  if (tag === "true") return true;
  if (tag === "false") return false;
  if (tag === "data") return new Uint8Array(0);
  return undefined;
}

/* ------------------------------------------------------------------ *
 * Reading a value out of a plist without trusting its shape
 * ------------------------------------------------------------------ */

function asRecord(value: PlistValue): { [key: string]: PlistValue } | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value) && !(value instanceof Uint8Array) && !(value instanceof Date)
    ? (value as { [key: string]: PlistValue })
    : undefined;
}

function numberOf(value: PlistValue | undefined): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string" && value.trim() !== "" && Number.isFinite(Number(value))) return Number(value);
  return undefined;
}

/**
 * The alternative the project says is active.
 *
 * **This is the field that must not be assumed.** A project may hold several alternatives under `Alternatives/`, and
 * `004` is as ordinary as `000`; a reader that opens `Alternatives/000/ProjectData` because that is the first name it
 * saw can import a different arrangement than the one the project is on. `Resources/ProjectInformation.plist` names
 * the active one, and when it names none this answers `undefined` rather than inventing `"000"` — the caller decides
 * what to do about a project that does not say.
 *
 * **`VariantNames` is not a substitute**, and a real fixture is why: the Logic 10.0-era projects in the textbook set
 * carry a `VariantNames` table keyed by `"0"` and **no `ActiveVariant` at all**. The table is the list of variants the
 * project knows about; it does not say which one is open, and answering its only key would be `"000"` wearing a
 * different name. So the field is read and nothing else is.
 */
export function activeVariant(projectInformation: Uint8Array): string | undefined {
  const record = asRecord(parsePlist(projectInformation));
  if (record === undefined) return undefined;
  const direct = record["ActiveVariant"];
  if (direct === undefined) return undefined;
  const text = String(direct).trim();
  return text === "" ? undefined : text;
}

/* ------------------------------------------------------------------ *
 * The ProjectData record stream
 * ------------------------------------------------------------------ */

interface LogicRecord {
  tag: string;
  /** The cluster (track) the record belongs to: `index << 18`, or `0` for a project-global record. */
  cluster: number;
  /**
   * The record **including its 36-byte header**, because the specification's field offsets (`+0x34` for a name,
   * `+0x3a6` for the tempo slot) are counted from the record's first byte, not from its payload. Getting this wrong
   * is invisible — every field still reads *something* — which is why the offsets here are named and used as the
   * specification states them.
   */
  payload: Uint8Array;
}

const ROOT_MAGIC = [0x23, 0x47, 0xc0, 0xab];
const RECORD_HEADER = 0x24;

function u32(bytes: Uint8Array, offset: number): number {
  return (bytes[offset]! | (bytes[offset + 1]! << 8) | (bytes[offset + 2]! << 16) | (bytes[offset + 3]! << 24)) >>> 0;
}

function u16(bytes: Uint8Array, offset: number): number {
  return bytes[offset]! | (bytes[offset + 1]! << 8);
}

/**
 * Walk the project's records.
 *
 * `ProjectData` is a 24-byte root header followed by a flat run of records, and each record is a 36-byte header —
 * four tag bytes, the cluster index at `+8`, the payload size at `+0x1c` — then its payload. The walk is driven by
 * that size and **never by a scan for the next tag**: a payload may contain any four bytes at all, and a scan would
 * find tags that are not records.
 */
function readRecords(bytes: Uint8Array): { records: LogicRecord[]; problems: string[] } {
  const problems: string[] = [];
  if (bytes.length < 0x18 || !ROOT_MAGIC.every((byte, index) => bytes[index] === byte)) {
    return { records: [], problems: ["the project data does not begin with the Logic root frame magic (23 47 C0 AB) — this is not a ProjectData file"] };
  }
  const declared = u32(bytes, 0x10);
  if (declared !== bytes.length - 0x18) {
    problems.push(`ProjectData declares ${declared} payload bytes but holds ${bytes.length - 0x18} — reading what is there`);
  }
  const records: LogicRecord[] = [];
  let offset = 0x18;
  while (offset + RECORD_HEADER <= bytes.length) {
    const tag = String.fromCharCode(bytes[offset]!, bytes[offset + 1]!, bytes[offset + 2]!, bytes[offset + 3]!);
    const payloadSize = u32(bytes, offset + 0x1c);
    const end = offset + RECORD_HEADER + payloadSize;
    if (end > bytes.length || payloadSize > bytes.length) {
      problems.push(`a ${tag} record at offset ${offset} claims ${payloadSize} payload bytes, past the end of the file — stopping the record walk there`);
      break;
    }
    records.push({ tag, cluster: u32(bytes, offset + 8), payload: bytes.subarray(offset, end) });
    offset = end;
  }
  return { records, problems };
}

/**
 * A named record: a `uint16` length in bytes, then a **UTF-8** string, at a record-relative offset.
 *
 * UTF-8 rather than ASCII: real fixtures carry Korean and Japanese track names (`스트링 수염 멜로디 연주`), and a
 * byte-per-character read renders them as mojibake. A name that is not valid UTF-8 is reported, not replaced
 * silently — the caller should see that the name was unreadable rather than see a plausible wrong one.
 */
function recordName(payload: Uint8Array, offset: number): { name?: string; invalidUtf8: boolean } {
  if (offset + 2 > payload.length) return { invalidUtf8: false };
  const length = u16(payload, offset);
  if (length === 0 || offset + 2 + length > payload.length) return { invalidUtf8: false };
  const bytes = payload.subarray(offset + 2, offset + 2 + length);
  const trimmed = bytes[bytes.length - 1] === 0 ? bytes.subarray(0, bytes.length - 1) : bytes;
  if (trimmed.length === 0) return { invalidUtf8: false };
  try {
    const text = new TextDecoder("utf-8", { fatal: true }).decode(trimmed);
    return { name: text, invalidUtf8: false };
  } catch {
    return { invalidUtf8: true };
  }
}

/* ------------------------------------------------------------------ *
 * The three things the stream says: tempo, meter, and the music
 * ------------------------------------------------------------------ */

/**
 * The three marker dwords that decide what an event sequence **is**.
 *
 * `0x90` is a MIDI note-on status byte and marks a region's note sequence; `0x60` and `0x30` mark the tempo track and
 * the signature track. A region holding no notes still writes its note sequence — the 16-byte `f1` tail and nothing
 * before it — so an empty sequence is accepted too. Without that, a region holding nothing is a record the walk never
 * saw, and a project with empty regions looks like a project that has none.
 */
const NOTE_MARKER = 0x90;
const EMPTY_SEQUENCE_MARKER = 0xf1;
const TEMPO_MARKER = 0x60;
const METER_MARKER = 0x30;

/** The 16-byte terminator every `qSvE` event run ends with, so a run's length is known before it is read. */
const SEQUENCE_TAIL = [0xf1, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x3f];
const SEQUENCE_TAIL_SIZE = 16;

/**
 * The two event sizes a note run is written in.
 *
 * **Both exist in real projects, and the size is the second byte of the marker dword rather than a field
 * anywhere.** The specification's own writer emits the 32-byte form (`90 00 00 00`), and that is what the fixtures
 * here were built from. Opening the owner's eight official projects shows the other form as well: the run is
 * `90 40 00 00` and each event is 48 bytes, with the same pitch/velocity/length offsets moved by nothing at all —
 * only the stride changes. A reader that assumed the 32-byte stride on one of those runs walks into the middle of
 * an event and reports zero notes, which is exactly what the measurement in `docs/OPEN_WORK.md` §123 found.
 */
const NOTE_EVENT_SIZE_32 = 32;
const NOTE_EVENT_SIZE_48 = 48;

function firstPayloadWord(record: LogicRecord): number | undefined {
  return record.payload.length >= RECORD_HEADER + 4 ? u32(record.payload, RECORD_HEADER) : undefined;
}

/** The marker dword of a note event, with the flag byte that carries the event size cleared. */
function noteMarker(record: LogicRecord): number | undefined {
  const word = firstPayloadWord(record);
  return word === undefined ? undefined : word & 0xff;
}

/**
 * Whether a payload ends with the terminator that closes an event run of `size`-byte events.
 *
 * `headered` says whether the bytes still carry the 36-byte record header, because the caller that decides *what a
 * record is* holds the whole record while the caller that reads its notes holds the payload alone.
 */
function hasSequenceTail(payload: Uint8Array, size: number, headered: boolean): boolean {
  const body = payload.length - (headered ? RECORD_HEADER : 0) - SEQUENCE_TAIL_SIZE;
  if (body < 0 || body % size !== 0) return false;
  const tail = payload.length - SEQUENCE_TAIL_SIZE;
  return SEQUENCE_TAIL.every((byte, index) => payload[tail + index] === byte);
}

/** One note event's own start, kept as an offset so `readNotes` reads the fields from the bytes it was given. */
interface NoteEventAt {
  at: number;
}

/** A run of note events at one stride, as the reader found it. */
interface NoteRun {
  /** The event stride the run is written at: 32 or 48 bytes. */
  stride: number;
  events: NoteEventAt[];
}

/**
 * The 32-byte run, read the way the specification and the reference implementation read it: the marker dword is
 * `90 00 00 00` **exactly**, and an event is one 32-byte slot.
 *
 * This is deliberately the strictest form. It is the one the byte-level specification defines, the one its writer
 * emits, and the one the committed fixtures are written in — so it is also the reading an existing measurement is
 * pinned to, and widening *this* test would silently move those numbers.
 */
function exact32Run(payload: Uint8Array): NoteRun {
  const events: NoteEventAt[] = [];
  for (let at = 0; at + NOTE_EVENT_SIZE_32 <= payload.length; at += NOTE_EVENT_SIZE_32) {
    if (u32(payload, at) === NOTE_MARKER) events.push({ at });
  }
  return { stride: NOTE_EVENT_SIZE_32, events };
}

/**
 * The 48-byte run, which the specification does **not** describe and which real projects nevertheless contain.
 *
 * It is admitted only when the payload's own length and terminator say the run is 48-byte framed **and** the framing
 * spans more than one event: the body must close on the terminator, and the marker is tested by its status byte
 * alone because the bytes beside it carry flags (`90 40 00 00`). The single-event minimum is not cosmetic — a short
 * payload can satisfy a terminator by coincidence, and a one-event 48-byte reading of a 32-byte run would move
 * numbers the 32-byte reading is pinned to.
 */
function framed48Run(payload: Uint8Array): NoteRun | undefined {
  if (!hasSequenceTail(payload, NOTE_EVENT_SIZE_48, false)) return undefined;
  const events: NoteEventAt[] = [];
  for (let at = 0; at + NOTE_EVENT_SIZE_48 <= payload.length; at += NOTE_EVENT_SIZE_48) {
    if ((u32(payload, at) & 0xff) !== NOTE_MARKER) break;
    events.push({ at });
  }
  return events.length < 2 ? undefined : { stride: NOTE_EVENT_SIZE_48, events };
}

/**
 * The notes a region's payload holds.
 *
 * Two framings exist in real files and the order they are tried in matters: the 48-byte framing is checked **first**
 * and only claims a payload its terminator closes, and everything else falls to the 32-byte exact reading. That
 * ordering is what makes this addition additive — a payload the old reader read, it still reads, byte for byte.
 */
function noteRun(payload: Uint8Array): NoteRun | undefined {
  return framed48Run(payload) ?? exact32Run(payload);
}

/**
 * Whether a note sequence with no readable notes is **empty** rather than in a form this reader does not know.
 *
 * The two cases reach `readNotes` the same way and mean opposite things to a person: an empty region is a region
 * with nothing in it, while an unrecognised form is a reader gap that has to be said out loud. A sequence holding
 * nothing but its terminator is the empty one; anything else that produced no notes is the reader's problem.
 */
function isCheckableEmpty(payload: Uint8Array): boolean {
  return payload.length <= SEQUENCE_TAIL_SIZE;
}

function isNoteSequence(record: LogicRecord): boolean {
  if (record.tag !== "qSvE" || record.payload.length < RECORD_HEADER + 16) return false;
  const marker = firstPayloadWord(record);
  if (marker === EMPTY_SEQUENCE_MARKER) return true;
  if (marker === NOTE_MARKER) return true;
  /**
   * A marker that is `0x90` in its **low byte** with flags beside it is the 48-byte form, and is admitted only when
   * the payload really is 48-byte framed. Testing the low byte alone would make every payload that happens to begin
   * with `90` a note region.
   */
  if (noteMarker(record) !== NOTE_MARKER) return false;
  return framed48Run(record.payload.subarray(RECORD_HEADER)) !== undefined;
}

function isTempoSequence(record: LogicRecord): boolean {
  return record.tag === "qSvE" && firstPayloadWord(record) === TEMPO_MARKER;
}

function isMeterSequence(record: LogicRecord): boolean {
  return record.tag === "qSvE" && record.payload.length >= RECORD_HEADER + 80 && firstPayloadWord(record) === METER_MARKER;
}

interface TempoReading {
  bpm?: number;
  /** How many tempo points the project holds, so a tempo map can be reported rather than silently flattened. */
  points: number;
}

/**
 * Tempo, from the project's own slots.
 *
 * The `gnoS` (song) record replicates the initial tempo at three fixed record-relative offsets, and, unlike the
 * tempo-track event list, these are plain `uint32` values of `round(bpm × 10000)` — no delta decoding and no
 * dependence on where an event happens to sit. `+0x3a6` is the slot the specification names as authoritative once a
 * tempo map exists, so it is read first and `+0x92` only when it is absent. (Reading the *first* slot would be a
 * silent bug: on a project with a tempo map that slot holds a playhead-dependent value.)
 */
function readTempo(records: LogicRecord[]): TempoReading {
  const song = records.find((record) => record.tag === "gnoS");
  if (song === undefined) return { points: 0 };
  const payload = song.payload;
  /**
   * **Tempo points, not tempo sequences.** One sequence holds every point — 31 of them in a fixture measured here —
   * so counting the sequences answers 1 for a project with a whole tempo ramp, which is the opposite of useful.
   */
  const points = records
    .filter(isTempoSequence)
    .reduce((total, record) => total + Math.floor((record.payload.length - RECORD_HEADER) / 32), 0);
  let raw: number | undefined;
  for (const offset of [0x3a6, 0x92, 0xea]) {
    if (offset + 4 > payload.length) continue;
    const value = u32(payload, offset);
    if (value > 0 && value < 100000000) {
      raw = value;
      break;
    }
  }
  if (raw === undefined) return { points };
  return { bpm: Math.round((raw / 10000) * 1000) / 1000, points };
}

interface MeterReading {
  timeSignature?: string;
  changes: number;
}

/**
 * The meter, from the signature `qSvE`: an 80-byte header holding the **initial** signature at `+0x0b` (the
 * denominator's power of two) and `+0x0c` (the numerator), then one 48-byte record per change.
 */
function readMeter(records: LogicRecord[]): MeterReading {
  const meter = records.find(isMeterSequence);
  if (meter === undefined) return { changes: 0 };
  const payload = meter.payload.subarray(RECORD_HEADER);
  const exponent = payload[0x0b]!;
  const numerator = payload[0x0c]!;
  if (numerator === 0 || exponent > 8) return { changes: 0 };
  const denominator = 1 << exponent;
  const changes = Math.max(0, Math.floor((payload.length - 80) / 48));
  return { timeSignature: `${numerator}/${denominator}`, changes };
}

interface NoteReading {
  /** Region-relative ticks, from the note event's own position field. */
  startTicks: number;
  lengthTicks: number;
  pitch: number;
  velocity: number;
}

/**
 * The notes of one region.
 *
 * A note event's fields are the five the specification names and they sit at the same offsets in **both** the
 * 32-byte and the 48-byte form: the position (`38400 + region-relative tick`), the fine and coarse velocity bytes,
 * the pitch, and the length in ticks. What changes between the forms is only the stride, which `noteRun` settles
 * from the bytes.
 *
 * The 48-byte form is the one the specification does not describe and real projects do contain: its marker carries
 * flags beside the status byte (`90 40 00 00`), and reading it is what turns a project that reported **no notes at
 * all** into one that reports the notes it holds.
 *
 * Every note is `>= 1` tick long: a zero-length note is a note that cannot sound, and one is reported.
 */
function readNotes(payload: Uint8Array): { notes: NoteReading[]; zeroLength: number } {
  const notes: NoteReading[] = [];
  let zeroLength = 0;
  const run = noteRun(payload);
  if (run === undefined) return { notes, zeroLength };
  for (const event of run.events) {
    const lengthTicks = u32(payload, event.at + 0x1c);
    const pitch = payload[event.at + 0x0c]!;
    if (pitch === 0 || pitch > 127) continue;
    if (lengthTicks === 0) zeroLength += 1;
    notes.push({
      startTicks: u32(payload, event.at + 4) - NOTE_ORIGIN_TICKS,
      lengthTicks,
      pitch,
      velocity: payload[event.at + 0x0b]!,
    });
  }
  return { notes, zeroLength };
}

/* ------------------------------------------------------------------ *
 * What the project holds that this model cannot
 * ------------------------------------------------------------------ */

/** Region tags that only ever appear on an audio track, so their presence is the audio-track count. */
function countAudioRegions(records: LogicRecord[]): number {
  const audioTags = new Set(["gRuA", "lFuA"]);
  return records.filter((record) => audioTags.has(record.tag)).length;
}

/**
 * The plugin names the project mentions, read as **ASCII strings**, because Logic 10.x records them that way.
 *
 * This is the weakest reading in the module and is labelled as such: newer Logic writes plugin state as an embedded
 * XML plist (a plain text scan), older versions write names as length-prefixed ASCII inside the environment record.
 * Both are looked for; what comes back is a **list for a person to act on**, never a track.
 */
export function scanPluginNames(projectData: Uint8Array): string[] {
  const found = new Set<string>();
  // Byte by byte and in chunks: `String.fromCharCode(...bytes)` on a buffer this size overflows the call stack.
  const limit = Math.min(projectData.length, 4_000_000);
  let text = "";
  const CHUNK = 8192;
  for (let offset = 0; offset < limit; offset += CHUNK) {
    const end = Math.min(offset + CHUNK, limit);
    let piece = "";
    for (let index = offset; index < end; index += 1) piece += String.fromCharCode(projectData[index]!);
    text += piece;
  }
  // The AU naming convention: a vendor prefix and a name, e.g. "AUPitch", "AUGraphicEQ", "AUChannelEQ", "AUDelay".
  for (const match of text.matchAll(/\bAU[A-Z][A-Za-z0-9]{2,20}\b/g)) found.add(match[0]);
  // Logic's own instruments, which are not spelled with an AU prefix.
  for (const name of ["ES2", "ES1", "EXS24", "Sampler", "Ultrabeat", "Drum Kit Designer", "Sculpture", "Retro Synth", "Alchemy", "Drummer"]) {
    if (text.includes(name)) found.add(name);
  }
  return [...found].sort();
}

/** Whether a record's payload carries an embedded text plist, which is how newer Logic writes plugin state. */
function containsEmbeddedXml(payload: Uint8Array): boolean {
  const limit = Math.min(payload.length - 5, 65536);
  for (let offset = 0; offset <= limit; offset += 1) {
    if (
      payload[offset] === 0x3c &&
      payload[offset + 1] === 0x3f &&
      payload[offset + 2] === 0x78 &&
      payload[offset + 3] === 0x6d &&
      payload[offset + 4] === 0x6c
    ) {
      return true;
    }
  }
  return false;
}

/** Whether a name marks a track as Logic's model-generated Drummer/Session Player track. */
function isDrummerName(name: string | undefined): boolean {
  if (name === undefined) return false;
  return /drummer|session player/i.test(name);
}

/* ------------------------------------------------------------------ *
 * The import
 * ------------------------------------------------------------------ */

export function fromLogicProject(input: LogicProjectInput): LogicProjectImport {
  const { records, problems } = readRecords(input.projectData);
  if (records.length === 0 && problems.length > 0) {
    return { parts: [], problems };
  }

  const meta = asRecord(parsePlist(input.metaData)) ?? {};
  const metaBpm = numberOf(meta["BeatsPerMinute"]);
  const metaNumerator = numberOf(meta["SongSignatureNumerator"]);
  const metaDenominator = numberOf(meta["SongSignatureDenominator"]);

  const tempo = readTempo(records);
  const meter = readMeter(records);

  if (tempo.bpm === undefined) {
    problems.push("the project states no tempo this reader can find; the arrangement's own tempo applies");
  }
  if (tempo.points > 1) {
    problems.push(`the project holds ${tempo.points} tempo points and this model can hold one tempo — only the project's initial tempo is imported`);
  }
  if (metaBpm !== undefined && tempo.bpm !== undefined && Math.abs(metaBpm - tempo.bpm) > 0.001) {
    problems.push(`MetaData.plist says ${metaBpm} BPM and ProjectData says ${tempo.bpm} BPM — ProjectData is the authoritative copy and is what was imported`);
  }
  if (meter.timeSignature === undefined) {
    problems.push("the project states no time signature this reader can find; 4/4 applies");
  }
  if (metaNumerator !== undefined && metaDenominator !== undefined && metaDenominator !== 0) {
    const stated = `${metaNumerator}/${metaDenominator}`;
    if (meter.timeSignature !== undefined && meter.timeSignature !== stated) {
      problems.push(`MetaData.plist says ${stated} and ProjectData says ${meter.timeSignature} — ProjectData is the authoritative copy and is what was imported`);
    }
  }
  if (meter.changes > 0) {
    problems.push(`the project holds ${meter.changes} time-signature change(s) and this model can hold one meter — only the initial signature is imported`);
  }

  /**
   * A region is a `qeSM` (MIDISeq) record whose cluster also carries a note `qSvE`. The instrument track a person
   * sees is a **different** cluster with its own `qeSM` at the same index plus `0x40000`, so no cluster is treated
   * as both.
   */
  const notePayloadsByCluster = new Map<number, Uint8Array[]>();
  for (const record of records) {
    if (!isNoteSequence(record)) continue;
    const list = notePayloadsByCluster.get(record.cluster) ?? [];
    list.push(record.payload.subarray(RECORD_HEADER));
    notePayloadsByCluster.set(record.cluster, list);
  }

  const parts: ImportedPart[] = [];
  let zeroLengthNotes = 0;
  let regionsWithoutNotes = 0;
  let unreadableNames = 0;
  let unreadableNoteForms = 0;
  const seenClusters = new Set<number>();
  for (const record of records) {
    if (record.tag !== "qeSM") continue;
    const payloads = notePayloadsByCluster.get(record.cluster);
    if (payloads === undefined || seenClusters.has(record.cluster)) continue;
    seenClusters.add(record.cluster);

    const named = recordName(record.payload, 0x34);
    if (named.invalidUtf8) unreadableNames += 1;
    const name = named.name;
    const notes: NoteEvent[] = [];
    let regionZeroLength = 0;
    for (const payload of payloads) {
      const reading = readNotes(payload);
      regionZeroLength += reading.zeroLength;
      /**
       * A payload that yields nothing is not evidence that the region is empty — it is evidence that this reader
       * could not read it. The two are counted apart so the sentence below can say which one happened, because the
       * original wording asserted the notes were correct on projects where **not one note was read at all**.
       */
      if (reading.notes.length === 0 && !isCheckableEmpty(payload)) unreadableNoteForms += 1;
      for (const note of reading.notes) {
        notes.push({
          // Logic's tick resolution is 960 per quarter note; this model counts beats.
          startBeats: note.startTicks / LOGIC_TICKS_PER_QUARTER,
          lengthBeats: note.lengthTicks / LOGIC_TICKS_PER_QUARTER,
          pitch: note.pitch,
          velocity: note.velocity,
        });
      }
    }
    zeroLengthNotes += regionZeroLength;
    if (notes.length === 0) {
      regionsWithoutNotes += 1;
      continue;
    }
    parts.push({ name: name ?? `Region ${parts.length + 1}`, notes });
  }

  if (regionsWithoutNotes > 0) {
    problems.push(`${regionsWithoutNotes} MIDI region(s) hold no notes and were not added as tracks`);
  }
  if (unreadableNames > 0) {
    problems.push(`${unreadableNames} region name(s) are not valid UTF-8 and were replaced with a generic name`);
  }
  if (zeroLengthNotes > 0) {
    problems.push(`${zeroLengthNotes} note(s) were stored with a length of zero ticks and were imported as zero-length notes`);
  }
  /**
   * Where a region sits on the timeline is **the one thing this reader cannot yet read reliably**, and it says so
   * rather than pretending the notes start at bar 1.
   *
   * The note events themselves give each note's position *within its region*, and those readings are what the notes
   * below are built from — they are checked against a real fixture and they agree with it. The **region's own start**
   * is a separate field whose layout moved between Logic versions: the specification documents the Logic 11.x shape
   * (a plain `uint32` after the variable-length name), and in the 10.x fixtures used here those bytes decode to a
   * value that **contradicts** the note positions they are supposed to bound — which is why it is not applied. The
   * consequence a caller can see is that every part is imported from beat 0 with its internal timing intact.
   *
   * ⚠️ **The tail of this sentence is conditional, and it has to be.** It used to end "the notes are correct" on
   * every project, including the ones where the reader had produced **no notes at all** — a claim about its own
   * output that it had no basis for. When a note sequence's form is not one this reader knows, that is now said
   * instead of being covered by the sentence about positions.
   */
  problems.push(
    unreadableNoteForms === 0
      ? "region start positions could not be read reliably from this ProjectData version, so every part is imported from beat 0 with its internal note timing preserved — the notes are correct, their position on the timeline is not yet"
      : `region start positions could not be read reliably from this ProjectData version, so every part is imported from beat 0 with its internal note timing preserved — and on top of that, ${unreadableNoteForms} note sequence(s) are in an event form this reader does not recognise, so the notes they hold were not imported at all`
  );

  /**
   * The named boundaries. Each one is a sentence a person can act on, and each names the thing rather than the count
   * alone, because "3 items were dropped" is not something anybody can act on.
   */
  const audioRegions = countAudioRegions(records);
  if (audioRegions > 0) {
    problems.push(
      `${audioRegions} audio region reference(s) were not imported: groove has no audio track kind (TrackKindV2 is drumkit/instrument/sampler/fx/folder), so audio tracks and their regions have no counterpart here`
    );
  }
  const automationRecords = records.filter((record) => record.tag === "rpyH").length;
  if (automationRecords > 0) {
    problems.push(`automation (volume/pan envelopes, ${automationRecords} record(s)) has no counterpart in this model and was not imported`);
  }
  const pluginNames = scanPluginNames(input.projectData);
  if (pluginNames.length > 0) {
    problems.push(
      `AU plugin chains have no counterpart in this model; the project mentions: ${pluginNames.join(", ")} — remap these by hand`
    );
  }
  const embeddedXml = records.filter((record) => record.tag === "ivnE" && containsEmbeddedXml(record.payload)).length;
  if (embeddedXml > 0) {
    problems.push(`${embeddedXml} environment record(s) embed plugin state as XML, which was not read; the plugin chain was not imported`);
  }

  const drummerParts = parts.filter((part) => isDrummerName(part.name));
  if (drummerParts.length > 0) {
    problems.push(
      `${drummerParts.length} Drummer/Session Player track(s) (${drummerParts.map((part) => part.name).join(", ")}) were converted from their MIDI — the notes survive, but "Logic generated this" is a fact this model cannot hold and it is lost`
    );
  }

  const result: LogicProjectImport = { parts, problems };
  if (tempo.bpm !== undefined) result.tempoBpm = tempo.bpm;
  if (meter.timeSignature !== undefined) result.timeSignature = meter.timeSignature;
  return result;
}

/* ------------------------------------------------------------------ *
 * The base64 entry point the MCP tool uses
 * ------------------------------------------------------------------ */

function decodeBase64(value: string, what: string): Uint8Array {
  const trimmed = value.trim();
  if (trimmed === "") throw new Error(`\`${what}\` is empty — it must be the base64 of the file's bytes`);
  if (typeof Buffer !== "undefined") {
    const bytes = Buffer.from(trimmed, "base64");
    if (bytes.length === 0) throw new Error(`\`${what}\` is not valid base64`);
    return new Uint8Array(bytes);
  }
  const binary = atob(trimmed);
  const out = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) out[index] = binary.charCodeAt(index);
  return out;
}

export interface LogicProjectBase64Input {
  projectDataBase64: string;
  metaDataBase64: string;
}

/** The same import, from the base64 that MCP arguments carry and JSON can hold. */
export function fromLogicProjectBase64(input: LogicProjectBase64Input): LogicProjectImport {
  return fromLogicProject({
    projectData: decodeBase64(input.projectDataBase64, "projectDataBase64"),
    metaData: decodeBase64(input.metaDataBase64, "metaDataBase64"),
  });
}

